### ISSUE TITLE
Statuses: Update to use sentence case

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1001]
### Issue Description

Our style guide specifies that the registrar should use sentence case whenever possible (i.e. only capitalize the first word). Therefore, we need to update our status labels in the UI to reflect that formatting. 

**Acceptance Criteria**
The following statuses appear in sentence case within the UI:

Application statuses:
- [ ] In review
- [ ] Action needed

Domain statuses: 
- [ ] DNS needed
- [ ] On hold

**Comment by michelle-rago** [comment]
@zandercymatics I'm seeing "On Hold" on staging, https://getgov-staging.app.cloud.gov/. It should be sentence case or "On hold". Should I create a new ticket to update that? 
![image](https://github.com/cisagov/manage.get.gov/assets/60157596/2f62c4ce-264f-4f73-af1d-a70c35890e02)
