### ISSUE TITLE
Federal Agency and State fields should be a dropdown in DjAdmin

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1008]
### Story

As a CISA analyst
I want to edit "Federal Agency" and "State" fields for an organization, using a DROPDOWN, rather than a TEXT field
so that I am presented with all valid available choices and the potential for errors is reduced.

Applicable to #1006 and #1007 

(Affects DjA, 

- [ ] Domains, 
- [ ] Domain Application and 
- [ ] Domain Information pages)

### Acceptance Criteria

- [ ] Fields mentioned above are implemented as Drop-downs.
- [ ] Contents (options) in the dropdown are aligned with Request dropdown. (update location from which data pulled)

### Issue Links

Relates to #1032 
Relates to #337

**Comment by Katherine-Osos** [comment]
@h-m-f-t Is this update dependent on completing this one first?: https://github.com/cisagov/getgov/issues/337?

**Comment by h-m-f-t** [comment]
@Katherine-Osos, no. We do have _something_ now, so #337  is basically an enhancement.
