### ISSUE TITLE
Required fields can be bypassed when "type of org" is changed mid-request

### ISSUE THREAD

**Issue by therealslimhsiehdy** [cisagov/manage.get.gov#1011]
### Current Behavior

**Big Picture:** If you change the type of organization while the application is in progress, and navigate away from a "required field" text box, the page lets you submit it without any information in it, and is shown as valid (the green check mark).

So as a user you can click through the different options (ie Type of Organization, About Your Organization, Contacts) on the left, and when you click past where that option would be -- you can basically progress through the list (bypassing).

Because you can bypass it, each of the pages has a "check" on it -- if that "check" fails, then you shouldn't be able to progress onto the next "menu" or "page"

Once you pass that "checkpoint" you can go back to previous ones - _this process seems to function sequentially_. If you go halfway through the list there's nothing stopping you from going to a "previous checkpoint" (or previously accessed menu item). 
**Note:** Because switching your type of organization creates a new menu item, and bc that new menu item may be "before" where the other menu items may be, one may have already gone past it

**However if you you switch to a different Type of Organization (ie Federal to Interstate), the "other checkpoints" are still "valid" even if they should be "locked checkpoints" (locked menu items). Also, one can still submit their application even if they have invalid "checkpoints" or "menu items"** 

(I am referring to checkpoint as one of the menu items, ie Type of Organization or About Your Organization, Contacts, etc)

### Expected Behavior

When you change the type of organization while the application is in progress and navigate away from a "required field" textbox/page - you should NOT be able to submit it in an invalid state (ie invalid numerics, empty textbox, etc) and it should NOT show as valid (should NOT have a green check mark beside the box).

### Steps to Reproduce

1. Go to started application or create one
2. Set it the Type of Organization to Federal
3. Navigate past the point where "About Your Organization" (leave it empty) would be on the menu (ie Your Contact Information)
4. Then go back to "Type of organization" and set it to "Special District"

### Additional Context

Discovered in https://github.com/cisagov/getgov/pull/975

![image](https://github.com/cisagov/getgov/assets/13954664/59ff5bd5-2a88-4bc3-b205-b0f788787374)
![image](https://github.com/cisagov/getgov/assets/13954664/0e72dd35-402a-49c5-a5a3-50ec42b815e3)
![image](https://github.com/cisagov/getgov/assets/13954664/0628ae7b-9deb-44f1-a126-267506387b42)
![image](https://github.com/cisagov/getgov/assets/13954664/a8733eed-d5da-45ac-8686-270030caf532)

### Issue Links

Addressed by #1686 which will prevent an incomplete request from being submitted. (This should still be fixed later)

**Comment by kitsushadow** [comment]
Asking for review and consideration potentially for Sprint 31.
@abroddrick @h-m-f-t @PaulKuykendall

**Comment by PaulKuykendall** [comment]
@therealslimhsiehdy @abroddrick - I would say that this is a low-priority bug at this time, but one that we will want to evaluate as we turn our focus on to Domain Request phase.

Reach - probably affect low-single-digit percentage of applicants
Impact - Analyst would evaluate and return to applicant for more information.

Effort to FIX?? If this is costly, definitely defer.

**Comment by h-m-f-t** [comment]
* I can see some organizations that only serve a hyper-local jurisdiction or that have a tightly scoped mission being confused on whether they are `state` vs. `special district` or something and attempting to change their org type mid-flight. 
* Let's get a rough size on this.
* Sprint 31+ probably makes sense.

**Comment by vickyszuchin** [comment]
This bug has been sized and meets DoR criteria. Moving to Ready.

**Comment by abroddrick** [comment]
We now block on submit, so I think this one should count as a won't do
