### ISSUE TITLE
Manage.get.gov & Get.gov: Update links in preparation for launch

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1030]
/### Issue Description

We don't want to link to the new registrar until that site is "live." Before launching the new registrar, update all buttons/links in beta.get.gov that should point to the registrar. Also, update all links that point to beta URLs. This is related to https://github.com/cisagov/getgov-home/issues/147. We'll get the URL from the work done for 147.

**Acceptance Criteria**

- [x] in manage.get.gov, update all links that point to get.gov (due 1/19!)
- [x] All buttons / links identified in [this spreadsheet ](https://docs.google.com/spreadsheets/d/1EeO_JDz7aD_XV0sgwSHP0JpZB_7c69ojcNzW873N5so/edit#gid=226737863)as "update later" have been updated to point to the new registrar.
- [ ] Update any hard-coded links to the beta site that couldn't follow the standard process for internal linking. (check with Michelle for details on this, if needed) [Example here](https://github.com/cisagov/getgov-home/pull/133#issuecomment-1832046825)
- [x] Ensure [Checklist](https://docs.google.com/spreadsheets/d/1elD_Y8hL_I4qQg1og54GnQp1Id2M4eROGnxTaWjlQAg/edit?pli=1#gid=346588381) item exists to activate these changes.

### Issue Links

Dev ticket to add modal: #[147](https://github.com/cisagov/getgov-home/issues/147)

**Comment by gabydisarli** [comment]
met with @dave-kennedy-ecs  and he will be updating any hard coded links (looks like there was just one!) in manage.get.gov.
