### ISSUE TITLE
Modify email content for migration domain invitation script

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/manage.get.gov#1034]
### Issue Description

The email content for domain invitations requires modification to be tailored for the migration script domain invitations. 

Considerations:
- For users with more than one domain, only one email will be sent but it will include the links to all their domains.
- This script is a one time design for use with the migration. Emails should not be expected to be resent as a part of the migration process.

_**NOTE:** Wait for feedback from user testing before starting this ticket_

**Acceptance Criteria**

- [x] update the current [domain invitation email](https://docs.google.com/document/d/1HnMdniAB9INphrLwKjiACyNLrenyXy0QFf0-yz4EStI/edit#heading=h.gjdgxs) based on feedback from user testing
- [x] then, create an alternate version of that domain invitation email to be used for the migration. Add new verbiage to communicate that we're updating to new registrar (i.e. explain why domain managers are receiving this email when they are already a manager)
- [x] ensure engineering tickets are created to make these updates

### Issue Links

Relates to: #927
Relates to: #482
Blocks: #1047

**Comment by gabydisarli** [comment]
Copy is being drafted here https://docs.google.com/document/d/1bSy6lNkoImlO3rG7kzgZQy1nVubXmEDmmMHyhuOuH6g/edit#heading=h.gjdgxs

**Comment by gabydisarli** [comment]
Approved!
