### ISSUE TITLE
{beta.}Get.gov: Update "Check availability" links and "whois" links

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1056]
### Issue Description

Currently, there are TBD links meant to point to the "check availability" search box and explain WHOIS.

**AC:** 

- Update all instances referencing "check availability" as captured in [this spreadsheet](https://docs.google.com/spreadsheets/d/1EeO_JDz7aD_XV0sgwSHP0JpZB_7c69ojcNzW873N5so/edit#gid=226737863).  They should point to the homepage
- Update the pending WHOIS reference captured in [this spreadsheet](https://docs.google.com/spreadsheets/d/1EeO_JDz7aD_XV0sgwSHP0JpZB_7c69ojcNzW873N5so/edit#gid=226737863). Reuse language that already appears on [this page](https://beta.get.gov/domains/security/).
- Double-check get.gov to ensure other instances were not overlooked.

### Additional Context (optional)
These updates may get made during the content review. If so, close this ticket.

**Comment by h-m-f-t** [comment]
See also [discussion](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1695399169464559?thread_ts=1695136849.155039&cid=C05BDEA3C11) in Slack about a future state for Whois/availability

**Comment by h-m-f-t** [comment]
There's not a great option for general web whois. Until/unless we offer one, I think we should write some content about what Whois is, and point links to there or to our "check availability" section.
