### ISSUE TITLE
Error evaluation for Django admin  

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1067]
### Scope

- [ ]  Evaluate Django admin error handling (to show better error messages)
- [ ]  Show human-readable error for bulk delete for domain invitations (505 errors)
- [ ]  Show human-readable error for bulk delete for user groups (505 errors)

Currently known ways to produce a 500 error in DjAdmin:

- throwing 500 error when bulk deleting a group using the checkbox 
- throwing 500 error when bulk deleting domain invitation  

### Additional Context (optional)

Per Neil, for troubleshooting:

For objects in Django that can “contain” related objects, you can’t delete the container until you have dealt with the containing objects. (In Django, these are sometimes called “cascade” or “protect”). I bet that the admin isn’t set up to show you the underlying error which is that you can’t delete the group because it still has related users.

**Comment by PaulKuykendall** [comment]
May be a future case for groups (user).

**Comment by vickyszuchin** [comment]
This issue is a duplicate of #1731.
