### ISSUE TITLE
Make setting contacts on Domain creation more efficient

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#1080]
### Issue Description

When a domain is being created in the registry, we are sending a Create contact and UpdatedDomain epp message for each contact. Instead we should send one domain update at the end with all 3 contacts. This would slightly reduce our calls

AC:
- make the change above
- update affected unit tests

Implementation note:

Passing a variable to the set_singleton_contact function and having it not do an UpdateDomain, followed by calling updateDomain inside the pendingCreate function should help to resolve this.

### Additional Context (optional)

This is easier and less lift that #1054 and #1079 but won't reduce lag as severely as them

### Issue Links

relates to #1054 
relates to #1053
relates to #1079

**Comment by abroddrick** [comment]
While a nice to have, I think our current improvements on epp messages are good enough for now. Suggest we just mark this as a later. @PaulKuykendall @h-m-f-t  any objections?

**Comment by h-m-f-t** [comment]
So, not sprint 34?

**Comment by abroddrick** [comment]
Correct, I don't think it's needed given how quickly the pooling is making the connection right now.

**Comment by abroddrick** [comment]
Closed because this isn't needed anymore "won't do"
