### ISSUE TITLE
Email notification for name server updates

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1086]
### Issue Description

As a domain manager,
I want an email notification for DNS name server updates only
So that I am alerted to, and have a record of, that security change.

Constraints: I only want this email notification for DNS changes that take place AFTER the initial DNS name servers are added to the domain. In other words, I do not want an email for DNS entries added from the "DNS Needed" state. However, I want this email notification for additions or changes in DNS entries made while in the "Ready" state.

AC:

- [ ] #2203 (deleted) "Content has been created."
- [ ] Domain manager is not sent an email when adding the initial DNS name servers from "DNS Needed" state.
- [ ] Domain manager is sent an email when adding or changing DNS name servers from domain "Ready" state.

Source: [Product Huddle](https://docs.google.com/document/d/1jatolB9YaQLITwqx25y0B1u5J23S_J19PawXtIaov8o/edit#bookmark=id.ahmsu0j9juh7)

### Issue Links

Replaced by: #2196 (then closing THIS ticket)

**Comment by Katherine-Osos** [comment]
@PaulKuykendall @katypies This was addressed in #2196. Closing this ticket.
