### ISSUE TITLE
Add additional DNS content on {beta.}get.gov's domain management page

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1089]
### Issue Description

On https://beta.get.gov/help/domain-management/, we should add some helper content about name servers/glue records and DNSSEC (generally re-using [some of the text](https://docs.google.com/document/d/1u-K1yQKb16H3AWj33mH2e1LJme6Ay9dNXMG8isiOXWk/edit#heading=h.euypw7qrupm0) we've already written for #893 and #1147). The content document for this page should be updated [here.](https://docs.google.com/document/d/1Lr6weGSYLebCOxJADMTZPMSuNL5sYyKZH7axAthlFtU/edit#heading=h.gjdgxs)

AC:
- [x] Approved content is active on new get.gov informational site.
- [x] Update "User Management" label to read "Domain managers"

### Additional Context (optional)

Source of this request: [Product Huddle](https://docs.google.com/document/d/1jatolB9YaQLITwqx25y0B1u5J23S_J19PawXtIaov8o/edit#bookmark=id.azmlj2xrgfxj)

### Issue Links

#893, #1147

**Comment by gabydisarli** [comment]
@PaulKuykendall We need to also add a section on Subdomain records (glue records)

**Comment by PaulKuykendall** [comment]
We'd expect content may be reused from previous work. See #893 and #1147.

**Comment by gabydisarli** [comment]
Making a note here that we should add some direction to the DNS name severs section on how they should format their name servers. See sample content to work from. 

> Enter your name servers in the required format, like ns1.example.com. Name servers can only contain supported characters (letters [A-Z], numbers [0-9], the minus sign [-], and the period [.]).  If you need help email us at help@get.gov.

**Comment by gabydisarli** [comment]
This is ready for review

**Comment by gabydisarli** [comment]
PR here: https://github.com/cisagov/getgov-home/pull/105
