### ISSUE TITLE
Fix Broken dependabot bump- gitpython 4.2.3

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#1110]
### Issue Description

Troubleshoot and fix the update that is currently failing when updating a minor version of gitpython. A minor change shouldn't be resulting in errors, but this one causes failures.

see branch dependabot/pip/src/gitpython-3.1.34 titled Bump gitpython from 3.1.31 to 3.1.34 in /src

**Comment by h-m-f-t** [comment]
Closed via #1758
