### ISSUE TITLE
help@get.gov is receiving lots of bouncebacks for failed test emails

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#1128]
Our new program inbox will be help@get.gov, hosted in M365. We are also sending automated registrar emails from this address via SES. SES is doing what it does and actually attempting to deliver test emails we're sending to fake addresses, which bounces-back into our real inbox.

Though we can filter out bounced emails from amazonses.com, let's dig into this and see if we can limit the bouncebacks or try another approach.

- [ ] Find the cause of the emails (dig into sending logic, SES logs)
- [ ] Decide on a course of action (create actual test inboxes?)
- [ ] Make a change and confirm impact
- [ ] fixtures and tests should not result in an email being sent

Check out our [Slack thread](https://cisa-corp.slack.com/archives/C05BJTNCY12/p1695764077201119) about it.

**Comment by zandercymatics** [comment]
These test cases don't appear to be using boto3 mocking:

"test_save_model_sets_restricted_status_on_user" and "test_save_model_sets_approved_domain" don't have the tag "@boto3_mocking.patching" in test_admin.py
In test_views, there isn't that mocking on "test_domain_user_add", "test_domain_invitation_cancel", "test_domain_invitation_cancel_no_permissions", and "test_domain_security_email_form"

**Comment by h-m-f-t** [comment]
The volume got so high this past weekend that M365 rate-limited the inbox. (Still a later.)
