### ISSUE TITLE
Setup production login.gov to launch manage.get.gov

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1132]
### Issue Description

"Productionize our [Login.gov](http://login.gov/) app (i.e., tell Login to launch it)"

After the data transition is complete, from Verisign to Cloudflare:
For Registry Cutover (est. Nov 15), the user journey needs to change so that they are directed to the production login.gov for their credentials, and subsequently redirected to manage.get.gov so that they can manage their domain.

As a test case:
Given a domain manager visiting the **legacy get.gov** site
When the domain manager selects "Manage your domain,"
Then they are redirected to production Login.gov so that they may login
And then, if successful, they are redirected to production manage.get.gov so that they may manage their domains on Cloudflare registry.

- [x] Prepare production login.gov app
- [x] Point login.gov app to "manage.get.gov" (in mid-November)
- [x] Above setup is complete and working.

**Comment by vickyszuchin** [comment]
As discussed in the refinement meeting (10/16), this ticket may need refinement, to provide better clarification of task. Added "refinement" tag. Cameron is taking a look at it.

cc: @PaulKuykendall @h-m-f-t

**Comment by neilmb** [comment]
This appears to be complete. If people have problems logging in, let's make bug tickets.
