### ISSUE TITLE
Import additional data for transferred domains

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#1139]
### Issue description and context

Analysts need good metadata about domains in-registrar. #923 pulled some data from exports, but we should also include a domain's type, the value for its ["Agency" and "Organization"](https://flatgithub.com/cisagov/dotgov-data/blob/main/?filename=current-full.csv&sha=40ebece364b35581ae2dbf3fe0e3eb5b55c3e2c8), the creation date, and expiration date.

* **Domain types** are defined in _domaintypes.adhoc.dotgov.txt_ (not all values are used). `domaintypeid` is the key, and the domain data is in _domainadditionaldatalink.adhoc.dotgov.txt_. Organization type has **federal type** and **organization type** (requires mapping)

* **Agency** data is at _agency.adhoc.dotgov.txt_. These are the agency names for federal agencies; everyone else is `Non-federal agency`. (I'm unsure where else this key appears.) This will map to pull out **federal_agency**

* **Organization** data is in _domainadditionaldatalink.adhoc.dotgov.txt_,  and `orgid` can be looked up in `20231009.organization.adhoc.dotgov`. 
**has organization name**
**Domain creation and expiration dates** are in `escrow_contacts.daily.dotgov.GOV`, the 8th and 12th column respectively (if useful, I believe the relevant RFC is https://datatracker.ietf.org/doc/html/rfc9022#section-5.1.2.1.1). has **creation date, expiration date **

### Acceptance criteria

- [ ] Transition domain model  is updated to include domain Organization Type, Organization Name, federal agency, federal type, creation date, expiration date 

- [ ] Analysts can easily see what a transferred domain's type is, when it was originally created and when its current expiration date is. 
  - [ ] creation date should be changed on a domain's object in the domain table while expiration is saved in the transition domains table.
  - [ ] domain information should be updated with the correct fields (org type, org name federal agency, federal type) 
- [ ] READMEs are updated accordingly

### Additional context
The .txt files mentioned are in [Drive](https://drive.google.com/drive/folders/1TWxHUZexMqTK6VH9iXgopiX7OknX4vOC?usp=drive_link).
Implementation suggestions not criteria: 
domain type should map to DomainInformation Organization Type
When getting domain type if it is federal, save the Judicial/executive/legistative portion in a new column on transition domains for federal_type
When creating domain information (see 980's implementation on user.py), adjust the DomainInformation creation to include organization type, federal_type (if applicable) and federal_agency (Non-federal agency)
When pulling in federal_agency, find the difference between our current list and the one provided from verisign and add any missing agencies to our AGENCY list defined in Domain Application. 
note on federal agency, if it is a Non-federal, the federal_agency field should just be null

### Links to other issues

🔁 Related to #980 #923

**Comment by abroddrick** [comment]
We would need to do an epp call for each domain in our transition table to get that expiration and creation date, which means cloudlfare will need to have migrated their data first before we can do our transition.

**Comment by vickyszuchin** [comment]
Per Cameron, making a single ticket for this though we may break it up later

**Comment by h-m-f-t** [comment]
Outstanding questions:
* Should we +1 year to all the expiration dates?
* Not for this issue, but related:
  * What would need to change in the analyst view to see creation dates?
  * Should we add the expiration date to a user's domain management view?
