### ISSUE TITLE
Update login.gov page

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1144]
### Issue description and context

Update the get.gov login page (also known as the login.gov page) to help our users understand that the .gov registrar is now using login.gov for authentication.

- [Google doc for content change ](https://docs.google.com/document/d/1ZpX_jxouqCHQSgQ4_shYTEKxzR22y-aPiMAjsX15h3s/edit#heading=h.qxac5ayqxyqy)

### Acceptance criteria

- [ ] the .gov login page has new text

### Links to other issues

🔄 Relates to #950, #949

**Comment by h-m-f-t** [comment]
After another review, I'm unsure about the text we drafted or the concern we were trying to address with these words. I recall talking about this in the context of #950 but am unsure I see a direct connection there. @gabydisarli, what say ye?

**Comment by michelle-rago** [comment]
We won’t update the Login.gov/registrar page until we update the security warning text in the blue box. See [Google doc convo](https://docs.google.com/document/d/1ZpX_jxouqCHQSgQ4_shYTEKxzR22y-aPiMAjsX15h3s/edit#heading=h.qxac5ayqxyqy) for more info.

@h-m-f-t Should we put this in the backlog or close it?

**Comment by h-m-f-t** [comment]
There are changes we'll make to that page after launch, so let's keep this in the backlog.
