### ISSUE TITLE
{beta.}get.gov : Change 'Manage your domains' button to include login.gov logo

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1146]
### Issue description and context

In November, once the registry cutover begins and users are able to manage their domains on the new registrar, we'll need to prepare them to encounter the login.gov page when they click the 'manage your domains' button on the [home page](https://beta.get.gov/). By adding the [login.gov logo](https://developers.login.gov/design-guidelines/#login-logo) to the manage domains button, this will give users a bit of a preview of what's to come. This work is to modify the button to include the login.gov logo mark (the shield only).  

Here are [Figma designs](https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&node-id=1451%3A74734&mode=design&t=erQVr7Z5amCUHoZU-1) to show how the button is modified and where it is modified. Note that only the button in the header is changing. 

### Acceptance criteria

- [ ] The manage your domains button on the home page (beta.get.gov) has the login.gov button on it.

### Links to other issues

🔄 relates to #950

**Comment by michelle-rago** [comment]
I think if we were using "Sign in" or something similar, having the Login logo would make more sense.
But we're promoting it as "Manage..." I'm concerned that adding the Login logo could make users think that they're managing their domains with Login.

**Comment by gabydisarli** [comment]
closing as a won't do because this work is getting folded in as a potential solution for story #1251
