### ISSUE TITLE
Use multiple application instances on our stable environment

### ISSUE THREAD

**Issue by neilmb** [cisagov/manage.get.gov#1151]
### Story

As a user
I want the registrar to be available as often as possible
so that I can manage my domains

### Acceptance Criteria

- [ ] Cloud.gov app in stable environment uses more than one instance: https://cloud.gov/docs/management/multiple-instances/
- [x] Cloud.gov app in stable environment uses zero-downtime deployments: https://cloud.gov/docs/deployment/production-ready/#zero-downtime-deploy

### Additional Context

In preparation for launch, we should consider reviewing other items on https://cloud.gov/docs/deployment/production-ready/ of which these are two and we have many of them already.

This ticket is exempt from automated testing requirement.

**Comment by PaulKuykendall** [comment]
I added this to the Project.

**Comment by neilmb** [comment]
The `cg-deploy-action` that we use to deploy to Cloud.gov already uses `cf push --strategy=rolling` so we don't need to change anything to get zero-downtime deployments once we add multiple instances.
