### ISSUE TITLE
UX: Redesign (rethink) Navigation for domain management pages

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1153]
### Story

As a domain manager
I want to understand how to navigate inside of my domain's management pages
so that I can quickly and easily get to where I want to go

### Acceptance Criteria

- [ ] Design to support decision on the link button
- [ ] Add appropriate links (Figma or other supporting links) to the associated dev ticket #1136 

### Additional Context

Prior to adding [DNSSEC functionality](https://github.com/cisagov/getgov/issues/893) all the pages in a domain's management section were at the same hierarchical level. Now that we've introduce sub pages (DNSSEC and Name servers live under the DNS page) the link button should take the user back to a page above in the hierarchy. There's also some other ways it could work such as having it behave like a true breadcrumb e.g., igorville.gov/DNS/DNSSEC. 

### Issue Links

Blocks #1136 (dev) ticket

**Comment by Katherine-Osos** [comment]
Idea from Michelle: If we want to maintain a link that points people back to the dashboard - what about adding "Manage your domains" to the left nav? This link could be above "Domain overview." We could then remove the specific domain from the left nav area since it's already in the main content area.

**Comment by PaulKuykendall** [comment]
We are fixing the "Back to Domains" with Rebecca's fix #1196, so this is more of a REDESIGN for usability, and has been deprioritized from launch.

**Comment by Katherine-Osos** [comment]
@PaulKuykendall @katypies Closing this ticket. Navigation will be addressed when DNS hosting is added to the domain mgmt section. Revising that navigation as a separate ticket could lead us down a path that won't be sustainable when that new feature is introduced.
