### ISSUE TITLE
Manually test a very small migration

### ISSUE THREAD

**Issue by neilmb** [cisagov/manage.get.gov#1161]
Just take a few domains from the Verisign data exports, maybe modify them so that they are pointing to our email addresses, run the scripts and see what the resulting state in the registrar is. 

Did we get Domain objects in the database and can our users access them?
Is there any DomainInformation associated with them?
Do the EPP/DNS/DNSSEC parts of the registrar work right?

**Comment by neilmb** [comment]
Can we use this migrated environment to do testing around domain manager uptake?

**Comment by h-m-f-t** [comment]
We did it in November!
