### ISSUE TITLE
Research and perform some automated load testing

### ISSUE THREAD

**Issue by neilmb** [cisagov/manage.get.gov#1163]
There are tools that can generate large amounts of traffic to a web application. We should see what we can do to test load levels against our Django application. Authentication being required might change how useful these tools can be as currently, every unauthenticated request would immediately be redirected to Login.gov.

**Comment by h-m-f-t** [comment]
Should we move this to the board?

**Comment by neilmb** [comment]
I think that this was pre-launch and isn't even relevant enough now to keep the issue open.
