### ISSUE TITLE
Nameservers return in a different order than were sent

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#1193]
### Current Behavior

If you add or delete a nameserver, you will notice _occassionally_ on save the nameservers get reordered. 

### Expected Behavior

A user would probably expect them to either be ordered with some reason to it, or be in the same order as they were sent.

For Refinement: 
I suggest if we want to fix this that we return them based on an alphabetical sort because we cannot guarantee them being returned in the same order they were sent as we are returning what came back from the registry.

### Steps to Reproduce

1. go to the nameserver's page
2. add and delete nameservers and click save as you do. 
3. Notice eventually the order on the nameservers changes

note: this is not consistent and may not repeat. 

### Additional Context

Note they are returned based on what is received from the registry, thus if the order changes on the registry side, we are displaying that. It is worth checking how we are storing the nameservers though and make sure there isn't some re-ordering we are doing.

**Comment by PaulKuykendall** [comment]
Can push to Sprint 34

**Comment by abroddrick** [comment]
@PaulKuykendall @Katherine-Osos and @h-m-f-t we determined it is already sending nameservers in alphabetical order, so is it okay if I just mark this as a won't do?

**Comment by abroddrick** [comment]
Closing as won't do, as we determined the current state is good enough. A new ticket can be made if user feedback tells us otherwise
