### ISSUE TITLE
For initial launch, remove the ability for users in stable to create new requests

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#1194]
### Issue description

Our November users shouldn't have the ability to request new domain names since that's not opening until later. We should prevent them from starting a new request _in stable_ but it should stay in staging and individual sandboxes so it can continue to be tested.

(The solution here may be a feature flag with e.g., `open_requests=Y/N`.)

### Acceptance criteria

- [ ] Users in stable can't create a new domain request by clicking the "Start a new domain" button, because the button is disabled and greyed out.
- [ ] Users in stable CAN still create a new domain request by using the direct link
- [ ] In stable environment, add language above the "Start a new" button to indicate "Coming in 2024."

(other environments)
- [ ] Users in all other environments can create a new domain request

### Additional context

We could remove this button. We could also keep the button but remove the link behind it (though without updated text it could confuse users).

<img width="1232" alt="Screenshot 2023-10-23 at 1 59 21 PM" src="https://github.com/cisagov/getgov/assets/603901/b1bcff4a-ae9c-4897-b7ae-38e148af0290">

### Links to other issues

Relates to #1143

**Comment by zandercymatics** [comment]
Self assigning as I used the premise of this ticket to experiment with tooltips. Just needs some javascript/css added in to mimic the behavior of a disabled button (on the backend its just an <a> tag) which shouldn't take too long
