### ISSUE TITLE
DNSSEC additional items

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1208]
### Issue description

These are two quick fixes that can be added to the DNSSEC flow to help user experience:

1. Change button copy on modal pop up when user clicks to delete all DS Data. Change button from saying 'Delete all DS Data' to '_Remove_ all DS Data'
2. Change error message for validation on Key tag field. Add validation to Digest field to only accept valid characters. Adjust error messages accordingly for digest.

### Acceptance criteria

- [ ] copy on modal button is changed
- [ ] Validation error message on key tag field reads: "Key tag must be less than 65535"
- [ ] Front end validation on Digest field only accepts alphanumeric characters [(see Slack conversation)](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1699893743536579)

**Comment by gabydisarli** [comment]
adjusted AC after conversations with Katherine

**Comment by Katherine-Osos** [comment]
@gabydisarli Dave and I talked about the update to the modal button. Since we're changing that language, we also changed the wording in the modal itself: "Warning: You're about to **remove** all DS records on your domain".
