### ISSUE TITLE
Side nav behavior on domain management pages

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1209]
### Issue description

It would be nice to "hide" the child links under the parent pages in the [side nav](https://designsystem.digital.gov/components/side-navigation/) on the domain management pages. This would present a cleaner UI and collapse pages like Name servers and DNSSEC under the larger DNS category. Users who will never be adding DNSSEC wouldn't need to see that page always present. 

### Acceptance criteria

- [ ] On clicking the DNS page, the Name servers page and DNSSEC unfurl out from under it
- [ ] DS Data page behaves the same way (upon clicking DNSSEC with the condition that the user has added DS Data already). The page shouldn't be present if they haven't added DS Data.

**Comment by PaulKuykendall** [comment]
Can push to 34
