### ISSUE TITLE
Modify the expiration dates of most registered domains by one year

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#1212]
### Issue description

In September, we [announced](https://get.gov/updates/2023/9/6/infrastructure-as-a-public-service/#how-these-changes-impact-governments) that we'd extend registered domains' expiration dates by a year. Following up on #1139, this issue takes the action of actually modifying expiration dates (but only for domains that are not currently past due). 

### Acceptance criteria

- [ ] Add 1 year to the expiration dates of all registered domains _except_ those with a current expiration date that is before November 15, 2023.

### Additional context

[Refinement chat in Slack](https://cisa-corp.slack.com/archives/C05TS76RVS6/p1698170644926469)

### Links to other issues

🔃 Related to #1139 
⛔ Blocked by #1217

**Comment by PaulKuykendall** [comment]
should be simple, but we haven't yet implemented the setter.
