### ISSUE TITLE
Design & Content: Dedicated "check availability" section on beta.get.gov/domains/choosing/

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1219]
### Issue description

Currently, we have a way for users to check domain availability from the homepage. However, there are various embedded links to "check availability" within content on beta.get.gov. And we may want to reference that function within future blog posts and emails. These links should point to the page Choosing your .gov domain name, where the new check availability section will live. The functionality of the button would behave the same way as the home page and the request form. There will have to be some tweaks to content so they make sense in context of the page.

### Acceptance criteria

- [x] Design a section for checking domain availability on beta.get.gov/domains/choosing
- [x] Create and/or link dev ticket

### Additional context
See this [Slack thread ](https://cisa-corp.slack.com/archives/C03QM0JGSQG/p1701210771816299)with the rationale behind this approach

### Links to other issues
dev ticket: #1693

**Comment by Katherine-Osos** [comment]
Moved this back to "next." See [slack thread](https://cisa-corp.slack.com/archives/C03QM0JGSQG/p1701210771816299) with decision.

**Comment by gabydisarli** [comment]
[Design review Slack thread](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1705088461613369)
