### ISSUE TITLE
Design: Expose WHOIS / registry info on beta.get.gov

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1221]
### Story

As a domain manager or registrant
I want an easy way to check registry info for a domain
so that I don't have to go to another site for that function.

### Acceptance Criteria

Design a way for users to view WHOIS / registry info on beta.get.gov

### Additional Context

Slack [thread](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1698353203577369)

This info could potentially be added to the dedicated check availability page created in this ticket: #1219

### Issue Links

Related to #1259

**Comment by h-m-f-t** [comment]
(Not transferring this issue to getgov-home since a core part of the work seems like to be done registrar-side, not solely getgov-home.)

**Comment by gabydisarli** [comment]
[Design review slack thread](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1705088461613369)
