### ISSUE TITLE
Fix typo on DNSSEC page

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1230]
### Issue description

There is a typo (missed word) in the paragraph on the DNSSEC page. I missed it reviews. Let's get this to be grammatically correct.

![Screenshot 2023-10-30 at 12 09 29 PM](https://github.com/cisagov/getgov/assets/107440934/c2067762-195c-4fa6-9ee3-d3dc75b23922)
It should say

> DNSSEC, or DNS Security Extensions, is **an** additional security layer to protect your website. Enabling DNSSEC ensures that when someone visits your website, they can be certain that it’s connecting to the correct server, preventing potential hijacking or tampering with your domain's records.

note: the word on the page should not be bolded. I've bolded it here to add emphasis for where the word needs to be added.

**Comment by therealslimhsiehdy** [comment]
Completed in [this PR](https://github.com/cisagov/manage.get.gov/pull/1233)

**Comment by therealslimhsiehdy** [comment]
Completed in [this PR](https://github.com/cisagov/manage.get.gov/pull/1233)
