### ISSUE TITLE
Increase Linter line length

### ISSUE THREAD

**Issue by CocoByte** [cisagov/manage.get.gov#1231]
### Issue Description
Increase linter's line-length allowance from 80 chars to 120 chars.

### Acceptace Criteria
- [ ] Linting with black allows 120char line lengths
- [ ] Running the linter allows 120char line lengths

**Comment by therealslimhsiehdy** [comment]
Quick add on from Engineering Huddle Notes, the fix should be pretty quick, see below:

`pyproject.toml: line-length=88` -> `pyproject.toml: line-length=120`
