### ISSUE TITLE
Content review support: Generate list of manage.get.gov URLs

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/manage.get.gov#1244]
### Issue description

We're planning to review all HTML pages on manage.get.gov this means the designers need a list of all the URLs on the websites. 

Devs mentioned a few ways they could generate a list of URLs (Django urls.py, URL map/route table, pick one domain instance and generate a list of subpages). 

### Acceptance criteria

- [ ] List of URLs for manage.get.gov. This should include database-backed content (e.g., /domains/7). 

### Additional context

[Preferred location for content spreadsheet](https://drive.google.com/drive/folders/1jnRIBcr1ZhI0BFq0i6l21X0lIOtUCIPD) 

Ensure that everyone doing content review has access to the domain: Katherine, Gaby, Michelle, Kristina.
Choose a representative set of domains to review the HTML for each view. (For example, domain requests are not shared across different users). Use staging when picking a domain

example of list
/domain
/domain/xxx/dns/nameservers
/domain/xxx/org-name-address
etc.

### Links to other issues

The URLs gathered via this ticket are needed for #1240

**Comment by zandercymatics** [comment]
This is located here:
https://docs.google.com/spreadsheets/d/107SrG3wu88o1CYMyz_nKeTIzu8WRRyDtiGX_lYDoSN0/edit?usp=sharing
