### ISSUE TITLE
Content review support: Generate error messages for manage.get.gov

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/manage.get.gov#1247]
### Issue description

We're planning to review all error messages on manage.get.gov. 

Devs suggested writing a script to generate a spreadsheet of messages in application_wizard.py. We understand that this would not capture all error messages.

### Acceptance criteria

- [ ]  Error messages (as many as can be generated automatically) in a way that allows reviewers to review content and formatting 

### Additional context

[Preferred location for content spreadsheet](https://drive.google.com/drive/folders/1jnRIBcr1ZhI0BFq0i6l21X0lIOtUCIPD)

### Links to other issues

Error message gathered via this ticket will be reviewed in #1287

**Comment by dave-kennedy-ecs** [comment]
Link to the error messages spreadsheet:
https://docs.google.com/spreadsheets/d/1hF7_n_zo3EpfbgqqqPUMtSMZXynMtRMsBMlcIqZ91ns/edit?usp=sharing

**Comment by PaulKuykendall** [comment]
@dave-kennedy-ecs  - this is "done" may we close?

**Comment by h-m-f-t** [comment]
Completed via #1287
