### ISSUE TITLE
Content review support: Generate email messages from the registrar

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/manage.get.gov#1248]
### Issue description

We're planning to review all email messages that will be sent from the registrar. However, for designers/content team there is not an easy way to see the emails with all the formatting that appears.  

Devs suggested that they could walk through the process of approving/rejecting a domain request to generate the system emails and then copy them to a folder or send them to a team email. We also need easy to read documentation on how to do this so designers can do this on their own next time.

NO CODING NEEDED HERE
### Acceptance criteria

- [ ] All auto-generated emails are sent to a team email or made available in a way that allows reviewers to review content and formatting
- [ ] Update documentation with step by step instructions on how to follow a path that results in generating each email. This should be easy enough for someone who is not a developer to understand. 
- [ ] update the [state flowchart ](https://miro.com/app/board/uXjVMuqbLOk=/)if anything is found that violates what actually happens 

### Additional context

[Preferred location for content spreadsheet or other output](https://drive.google.com/drive/folders/1jnRIBcr1ZhI0BFq0i6l21X0lIOtUCIPD)

Note the flow chart doesn't include domain invitations to manage a domain, but that email should also be sent to design as part of this

### Links to other issues

This ticket is necessary to complete #1286

**Comment by zandercymatics** [comment]
Setting ticket to "done" per approval from Katherine
