### ISSUE TITLE
New log in flow for domain managers (transition experience)

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1251]
### Story

As a domain manager
I want to understand that in order to manage my domains I will be logging in with Login.gov 
so that I am not surprised when I am taken to a new page 

### Acceptance Criteria

- [ ] new flow is designed
- [ ] dev tickets for implementation work created

### Additional Context

This story comes out of our previous work designing the the new experience #950 for users transitioning from the old system to our new system. The flow from log in to manager dashboard will be changing, and instead of using a in-site login feature or page we'll be using login.gov's sign in service. [This document outlines text changes for the .gov login page](https://docs.google.com/document/d/17nKEmFy9uUauE_NxlP4H_dtzo10HYWXasfZlTJiNKuo/edit#heading=h.xbsz0zbe1fz5) and also shows some examples below of other agencies flows using login.gov's service. Note that the login.gov text updates (and other changes) are being tracked in #1144 , #1143 , and #1194

**Potential changes**
1. An interstitial page between get.gov and manage.get.gov with login options like SSA's. These buttons have the logos for the respective services (login.gov; id.me). 
2. A modal on clicking "manage my domains" like the FAC's website, which tells the user that .gov uses login.gov to authenticate.
3. A smaller change: Add the login.gov logo to the "manage my domains" button on the home page ([Figma link](https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&node-id=1451%3A74734&mode=design&t=9Y3UmJoLl6Uj6QWD-1))

### Issue Links

Login.gov text updates and other transition experience changes are being tracked in #1144 , #1143 , and #1194

**Comment by gabydisarli** [comment]
**Note for planners:** This ticket is to replace #1146 which I am closing as a won't do, since new proposals for this experience have been suggested

**Comment by h-m-f-t** [comment]
I like option 2, but only if it's temporary or we cookie it. 3 is a maybe, but I agree with @michelle-rago's concern that we don't want users to think they're using login.gov to _manage_ their domains. Will discuss in refinement.

**Comment by gabydisarli** [comment]
@h-m-f-t For option #3 when Ryan and I were initially noodling on how to incorporate the login.gov logo with the manage my domains button we thought about changing the wording and design so that the logo didn't imply managing your domain. This was a rough draft that was left on the chopping block.


![Image](https://github.com/cisagov/manage.get.gov/assets/107440934/7a3e3034-5a54-4aee-9fd3-9652fbb43fd8)

After hearing concerns about the previous design, I'm wondering if some version of this satisfies both needs (more passive engagement while not conflating domain management with login.gov).

**Comment by h-m-f-t** [comment]
Gaby, I really appreciate you taking the time to think through how users would feel about an authentication transition, and I'm sorry for letting this one sit so long. 

I think the moment for this issue has passed. We provided all domain managers with emails that outlined they'd need to use Login.gov, and though we received many (many!) emails about what Login.gov was asking from them, none were confused about what it was or why they were directed there before accessing their domain.

Ultimately, I think this one is largely solved by the content we provided users and by the Login.gov capture page that shows when trying to authenticate at manage.get.gov.

I'm going to close this issue, but if you feel strongly that we've missed something, please re-open it.

**Comment by gabydisarli** [comment]
> Gaby, I really appreciate you taking the time to think through how users would feel about an authentication transition, and I'm sorry for letting this one sit so long.
> 
> I think the moment for this issue has passed. We provided all domain managers with emails that outlined they'd need to use Login.gov, and though we received many (many!) emails about what Login.gov was asking from them, none were confused about what it was or why they were directed there before accessing their domain.
> 
> Ultimately, I think this one is largely solved by the content we provided users and by the Login.gov capture page that appears when trying to authenticate at manage.get.gov.
> 
> I'm going to close this issue, but if you feel strongly that we've missed something, please re-open it.

I'm totally cool with that. Michelle's work on #547 will help to inform new users of the login.gov requirement before they land on the login page (when starting a new domain request) so I'm happy. 😄
