### ISSUE TITLE
Bug on name servers page

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1252]
Not sure if it's a bug, but, if I enter the two name server minimum, hit save, and then copy on name server into the 1st or 2nd field I'm able to save without getting the "minimum 2 required" error message.

_Originally posted by @gabydisarli in https://github.com/cisagov/manage.get.gov/issues/1236#issuecomment-1791454411_
            

Expected behavior:
On Name server page: 

New error message that says: 

Remove duplicate entry (field-level & top of page) + forcing the 2 minimum error if they have less than 2 name servers.

**Comment by PaulKuykendall** [comment]
This allows you to save with, effectively, only ONE name server. However, the status remains "DNS Needed"

**Comment by PaulKuykendall** [comment]
https://cisa-corp.slack.com/archives/C05BDEA3C11/p1699024500799679
