### ISSUE TITLE
Conditionally/Dynamically show urbanization field for Puerto Rico

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1261]
### Issue description

On the "Organization name and mailing address page," the data field referencing "Urbanization" should be visible ONLY when the "State, territory, or military post" is set to Puerto Rico. Otherwise, this field should not be shown.

![Image](https://github.com/cisagov/manage.get.gov/assets/62573986/86cf27ad-2ee9-482c-9eab-d2f03f5ae176)

If Urbanization data exists for an organization, and the "State, territory" field is changed to a non-Puerto Rico value, that data should be deleted from the table. (If the user subsequently changes the "State, territory" field back to PR, then they will need to re-enter the Urbanization data.

### Acceptance criteria

- [ ] When "State..." field is set to Puerto Rico, the Urbanization field is visible and available, otherwise the Urbanization field is not presented on the page
- [ ] When "State" field is changed from PR to a non-PR value, the Urbanization field data is deleted from the db. 
- [ ] This rule applies to both the domain request organization page, as well as the manage domain organization page.

### Additional context

[Miro Research Board](https://miro.com/app/board/uXjVNZhbw-s=/?openComment=3458764567842574552)
[Insights repository reference](https://docs.google.com/spreadsheets/d/1BIMwEe1YX_iJkRmE9nX7xmYTbfOtNefQyZshh3m8jZE/edit#gid=1604909472&range=E23) (converted to this ticket)

Interesting information about urbanization in Puerto Rico: ["In Puerto Rico, identical street names and address number ranges can be found within the same ZIP Code. In these cases, the urbanization name is the only element that correctly identifies the location of a particular address."](https://pe.usps.com/text/pub28/28api_008.htm#:~:text=In%20Puerto%20Rico%2C%20identical%20street%20names,the%20location%20of%20a%20particular%20address.&text=In%20Puerto%20Rico%2C%20identical,of%20a%20particular%20address.&text=Rico%2C%20identical%20street%20names,the%20location%20of%20a)

**Comment by gabydisarli** [comment]
@vickyszuchin Alysia asked me to bring in this ticket to the Org model work since I will be adjusting this field for Org model users. It wont show to federal agencies.

**Comment by vickyszuchin** [comment]
Slotted it into sprint 50 which #2377  is in.

**Comment by vickyszuchin** [comment]
Currently being worked. Adding to current sprint.
