### ISSUE TITLE
Show error on Django admin if approving a domain with a duplicate name

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#1263]
### Issue description

A domain request can not be approved by an analyst if a domain was already approved with that identical name. In this case, when an analyst goes to approve the  duplicate domain request on django admin, they get an ugly 500 error with no information as to what happened.

### Acceptance criteria

- [ ] if an analyst tries to approve a domain request with a domain name that is already in use (and not deleted) show an error message not a 500 error. The domain request should not move to approved in this case.
- [ ] the content of the error message should be "The domain name for this request is already in use. The name will need to be updated before this request can be approved."

**Comment by abroddrick** [comment]
@Katherine-Osos I am thinking this would just be an error that explains "The domain name selected is already in use, please select an alternative domain name on this application before approving." Or something like that. Do you want a separate content ticket, or do you think since it's a one liner the designer PR reviewing can just comment on the PR with what language they prefer?

**Comment by abroddrick** [comment]
@Katherine-Osos retagging for the question above

**Comment by Katherine-Osos** [comment]
It seems worthwhile to alert the analyst long before they approve. Like some sort of flag that appears on the request when more than one request has the same name. Do we have a ticket for something like that?

As for error messaging, let's try: 

> The domain name for this request is already in use. The name will need to be updated before this request can be approved.

**Comment by PaulKuykendall** [comment]
@abroddrick - is this overcome by events? Or do we still need to consider?

**Comment by abroddrick** [comment]
Missed this tag. @Katherine-Osos no we do not have a ticket for adding some sort of flag on the domain request if the name is a duplicate of something else that is approved. We would need a new ticket for that. Copying the content for the error message Katherine mentions above into the AC

**Comment by abroddrick** [comment]
@katypies pies, why does this have a bug tag? This is a new feature beyond things initially planned, not a feature that is not operating as designed. I would like to remove the "bug" label as it is a bit misleading.
