### ISSUE TITLE
Update the Domain creation date if out of sync with registry

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#1267]
### Issue description

We are storing the domain creation date, but currently it is only populated for transition domains. For new domains, such as those made when new applications are approved, we need to make sure this creation date gets populated as well. To do this, anytime we get the creation date from the registry we can just check if our stored created_at date is the same as the registry's, and if not, we set ours to be that of the registry.

### Acceptance criteria

- [ ] creation date is set on the domain if out of sync with the registry and is set the value received from the registry
- [ ] unit test

**Comment by PaulKuykendall** [comment]
@abroddrick - This is "Done," may we close??

**Comment by h-m-f-t** [comment]
Completed in #1492
