### ISSUE TITLE
DNSSEC page show error if trying to add a different .Gov as a nameserver

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#1268]
### Issue description

Currently, if you add a nameserver that ends in .gov with no ip address filled in, no error shows on the field when you click save. Instead you get the registry error message at the top of the screen and the line you entered just goes away.  We should add a simple check on the nameserver fields so that if they end in .gov they get a field level error.

### Acceptance criteria

- [ ] add a check for a '.gov" that is not a subdomain of the current domain in the nameserver fields and provide an error on save to indicate that this is blocked.

### Additional context

Cloudflare doesn't allow .govs as nameservers without a ips, and we don't allow other .gov nameservers in general.

**Comment by abroddrick** [comment]
@Katherine-Osos or @gabydisarli does this also need a corresponding content ticket for the error message?

**Comment by h-m-f-t** [comment]
@abroddrick This is a bug, as a number of agencies serve as the DNS host for other agencies. 

> Cloudflare doesn't allow .govs as nameservers without a ips, and we don't allow other .gov nameservers in general.

This is happening now, though? Check out coldcaserecords.gov.

**Comment by abroddrick** [comment]
Closing as we have determined it will only throw an error if you add a host for another .gov that does NOT already exist in the zone. If it does exist currently then you can add it just fine.
