### ISSUE TITLE
UX: Improve Django Admin layout of "Domain Change" page

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1269]
### Issue description

During analyst usability research, some improvements were requested to the layout of the /admin/registrar/domain/xxx/change/ page:

- [ ] Remove the “.gov domain” section heading. There’s a “.gov domain” section on the “Domain’s” page that doesn’t display any information. It’s currently blank because that section only applies to “Domain applications.” We should remove this so that analysts don't think that there is missing information.

- [ ] Make the section headings bold. One analyst noted that the section headings were difficult to read against the blue bars on the “Domains” page. He thought bolding the font would help so that the headings are more easily read.

- [ ] OPTIONALLY (idea/insight): Clarify which fields are editable: One analyst didn’t immediately understand which fields were editable. There may be an opportunity to adjust the visual indicators for this function, so that analysts know where they can make changes.

![Image](https://github.com/cisagov/manage.get.gov/assets/62573986/606f4b16-42af-4805-b6c9-92fe563c1a5f)

### Additional context

[Miro Research](https://miro.com/app/board/uXjVNZhbw-s=/?openComment=3458764569047770366)

**Comment by katypies** [comment]
@PaulKuykendall  I think we should close this as wont-do -- we have some newer tickets/issues for how to structure the domains for Analysts, which may end up making this redundant. Seems like our newer work is likely to aim to address this. Thoughts?

**Comment by abroddrick** [comment]
@katypies, not Paul, but I agree we should close this as a won't do. It's expensive with no real gain.
