### ISSUE TITLE
UX: Add columns to "Select a Domain" view in Django Admin

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1270]
### Issue description

During Usability research, analysts indicated that the "Select a Domain" page view would be more useful if additional columns were easily visible.

The analysts suggested adding these columns to the “Select a domain” table to help with their analysis:
- Domain creation date / Date of approval
- Federal branch
- U.S. state
- Expiration date
- Submitted by
- Authorizing official

![Image](https://github.com/cisagov/manage.get.gov/assets/62573986/0a88e8e7-31ae-44db-9895-5f8e5571f6ff)

### Additional context

[Miro Research Board](https://miro.com/app/board/uXjVNZhbw-s=/?openComment=3458764569050258538)

**Comment by Katherine-Osos** [comment]
@PaulKuykendall @katypies Closing this ticket because we already added these columns to the "domains" page within the admin.
