### ISSUE TITLE
Django Admin: Remove "Get registry status" button

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1272]
### Issue description

It was suggested that we remove the “Get registry status” button from the “Domains” page. Analysts will not need this status and, if they do, they can do a WHOIS lookup separately.

![Image](https://github.com/cisagov/manage.get.gov/assets/62573986/829958f8-d505-442e-8a8d-a3a9b37a07fd)

### Acceptance criteria

- [ ] "Get registry status" button is no longer present on the "Change domain" (/admin/registrar/domain/xxx/change/) page

### Additional context

[Miro Research](https://miro.com/app/board/uXjVNZhbw-s=/?openComment=3458764568087182709)

**Comment by PaulKuykendall** [comment]
This is still valuable for troubleshooting. Maybe keep it in a better place.

**Comment by katypies** [comment]
@PaulKuykendall  @h-m-f-t - this seems like one we could close. It seems useful for troubleshooting right now, but suggests broader changes to our display and decision support rather than just removing this button. Thoughts?

**Comment by h-m-f-t** [comment]
Yeah, we can drop this.
