### ISSUE TITLE
Django Admin, dynamically display fields based on Org Type

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1273]
### Issue description

Currently, all fields related to any organization type are displayed on the “Domains” page. We should update this to only expose fields related to the selected org type for a domain.

For example, if "Federal" org type is selected, the user should not see "Tribal" subfields in "Type of organization" section.

![Image](https://github.com/cisagov/manage.get.gov/assets/62573986/60dc36bb-9c66-4dbe-8095-cfb02aaea897)

### Additional context

[Miro research](https://miro.com/app/board/uXjVNZhbw-s=/?openComment=3458764568091712070)

**Comment by Katherine-Osos** [comment]
@PaulKuykendall This is a duplicate with #1042, so I think this one can be closed. (The other ticket provides more detail, so I'd keep that one)
