### ISSUE TITLE
UX: Django Admin: Protect multi-select fields from being de-selected inadvertently.

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1276]
### Issue description

Multi-select entries appear in a scrollable container and, if you click that container to adjust the entries, they all get removed. This is a frustrating user experience and could result in data errors.

For example, given that three names are selected and saved.

![Image](https://github.com/cisagov/manage.get.gov/assets/62573986/4d945a09-6ee6-48e9-a3fc-f406a3d3f53c)

If the user is navigating the form, and clicks back into this field, it will de-select ALL the previous choices, resulting in possible information (linkage) loss, and frustration trying to remember and reestablish the selections

![Image](https://github.com/cisagov/manage.get.gov/assets/62573986/05ffd0f8-4cf0-4766-bce0-2de3713ea8b5)

### Acceptance criteria

- [ ] When clicking into a multi-select input field, the previous selections are preserved, and the user may make further selections/deselections.

### Additional context

[Miro Research board](https://miro.com/app/board/uXjVNZhbw-s=/?openComment=3458764568092147281)

**Comment by Katherine-Osos** [comment]
@PaulKuykendall I believe this ticket can be closed. It was addressed in #1073
