### ISSUE TITLE
Django Admin: Clarify language and terms in several places

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1277]
### Issue description

Unfamiliar terms: There were a handful of terms that caused confusion in the admin. Some of the confusion may be cleared up with training and usage of the system, but we should identify ways to make the terms more understandable:
- users vs. contacts
- “unknown” status
- domain information vs. domain application
- creator
- draft domains
- state (currently used for domain status rather than U.S. state). 

### Additional context

[Miro research board](https://miro.com/app/board/uXjVNZhbw-s=/?openComment=3458764568091282270)

**Comment by PaulKuykendall** [comment]
Get a little more experience from the analysts' usage of the system.

**Comment by h-m-f-t** [comment]
I think I'm not blocking this anyone but I'll leave the PO label on until someone says otherwise. =)

**Comment by Katherine-Osos** [comment]
@h-m-f-t You're no longer blocking! I'll remove the PO label.
