### ISSUE TITLE
Change URL path for domain requests from "register" to "request"

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1288]
### Issue description

Currently, the "Request a domain" process involves a URL subdirectory named /register. This should be changed everywhere so that it is not implied that a user is actually registering a domain, but is rather just requesting a domain.

![Image](https://github.com/cisagov/manage.get.gov/assets/62573986/5f0ce4f9-390c-423e-8abd-84632a91c4bc)

### Acceptance criteria

- [ ] When Requesting a new domain, the user sees the URL /request/dotgov_domain.
- [ ] Ensure that any and all links or buttons targeting these pages still work.
- [ ] pa11y scans links and other sections may need updates as well to accomodate

### Additional context

Per conversation with Michelle, late Oct/early Nov.

**Comment by rachidatecs** [comment]
!!!!!!
This involves changing things in manage.get and in beta.get. 2 PRs
!!!!!!
