### ISSUE TITLE
Design operations: Audit Figma file

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1295]
### Issue description

Audit the Figma file and document inconsistencies between the file and what's in production. 

### Acceptance criteria

- [x] Create a document for the audit so we can track the work and make sure all updates get made. This document should result in a list of updates needing to be made.
- [x] Create any follow on tickets breaking up the update work into manageable chunks ie. the request form, domain management, info site, etc.

### Additional context

The Figma file is out of date and doesn't always match what's in production. This leads to doubled efforts when designers have to make updates to a screen that hasn't been kept up to date in Figma. The Figma should have parity with what's in production so devs and designers know that the Figma is correct and can be trusted. 

### Links to other issues

- [ ] #1957 
- [ ] #1958 
- [ ] #1959 
- [ ] #1960 
- [ ] #1961 
- [ ] #1963 
- [ ] #1964 
- [ ] #1966 
- [ ] #1967 
- [ ] #1968 
- [ ] #1969 
- [ ] #1970 
- [ ] #1971 
- [ ] #1972 
- [ ] #1973

**Comment by kristinacyin** [comment]
We need to move the Figma files from Truss to CISA workplace, so it might make sense to audit + update the Figma files as we move them

**Comment by gabydisarli** [comment]
[Discussion notes](https://docs.google.com/document/d/1moiKfLuFP9Kho5cZvk2XWgx6ZabEC0sYzMwiwjduNis/edit?usp=sharing)

**Comment by rileyorr** [comment]
The audit is in progress in the form of [a spreadsheet in Google Drive](https://docs.google.com/spreadsheets/d/10OMqnuahDxS5cLfU8u2NIgLNWHbW_A75w_0V4tw2UPs/edit?usp=sharing) but hasn't yet been shared out to the design team.

**Comment by rileyorr** [comment]
Finished the audit this morning! I will schedule time to review the audit with Katherine, Gaby, and Kristina. I'd like their feedback and perspective on some of my findings and open questions prior to creating tickets.

**Comment by gabydisarli** [comment]
@rileyorr Everything looks great! Can you link all the tickets created as a result of this work to this ticket under the "Links to other issues" section. That way it's easy to see them all at a glance.

**Comment by h-m-f-t** [comment]
@gabydisarli I just did that! Looks great. cc: @rileyorr

**Comment by rileyorr** [comment]
@h-m-f-t thank you for linking those tickets! @gabydisarli let me know when I'm good to close this ticket
