### ISSUE TITLE
Handle long strings inputted in domain availability search

### ISSUE THREAD

**Issue by erinysong** [cisagov/manage.get.gov#1304]
Detailed in [PR#100 for get.gov](https://github.com/cisagov/getgov-home/pull/100).

- [ ] Handle edge case of a user inputting a very long domain name. The alert should truncate the domain name, `verylongdomainstraing12345567889` into something like `verylongdomainnamest....gov` and include aria-text displaying the full domain name upon hover.

_Originally posted by @erinysong in https://github.com/cisagov/manage.get.gov/issues/476#issuecomment-1802816996_

**Comment by PaulKuykendall** [comment]
Edge case, so deferring for a bit. Moved to Next
