### ISSUE TITLE
Update getgov-home availability base URL from staging to stable

### ISSUE THREAD

**Issue by erinysong** [cisagov/manage.get.gov#1306]
[PR#100 in getgov-home for additional context
](https://github.com/cisagov/getgov-home/pull/100)

Update API base URL from staging link to stable link after Cloudflare migrates its data 11/15/2023.
Currently beta.get.gov pulls data from the registrar's staging environment (https://getgov-staging.app.cloud.gov/api/v1/available/) because the registrar's stable environment API is not accurate until Cloudflare migrates data on Wednesday, November 15, 2023. Once Cloudflare updates its migrations, we will need to update the base URL to the stable environment (https://manage.get.gov/api/v1/available/

_Originally posted by @erinysong in https://github.com/cisagov/manage.get.gov/issues/476#issuecomment-1802873524_

**Comment by therealslimhsiehdy** [comment]
Additional notes:

* Add the baseURL to a constants file or as an env variable in package.json

See [Slack comment here ](https://github.com/cisagov/getgov-home/pull/100#discussion_r1387992448)
