### ISSUE TITLE
Remove redundant .gov in domain availability alert when input in search

### ISSUE THREAD

**Issue by erinysong** [cisagov/manage.get.gov#1307]
[PR#100 in getgov-home for additional context
](https://github.com/cisagov/getgov-home/pull/100)

Remove the redundant .gov added when a user inputs a domain name with .gov into the search input.

![image](https://user-images.githubusercontent.com/121973038/281568150-d116bd24-0fbb-4689-829f-6b5a5ea75539.png)

_Originally posted by @erinysong in https://github.com/cisagov/manage.get.gov/issues/476#issuecomment-1802874800_

**Comment by therealslimhsiehdy** [comment]
I'm going to throw the AC into this ticket (can make another ticket if needed later):

We just want to make sure that with when a user puts in search input that when they hit the "enter" button, it'll click the check availability button instead of refreshing the page!
