### ISSUE TITLE
Remove second "Start a new domain request" button in manage.get.gov's dashboard

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1309]
### Issue description

On the domains dashboard. If a user has 0 domain requests, they see the "Start a new domain request" button twice: once at the top of the page under the header, and again in the domain requests section. Since a large majority of our users might only have one domain and 0 requests going, let's remove the second button. It's already a very prominent button, and having it twice adds visual clutter to the page.

![Screenshot 2023-11-09 at 11 58 31 AM](https://github.com/cisagov/manage.get.gov/assets/107440934/e69b2e7f-d7d9-46c0-99fb-deb5b14d6ba3)

### Acceptance criteria

- [ ] Remove the second "Start a new domain request" button

### Additional context

We discussed dropping this button just from production so we can include it in our November launch. This would leave it in for the future. If it's not too much effort, let's drop the button completely. (cc: @abroddrick)

### Links to other issues

🔄 Related to issue https://github.com/cisagov/manage.get.gov/issues/1194, PR https://github.com/cisagov/manage.get.gov/pull/1256

**Comment by abroddrick** [comment]
Agreed with dropping the button completely given that is the design input!
