### ISSUE TITLE
Update initial email to domain managers if organization address doesn't get migrated

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/manage.get.gov#1310]
**Issue description**

If organization address does not get migrated we need to change the domain invitation email.

Change this line in the domain invitation email from

> After verifying who has access to your domains, we also suggest reviewing your contact information and organization mailing address to ensure those are up to date.

To

> After verifying who has access to your domains, review your contact information to make sure it’s up to date.

**Acceptance criteria**

- [ ] Domain invitation email does not reference an organization's mailing address

**Related to**
#1293

**Comment by PaulKuykendall** [comment]
Urgent: Must be done by Monday, Nov 13th, 2023.
