### ISSUE TITLE
"Enter" submit clicks button instead of page refresh 

### ISSUE THREAD

**Issue by therealslimhsiehdy** [cisagov/manage.get.gov#1318]
### Issue description

Taking from [a different ticket comment](https://github.com/cisagov/manage.get.gov/issues/1307#issuecomment-1804297616) so it's separated into it's own ticket

We want to make sure that with when a user puts in search input that when they hit the "enter" button, it'll click the check availability button instead of refreshing the page

### Acceptance criteria

- [ ] When user clicks "Enter" on their keyboard, they see the alerts instead of a page refresh

### Additional context

https://github.com/cisagov/getgov-home/pull/100

### Links to other issues

User submitted issue: https://github.com/cisagov/getgov-home/issues/145

**Comment by gabydisarli** [comment]
@CocoByte note that this behavior is also happening on the request form as well as beta.get.gov cc: @h-m-f-t
