### ISSUE TITLE
Track and report priority metrics

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/manage.get.gov#1320]
- [x] Determine how priority metrics will be tracked
- [x] Create tickets for needed dev work
- [ ] Decide which metrics should be made public
- [ ] Decide how public metrics will be shared/exposed
- [ ] Create tickets for design work

[Key metrics are prioritized in this spreadsheet](https://docs.google.com/spreadsheets/d/1jEI2Vuy76HnRQoFnV5HbFrKrvlsbU07iWz7wTt2RZDQ/edit#gid=0)

[Convo with @abroddrick re: tracking the amount of time it takes to complete a domain request](https://gsa-tts.slack.com/archives/C05BDEA3C11/p1706905023794509).

Related Issues:
Related to: #1789 (dev ticket for top four desired metrics)

**Comment by abroddrick** [comment]
@michelle-rago can you provide more information here? Not sure how this got through refinement, but I wouldn't know what to do here without asking what this is about.

**Comment by michelle-rago** [comment]
@abroddrick We identified [key metrics and prioritized them](https://docs.google.com/spreadsheets/d/1jEI2Vuy76HnRQoFnV5HbFrKrvlsbU07iWz7wTt2RZDQ/edit#gid=0). The next step is to select a few metrics to figure out how to track and report them (e.g., Number of domains that don’t have any managers who logged in to the new registrar). 

It would be useful to know if the metrics marked as high priority are things we're able to track now or if they will require dev work.

**Comment by PaulKuykendall** [comment]
AI: @PaulKuykendall - schedule a meeting with @michelle-rago to get traction on this, and get some tickets created and prioritized.

**Comment by h-m-f-t** [comment]
This issue's A/C's aren't 100% complete, but we started initial work on this and have plans to revisit it regularly. I'm closing for now.
