### ISSUE TITLE
Manage domain: Add domain name above registrar navigation

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1331]
### Issue description

Django Admin > Domains page: When click “Manage domain” which bumps to registrar view, the domain name isn’t showing above the left navigation. If an analyst navigates away from the overview page, it’s not clear which domain they’re viewing. This could be particularly problematic if they have multiple tabs open and are reviewing multiple domains. 

Note: When viewing as a registrant (i.e. not going thru the admin), the domain name displays above the left nav. We should do the same for the analyst view.

![Image](https://github.com/cisagov/manage.get.gov/assets/119689946/655034e5-1cc8-4ddf-ae73-740b33d7936c)

### Acceptance criteria

Show domain name above the left navigation when viewing a domain via the admin portal

**Comment by PaulKuykendall** [comment]
I made this MVP because of the confusion it could cause. Would like to hear additional feedback @gabydisarli, from our Analysts. But this seems important.

**Comment by vickyszuchin** [comment]
@therealslimhsiehdy Katherine is unable to reproduce this. Would you do the final confirmation that it has been fixed?

**Comment by therealslimhsiehdy** [comment]
AC could not be reproduced, see [Slack discussion here](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1702034014174519)!
