### ISSUE TITLE
Federal domains with null domain_agency values

### ISSUE THREAD

**Issue by erinysong** [cisagov/manage.get.gov#1346]
### Issue description

There are 11 federal domains that do not have a listed domain agency. These domains should all have an associated federal agency as listed in [dotgov-data](https://github.com/cisagov/dotgov-data/blob/main/current-full.csv).

These values should be corrected in the registrar database to accurately reflect dotgov-data.

### Domains without a listed federal agency
Domains on the same bullet point lead to the same web address
- voa.gov
- fpisc.gov
- tsp.gov, exploretsp.gov, tsptest.gov (broken link)
- frtib.gov, frtibtest.gov
- usagm.gov, ibb.gov, bbg.gov
- fd.gov

### Steps to Recreate
1. ssh into stable: `cf ssf getgov-stable`. Enter shell and then run `./manage.py shell`.
2. Run the below queries in shell:
```
>>> info = DomainInformation.objects.all()
>>> federal_without_agency = info.filter(organization_type="federal").filter(federal_agency=None)
>>> federal_without_agency
[ should return a QuerySet with 11 domains without an agency ]
```

### Acceptance criteria

- [ ]  use values stored at https://github.com/cisagov/dotgov-data/blob/main/current-full.csv to change federal_agency on DomainInformation for the 11 domains here. Best to do this manually for speed.
- [ ] This is done on stable  
- [ ] visually check that all have been updated correctly

**Comment by therealslimhsiehdy** [comment]
This has been completed, see thread here - https://cisa-corp.slack.com/archives/C056K5ZJ48L/p1700151311242299
