### ISSUE TITLE
Explore and configure caching options can still work well with our application

### ISSUE THREAD

**Issue by neilmb** [cisagov/manage.get.gov#1371]
### Issue description

During launch, we forced all caching off by including `Cache-Control: no-cache` headers on every response. This is more draconian than we need. In particular, it means that every static resource from `/public/...` is hitting our Django application inside of Cloud.gov. We already use a Django plugin called `whitenoise` that can do hash-based linking to static assets so that they can be cached forever by Cloudfront. (If the content changes, then the hash changes, then it results in a different filename.)

We should configure Whitenoise to use this compressed and hashed storage backend https://whitenoise.readthedocs.io/en/latest/django.html#add-compression-and-caching-support and then relax our global `Cache-Control: no-cache` fix to allow these static files to be cached by Cloudfront.

### Acceptance criteria

- [ ] Configure Whitenoise to use the compressed/hashed storage backend for static files
- [ ] Adjust our Cache-Control fix to not apply to paths inside of `settings.STATIC_URL`
- [ ] Test to be sure that Cloudfront caching is working on stable so that requests for e.g. `/public/img/usa-icons/launch.svg` are being handled by Cloudfront and never appearing in our Django application at all.

### Additional context

This is an optimization for performance that is probably quite unnecessary, but would generally be a best practice and it seems like we are close to a solution. Perhaps this effort would be best as a timeboxed exploration to see if we can succeed and take notes on what we learn.

**Comment by therealslimhsiehdy** [comment]
Who you're gonna call? CACHE BUSTERS

Helpful links:

- https://cloud.gov/docs/services/external-domain-service/
- https://cloud.gov/docs/management/custom-domains/
- https://whitenoise.readthedocs.io/en/latest/django.html#add-compression-and-caching-support

**Comment by CocoByte** [comment]
Analysis of load times:

If we look at [average load times in Kibana](https://logs.fr.cloud.gov/app/visualize#/create?_a=(filters:!(),linked:!f,query:(language:lucene,query:''),uiState:(),vis:(aggs:!((enabled:!t,id:'1',params:(customLabel:'Average%20Response%20Time%20in%20ms',field:rtr.response_time_ms),schema:metric,type:avg),(enabled:!t,id:'2',params:(drop_partials:!f,extended_bounds:(),field:'@timestamp',interval:d,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:now-15m,to:now),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(addLegend:!t,addTimeMarker:!f,addTooltip:!t,categoryAxes:!((id:CategoryAxis-1,labels:(filter:!t,show:!t,truncate:100),position:bottom,scale:(type:linear),show:!t,style:(),title:(),type:category)),grid:(categoryLines:!f),labels:(show:!f),legendPosition:right,seriesParams:!((data:(id:'1',label:'Average%20Response%20Time%20in%20ms'),drawLinesBetweenPoints:!t,lineWidth:2,mode:stacked,show:!t,showCircles:!t,type:histogram,valueAxis:ValueAxis-1)),thresholdLine:(color:%23E7664C,show:!f,style:full,value:10,width:1),times:!(),type:histogram,valueAxes:!((id:ValueAxis-1,labels:(filter:!f,rotate:0,show:!t,truncate:100),name:LeftAxis-1,position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Average%20Response%20Time%20in%20ms'),type:value))),title:'',type:histogram))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-2w,to:now))&indexPattern=logs-app*&type=histogram), it looks like we are doing great, staying under 200ms (in the last 4 weeks) and usually hovering around 40-80ms.  Some google searching suggests that "an ideal page load time is between 0-2 seconds, but 3 seconds is also considered to be an acceptable score. Anything above 3 seconds increases the likelihood of visitors leaving your site." (Quote shamelessly copied from Sematex)

![Image](https://github.com/cisagov/manage.get.gov/assets/16280277/3175bb28-26d0-41b3-b345-7244f880e5e1)

**Comment by CocoByte** [comment]
Adding this clip from Alysia for documentation purposes.  A quick glance suggests our static resources typically take less than 10ms to load...


![Image](https://github.com/cisagov/manage.get.gov/assets/16280277/0f707dc3-0165-428a-8d32-91a1a680b146)
