### ISSUE TITLE
Availability endpoint on the request form not working

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#1378]
### Current Behavior

Entering any domain into the check domain availability box on the application workflow fails. 

### Expected Behavior

Domains that are available should result in a the green success message indicating that this domain is available to request.

### Steps to Reproduce

1. in the request form go to register/dotgov_domain/
2. enter a domain name that should be available
3. see that it shows red

### Additional Context

![image](https://github.com/cisagov/manage.get.gov/assets/109625347/817c81f8-521d-41b8-a185-f7153b642504)

**Comment by erinysong** [comment]
Would be interested in getting data on whose envs this is not working on - I know @kristinacyin was having issues with the availability endpoint consistently not working while others have been able to successfully use the availability check either immediately or with their own set of bugs

**Comment by erinysong** [comment]
Alysia reproduction: "The first block is the first attempt and the second block is the second time I used the endpoint, and then on the third attempt it worked."
![image](https://github.com/cisagov/manage.get.gov/assets/121973038/336320aa-25e0-4a28-b026-617de0ecb764)
