### ISSUE TITLE
Content: Confirmation when remove invitation for domain manager

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1379]
### Story

As a domain manager
I want clear confirmation that an invitation for domain manager has been revoked
so that I understand it happened successfully.

### Acceptance Criteria

If you add a domain manager that is not a current user of the registrar, the name gets added to an "Invitation" table. Within that table, there is the option to "Cancel" the invitation. Currently, if you click that Cancel button, the name is removed (and the table disappears if it was the only invitation) but there is no confirmation message. This is inconsistent with other actions within the registrar.

### Additional Context

- [x] Create confirmation message for when a domain invitation is "canceled"
- [x] Create dev ticket to implement the confirmation

### Issue Links

dev ticket: #1601

**Comment by gabydisarli** [comment]
We probably don't want to send an email to the recipient that their invite has been rescinded. This could be partially solved in the future when we incorporate the [history log](https://github.com/cisagov/manage.get.gov/issues/1466), so there's a paper trail for the domain manager, at least.

**Comment by gabydisarli** [comment]
Designs here: https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&node-id=3328%3A18978&mode=design&t=to1hzbCO8RVus9j0-1
