### ISSUE TITLE
Improper handling of IP address with blank spaces on DNS nameserver form

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1381]
### Current Behavior

User enters "1.1.    2.2" into the IP address field of a nameserver form in domain management

1. IP address is NOT stripping the blanks
2. "1.1.       2.2" is submitted as the IP address value on form
3. Throws the error, "Unable to update domain, changes were not applied. Check logs as a Registry Error is the likely cause"

### Expected Behavior

Enter '1.1.      2.2' into the IP address field of a nameserver form 

1. Blank spaces are stripped from the user entered IP address (code handles scenario)
2. 1.1.2.2 is submitted as the IP address value on form

### Steps to Reproduce

1. Enter an IP address with spaces (e.g., "1.1.        2.2.")

### Additional Context

Acceptance criteria:
- fix bug
- create unit tests to check for scenario (to prevent IP address form fields with spaces from causing EPP errors)

**Comment by dave-kennedy-ecs** [comment]
I think this is a bug.  The initial spec had all spaces removed before IP addresses were submitted to registry.  Which was originally implemented, and done silently from the user perspective, with no errors.  Somehow though, the spaces stopped being removed properly and now a non-descript error message is presented.  I think we should fix the bug, and add unit test to prevent this bug in the future.
