### ISSUE TITLE
Populate Staging data with "safe" production-level data

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1390]
### Issue description

As a delivery team working in the STAGING environment,
We want a representative dataset that has been sanitized of PII and other contact information,
So that we may fully exercise and test the system features without risking external, erroneous notifications or actions that could affect production operations.

### Acceptance criteria

- [x] STAGING environment has a dataset that closely resembles the production dataset in number of records and quantity of data.
- [x] In that STAGING data, all contact info (email and phone) has been altered so that no notification can be inadvertently sent to a real user.
- [x] Ensure that PII information of the 28 domains (that were added)  is removed on staging
- [x] brainstorm in refinement... other safeguards??? (Mangle names, for example)

### Additional context
Staging has been loaded with all original transition domains with all PII removed, however, when the original 28 domains were loaded onto staging they included PII, we should remove just the PII. As a one time thing, we could do this manually. 

### Links to other issues

relates to: #1373 (which indicates to the user that they are NOT in a production environment)

**Comment by zandercymatics** [comment]
Done. Awaiting review

**Comment by rachidatecs** [comment]
LGTM
