### ISSUE TITLE
Make Domain Status more meaningful for user

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1411]
### Issue description

During Analyst usability testing, some users did not understand the domain status, especially, what is the meaning of "On Hold." The thought (from the user) was that perhaps it was just waiting for something, and not that there was action required.

Implement solution per current design

user insight source: [Miro ](https://miro.com/app/board/uXjVNZhbw-s=/?openComment=3458764567841331692)(Heading: "Uncertainty about domain statuses")

### Acceptance criteria

- [ ] implement domain status per current design: see [Figma mockup](https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&node-id=2296-42994&mode=design) for style and [google doc](https://docs.google.com/document/d/152rI_svP_MB6LYrhmHv8-QyWbAbyJfnjXHuL6rlRlUk/edit?usp=sharing) for content

### Links to other issues

🔄 Corresponding design ticket #1202

**Comment by PaulKuykendall** [comment]
Need additional phrasing for the "expired" status. (Not a blocker, but needs to be added sooner or later) @Katherine-Osos
