### ISSUE TITLE
 Investigate disabling identity verification for current users 

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#1414]
### Issue description

We require PII proofing via login.gov on all users, even users brought over and who manage existing domains. This is done to gain assurance that all .gov domain managers are authentic. 

Some users have expressed concerns: 
* They don't want to share sensitive information, or don't want to share it for this purpose.
* They are concerned about mixing personal information with an account related to their work.
* They believe prior access is evidence that access should continue.
* They can't be proofed via Login.

Though it may not meet our goals for a higher-trust threshold for our ~legacy~ established domains, we can investigate turning off identity verification just for existing domain managers. However, we still need to require verification for all new domain requestors.

### Acceptance criteria

- [ ] Determine if we can:
  - [ ] turn off verification for current domain managers, AND
  - [ ] still require PII proofing for new users 
- [ ] If possible, create issues for that work.

### Additional context

refinement question: To determine who the current domain managers are, it was discussed we could use User domain role table and the Transition Domain table to determine who who counted as domain managers. This would require removing the emails of removed domain managers( those who request to not be considered managers on a domain) from Transition Domain table as well. The alternative is another table that has the emails from the both of this, but still requires excluding any users who have requested their access be remove.

**Comment by PaulKuykendall** [comment]
Cameron meeting with login.gov folks on week of Dec 4, which may change the scope of this ticket, slightly.
