### ISSUE TITLE
Design: define approach to remove extra contacts from "Other employees from your organization" page

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1432]
### Story

As an applicant, I want to be able to remove extra contacts I've added on the [Other employees from your organizatio](https://getgov-staging.app.cloud.gov/register/other_contacts/) page
so that I don't waste time erasing the data I entered into the organization contact fields

### Acceptance Criteria

- [x] A figma design is created to show how to remove extra contacts from  "Other employees from your organization" page

### Issue Links

relates to #903 (corresponding dev ticket)

**Comment by vickyszuchin** [comment]
Per refinement meeting (12/1/2023), create a design ticket to correspond with dev ticket #903. Add to the design ticket to sprint 35. Plan the dev ticket (#903) for sprint 36.

**Comment by gabydisarli** [comment]
Mockup is completed and we've decided to go with option 4. See [Slack thread.](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1703716589366159)
