### ISSUE TITLE
Modify our OIDC library to allow differentiating identity-verification levels for different users

### ISSUE THREAD

**Issue by neilmb** [cisagov/manage.get.gov#1433]
### Issue description

As part of #1414, we want to make it possible to send users to the Login.gov OIDC provider with a value of `http://idmanagement.gov/ns/assurance/ial/1` for `acr_values` (see https://github.com/cisagov/manage.get.gov/blob/c569db24f35a4f088c0bd177bc84606e271f7b3a/src/djangooidc/oidc.py#L103 and https://github.com/cisagov/manage.get.gov/blob/c569db24f35a4f088c0bd177bc84606e271f7b3a/src/registrar/config/settings.py#L521) BUT then for certain users, we want to NOT log them in at that point, instead we would want to redirect them BACK to Login.gov with `acr_values` of `http://idmanagement.gov/ns/assurance/ial/2` to require those users to be identity verified in order to log in.

Our `src/djangooidc` library will need some changes to be able to handle this pattern. We will need to add an attribute on our `User` model (`needs_identity_verification`?) that we check from inside `djangooidc` to determine which users need this treatment. We will also need to modify the `behaviour` configuration inside of `djangooidc` to allow for configuring two distinct settings for `acr_value`.

Because this is an invasive change to a crucial user-facing experience, we want to be sure that it is working as we expect. We should make unit tests for the oidc login flow (some unit tests are here https://github.com/cisagov/manage.get.gov/tree/c569db24f35a4f088c0bd177bc84606e271f7b3a/src/djangooidc/tests) that completely mock out the requests to Login.gov, but otherwise give us a fairly complete end-to-end example of logging in. The actual redirect request that we could mock out is at https://github.com/cisagov/manage.get.gov/blob/c569db24f35a4f088c0bd177bc84606e271f7b3a/src/djangooidc/oidc.py#L137.

### Acceptance criteria

- [ ] Some users can log in WITHOUT being identity-verified with Login.gov
- [ ] Some other users cannot log in WIHTOUT being identity-verified with Login.gov (this should be the default for "unrecognized" users).
- [ ] Unit testing for both aspects of this flow is in place.

### Additional context

Login's engineering staff is available on #login-partner-support Slack channel or via Zendesk ticket https://zendesk.login.gov/ for consulting about this. They have been very helpful in the past, so reaching out earlier rather than later would be best. https://github.com/18F/identity-oidc-sinatra/ has a working example of this pattern of two consecutive redirects with different `acr_value` in a Ruby web app.

### Links to other issues

#1414 is for an investigation into the feasibility of doing this.

**Comment by neilmb** [comment]
Just another implementation note that we probably have to keep around a table of email addresses to check on "needs identity verification" status rather than using a property in the `User` table. Or both. Because most of the legacy domain managers from the previous system have not logged in and we won't have `User` entries for them until they do. So we'll just need to keep a table of email addresses and check whether a new user who is logging in is on that list? Or maybe we can just use that table of email addresses to set the `needs_identity_verification` property on their newly created `User`?

But however we do it, we're going to need a new table to store these "special" email addresses.

**Comment by abroddrick** [comment]
@neilmb was the AC supposed to include the user table, I thought that portion was going to be another ticket?

**Comment by neilmb** [comment]
> @neilmb was the AC supposed to include the user table, I thought that portion was going to be another ticket?

Oops, that comment probably belonged on #1435
