### ISSUE TITLE
Django Admin: name-related dropdowns are not sorting properly.

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1457]
### Current Behavior

Example: The "Creator" dropdown on the Domain Information page is also not inserting new values in alphabetical order.

![image](https://github.com/cisagov/manage.get.gov/assets/144387994/bc1cd8d8-259e-4083-83f2-2cc547e3ff61)

[Slack thread](https://app.slack.com/client/T02QH7E1MHA/C05BGB4L5NF/thread/C05BGB4L5NF-1701973683.652729)

### Expected Behavior

1. Name-related dropdowns are sorting properly.

### Steps to Reproduce

1.The "Creator" dropdown on the Domain Information page is also not inserting new values in alphabetical order.

### Additional Context
A potential solution would be to include the username field in the `foreignkey_orderby_dict` property on `AdminSortFields`. This bug seems to occur when the first_name and last_name of the user are None.
![image](https://github.com/cisagov/manage.get.gov/assets/141044360/56f52ed3-ac54-47e0-9cd1-17e790fd7c0c)

The exception to this rule is for the `Domain` class. This is likely due to scope, so another solution would be to add another `SortingDict`, such as `SortingDict(["domain__domain_information__submitter", "domain__domain_information__investigator", etc], ["first_name", "last_name"])`
_No response_

### Issue Links

Related to #1456 (Fix at the same time)

**Comment by Katherine-Osos** [comment]
@dave-kennedy-ecs Looks like the "user" dropdown when creating a "User Domain Role" is not sorting properly.
