### ISSUE TITLE
Remove blog subscription information from beta.get.gov 

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1460]
### Issue description

Blog subscription is not part of the January MVP release. We need to remove the blog information from beta.get.gov.

Currently there is a placeholder "Subscribe" email box on the blog index page and on each individual blog post, but no subscription implementation yet.

### Acceptance criteria

- [ ] Hide the placeholder "Subscribe" email box on the blog index page and on each individual blog post

### Additional context

**See bottom right corner of this screenshot for current display on blog index page:**
![image](https://github.com/cisagov/manage.get.gov/assets/109625347/25875e5a-b049-400e-8730-73995daff391)

**See bottom of screenshot for current display on individual blog post page:** 
![image](https://github.com/cisagov/manage.get.gov/assets/60157596/85fbccba-248b-4666-b30f-d321120391dd)

### Links to other issues

🔄 Relates to https://github.com/cisagov/getgov-home/issues/128

**Comment by michelle-rago** [comment]
PR for this work https://github.com/cisagov/getgov-home/pull/143
