### ISSUE TITLE
Display Federal Agency, if applicable, on the Domain Overview/Review/Manage pages

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1465]
### Issue description

As a domain registrant/manager of a Federal domain
I want to see the Federal agency associated with my organization
So that I can confirm that this information is correct.

1) On the registrar domain overview page:
If the `organization type` is Federal,
Then display the Federal agency immediately above the Organization name.

2) On the domain request "review" and "manage" pages:
If the `organization type` is Federal,
Then display the Federal agency immediately above the Organization name.

3) On the submitted request email (in the SUMMARY OF YOUR DOMAIN REQUEST) section

### Acceptance criteria

- [ ] When viewing the Domain Overview page, the Federal agency is displayed immediately above the Organization name in the "Organization name and mailing address" section.
- [ ] When viewing a domain request's "review" or "manage" page, the Federal agency is displayed immediately above the Organization name in the "Organization name and mailing address" section.
- [ ] On the submitted request email (in the SUMMARY OF YOUR DOMAIN REQUEST section). Add federal agency under "Organization name and mailing address:" section

### Additional context

During the request process, if the requestor specifies that the domain is for a Federal org type, then they are prompted, by dropdown on the `/request/organization_contact` page, to select a Federal agency along with the org name and address information.

Similarly, when managing the domain, the Federal agency name is editable, by dropdown, on the `org-name-address` page. However, the Federal agency is not shown on the Domain Overview page as part of the Org contact. It makes sense that this conditional data be displayed there.

Source: [User feedback](https://docs.google.com/document/d/1M5foXX34qPc7R_J1uhBACHWUhg8WHwX3bB6nurvNNWE/edit#bookmark=id.s5dr58755312).

**Comment by Katherine-Osos** [comment]
@abroddrick I don't think this needs design, but can you confirm whether you need input from us? I also added the "next" label because I noticed that was missing even though I believe that was the decision in our last refinement meeting.

**Comment by vickyszuchin** [comment]
Decision to add this ticket to the sprint since it's related to current ticket and given the low effort. 

[Slack thread](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1705962509582669)
