### ISSUE TITLE
DISCOVERY: Notification and change log for domain managers

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1466]
### Issue description

As a domain manager,
I want an in-app log of all changes made to my domain
So that I can ensure that it is correct, and track any changes that have been made, avoiding and correcting errors.

### Acceptance criteria

TBD

### Additional context

Notifications about changes to domain info:

All users wanted to be notified of changes to their domain information–in particular, updates to name servers. Most users said they’d like an email notifications because they rarely visit the registrar. However, an in-app audit trail would be helpful, as well, for future reference or in case an email was missed. Need to do some discovery and design exploration around this.

Souirce: [User feedback](https://docs.google.com/document/d/1M5foXX34qPc7R_J1uhBACHWUhg8WHwX3bB6nurvNNWE/edit#bookmark=id.pa0k2x54vkx1)

**Comment by Katherine-Osos** [comment]
@PaulKuykendall @katypies This looks like a duplicate for this ticket #1088. Can one be closed?

**Comment by PaulKuykendall** [comment]
Closing as duplicate.
