### ISSUE TITLE
Unlock request pages that users have already visited

### ISSUE THREAD

**Issue by kristinacyin** [cisagov/manage.get.gov#1472]
### Story

As a requester
I want to be able to quickly navigate through request pages I have already visited
so that I do not have to waste time going through each page

### Acceptance Criteria

Given that I am a requestor who is revisiting an application I am working on (or a requestor who is revisiting my application under guidance from analysts to complete an action) 
When I click to edit my application
Then I should be able to click through the navigation on the right to revisit any page I had already visited once

### Additional Context

If a user ever leaves the application (ex. going back to the dashboard), navigation progress will be lost and the previously 'checked' pages will turn back into 'locked' pages. 

Demo:
![video1725342723](https://github.com/cisagov/manage.get.gov/assets/140533113/3fa09f53-c9be-4855-b100-aab2f7f62780)

### Issue Links

- [ ] Depends on Spike #1624

**Comment by michelle-rago** [comment]
FYI on a related discussion https://github.com/cisagov/manage.get.gov/issues/393
