### ISSUE TITLE
Fix capitalization for "Domain Information" page title in admin portal

### ISSUE THREAD

**Issue by kristinacyin** [cisagov/manage.get.gov#1477]
### Current Behavior

Currently, the page is titled "Domain Information" - with both words capitalized. It should be in sentence case with "information" in lowercase. 

What it currently looks like: 
![information_capitalized](https://github.com/cisagov/manage.get.gov/assets/140533113/176c5659-ce81-4376-9388-89d8b1e19eed)

### Expected Behavior

The word "information" should be lowercase, as shown here: 
![information_lowercase](https://github.com/cisagov/manage.get.gov/assets/140533113/85cdbec8-0145-4a8d-bb72-f0f81fc3e459)

### Steps to Reproduce

Page title seen in the home page of the admin dashboard

**Comment by neilmb** [comment]
Likely this comes from the `verbose_name_plural` set on https://github.com/cisagov/manage.get.gov/blob/main/src/registrar/models/domain_information.py#L247 and can be changed there.
