### ISSUE TITLE
Ensure beta.get.gov shows error messages from the registrar

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1486]
### Issue description

Updating the availability endpoint on the beta site + some error messaging changes (see [this Slack discussion](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1701824406852919) for adding in the error messaging).

### Acceptance criteria

- [ ] Update the availability endpoint on the beta site to show error messages from the registrar

### Additional context

References [this PR](https://github.com/cisagov/manage.get.gov/pull/1439) for updating the availability endpoint in the registrar + updated error messaging for if a user adds `.` in their to be domain. Please note in the above PR, the error message of `Enter the .gov domain you want without any periods.` will display when you click "Save and Continue" which is correct -- currently the error messages are not synced and we are aware of that.

![image](https://github.com/cisagov/getgov-home/assets/13954664/dcd443a1-2e04-4f4b-999f-e937039c87f4)

**Comment by therealslimhsiehdy** [comment]
Availability endpoint change PR [has been merged ](https://github.com/cisagov/getgov-home/pull/136)
