### ISSUE TITLE
Reduce email notifications for some status changes

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1489]
### Issue description

As a domain requestor
I want to receive notifications of status changes ONLY when those changes initially occur
So that I do not get excessive emails which are not meaningful to me

Existing behavior: A notification email is sent to the requestor upon each occurrence of a status change. (Submitted, withdrawn, approved, rejected)

### Acceptance criteria

- [x] No notification is sent when the request moves from "Action Needed" to "Submitted" (requester re-submits with changes)
- [x] No notification is sent when the request moves from "In Review" back to "Submitted" (analyst returned it to the queue)
- [x] #1582

### Additional context

Consider the following statuses, listed horizontally, with the possible transitions listed vertically below each.
![Image](https://github.com/cisagov/manage.get.gov/assets/62573986/0853ad49-e9a2-42a8-9eb8-eef8c70dadf7)

For those statuses that have the corresponding email icon, a notification email should be sent when the request INITIALLY enters that status. Subsequent status changes may take place which might return the request to a previously held status. When this happens, a second email should NOT be sent to the requestor as this adds no valuable information and may even be confusing to the user.
 
For example, a request may be `submitted` by the requestor, which triggers a notification email confirming the submission. Later, the request may be moved to `In Review` (which does not use a notification). If this request is moved back to `submitted` status, this does NOT trigger another notification email, as it has already been in that status.

### Links to other issues

Related to:  #1582 

_No response_

**Comment by h-m-f-t** [comment]
Let's discuss in product huddle, 31 Jan.

**Comment by vickyszuchin** [comment]
This ticket need more refinement. It is moved from sprint 37 to sprint 38.
