### ISSUE TITLE
Design: in the request form, make the behavior for submitting domain requests and alternates the same 

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1495]
### Issue description

In the request form, the "What .gov domain do you want?" and "Alternative domains (optional)" fields behave differently when given input. 
* `What .gov...`, the first field, requires a user to click "Check availability" before showing whether the desired domain is available. 
* `Alternative domains...` automatically shows the response a few moments after typing has stopped.

Let's decide which behavior we want and make both fields behave the same.

### Acceptance criteria
- [x] A figma design is created to make the behavior for submitting domain requests and alternates the same

### Figma file 
Here is the [Figma design file ](https://www.figma.com/file/v9EiY4kYfIHVWb8J58vXHS/Registrar%2FRequest%2F.gov-Domain?type=design&node-id=0%3A1&mode=design&t=G0cZ3bAI9gEZck03-1) and the [prototype](https://www.figma.com/proto/v9EiY4kYfIHVWb8J58vXHS/Registrar%2FRequest%2F.gov-Domain?type=design&node-id=3-4259&t=1FVDm6ht1KQxFJc9-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=3%3A4259&mode=design) that showcases it's behavior. 
A couple of things to note:
- The green success alert has been changed to the blue info alert ([USWDS alerts](https://designsystem.digital.gov/components/alert/))
- There is only one "Check availability" button in the 'Alternative domains' section. It will check the availability of ALL the provided alternative domain names once clicked. 

NOTE: To access the Figma file, you will need to request access. Let me know that you've done so and I can approve it ASAP. 

### Additional context

Note the "Check availability" button on the first field but not the second:

<img width="560" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/603901/3b536489-1843-4bf5-b794-f8426204afc4">

### Links to other issues
Implementation #1500 (dev ticket)

**Comment by abroddrick** [comment]
@kristinacyin I can't access the figma, so I'm not sure other devs will be able to. Are you able to have it so we all have access?

**Comment by therealslimhsiehdy** [comment]
Hey @kristinacyin! Would it be possible to give me access to the Figma linked above? I have requested access :D

**Comment by gabydisarli** [comment]
I've updated this ticket slightly to reflect the new design and content changes to the success alert and linked the new dev ticket to update the message (#1698)
