### ISSUE TITLE
Security emails aren't making it to WHOIS

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#1497]
### Current Behavior

Thousands of domains with security emails are showing `REDACTED FOR PRIVACY` in WHOIS. 

### Expected Behavior

If a domain has a security contact that isn't dotgov@cisa.dhs.gov, they have opted to have that email published and it should appear in WHOIS.

### Steps to Reproduce

1. Ask WHOIS about get.gov:
```
$ whois -g get.gov|grep "Security Email"
```
2. See a redacted response:

`Security Email: REDACTED FOR PRIVACY`

Querying for igorville.gov will show up correctly because the field has been manually set to `disclose` in the registry admin portal:
```
$ whois -g igorville.gov|grep "Security Email"
```
`Security Email: help@get.gov`

### Environment

Stable

### Additional Context

@abroddrick confirmed the tag was being disclosed correctly as it left our registrar. It's possible the registry admin panel is overriding our setting. See [Slack convo](https://cisa-corp.slack.com/archives/C05TS76RVS6/p1702399532090829?thread_ts=1702396340.398449&cid=C05TS76RVS6).

### Acceptance Criteria

- [ ] unlike normal bugs this can be used as just a discovery to determine the cause of the issue, and a follow on ticket can be made for solution as needed. 

### Issue Links

blocks #1535

**Comment by vickyszuchin** [comment]
Discovery in sprint 35 and worked in sprint 36.
