### ISSUE TITLE
Allow users to delete domain requests they've started or withdrawn

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1501]
### Issue description

To respect user's privacy, we should enable the ability for users to delete domain applications before they have submitted them or after they have withdrawn them.

### Acceptance criteria

- [ ] domain managers can delete domain applications before they have been submitted
- [ ] domain managers can delete domain applications that were withdrawn
- [ ] Implement design as defined in the [Figma mockup](https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&node-id=2955%3A12612&mode=design&t=Xf9KhN638FAIhaiC-1) Click the "present" button at the top right to see the prototype. 
- [ ] ~Number new domain requests that do not have a requested domain (see #1482)~ this was deemed too difficult, the creation date will be shown instead

### Links to other issues

Design ticket: #735 
Related to: #1482

**Comment by abroddrick** [comment]
@gabydisarli do you have a link to the figma that could be added here, I may be blind but I couldn't see it referenced on the design ticket.

**Comment by abroddrick** [comment]
CC: @vickyszuchin on the above
