### ISSUE TITLE
Expire non-approved domain requests after some time

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#1504]
### Issue description

We intend to offer users the ability to delete domain requests, but some won't do this and abandoned requests will sit around forever. 

### Acceptance criteria

- [ ] A new domain request state exists called "expired"
- [ ] Domain requests have an expiration date (consider 1 year the date created)
- [ ] Domain requests that are not "approved" after the expiration date are changed to the "expired" state

### Additional context

* How long should a request live the unexpired life?

Some related product questions we can consider: 
* Do expired requests ever leave the "domain requests" table interface?
* Do expired requests ever get completely deleted?
* Should requestors get notifications reminding them about their request's expiration? (see https://github.com/cisagov/manage.get.gov/issues/732)

### Links to other issues

🔄 #732

**Comment by Katherine-Osos** [comment]
@h-m-f-t I believe this is covered in this newer ticket: #2488. Thoughts on closing this one?
