### ISSUE TITLE
Django Admin: Improve Filters for Analysts to work more quickly

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1524]
### Issue description

During Usability research, an analyst would like some “quick filters” to find some of his work more quickly.

Collaboratively research the most useful and impactful filters that are currently missing, and gauge how beneficial they would be in terms of productivity.

### Acceptance criteria

- [ ] Discovery and Design complete for highest value filters to aid Analysts workflow.
- [ ] Dev tickets created to implement if necessary.

### Additional context

[Research affinity mapping](https://miro.com/app/board/uXjVNDibjyQ=/?openComment=3458764573276598886
)

**Comment by vickyszuchin** [comment]
Refinement tag added: PO accepted into the backlog. Suggest for Product and Design to review ACs.

**Comment by Katherine-Osos** [comment]
@PaulKuykendall @katypies This ticket feels a bit generic and was written before we launched the registrar and admin. Since then, we've made a lot of adjustments to that workflow. I think we should close this for now. Thoughts on this?

**Comment by PaulKuykendall** [comment]
I agree, this is out updated now, and will be covered by more recent tickets for analyst efficiency improvement.
