### ISSUE TITLE
Content: Clarify that "Other Employees" added to a request will NOT be notified.

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1526]
### Issue description

Other employees: adding employees does not automatically notify them, this is by design. We should add language letting the requestor know this.

### Acceptance criteria

- [ ] Appropriate content is updated (collaborative agreed upon between design and dev)

### Additional context

[Came from Usability Research](https://miro.com/app/board/uXjVNDibjyQ=/?openComment=3458764573381430949)

**Comment by Katherine-Osos** [comment]
@PaulKuykendall This is being addressed in the content review for the request flow, so I think we can close this ticket.

**Comment by Katherine-Osos** [comment]
@PaulKuykendall ^^ following up on my note above.
