### ISSUE TITLE
Clean up test noise (that includes EPP and migration scripts)

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1541]
### Issue description

Right now if you run the test suite locally or see the output from github, there is a lot of added prints and logs that make it hard to troubleshoot where your particular error is coming from. This ticket is clean up test noise in general including EPP and migration scripts. 

### Acceptance criteria

- [ ] unnecessary prints/logs on tests are removed

**Comment by vickyszuchin** [comment]
This ticket is an action item coming out of the Engineering huddle on 12/18. See meeting notes for the general discussion.

**Comment by PaulKuykendall** [comment]
It's getting hard to troubleshoot in test, due to this noise. So, let's get this fixed shortly after Jan launch. Refined 12-29
