### ISSUE TITLE
Content: High unavailability in our availability check beta.get.gov

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1545]
### Issue description
Implement as part of cisagov/getgov-home#163
In our availability check response, the fact that a domain is unavailable is mentioned twice, consecutively. This reads poorly, and the second reference should be removed.

![Image](https://github.com/cisagov/manage.get.gov/assets/62573986/22d920ec-dab5-41f8-94a7-009be6e6c463)

### Acceptance criteria

- [ ] The redundant statement "That domain isn't available," is removed from the dialog box.
- [ ] The redundant link "Read more about choosing your .gov domain" is removed from the dialog box.

### Additional context

[Pointed out in Slack.](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1703075389482289)

### Links to other issues

Implement as part of cisagov/getgov-home#163

**Comment by PaulKuykendall** [comment]
I think this is MVP. Low hanging fruit that may be seen a lot and should be cleaned up.

**Comment by abroddrick** [comment]
@PaulKuykendall or @vickyszuchin this is on beta.get.gov but is mismarked here as manage.get.gov for the repo. Could someone switch repos for this ticket please?

**Comment by h-m-f-t** [comment]
Completed at cisagov/get.gov#173
