### ISSUE TITLE
User/Contact bug: Signals double saving, overwriting data for test cases

### ISSUE THREAD

**Issue by zandercymatics** [cisagov/manage.get.gov#1547]
### Current Behavior

A bug was introduced [with a PR](https://github.com/cisagov/manage.get.gov/pull/1491) that fixed our oidc login clearing out user information. To fix this, the Contact object was linked to the User object, such that they would remain in sync.

However, this introduced a sneaky double-save bug wherein if signals get called more than once for the same contact object (as we found happens in our test cases), it overrides information when it should not do so.

![image](https://github.com/cisagov/manage.get.gov/assets/141044360/f9d35949-5138-4337-a189-9e2a843191f5)
![image](https://github.com/cisagov/manage.get.gov/assets/141044360/917e6db7-6cfd-48c8-a9b0-e0b8f01f2831)

### Expected Behavior

When a `Contact` object is saved, the `save()` function checks to see if `self.user` is not None. When it is not, it will update the  `self.user` object with whatever value is located at `self`. It appears that in certain situations, (such as our test cases),  the `User` field is behaving as if it were a one-to-many relationship (one Contact object to many User objects). This should not be the case, and `Contact` should only update one `User` field.

### Steps to Reproduce

1. Create a new test case in `test_admin.py`, and create 3 fake User objects. Populate them with unique data. Then, log their values. Note that their data seems to get overwritten.

### Additional Context

This bug seems to be originating in the `signals.py` file in the ` handle_profile` class. By passing in a flag that disables the save behavior (or just commenting it out), this issue seems to resolve. 
![image](https://github.com/cisagov/manage.get.gov/assets/141044360/e19a1508-72c7-405a-96db-3540305dcc4b)

### Issue Links

🔄 Relates to: [#1464 / #1468](https://github.com/cisagov/manage.get.gov/pull/1491)
🔄 Relates to: [this PR](https://github.com/cisagov/manage.get.gov/pull/1543) (pinpoints where the behavior is occurring but does not solve it)

**Comment by PaulKuykendall** [comment]
@zandercymatics - investigate a little further and see if this is truly serious.
