### ISSUE TITLE
MILESTONE: DNS Hosting Services (feature)

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1548]
### Description
.gov wants to offer DNS Hosting to its clients, as part of its Infrastructure as a Service. At a high level, this involves these key features:

* **Domain Name Resolution Services (Services)
  * domain translation
  * domain lookup
  * DNS forwarding
* **Provision Domain Name Servers (Infrastructure)
* **Integrate Domain Name Servers with Registrar, Web-hosting, and ISP as required
* **DNS Monitoring
* **Customer service and support
* Uptime history
* Speed
* Customization options
* Query analytics
* Scalability

**MVP Deliverables

### Business Value
By offering DNS Hosting to its clients, dotgov believes that .... will result in .... which can be measured by ...

### Workflow for this Epic

- [ ] Discovery - Requirements
- [ ] Design - UX 
- [ ] Design - System Architecture based on UX
- [ ] Development - slices
- [ ] Deploy - MVP

**Comment by h-m-f-t** [comment]
Since we have other issues in this milestone now, let's close this placeholder issue.
