### ISSUE TITLE
Make it easier to tag designers

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#1552]
### Issue description

Let's make it easier to request design reviews on PR and get notifications about it.

### Acceptance criteria

- [x] Make a team for @cisagov/gov-designers 
- [x] Play around with [Slack notifications for GitHub](https://github.com/integrations/slack#how-does-mentions-work)
- [x] See if it works ([thread](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1703279115749369?thread_ts=1703107095.178139&cid=C05BDEA3C11))

**Comment by gabydisarli** [comment]
nice! I don't see a way to tag the group here but maybe it's only taggable on a PR?

**Comment by h-m-f-t** [comment]
I think we've solved this for now!
