### ISSUE TITLE
Email for "submitted" request: Info missing from request summary

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1562]
### Current Behavior

Within the "submitted" domain request email, we show a "Summary of your domain request." However, that summary is missing some information (E.g. type of work, current website, etc). 

### Expected Behavior

The "submitted" email should list all submitted information for the request. It should match the "Review" page in the registrar.

**One exception:** Do not display "Requirements for operating .gov domains" field. This is a required checkbox to complete the request process. No need to call it out in the email.

### Steps to Reproduce

1. Trigger an auto-generated email for a "submitted" domain request
2. Review the "summary of your domain request" within the email and compare to the submitted request.

### Additional Context

Some fields only appear for certain Org Types. Ensure you test this for each Org Type.

NOTE: we're removing the "Summary of your domain request" from all  domain-request emails EXCEPT for the "submitted" email. That's why the "submitted" email is the only one mentioned in this ticket.

**Comment by PaulKuykendall** [comment]
This is High priority due to the potential "reach" of the problem, as there will be many submissions shortly after launch.
