### ISSUE TITLE
Domain's "Your contact information" is incorrectly showing another user's information

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1571]
### Current Behavior

Per Cameron Dixon,  while going to [ctbiglist.gov](http://ctbiglist.gov/) to add a domain manager and I'm being presented with **"Your contact information"** which is not mine nor any user's on the domain

See [Slack thread]( https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1703264385316429) for screenshot of issue.

### Expected Behavior

"Your contact information" shows the current user's information.

### Steps to Reproduce

1. logon as domain manager
2. select to manage ctbiglist.gov](http://ctbiglist.gov/
3. View "Your contact information" section

### Environment

Stable

### Additional Context

See Slack thread. Per Alysia, This sounds like a side effect of the change we made to reduce the empty first and last names from appearing.

### Issue Links

Related to #1607 
[Slack thread]( https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1703264385316429)

**Comment by vickyszuchin** [comment]
Per Alysia request, this ticket is added to sprint 36.

**Comment by abroddrick** [comment]
Per refinement today, if we need to disconnect User from the contact on AO that is okay. Up to dev to find the best solution here.
