### ISSUE TITLE
Domain request emails:  “Request received on: ” displays the original request submission date 

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1572]
### Issue description

Within all domain-request emails, we list a date for: "request received on." It do not _necessarily_ reflect the original request submission date. Currently, it doesn't reflect the original submission date as updates are made to the request.

For example, if a user submits a request on Dec 1, that date reads "Dec 1." For most status changes, that date remains unchanged within the emails. However, if the status is switched to "Action needed," that date resets to the current date (e.g. it would read "Dec 26," if changed to that status today). 

We're getting rid of the Action Needed email, but subsequent emails—when the request is approved/rejected— will reflect the new date (Dec 26) rather than the original submission date.

![image](https://github.com/cisagov/manage.get.gov/assets/144387994/27a3b40b-c57b-433d-9112-43ac69fee924)

### Acceptance criteria

- [ ] On all domain-request emails, the date displayed for "request received on: " is the original submission date

**Comment by neilmb** [comment]
The initial implementation of this just used the `DomainApplication` object's `updated_at` timestamp, but when the status goes from `submitted` to `in review` it changes that `updated_at` timestamp. There are two possible solutions: (1) add an explicit `submitted_at` field that is set when the state first transitions to `submitted`or (2) try using our existing audit log to query when the status became "submitted".
