### ISSUE TITLE
Domain managers can delete domain requests they've started or withdrawn

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1574]
### Issue description

Enable the ability for domain managers to delete domain applications before they have submitted them or after they have withdrawn them.

### Acceptance criteria

- [ ] Domain manager can delete a domain that has been started
- [ ] Domain manager can delete a domain that has been withdrawn
- [ ] Implement design as defined in the [Figma mockup](https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&node-id=2955%3A12612&mode=design&t=Xf9KhN638FAIhaiC-1) Click the "present" button at the top right to see the prototype. 
- [ ] Number new domain requests that do not have a requested domain (see #1482)

### Links to other issues

🔄 related to #735 (design ticket)

**Comment by PaulKuykendall** [comment]
refined 12-29. put at end of S36... stretch goal

**Comment by vickyszuchin** [comment]
This ticket is a duplicate of #1501 and should be closed.

**Comment by vickyszuchin** [comment]
Duplicate ticket. Will not do.
