### ISSUE TITLE
Submission dates for fixture domain requests are blank

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1576]
### Current Behavior

For applications generated by fixtures, submission dates are not showing because they are not set to begin with

![image](https://github.com/cisagov/manage.get.gov/assets/144387994/46ca040a-3b72-4ff4-be4b-5094eb604bcd)

### Expected Behavior

Submission dates are shown

### Steps to Reproduce

1. Logon as Domain Manager with an account associated with fixtures
2. View Domain request table
3. Date submitted column is blank (for any requests from fixtures)

### Environment

Development sandbox

### Additional Context

Per Alysia, submission date should be added to fixtures for the fake data

**Comment by PaulKuykendall** [comment]
This is high impact because it affects testing in sandbox environment. Refined 12-29
