### ISSUE TITLE
In registrar admin, allow an analyst to set a "reason for rejection" and have the registrar send an email based upon the reason

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#1578]
### Issue description

As an analyst
I want to tell a requestor why their domain name was rejected in the same place I reject it
so that...
* we track rejection reasons as a category in the registrar
* users don't have to receive two emails about their request being rejected
* I don't have to write a separate email 

In the past, people whose request had been rejected got an automated email from the registrar simply stating the request was rejected _and_ a bespoke, analyst-crafted email that included the rejection reason. We've now [summarized the rejection reasons](https://github.com/cisagov/manage.get.gov/issues?q=is%3Aissue+is%3Aopen+reject+author%3Agabydisarli+) into 6 different circumstances. 

In the registrar admin, after setting the rejection status, an analyst should be able to select the "rejected reason". Once saved, the requestor should be sent the email template that corresponds to the rejected reason.

[Rejection email templates are in our Google Drive](https://drive.google.com/drive/folders/1gkUyKEad42GiwzN7carJtMAw1RHyG8KC)

### Acceptance criteria

- [ ] After setting a rejection status in the domain request, an analyst can select from the 6 rejection reasons (ideally without having to save the reject status first before viewing the reasons).
- [ ] After an analyst saves the domain request, the requestor receives a [reject-reason-dependent email](https://drive.google.com/drive/folders/1gkUyKEad42GiwzN7carJtMAw1RHyG8KC). 
- [ ] Analyst is able to **filter** by Rejection Reason code

### Additional context

When Status = Rejected, another field should be shown, "Reason for rejection". Mocked example:

<img width="557" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/603901/9fd2d720-4336-47f4-8f99-c1541c188a31">

### Links to other issues

🔄 Relates to #608

**Comment by PaulKuykendall** [comment]
Refinement 12-29

**Comment by PaulKuykendall** [comment]
Based on a discussion we just had in a huddle, including Rachid, Dave, Vicky and me, it's clear that all six of these reject reason codes are applicable to a terminal reject. It just so happens that three of these reasons may **also** apply to the "Action Needed" status. That is a separate workflow, not directly related to the Reject workflow affected by this ticket, so these 6 reject reasons are STILL appropriate to a rejected request. The ACs do not need to be changed at this point.
