### ISSUE TITLE
Design: Centralized place to update contact information (i.e. user profile)

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1585]
### Story

As a domain registrant / manager
I want to easily update my contact information in a logical place within the registrar
so that I can ensure my contact details are accurate

### Acceptance Criteria

- [x] Figma designs have been created that provide a centralized place for updating user contact information
- [ ] Dev ticket has been created to implement the design

### Additional Context

Currently, there's a page to update "Your contact information" within the domain management section for each domain. Since each domain displays this page, the implication is that you can create separate contact info for each one - which is false. If you update the contact info for one domain, it will automatically be applied to all domains. We need to create a centralized place for updating this info that trickles down to the individual domains. 

Once the contact info has been populated for an account, we could auto-fill those details in the domain request form, as well. 

### Issue Links

Relates to: #1087

**Comment by gabydisarli** [comment]
The implementation work for this is blocked until we figure out the how we want to handle the issues with the Your contact information page.
