### ISSUE TITLE
Implement confirmation message when a user cancels a domain manager invitation

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1601]
### Issue description

To follow other patterns across the application, we need to implement a confirmation message when a user cancels a domain manager invitation.

### Acceptance criteria

- [ ] When user clicks cancel in the Invitations table on the Domain managers page
- [ ] The confirmation message is: "Canceled invitation to [email address]."

### Links to other issues

Design ticket: #1379 
[Figma design ](https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&node-id=3328%3A18978&mode=dev)

**Comment by vickyszuchin** [comment]
Moving this ticket from sprint 39 to sprint 38. Currently, its status is "In review".

@abroddrick
