### ISSUE TITLE
Allow analysts to view cancelled invitations 

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1604]
### Issue description

As a CISA analyst
I want to know which invitations have been cancelled/revoked
so I can track the status of those invitations  

### Acceptance criteria

- [ ] A "canceled" status is added to Domain invitations 
- [ ] Domain invitations in the canceled status show on the Domains page, in Django Admin.
- [ ] CISA analysts can view cancelled invitations in the Domain invitation table
- [ ] ensure canceled invitations don't show on the csv reports
- [ ] a registrar user should not see the canceled invitations; they should still disappear from their Domain Managers view.

### Links to other issues

- Related to: #1601

**Comment by abroddrick** [comment]
@Katherine-Osos We still want domain invitations to not be shown on the invitation table on Manage Domain if they have been canceled, right?

**Comment by Katherine-Osos** [comment]
@abroddrick Correct. Or at least, that is not part of this ticket and has not been discussed.

**Comment by abroddrick** [comment]
Should a canceled invite in DomainInvitations leave the table when a user resends the invite to the same person? @Katherine-Osos

**Comment by PaulKuykendall** [comment]
> @Katherine-Osos We still want domain invitations to not be shown on the invitation table on Manage Domain if they have been canceled, right?

Yes, canceled domain invitations go away, if the user is invited.

**Comment by vickyszuchin** [comment]
Moved all "In progress" sprint 57 tickets to the current sprint (sprint 58), per guidance.
