### ISSUE TITLE
Django "contacts": map user scenarios and needs

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1607]
### Issue description

Currently, setup for the "contacts" model in Django is causing a few user issues. We need to map scenarios related to use of "contacts" (from a user perspective) and define requirements for improving this setup. We also need to partner with engineering to determine how we might approach this in the admin.

### Acceptance criteria

- [ ] User scenarios have been defined and mapped
- [ ] User needs have been identified and documented
- [ ] ensure that necessary dev issues are created.

### Links to other issues

Related to: #1571

**Comment by Katherine-Osos** [comment]
@PaulKuykendall I created this ticket and no longer remember why. I think this may have been handled with the profile update. I suggest closing this, unless you remember why we needed design to create this and can expand the description.

cc: @katypies

**Comment by PaulKuykendall** [comment]
I agree, this has been over by the user profile work. I will close as not planned.
