### ISSUE TITLE
Hide “registrar@dotgov.gov” email on the Security Contact page of Domain Management

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1620]
### Issue description

We should not show the registrar@dotgov.gov email on the Security Email page in the Manage Domain section of our system. It should never be shown to our users. 

### Acceptance criteria

- [ ] Hide this email “registrar@dotgov.gov” on the Security Contact page of Domain Management
- [ ] Add unit test as appropriate.

### Additional context

Per Alysia, there should never be a real security email with the value of registrar@dotgov.gov, but it makes sense for that to be our registry's default value. So, our reports that show security contact can represent that field as blank.

### Links to other issues

[Slack thread](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1704911540816609)

**Comment by zandercymatics** [comment]
This ticket was already completed, but I did find an edge case where the overview page would still show this email. I've fixed that instead
