### ISSUE TITLE
Design pagination for registrants with many domains

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#1629]
### Issue description

Most registrants have 1 or maybe 2 domains. Federal agency domain managers often have dozens. Let's add pagination so their domain dashboard isn't a mile long.

### Acceptance criteria

- [ ] Create a prototype
- [ ] Decide if pagination always appears in the domain dashboard or only shows
- [ ] Consider offering a toggle to change the number of domains we show by default (e.g., from "10" to "50")
- [ ] Determine whether we should also offer the same functionality in the domain request table
- [ ] Determine how we'll test the prototype

### Additional context

(This is a design issue. An implementation issue has not been created.)

### Links to other issues

🔄 Similar to #1630

**Comment by vickyszuchin** [comment]
Suggested timeframe: 4-5 sprint away (May)

**Comment by PaulKuykendall** [comment]
I move this to the `org model ` epic, because the pagination will be addressed elegantly during that effort. Based on the previous comment, it belongs with that work.

**Comment by h-m-f-t** [comment]
Closing in favor of #2177
