### ISSUE TITLE
Design how to make it easier to find a specific domain from a long list in the registrar dashboard

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#1630]
### Issue description

Most registrants have 1 or maybe 2 domains. Federal agency domain managers ofter have dozens. For registrants with many domains, let's design a way to make it easier to find just the one that's sought for.

### Acceptance criteria

- [ ] Consider text filters, "starring a favorite", or other mechanisms to find a given domain in a list
- [ ] Create a prototype
- [ ] Determine how we'll test the prototype

### Additional context

(This is a design issue. An implementation issue has not been created.)

### Links to other issues

🔄 Similar to #1629
🔄 Similar to #2179

**Comment by vickyszuchin** [comment]
Suggested timeframe: 4-5 sprint away (May)

**Comment by h-m-f-t** [comment]
Closing in favor of #2179. That issue doesn't include starring a domain, but maybe stars and hiding domains can be future additions.
