### ISSUE TITLE
Remove AO, current site request pages, and org address fields for federal requests

### ISSUE THREAD

**Issue by kristinacyin** [cisagov/manage.get.gov#1635]
### Issue description

During soft launch testing, we identified that federal organizations should not need to provide information regarding their authorizing official, organization address, and current website(s). 

### Acceptance criteria

- [ ] For **federal** orgs, complete the following for steps in the _request_ flow:
  - [ ] in the "Organization name and mailing address" (/organization_contact) page, don't show and don't require "Street address"/"Street address line 2 (optional)"
  - [ ] "Authorizing official" (/authorizing_official) page should be skipped and not appear in side nav. Ensure it is not required for this application 
  - [ ] "Current website for your organization" (/current_sites) page should be skipped and not appear in the side nav. Like with AO, ensure it is not required for this application.
- [ ] Update the final review step before submission to remove these 3 fields for federal requesters
- [ ] Update the email sent to federal agencies to not include these 3 fields
- [ ] Update all content referring to the AO, as appropriate.

### Links to other issues

related to: #1701

**Comment by vickyszuchin** [comment]
I have added the "refinement" tag to this ticket because of the discussion from this[ slack thread](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1706272252539569).

**Comment by h-m-f-t** [comment]
I've removed the refinement label all the major questions here have been addressed. See [Slack](https://cisa-corp.slack.com/archives/C05TS76RVS6/p1706269369364219).

However, I've added the blocked label because we shouldn't remove these fields until an org model exists and only federal orgs can make federal requests.

**Comment by abroddrick** [comment]
The new  AC for "updating all content regarding AO" are we just talking on manage.get.gov and should this be more of a content review thing? Ideally, I would want this to be specific and say what other unlisted content we are referring to and how it would need to be updated.

**Comment by h-m-f-t** [comment]
Though this does affect the new request form experience, I've change the epic to "org model" since that is when we'll do this work.

**Comment by PaulKuykendall** [comment]
Per refinement today, this could be OBE due to Org Model work.

**Comment by PaulKuykendall** [comment]
OBE
