### ISSUE TITLE
Add note about "Anything else?" in Purpose request page

### ISSUE THREAD

**Issue by kristinacyin** [cisagov/manage.get.gov#1637]
### Issue description

During soft launch testing (for federal orgs in particular), participants ran out of characters in the textbox of the "Purpose of your domain" (/purpose) request page. We should add a note about how there is additional space in the "Anything else?" page for them to add anything that didn't fit. 

### Acceptance criteria

- [ ] Add a line in the description of the "Purpose of your domain" (/purpose) request page about how there is additional space in the "Anything else?" page

### Links to other issues

related ticket: #1651

**Comment by h-m-f-t** [comment]
@kristinacyin Do you think simply adding more characters in this section is viable, instead of telling them to flow to another section?

**Comment by vickyszuchin** [comment]
Per refinement meeting, a better solution is to increase the textbox size. 

Decision:
-  close this ticket as "Won't do"
- create new ticket for increasing text box size
- link this ticket to the new ticket
