### ISSUE TITLE
Legal requirements: Update page title

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1639]
### Issue description

During the content review, we decided to change the name of a page where registrants are asked to review .gov requirements. This is within the domain-request form.

**Current page title:** Requirements for operating .gov domains
**New page title:** Requirements for operating a .gov domain

(i.e. we're changing the title from plural to singular)

### Acceptance criteria

- [ ] The page title has been updated to "Requirements for operating a .gov domain" in all instances that reference that page (to include title on the page and label for the link in the side nav)

### Links to other issues

Related to #1626 
Likely Resolved by #1667

**Comment by michelle-rago** [comment]
This has been addressed in https://github.com/cisagov/manage.get.gov/pull/1667.

**Comment by abroddrick** [comment]
Already tackled in another ticket
