### ISSUE TITLE
 Logout is not redirecting to get.gov in production

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1642]
### Current Behavior

On Chrome, after clicking "Sign out" on [manage.get.gov](http://manage.get.gov/)  the user gets the following screen.

![image](https://github.com/cisagov/manage.get.gov/assets/144387994/a5b3c219-0d76-4936-99d1-8c78547f7db7)

When user clicks "Yes", nothing happens.
When user clicks "No" option, user is logged out of Login.

### Expected Behavior

“Yes, user will sign out of [Login.gov](http://login.gov/) then they should get redirected back to the [manage.get.gov](http://manage.get.gov/) application which will transparently give them ANOTHER redirect to [get.gov/](http://get.gov/).

“No, user will go to "my account page” is meant to take to their [Login.gov](http://login.gov/) account page. 

### Steps to Reproduce

1.

### Environment

Environment: Stable
Browser: Issue occurs on Chrome and Edge

### Additional Context

See [Slack thread](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1705434610109389) as it mentions a simple setting that just may need to be changed to get this working

**Comment by vickyszuchin** [comment]
"Blocked" tag add: to note dependency on login.gov response.

**Comment by dave-kennedy-ecs** [comment]
Alysia advised by login.gov support that we should add manage.get.gov to the list of redirect_urls.  Alysia did this on 3/7.  Changes, according to documentation, do not take effect until two weeks after.  So, need to confirm on or about 3/21 that the situation has been resolved.
