### ISSUE TITLE
Domain managers should not be able to DELETE retrieved domain invitations

### ISSUE THREAD

**Issue by neilmb** [cisagov/manage.get.gov#1652]
### Issue description

We have seen users who are newly added to a domain choosing to press "Cancel" in the "Domain Invitations" table on the "Domain Managers" for the invitations that they just retrieved, which were presumably marked as status "retrieved". This takes them out of that table entirely which is not something we want (the "Cancel" button actually deletes a row from the DomainInvitation table).

To prevent losing that information, we probably want to remove the "Cancel" link from domain invitations that are retrieved so that they stay in that table forever. Domains who do lots of inviting and uninviting people might get confused with that table as it grows, but not deleting seems better at this point than confusing people.

### Acceptance criteria

- [ ] In the Domain Invitations table, there should not be a "Cancel" link for entries that are in the "retrieved" status
- [ ] We should check in the `DomainInvitationDeleteView` that the invitation is not retrieved so that a user can't use a POST request to delete a retrieved invitation in the absence of a "Cancel" link.

### Additional context

@h-m-f-t and @amcelya observed this with a new domain manager.

**Comment by vickyszuchin** [comment]
Suggested timeframe: sprint 41/42
