### ISSUE TITLE
In the registrar, update error message on character-limited open field

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1666]
### Issue description

Update error message when a user exceeds 1000 characters from:

> "Response must be less than 1000 characters."

to

> "Response must be 2000 characters or less."

(Based on #1651 increasing the field size)
On the following open field responses on the request form:

/about_your_organization/
/purpose/
/anything_else/

### Acceptance criteria

- [ ] error message matches the change above

### Links to other issues

Depends on: #1651

**Comment by vickyszuchin** [comment]
This is a duplicate.
