### ISSUE TITLE
Error 500 encountered moving request from "Approved" to "In review" and back to "Approved"

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1674]
### Current Behavior

Error 500 encountered moving application from "Approved" to "In review" and back to "Approved"

Steps:
1. Set the application to "approved"
2. Set the application back to "in review"
3. Try to set it back to "approved"

### Expected Behavior

Application should be allowed to transition from "Approved" to "In review" AND to "Action needed" and back without issues, as defined in FSM. The domain and domain information should also be deleted when it moves out of the Approved status.

### Steps to Reproduce

Steps:
1. Set the application to "approved"
2. Set the application back to "in review"
3. Try to set it back to "approved"

### Environment

Staging

### Additional Context

Analysis of issue and solution in [slack thread](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1706027401403539?thread_ts=1706027102.482849&cid=C05BGB4L5NF)

**Comment by rachidatecs** [comment]
We should treat these transitions the same way we treat approved -> rejected and approved -> denied:
- If the domain is not yet READY, delete it
- If the domain is READY, block the transition
