### ISSUE TITLE
Django admin: Display the datetime information in user's local time zone (feature)

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1677]
### Current Behavior

On Django admin, the datetime information is not displaying in user's local time zone for the following tables:
- Domain applications
- Domain information
- Domains

![image](https://github.com/cisagov/manage.get.gov/assets/144387994/7ff37166-a871-4329-9151-e13c803d8d61)

![image](https://github.com/cisagov/manage.get.gov/assets/144387994/c226f5f3-c549-45ee-9b47-932ba25ff327)

### Expected Behavior

Datetime information is displayed in user's local time zone

### Steps to Reproduce

1. Log into Django admin.
2. View the datetime field in the following tables:
- Domain applications
- Domain information
- Domains

### Environment

Staging

### Additional Context

Identified in pre-launch testing. See [issues](https://docs.google.com/document/d/1GvNzvdFOHL8jIiuDfmcxAFXeXXpbkoQx4XkRtAfSVOw/edit)

Caveats: it should already be supported so it may be hard to troubleshoot why this doesn’t work right in admin, OR we may need another setting in admin. There may already be a known method for doing this/ a reliable plugin

https://docs.djangoproject.com/en/5.0/topics/i18n/timezones/
https://docs.djangoproject.com/en/2.2/ref/settings/#time-zone

**Comment by PaulKuykendall** [comment]
Creating a new ticket, based on this information, to add the feature for local time zone displays, under User Profile - localization.
