### ISSUE TITLE
Requestors shouldn't be able to submit a request with missing information

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1686]
### Current Behavior

Domain requestor can submit domain request with missing information

1. Start a new domain request for a given org type (e.g., School District) and complete the domain request application until the final confirmation page Review and submit your domain request. 
2. Go back to Organization type and mailing address and change the organization type (e.g., State). You will be redirected to a new state-specific form for Election Offices. 
3. Do not submit anything on this form and redirect back to the Review and submit your domain request form. 
4. You are able to successfully submit this domain request even though the required Election Offices form is incomplete.

### Expected Behavior

Domain requestor should not be able to submit request with missing information.

### Steps to Reproduce

1. Start a new domain request for a given org type (e.g., School District) and complete the domain request application until the final confirmation page Review and submit your domain request. 
2. Go back to Organization type and mailing address and change the organization type (e.g., State). You will be redirected to a new state-specific form for Election Offices. 
3. Do not submit anything on this form and redirect back to the Review and submit your domain request form. 
4. You are able to successfully submit this domain request even though the required Election Offices form is incomplete.

![image](https://github.com/cisagov/manage.get.gov/assets/144387994/a7fc6cdf-24a8-481a-bd3f-303078f0ac31)
![image](https://github.com/cisagov/manage.get.gov/assets/144387994/a77a881d-f461-4b54-b41b-4fe932e5ef94)
![image](https://github.com/cisagov/manage.get.gov/assets/144387994/5c96275d-411b-4a65-824d-9ad188bd89bd)

### Acceptance Criteria

- [ ] Fire page-level alert upon submit of an incomplete form on the final review page.
  - [ ] _option 1_: attempt to scroll to the top and locate where the error is. 
  - [ ] _option 2_: put a generic error message above the submit button, _without_ indicating specific sections that are incomplete
- [ ] log the occurrences to determine incidence of this error.
- [ ]  Confirm with Design for exact working of message during PR review.
### Environment

Staging

### Additional Context

Identified in pre-launch testing. See [issues](https://docs.google.com/document/d/1GvNzvdFOHL8jIiuDfmcxAFXeXXpbkoQx4XkRtAfSVOw/edit)

**Comment by PaulKuykendall** [comment]
Per Product huddle, 4-3-24, 

1. Fire page-level alert upon submit of an incomplete form.
2. log the occurrences to determine incidence of this error.
3. optional: attempt to scroll to the top and locate where the error is. (alternately, put error above the submit button)

**Comment by vickyszuchin** [comment]
Moved it from "Ready" to "Backlog" because it does not have a storypoint.

**Comment by vickyszuchin** [comment]
Per guidance, any "In progress" tickets from sprint 45 will be moved over to Sprint 46 noon EST on Day 1.
