### ISSUE TITLE
Unable to edit any nameservers when using a subordinate host for another .gov

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#1699]
### Current Behavior

Currently, you can **add**  a nameserver that is a subordinate host to another .gov. For example, you can add ns.example.gov as a nameserver to mydomain.gov. After adding this host, on save, you will receive the hostname and corresponding ip addresses. Then if you try to edit ANY nameserver an error is thrown on that subordinate host saying "Name server address does not match domain name"

### Expected Behavior

It shouldn't throw an error on the nameserver in question and the user should be able to make changes to other nameservers

### Steps to Reproduce

1. add a nameserver that already exists in our zone and is a subordinate host to another domain. 
2. click save and notice IP addresses appear
3. edit/remove or add another nameserver and click save
4. see the error "Name server address does not match domain name"

### Additional Context

Note this error is occuring purely because the nameserver in question has IP addresses and is not a subdomain of the current domain (aka it has IPs and it belongs to another .gov). 

Implementation:
Do not edit the UX or allow IP addresses all the time. Instead, just make sure the user never sees the IP addresses to begin with. Also on createHost you don't want to send the ip addresses for a hostname that belongs to another .gov. By removing it on the front end, then when it is sent to the backend there is no worry of a create being called with ips for another .gov
### Issue Links

relates to: #1662

**Comment by therealslimhsiehdy** [comment]
[Slack convo](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1707418410439089) for reference
