### ISSUE TITLE
Change VIP Table to Verified by Staff

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#1708]
### Issue description

The Very Important Person table was originally supposed to Verified by staff, but django added an s to make it plural. As a result it was decided to make it VIP instead, however, there is a simple setting to remove the s so we can go back to the original name

### Acceptance criteria

- [ ] VIP table is renamed to Verified by staff ( and does not show up in django admin as Verified by staffs)

**Comment by gabydisarli** [comment]
@abroddrick following our content guide, I think this should be "Verified by staff" with no capital S

**Comment by abroddrick** [comment]
You're right, my bad!
