### ISSUE TITLE
Admin Portal: Disappearing contacts and current websites

### ISSUE THREAD

**Issue by kristinacyin** [cisagov/manage.get.gov#1730]
### Current Behavior

In the admin portal, when you click to go see the **contact** details (for another contact, submitter) by clicking on the info icon (which opens up a new pop up page), and then go back to the domain application page, the other contacts disappear (analysts say this happens every time when there is two and three contacts listed, might happen when there is only one). The current **website(s)** can also disappear. They reappear when you refresh the page. 

### Expected Behavior

Current website and contacts should not disappear from the domain application page

### Steps to Reproduce

1. Open a domain application in the admin portal
2. Select one entries in the "other contacts" or "websites" right-hand panel
3. Click on the "eye" icon to see detailed information about the selection
4. Notice the detailed contact information page displays OK.
5. Hit "Back" to return to the previous view.
6. Notice that only the selected contact is visible in the window, the others have disappeared. (Does not always happen)

### Environment

Analysts report that this happens in Firefox and Edge. 

### Additional Context

Screen recording can be found [here](https://drive.google.com/file/d/1Npz9Xv2uMvuvXEKie2ao1Kmc51YU4Noj/view?usp=sharing).

**Comment by vickyszuchin** [comment]
Rachid submitted [Django issue](https://code.djangoproject.com/ticket/35239).
