### ISSUE TITLE
Research uptime monitoring tools

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#1748]
### Issue description

Now that we have a production system, we should expand our infrastructure to include out of the box uptime monitoring tools that could be used to notify us should any production level event occur. This requires first research options that best fit our needs and their costs.

### Acceptance criteria

- [x] Build a research document with the desired features (see link below)
- [x] Determine a few of the best options for our project and needs
- [x] Narrow down to one monitoring after providing pros and cons as well as any pricing
- [x] Share recommendation with Cameron

### Additional context

[Link to a working document of "Desired Features" here. 
](https://docs.google.com/document/d/1z9598mvA76ohrxrLlyny3a3ZYKqq554mWR8ul85Jdbk/edit)
### Links to other issues

[Slack thread](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1709770404162409)

Blocks: #1737

**Comment by vickyszuchin** [comment]
For reference, [Slack discussion](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1709770404162409)
