### ISSUE TITLE
Transfer Figma file to CISA

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1752]
### Issue description

CISA recently set up a Figma instance for our team and distributed licenses to .gov designers. 

Currently, our .gov Figma file lives at Truss and we need to transfer it to CISA. Once that happens, all edits to the file will happen within the CISA instance and that will become the source of truth

### Acceptance criteria

- [x] Figma file is moved to the CISA instance
- [x] All designers are able to successfully access and edit the file in CISA instance
- [x] All fonts have been verified and updated, as needed
- [ ] Determine/implement any updates that should be made to the file to help with governance

### Additional context

How should we handle existing GitHub tickets that link to the Truss instance of the file? Need to ensure we don't edit that version of the Figma file if modifications are made during implementation.

**Comment by gabydisarli** [comment]
File was moved to CISA account March 11th. Legacy file will remain to protect old links.
