### ISSUE TITLE
Create an incident response playbook

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1756]
### Issue description

An incident response playbook is needed to ensure that the team can handle an application outage successfully. The playbook should include the actions that should be followed in case of incident. This includes but is not limited to:
- expectations for communication
- procedure for informing users

### Acceptance criteria

- [ ] Develop an incident response playbook
- [ ] Product team approves the corresponding PR

### Links to other issues

related to: #1739 #1737 #[226 ](https://github.com/cisagov/get.gov/issues/226)

**Comment by h-m-f-t** [comment]
@abroddrick talk to @trevorbryant-cisa
