### ISSUE TITLE
Django admin: "Joined" message appearing unexpectedly in admin

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1762]
### Current Behavior

When switching statuses ("Action" field) on requests in Domain application, sometimes, a message is displayed to inform the user that the request was joined to itself, in addition to the success message.  Some updates trigger message but not consistently. 

No user action pattern detected for triggering the "joined" message.

![image](https://github.com/cisagov/get.gov/assets/144387994/039f1a2b-fbf6-43f8-9e7b-26ca1f25d8d2)

### Expected Behavior

When user updates statuses ("Action" field) in Domain application, a "joined message should not be displayed.

### Steps to Reproduce

1. Login to /admin
2. Navigate to Domain application
3. Update "Action" field multiple times
4. Results: some updates will result in a "Join" message AND a success message.

### Environment

Environment detected: 
- Rachid's sandbox
- Staging ??

### Additional Context

Per Alysia,
The intent was for it to be just on the contact page.

[Slack discussion](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1707516985739349)

**Comment by vickyszuchin** [comment]
This bug has been size and meets DoR criteria. Moving to "Ready."

**Comment by abroddrick** [comment]
Closing as found to no longer be a bug

**Comment by vickyszuchin** [comment]
Re-opening this ticket because @Katherine-Osos encountered this on 7/11 again. cc: @abroddrick

**Comment by rachidatecs** [comment]
Still can't recreate. That joined message is only triggered in ContactAdmin (search 'Joined to').
