### ISSUE TITLE
Reduce field sizes on Admin page for readability

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1774]
### Issue description

This affects page: **/admin/registrar/contact/{number}/change/**

The first name, middle name, last name, and title fields are one-word (or minimal word) entries. Reduce the size of the fields so it’s easier to scan through the contact info page.

Desired final look:

![Image](https://github.com/cisagov/manage.get.gov/assets/62573986/3a12a4bc-66cb-4f07-af50-dede22261a45)

### Acceptance criteria

- [ ] Displayed field sizes are as shown in the graphic.

### Links to other issues

Split from #1041

**Comment by Katherine-Osos** [comment]
Closed ticket because the AC is being addressed in #1045.
