### ISSUE TITLE
Design: Indicate when an invitation for design manager has failed

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1779]
### Issue description

Currently, when an invitation cannot be sent (after the system retries a few times), it still populates in the "Invitations" table as though it was sent successfully.

We need to design a way to indicate that the invitation failed and (possibly) an option to manually retry. 

### Acceptance criteria

- [ ] Figma design is created for this scenario
- [ ] Dev ticket is created and linked to the Figma design

### Additional context

Current state: 

![Image](https://github.com/cisagov/manage.get.gov/assets/119689946/01b185e1-7d74-4cd2-a6a0-da5d1762182e)

**Comment by vickyszuchin** [comment]
Per request from PO, added to refinement fireside meeting on 3/14.

**Comment by h-m-f-t** [comment]
In product huddle, we determined that this design is correct for implementing #1780, so closing this as not planned.
