### ISSUE TITLE
Audit and organize the "research" folder on Google drive

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1796]
### Issue description

We need to assess the way we're organizing documents so they are easier to find and maintain. This will be particularly helpful for new team members as they onboard.

The "[research](https://drive.google.com/drive/folders/1yEbS8EjjbUUeSU_470ijrWkf3tHaEqB_)" folder, in particular, has gotten a little disorganized. The purpose of this ticket is to audit what's in that folder and come up with a new structure. 

### Acceptance criteria

- [x] Audit the "[research](https://drive.google.com/drive/folders/1yEbS8EjjbUUeSU_470ijrWkf3tHaEqB_)" folder on Google drive
- [x] Determine a new structure for organizing the files/folders
- [x] Create an overview page (table of contents) to help guide people to the most useful documents
- [x] Establish a new naming structure for files 

### Additional context

**Note:** Will need assistance from someone with full access to help move the files around once a new structure is defined.

**Comment by vickyszuchin** [comment]
Timeframe (per PO): given new designer is coming in April, it may be good to have this completed by then. Consider doing this ticket next 2 sprints (sprint 42/43).
