### ISSUE TITLE
Ask for more context to expedite process in request flow

### ISSUE THREAD

**Issue by kristinacyin** [cisagov/manage.get.gov#1801]
### Issue description

We've received requests that do not give enough context in the "Purpose" page of the request flow, which lengthens the amount of time it takes to adjudicate those requests. For example, a requester asked for their application to be expedited, but did not provide information about _why_ in the application. Instead, the requester provided the context by filling out the contact form. 

We should add language in our request flow specifying that the more relevant information the requester can provide, the better - especially for those who ask for special consideration.

>  I think having a discussion about what additional language here might encourage users to provide a bit more depth would be helpful. We don't need 2-page essays, but especially if you're asking for special consideration, more details are highly useful...especially when you are asking for something out of the ordinary, there is no way for us to assess the validity of such an irregular request or process without additional information 

-Alex

### Acceptance criteria

- [ ] Come up with additional language to add to the "Purpose" and/or "Anything else?" pages of the request form, mentioning that if the requester wants special consideration or something else out of the ordinary, they should provide more context for why
- [ ] Time-boxed effort for content generation process (see story points) and have Product review for final language.

### Additional context

[Slack thread discussion](https://cisa-corp.slack.com/archives/C066ZBWFLRW/p1706891884208759)

### Links to other issues

Related to #1598

**Comment by vickyszuchin** [comment]
Refinement tag: ticket was reviewed but deemed not ready for the backlog until more specifics on how to handle the situation.

**Comment by vickyszuchin** [comment]
Ticket updated with additional information.

**Comment by PaulKuykendall** [comment]
This may be resolved by the "Action Needed" email work.

**Comment by h-m-f-t** [comment]
I do think this has been resolved by allowing analysts to put a request in the `Action needed` state while specifying a reason. That kicks off an email that the user can reply to, and it's working well.

I believe that inviting requestors to explain why their request should be expedited will result in most requests asking for faster process.

Thanks @kristinacyin for taking the time for make this issue.
