### ISSUE TITLE
Domains can be renewed for a year from the current date

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#1806]
### Story

As a .gov product team
We want to offer a simple registration experience for domains with expiration dates potentially _years_ in the past
So that the new expiration date accurately represents one year from when we last affirmed a registration

### Acceptance Criteria

- [ ] The registry supports the functionality, in production, to renew a domain for one year from the current date

### Additional Context

We'd like our registrar to send an update to the registry extending the expiration one year from today's date, not one year from the expiration date. 

.gov's renewal story is different than other registries: we don't drop domains from the zone based on a calendar and/or lack of payment. We drop domains when, after every effort, we cannot re-establish contact with a government organization. Losing contact happens, in part, because our users don't (currently) manage most DNS records with us. Once they obtain a domain and delegate nameservers, there aren't many hard forcing-functions to bring them back (except when DNS isn't working for them).

So, our domains may be "expired" for an undefined time as we work to confirm the domain managers we have on file are still at the government. 

As an example, today is 21 Feb 2024. If a domain's expiration date is 21 August 2022, extending the expiration by one year from the last expiration date results in an new expiration date that is 6 months in the past. Extending the domain name _twice_ would have the domain expiring on 21 August 2024, only 6 months in the future. 

Neither approach produces good experiences for users (who will wonder why they have to click a button twice to get current and feel frustrated they have to renew again in 6 months) nor the .gov team (which will lose track of when we last confirmed their registration _for real_).

#### Technical Context
In [RFC 5731](https://www.rfc-editor.org/rfc/rfc5731.html#section-3.2.3), the domain renewal message is sent to renew the domain by a specified unit and number. This renewal message has a "period" attribute (periodType) which in turn has "units" that are defined by "pUnitType" in the XML. "Period" is the amount to renewal, "units" is the units to renew by, and the number value passed in is the number of total units to be applied (i.e., number of years). These pUnitType values are set in the RFC to allow "m" and "y" – month and year, respectively – however the RFC notes that it is up to the server (the registry) to determine allowed units. Currently our registry only allows years. 

From our perspective, there are a few possible solutions. Here are three (presented in order of preference):

1. The registry renewal command accepts the current date value instead of only the last expiration date
2. The registry continues to only allow the last expiration date value, but allows for a day unit "d"
    - Note: "d" is just to follow the 'm'/'y' naming convention mentioned above and is not found in RFC
    - This change would still allow the registrar to complete this story by simply calculating the number of days needed to reach a year into the future from the old expiration date
3. The registry continues to only allow the last expiration date value, but allows for a unit "m" corresponding to month
    - This would **not** met the acceptance criteria perfectly.
    - The registrar would calculate the number of months to reach approximately a year in the future from the current date, but the expiration date would only have the month and year updated and the day of the month would remain the same as before. For example, if the old expiration date was 21 Feb 2022 and today was 14 April 2024 the new expiration date would be 21 April 2025. This is not ideal, but it would be better than the current state.

### Issue Links

⛔ Relates to: #1602
Block by #2003

**Comment by h-m-f-t** [comment]
We've shared this with our registry services provider and they're evaluating what implementation might look like.

**Comment by vickyszuchin** [comment]
Block tag added: this is pending cloudflare adding the capability to do this.

**Comment by h-m-f-t** [comment]
Registry operator anticipates supporting this feature in late April. Marking it as planned for sprint 44.

**Comment by abroddrick** [comment]
@PaulKuykendall @vickyszuchin per findings on the feature that was added, this has been removed from sprint 45 and should be slotted for around sprint 47. I moved the confirmation ticket #2003 to sprint 46. I already confirmed part of the feature works but their current setup up won't work for the majority of requests. No point in implementing anything yet

**Comment by abroddrick** [comment]
Feature has been added to the registry's test environment and confirmed to be working. It has not arrived yet on their production environment but given it is meeting all of our needs we can confidently close this
