### ISSUE TITLE
Implement user profile in registrar

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1807]
### Issue description

Add a new page called `Your profile,` accessed through the header on the domain management dashboard, where domain managers can add/update their contact info. Implement according to Figma designs (below).

### Acceptance criteria
- [ ] use a feature flag for displaying the ACs below. use the one created in #2054 and ensure it defaults to not being displayed
- [ ] Create the [new profile page](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?type=design&node-id=4184-8856&mode=design&t=BAgCO0R1xMJIY3Fz-11) 
- [ ] Use content from the [official google doc](https://docs.google.com/document/d/1u-K1yQKb16H3AWj33mH2e1LJme6Ay9dNXMG8isiOXWk/edit#heading=h.vk9e6omzw3ms) for this page. Reminder again to note that this should be wrapped in a feature flag, so it's only gone when the profile feature flag is turned on.
- [ ] [Add new link to header](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?type=design&node-id=4184-8314&mode=design&t=BAgCO0R1xMJIY3Fz-11), next to sign out, to the new profile page. Note that when the user is on that page the blue underline appears, similar to what we do on the get.gov header
- [ ] [Remove Your contact information page](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?type=design&node-id=4274-18640&mode=design&t=BAgCO0R1xMJIY3Fz-11) from the domain management pages (this contact info is now managed through the user's profile). Reminder, it will appear to a user as "removed" but really you want it to not show when this flag is turned on, when flag is off you will still see Your Contact
- [ ] [Success message when page is updated succesfully](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?type=design&node-id=4270-18494&mode=design&t=BAgCO0R1xMJIY3Fz-11)
- [ ] Reuse field error messaging from Your contact information page

### Additional context

Note, we will be combining User and it's associated contact so keep this in mind when programming, as any reference to the Users contact will switch to just the User value. This shouldn't be a huge change so shouldn't stop development, but perhaps avoid using the word "contact" in code comments or function names to limit changes

### Links to other issues

Related to: #1808 
Related to: #2047 
Blocked by: #2054 
Blocked by: #2057 
Blocked by: #2015
Design ticket: #1585
Blocks: #1919

**Comment by abroddrick** [comment]
@gabydisarli the content link takes me to your contact which is all crossed out

**Comment by vickyszuchin** [comment]
"blocked" label added: this ticket is blocked by tickets being implemented in sprint 44.

**Comment by vickyszuchin** [comment]
Per guidance, any "In review" tickets from sprint 45 will be moved over to Sprint 46 noon EST on Day 4 (5/28).
