### ISSUE TITLE
UX: Update CREATOR and SUBMITTER concepts across request form & domain management

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1808]
### Story

As a domain manager
I want to understand where my contact information lives
so that when I create a new request, I understand how my contact info will be attached to the request

### Acceptance Criteria

- [x] Figma designs, prototypes, diagrams created demonstrating new UX
- [x] Dev ticket created

### Additional Context

During discovery work done to create a User profile (#1585), it was uncovered that the way we distinguish creator and submitter contacts does not make much sense from a user perspective. When a person creates a login.gov account and then creates a request, we create a new contact associated with the login.gov info that we call `creator`. As this person fills out the request form they fill the page Your contact information. The info entered here, when submitted, creates a separate contact called `submitter`. These two contacts are often the same. But we treat them like entirely different entities on the back end. From a user-perspective, they will likely fill in that info with info that matches their login.gov info. It's likely that these two contacts were separated early on in an architecture decision to accommodate multiple users who might want to be involved in creating the request or managing the domain. 

![Screenshot 2024-02-20 at 9 40 43 PM](https://github.com/cisagov/manage.get.gov/assets/107440934/df48a6ad-927a-4848-8496-89bc635fb0a2)
[diagram](https://miro.com/app/board/uXjVN9CK7to=/?moveToWidget=3458764578908091472&cot=14) mapping the way we currently organize `creator` and `submitter`

Let's say the request has been approved, the creator contact gets passed along to the domain management side, but the submitter contact gets left behind. There is no way currently for a user to manage that submitter info once the domain is approved. Now if a domain manager starts a new request and then decides they'd like to update their contact information at the same time that they're submitting a new form we have a problem. That contact information does not connect to their contact information as a domain manager, but the content and design of this page imply that they do. The work here is to map out the user scenarios, figure out what needs to change, and then design the new experience and create new content.

**Some questions to figure out:**

- If we combine `Submitter` and `Creator`, what happens to legacy contacts following the old architecture?
- In what scenarios might we want to give the user an option to add another person to the request who will be notified and able to manage the request along the way? If we do add an additional involved party, do they go on to automatically become a domain manager too?
- Do we want to auto populate contact information into the form for current domain managers who start new requests? If we do, do we make it editable? 

### Issue Links

Relates to: #1585
Blocks: #1807 
Relates to: #404 
Relates to:  #523

**Comment by h-m-f-t** [comment]
@gabydisarli can you let me know if I'm still blocking?

**Comment by h-m-f-t** [comment]
I've cleared; removing the PO label.
