### ISSUE TITLE
Discovery: Organizational model for domain management

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1818]
### Issue description

Discovery work associated with #1817 

- [x] Kickoff meeting during Discovery: [bookmark to 2-22-24 NOTES](https://docs.google.com/document/d/1M4KdBZOCcL8nmD0HILuuSeYIAABrGzSXocWn7w2ca-Q/edit#bookmark=id.ngo4g934zr4g)
- [x] Workshop held 3-12-24 to develop use cases and goals. [NOTES from 3-12-24 meeting](https://docs.google.com/document/d/1rBblGavYKKWf-H7QLA-4yu9LuZPcAyeginE-JGjOp5s/edit#heading=h.ybuai578ljg5) including link to Miro board.
- [ ] User Research and Usability testing

### Acceptance criteria

- [x] Goals defined ([view doc](https://docs.google.com/document/d/18R6w8eRC11PwPx3gGRFsm4bMd0SuNKEaV6rEsnDAPk0/edit#heading=h.bwz6akfvtix))
- [x] User scenarios created ([view doc](https://docs.google.com/document/d/18R6w8eRC11PwPx3gGRFsm4bMd0SuNKEaV6rEsnDAPk0/edit#heading=h.bwz6akfvtix))
- [x] Research questions created (Started, [view doc](https://docs.google.com/document/d/1toCnuuULVRaLj39rE_hi0gAdi8uZlhk8Yds2-8QY5L0/edit#heading=h.ugpx44z8p0jy), [view Miro](https://miro.com/app/board/uXjVNm-Av80=/?moveToWidget=3458764582977813887&cot=14))
  - [x] Research questions answered and summarized 
- [x] User interviews completed
  - [x] Summary of user interviews documented
- [x] User flow diagram created (separate ticket here: [1939](https://github.com/cisagov/manage.get.gov/issues/1939))
- [ ] Requirements defined and documented
  - [ ] Confirm which elements should be included in v1
- [ ] Determine which dev aspects can begin before design is complete
- [ ] Design & dev tickets created

### Additional context (incomplete)

_Rough requirements_

- [ ] An "organization" exists and is the "parent" to 1 or more domains. 
- [ ] The organization has a name, an AO, an address, domains, and at least one org manager. 
  * An AO is mapped 1:1 to an agency. If a domain's agency changes, the AO for the domain is the new agency's AO. If an AO for the organization changes, the AO for that org's domains are updated.
- [ ] An org manager can request new domains for the organization, manage any domain in their org, create/modify domain managers (including metadata, assigned domains, and relevant permissions), and run org-wide reports. 
- [ ] Only users that are part of a federal agency _organization_ may make requests for a federal domain.
- [ ] An org manager can restrict access to their organization's domains to Login.gov accounts that (solely) use their organization's official email address.
  * This requires that we review all email addresses on a Login.gov account (#523), and do that on each authentication.

Changes that follow on after the org model exists:
 - [ ] In the request form, we provide a way for people that believe they should be able to make a federal domain request (i.e., drop to email; we won't allow these requests to be submitted).

_No response_

### Links to other issues

EPIC: #1817

**Comment by h-m-f-t** [comment]
* We made a board outlining goals, non-goals, use cases
* We emailed a federal agency asking to interview them about how they might use these features

**Comment by PaulKuykendall** [comment]
Sounds like we can meet with GSA on Thursday, March 21,2024 to hear about their needs managing multiple domains.

**Comment by vickyszuchin** [comment]
Moving to this sprint 44 "In-review" ticket to sprint 45 per below guidance:

There is a grace period for sprint tickets that need just a little more time to close at the end of the sprint. The guideline are as follows with the following status :

In-progress: the ticket will move over at noon EST on Day 1 (Wed) to the new sprint
In-review: the ticket will move over at 9am EST on Day 4 (Monday) to the new sprint

**Comment by vickyszuchin** [comment]
Per guidance, any "In progress" tickets from sprint 45 will be moved over to Sprint 46 noon EST on Day 1.

**Comment by vickyszuchin** [comment]
Per guidance, any "In review" tickets from sprint 46 will be moved over to Sprint 47 noon EST on Day 3 (6/10).

**Comment by h-m-f-t** [comment]
@katypies started creating new epics for this work that takes over this issue. See the (Slack thread](https://cisa-corp.slack.com/archives/C03QM0JGSQG/p1718646916529869) pitching it to the team.
