### ISSUE TITLE
Better advertise .gov townhalls

### ISSUE THREAD

**Issue by kristinacyin** [cisagov/manage.get.gov#1827]
### Issue description

Think of ways to better advertise and conduct future townhalls (next one is coming up in May)

A few ideas:
- Add content advertising townhall events to get.gov (blog post?)
- Update townhall slides to be more visually appealing
- Ways to improve the Microsoft events page?

### Acceptance criteria
- [x] Plan is documented and confirmed with Cameron
- [x] GitHub tickets created (if needed)

**Comment by vickyszuchin** [comment]
Suggested timeframe: work in April (Sprint 42/32) for May townhall

**Comment by kristinacyin** [comment]
[Figma drafts](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?type=design&node-id=2970-5013&mode=design)

**Comment by vickyszuchin** [comment]
Moving to this sprint 44 "In-review" ticket to sprint 45 per below guidance:

There is a grace period for sprint tickets that need just a little more time to close at the end of the sprint. The guideline are as follows with the following status :

In-progress: the ticket will move over at noon EST on Day 1 (Wed) to the new sprint
In-review: the ticket will move over at 9am EST on Day 4 (Monday) to the new sprint
