### ISSUE TITLE
Define & document the user research process

### ISSUE THREAD

**Issue by kristinacyin** [cisagov/manage.get.gov#1830]
### Issue description

Goals
- Define standard approach for conducting research (there are always exceptions, though!)
- Streamline our research efforts with templates
- Ensure the process is documented for future team members

### Acceptance criteria

- [x] Audit existing research materials and determine which pieces could be standardized
- [x] <Strike>Document the research & recruitment process; create a checklist for setting up research</strike>
- [x] <Strike>Create templates that can be reused for future research efforts</strike> Turned these ACs to #2155 
- [x] Brainstorm other ways our current process can be improved upon (create separate tickets, as needed)
- [x] <Strike>Conduct an analysis of research tools (ideally have already been used in federal government settings)</strike> This should not be part of this ticket

### Additional context

- [Miro board](https://miro.com/app/board/uXjVNAv2Lic=/) for laying out steps in our current user research process, and finding opportunities for improvement (will transition this to FigJam)
- [Retro board](https://miro.com/app/board/uXjVNVGR0yw=/) (will also transition this to FigJam)

**Comment by vickyszuchin** [comment]
Accepted into the backlog. Nice to have before new hires onboard. Suggested timeline: 1-2 sprint away from Sprint 41.

**Comment by PaulKuykendall** [comment]
in refinement: 4/15 - perhaps Christina could work this, spanning over a couple of sprints.
