### ISSUE TITLE
Multi-select Delete button does not cause the list (either one) to refresh

### ISSUE THREAD

**Issue by rachidatecs** [cisagov/manage.get.gov#1833]
### Current Behavior

Deleting an item from the available or chosen lists works as expected but the widget does not update.

### Expected Behavior

After deleting an item from either list, the lists should update to show that the item was removed.

### Steps to Reproduce

1. Go to a domain request
2. Delete a 'alternative domain' or 'other contact'
3. The list does not refresh even though the item is deleted

![Screenshot 2024-02-29 at 1 26 46 PM](https://github.com/cisagov/manage.get.gov/assets/107004823/38aa2647-951a-4e41-9760-51f7daef7900)

### Additional Context

This is due to how the Django JS works. The JS looks at selected options on page load, creates a new <select>, moves the options to the new <select> and deletes them in the source <select>

This JS does not run when our custom delete button is clicked. The item does get deleted but the markup does not referesh.

An ideal solution is to run the Django code from our JS. If that proves too tricky, we should probably just trigger a page refresh after a delete which would take us a couple of minutes to implement.

**Comment by PaulKuykendall** [comment]
4-10 bug triage. Close as no longer relevant.
