### ISSUE TITLE
On Domain requests table, by default, show only domains that are in an active state

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#1838]
### Issue description

When picking up a new domain request, analysts don't initially need to see requests in a `Started` state because they are not yet `Submitted` and may not have been completed by the requester. Similarly, they don't need to see `Approved`, `Rejected` or `Ineligible`, all of which are in a non-active request status.

### Solution:
The default view in the `Domain applications` (soon `Domain requests`) table in DjA should **exclude** domains in a non-active request state. However, it should still be possible for analysts to see them of they so choose. This will require a multi-select filter.

### Acceptance criteria

- [ ] On the domain requests list page, the domain status filter allows for multi-selections.
- [ ] The default view (first render) in the `Domain requests` displays with the domain status filter set to include only `submitted`, `in review`, and `action needed` statuses.
- [ ] A selection is available to clear or modify all filter settings, so that all request appear for the analyst.

### Additional context
[Slack discussion ](https://cisa-corp.slack.com/archives/C05TS76RVS6/p1709053285399059)

<img width="628" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/603901/cdf4b83a-26dd-4714-b03a-5329b2f01914">

### Links to other issues

🔄 #1837

**Comment by PaulKuykendall** [comment]
@rachidatecs - is it possible/easy to create a compound filter, allowing for include as well as exclude? (Not sure how difficult this is with the DjA toolbox)

**Comment by PaulKuykendall** [comment]
Edited the original description to include from a multi select on the filter, as well as clarifying the default settings for first rendering of the page.

**Comment by vickyszuchin** [comment]
Action item from 3/6 product huddle met. Removed "refinement" tag.
