### ISSUE TITLE
Improving the layout of domain requests for analysts

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1839]
### Problem:
Analysts need to scroll and sometimes navigate to different pages to collect the information most useful to them when adjudicating a request. Creator, Submitter, and AO are of particular interest to them in quickly assessing their confidence with the supplied information.

### Solution:
(based on UX research and feedback from Alex)
Bring the most relevant information to the TOP of the request form, in the Analyst view, so that the analysts save time and have a delightful experience.

See the Miro Wireframe for layout.
[Layout #2](https://miro.com/app/board/uXjVNtCl1JY=/?moveToWidget=3458764580518702651&cot=14)

### Acceptance criteria

- [ ] Admin Domain Request page layout is updated per the Miro
- [ ] Review with designer and @amcelya for acceptance

### Links to other issues

Blocks: #1852

**Comment by h-m-f-t** [comment]
I think option 3 in the Miro is the most viable, though I have some recommendations on it, too.

**Comment by PaulKuykendall** [comment]
We'll be doing Option #2 in this ticket, then Option #3, then Option #4 to complete the layout revamp.
