### ISSUE TITLE
Add language encouraging registrants to "plan ahead" when requesting a domain

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1847]
### Issue description

Sometimes it takes longer than expected to approve a domain, which can be frustrating for our users. We should add language to the following pages encouraging registrants to plan ahead and request their domain long before they may want to use it.

https://get.gov/domains/moving/ 
https://get.gov/domains/before/.

### Acceptance criteria

- [x] Write content
- [x] Update language on the pages mentioned above

**Comment by vickyszuchin** [comment]
Suggested timeframe: sprint 42

**Comment by vickyszuchin** [comment]
This ticket was moved to sprint 44 in the "In review" status.
