### ISSUE TITLE
Django Admin: Show audit trail for status changes

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1849]
### Issue description

Problem/Opportunity: analyst want to see the history of status changes to a request so that they can easily discern how many times it has been worked or reworked.

Solution: provide an audit trail of just the status changes, easily accessible to the analyst. 

### Acceptance criteria

- [ ] On the domain request page, analysts see an audit trail showing just status changes for the current request they are reviewing, directly below the current status.
- [ ] Feedback and approval from design team/PO

### Additional context

For each status change displayed in the list, include Status, Analyst/user, date&time.
Put this at the top, default to Shown, with a "More Details (**Show/Hide**)," option as was implemented in #1853.

![Image](https://github.com/cisagov/manage.get.gov/assets/62573986/7c5b0848-3d24-4746-9137-080b93fbea85)
[Working Miro can be found here.](https://miro.com/app/board/uXjVKWEbutM=/)

### Links to other issues

Blocked by: #1853

**Comment by vickyszuchin** [comment]
Refinement tag: pending diagram

**Comment by PaulKuykendall** [comment]
Changed the field order per PO feedback, and cleaned up the additional context a bit.

**Comment by vickyszuchin** [comment]
[Slack discussion](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1714070964000459) on WIP review.
