### ISSUE TITLE
Django Admin: Make the Save... panel a sticky bar for the domain request

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1854]
### Issue description

Problem: Analysts need to scroll clear to the bottom of the domain request page in order to "Save" their changes. This journey is so long, that they sometimes forget why they were scrolling and might need a snack or nap along the way.

Solution: Make that "save" panel a sticky bar so that it's always handy and convenient, like a highway gas station. The bar should stay fixed to the bottom of the viewport.

Also, include the requested domain name above the buttons and contained within that sticky bar.

### Acceptance criteria

- [ ] Per the [simple diagram note](https://miro.com/app/board/uXjVNtCl1JY=/?moveToWidget=3458764580801065500&cot=14), the Save panel is sticky and will remain accessible to the analysts throughout any scrolling.
- [ ] the requested domain name should be above the buttons and contained within that sticky bar.

### Links to other issues

Blocked by: #1839

**Comment by vickyszuchin** [comment]
Per @abroddrick , this ticket should be considered for sprint 41.
