### ISSUE TITLE
Remove filter for the "Verified by Staff" table

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1861]
### Issue description

Django admin: On the "Verified by Staff" page, the "by requestor" filter is unnecessary and it lists every requestor in the registrar (making it impossible to use).

### Acceptance criteria

- [ ] Remove the "by requestor" filter on the "Verified by Staff" page in the admin

### Additional context
Remove this:
<img width="297" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/603901/52233001-44a1-4f8f-a0b9-850d63852b8d">

**Comment by vickyszuchin** [comment]
Per Cameron to move it from "future analyst experience" to " analyst quick wins". (3/4 - refinement trio).
