### ISSUE TITLE
Django Admin: List all associated domains and requests for `contacts`

### ISSUE THREAD

**Issue by kristinacyin** [cisagov/manage.get.gov#1875]
### Story

As an analyst
I want to be able to view all the existing domains or requests associated with a particular **contact**
so that I can adjudicate requests much easier

### Acceptance Criteria
- [ ] Figma design has been created for displaying existing domains or requests associated with a particular contact
- [ ]  Link design approach to dev ticket for implementation (https://github.com/cisagov/manage.get.gov/issues/2026 )

### Issue Links

- Relates to: #1668 (implementing this for users)
- Relates to: #1623 (PR is #1664)
- Relates to: #1850 (1850 should be done first)
- Blocks: #2026 

### Additional context
While the pictures shows multiple items associated with the contact, this is not what will show, we will most likely just have one domain and or one request associated with each contact since we allow duplicates and do not consolidate contacts.  May not actually provide a ton of value to analysts

**Comment by vickyszuchin** [comment]
Split into design ticket and dev ticket.

**Comment by Katherine-Osos** [comment]
@abroddrick I know a lot of things changed with the profile work and some connections were severed. Is this ticket still relevant?

**Comment by katypies** [comment]
Closing this per comments on #2026
