### ISSUE TITLE
Registrar stays online but inaccessible to users during a release

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#1878]
### Current Behavior

manage.get.gov stays "online" during a release but is unavailable to users. A white screen of ~~death~~ slumber is displayed while it updates with the new code.

See [Slack thread ](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1709764847895839?thread_ts=1709764784.188419&cid=C05BGB4L5NF) for screenshot and troubleshooting discussion.

### Expected Behavior

manage.get.gov should be available to users during a release. 

### Steps to Reproduce

1. During a release, access manage.get.gov
2. See the blank screen displayed. 

### Environment

Environment: Stable

**Comment by vickyszuchin** [comment]
Added to current sprint (sprint 40) by approval of Alysia and Cameron. This may run into the next sprint.

**Comment by vickyszuchin** [comment]
"Block" tag added: dependency on external partner.

**Comment by abroddrick** [comment]
External partner replied back saying we are doing the releases right currently and there is nothing we can or should change there. They said it is most likely an issue with out application.

seems like a low reward bug for further investigation at the moment

**Comment by abroddrick** [comment]
blocked tag removed per the above comment

**Comment by katypies** [comment]
Closing this. We don't have a strong view of how this should be handled right now, so will reopen if/when that's the case.
