### ISSUE TITLE
Admin: Send automated emails at 30 day mark for "in review" and "submitted" requests

### ISSUE THREAD

**Issue by kristinacyin** [cisagov/manage.get.gov#1903]
### Issue description

A lot of the helpdesk emails we receive are checking in on requests that have not yet been approved/rejected. To reduce the amount of helpdesk emails we receive, we should sent an automated "hey this might take a bit longer" email for requests with the "submitted" or "in review" status if they've had those statuses for over 30 days. 

### Acceptance criteria

- [ ] _Content_: [Draft](https://drive.google.com/drive/folders/1Pt2kQIKJ8f4AWYuGp5OcI9aipqyV5BvR?usp=drive_link) email content ("submitted" vs "in review" requests will probably have different wording)

### Additional context

[Product huddle notes 3/13/24](https://docs.google.com/document/d/1jatolB9YaQLITwqx25y0B1u5J23S_J19PawXtIaov8o/edit)

### Links to other issues

Blocks: #1994

**Comment by vickyszuchin** [comment]
Per Product:  consideration for sprint 42 or sprint 43.

**Comment by abroddrick** [comment]
This ticket needs to be broken up into one for content and one for developers

**Comment by abroddrick** [comment]
Hey @vickyszuchin and @PaulKuykendall I put in her and mentioned in refinement that this ticket needed to be broken up to remove the dev portion and have the dev portion in a follow on ticket. Was this ticket made?

**Comment by PaulKuykendall** [comment]
> Hey [@vickyszuchin](https://github.com/vickyszuchin) and [@PaulKuykendall](https://github.com/PaulKuykendall) I put in her and mentioned in refinement that this ticket needed to be broken up to remove the dev portion and have the dev portion in a follow on ticket. Was this ticket made?

one moment... ran into trouble on Friday afternoon, and I don't think it saved properly.

**Comment by h-m-f-t** [comment]
Content note: The language we've been using is "business days", not simply "days". Let's take this into account when we send a notice.

**Comment by vickyszuchin** [comment]
Discussed in refinement meeting (4/9). Request to have this discussed in next product huddle.
