### ISSUE TITLE
404s on contact links in search results

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1907]
### Current Behavior

We used to have the contact us page live at get.gov/help/contact but we've since changed it to get.gov/contact. When searching the site, the old links show up and when clicked, result in 404. 

![Image](https://github.com/cisagov/manage.get.gov/assets/144387994/803304df-4685-4b15-a990-640dbdcb3d9d)

### Expected Behavior

These old links shouldn't show up in search results

### Steps to Reproduce

1. Go to get.gov
2. Search "contact us"
3. Observe both pages in the search results and click on the old link, see 404.

### Environment

Live, Chrome

**Comment by rachidatecs** [comment]
Probably cached indexing in search.gov

**Comment by h-m-f-t** [comment]
Maybe we should consider doing something like https://brianm.me/posts/eleventy-redirect-from/

**Comment by abroddrick** [comment]
Closing as a won't do given we can no longer replicate it. This was most likely a caching issue. We can reopen this ticket if it resurfaces. Note, if this issue resurfaces we should investigate if this issue is coming from something bigger.
