### ISSUE TITLE
Dev: Require invited domain managers to provide contact information 

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#1919]
### Issue description

In certain scenarios (see design ticket for more info) we switch to IAL1 for domain managers. Because we can't return a contact object with a first or last name we need them to add this information on first log in. 

### Acceptance criteria

- [ ] All of the following ACs should be under the feature-flag for User Profile.
- [ ] For any domain managers on log in while missing required profile information, (usually this will be those who login for the first time and go through IAL1 ) take them to the User Profile and [present a modal](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=4293%3A18647&mode=dev) that they must confirm in order to proceed. 
- [ ] The [User profile page is modified](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=9%3A6826&mode=dev) so that users can't do anything else in the registrar without first updating their contact info. The .gov Registrar logo in the header is disabled. In the footer, the Manage your domains link is removed.
- [ ] On hover over the header logo, [a tooltip appears](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=30%3A62830&mode=dev)
- [ ] [Success message displays](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=4263%3A17258&mode=dev) when user adds contact info. The header logo becomes clickable, a link button appears so users can navigate back to dash, the Manage your domains link appears back in the footer
- [ ] If user dismisses modal and tries to save the form with no inputs, all the regular field validation error shows as well [as a unique error telling them they have to add this contact info to proceed](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=7%3A6533&mode=dev)

### Additional context
Note for ial1, you can just check if they are missing first and last name.
[Content document](https://docs.google.com/document/d/1u-K1yQKb16H3AWj33mH2e1LJme6Ay9dNXMG8isiOXWk/edit#heading=h.316dzhhhorkm)

### Links to other issues

Blocked by #1807 
Blocked by #2054

**Comment by vickyszuchin** [comment]
Removed "blocked": tickets blocking this ticket have been completed.

**Comment by vickyszuchin** [comment]
Moved this out of sprint 46 because of dependency.
