### ISSUE TITLE
Django admin: Update field labels

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1920]
### Issue description

We audited field labels across the admin and identified opportunities to make the labels more meaningful and consistent. 

Also, we audited the search bar "helper text" (which appears below each search bar in the admin). We need to make a few tweaks to those, as well.

### Acceptance criteria

- [x] Update field labels within the admin as outlined within the [updates to labels](https://docs.google.com/spreadsheets/d/1dXe28ZpyghFpxB_T-GZsDpFUKb96AdztsNPhFL0BvpE/edit#gid=393682108) tab of the spreadsheet. 
- [x] Update the search bar "helper text" as outlined with the [search helper](https://docs.google.com/spreadsheets/d/1dXe28ZpyghFpxB_T-GZsDpFUKb96AdztsNPhFL0BvpE/edit#gid=1935823459) tab of the spreadsheet.
- [x] Applies to Analysts and Super Users.

### Additional context

Reach out to Katherine if there are any questions about the spreadsheet.
### Links to other issues

Related to #1946

**Comment by vickyszuchin** [comment]
Accepted into the backlog. Proposed timeline: sprint 42.
