### ISSUE TITLE
============= T H E  L I N E =============

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#1932]
Issues above this line are prioritized relative to one another.

Issues below this line are NOT necessarily in priority order.

This marker has many labels applied, so it appears in most views of the backlog.
**_This marker should not be assigned to a Sprint, nor to an Epic or Slice._**

**Comment by h-m-f-t** [comment]
🤣😆🤣😆🤣😆🤣😆🤣😆🤣😆🤣😆🤣😆  

We should show this to the product team behind GitHub Projects.

**Comment by PaulKuykendall** [comment]
The LINE has served its purpose, and is being retired.
