### ISSUE TITLE
Org model: Create a user flow diagram to inform design

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#1939]
### Issue description

During the discovery process for the org model, we'll be defining goals and requirements as well as getting input from users. To help illustrate everything we're learning, we will create a user flow diagram and validate it with the team.

### Acceptance criteria

- [x] Draft of user flow diagram created
- [x] Draft has been shared with the team and modified, as needed, based on feedback
- [ ] Finalized version of the user flow diagram receives sign-off

### Links to other issues

Relates to #1818

**Comment by vickyszuchin** [comment]
This ticket was moved to sprint 44 in the "In review" status.
