### ISSUE TITLE
Figma: Updates to Manage domains and domain overview pages to match dev

### ISSUE THREAD

**Issue by rileyorr** [cisagov/manage.get.gov#1969]
### Issue description

The form registrar's [Manage domains](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?type=design&node-id=428-9590&mode=design&t=ny0XC44Ax1EHoq5t-4) and [Link](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?type=design&node-id=3768-22749&mode=design&t=Aux4LFPg8CFStYTE-4) Figma pages do not match dev. They should be updated and the existing art boards should either be deleted or archived.

Updates needed per [the audit spreadsheet](https://docs.google.com/spreadsheets/d/10OMqnuahDxS5cLfU8u2NIgLNWHbW_A75w_0V4tw2UPs/edit#gid=249167645):
- Empty state dashboard incorrect color styles (Rows 5 and 6)
- Updates are needed in the dashboard table component (Rows 7 and 8)
- Domain overview:
   - Remove 'Back to your domains' link (Row 9)
   - Content updates (Row 11)
   - Left stepper menu (Row 12)
   - 'Submitted' domain request state is missing (Row 13)

### Acceptance criteria

- [x] Updates have been made to the domain dashboard art boards 
- [x] Updates have been made to the domain overview art boards
- [ ] Gaby has reviewed the Figma branch and updates have been merged into the main file

**Comment by vickyszuchin** [comment]
Per guidance, any "In progress" tickets from sprint 45 will be moved over to Sprint 46 noon EST on Day 1.

**Comment by rileyorr** [comment]
@gabydisarli I just sent you over a branch review request!
