### ISSUE TITLE
Figma: Updates to Manage DNS page and sub pages to match dev

### ISSUE THREAD

**Issue by rileyorr** [cisagov/manage.get.gov#1970]
### Issue description

The [Manage DNS](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?type=design&node-id=1143-33696&mode=design&t=3TkcRRxwxxtK0MZ8-4), [DNS name servers](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?type=design&node-id=1539-97539&mode=design&t=3TkcRRxwxxtK0MZ8-4), and [DNS DNSSEC](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?type=design&node-id=1211-54145&mode=design&t=3TkcRRxwxxtK0MZ8-4) Figma pages do not match dev. They should be updated and the existing art boards should either be deleted or archived.

Updates needed per [the audit spreadsheet](https://docs.google.com/spreadsheets/d/10OMqnuahDxS5cLfU8u2NIgLNWHbW_A75w_0V4tw2UPs/edit#gid=249167645):
- Manage DNS updates:
   - Content updates (Row 14)
   - Left stepper menu updates (Row 15)
- DNS name servers updates:
   - Art board formatting is making multiple components flow outside of the boards' borders (Row 16)
   - Error state mockup needed (Row 17)
   - Error state component updates needed (Rows 18 - 21)
   - Happy path success message is using an info alert rather than success alert component (Row 22)
- DNS DNSSEC updates:
   - Remove 'Back to manage your domains' link on all art boards (Row 23)
   - Content updates to info alert (Row 24)
   - Error state updates (Rows 25 and 26)
   - DS data record input fields component needs to be fixed to display correct width (Row 27)
   - DS data record success alert is currently using an info alert (Row 28)
   - Content updates (Row 29)

### Acceptance criteria

- [ ] Manage DNS updates have been made
- [ ] DNS name servers updates have been made
- [ ] DNS DNSSEC updates have been made
- [ ] Gaby has reviewed the Figma branch and updates have been merged into the main file

**Comment by joet333** [comment]
@Katherine-Osos do we want to update this issues based on the recent audit? All updates need are on each page within the [.gov registrar Figma file.](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=3816-38507)
