### ISSUE TITLE
Figma: Get.gov updates for existing pages in the Figma file

### ISSUE THREAD

**Issue by rileyorr** [cisagov/manage.get.gov#1972]
### Issue description

The Figma file's Get.gov existing pages need updates. This ticket captures updates for those existing pages. 

Updates needed per [the audit spreadsheet](https://docs.google.com/spreadsheets/d/10OMqnuahDxS5cLfU8u2NIgLNWHbW_A75w_0V4tw2UPs/edit#gid=249167645):
- Global update for site footer across all pages (Row 4)
- Home page content updates (Row 3)
- Domains page content updates (Row 5)
- Benefits of .gov domains content updates (Row 7)
- Blog page styling updates (Row 16)
- Blog article styling updates (Row 17)
- Help page content updates (Row 18)
- Search results styling updates (Row 23)
- HTML error styling updates (Row 24)

### Acceptance criteria

- [ ] Global updates have been made 
- [ ] Content updates have been made for the following pages:
   - [ ] Home
   - [ ] Domains
   - [ ] Benefits of .gov domains 
   - [ ] Help
- [ ] Styling updates have been made for the following pages:
   - [ ] Blog
   - [ ] Blog article 
   - [ ] Search results
   - [ ] HTML error
- [ ] Gaby has reviewed the Figma branch and the updates have been merged into the main file

**Comment by joet333** [comment]
@Katherine-Osos do we want to update this issues based on the recent audit? All updates need are on each page within the [get.gov Figma file.](https://www.figma.com/design/qeWM03sfjXgHBHB23rsD6X/get.gov?node-id=2211-25393&t=SHWmXIOpZrqrBVNl-1)

**Comment by joet333** [comment]
I think this one is already accounted for in the new one we just created do we want to delete or archive this? (Idk what you typically do for outdated/not doing work?)

@Katherine-Osos

**Comment by Katherine-Osos** [comment]
This is covered in #1973
