### ISSUE TITLE
Migrate Domain Requests and Domain info to no longer use deprecated agency names

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#1975]
### Issue description

We created a Federal agency table that removed duplicate and incorrect values (ticket #1928). However, that ticket just created the table and filled it with the correct values, and it will be connected with the federal agency drop down in ticket #1793. However, some requests and domain information objects may be using the old agency names or invalid values that we do not to keep around. We should migrate any request or domain information to use the appropriate new federal agency name. This ticket can be done at the same time as 1793, but it's advised they be separated branches/PRs for ease of reviewing. 
### Acceptance criteria

- [ ] create a migration script or the like to change any _domain request_ and _domain information_ object that is using "removed" agency names and have them use their correct counter part in the field created in #2029 (see additional context)
- [ ] unit test for some cases (don't need to test everything)

### Additional context
Note: the field that should be updated is the updated_federal_agency field and it should contain the foreign key to Federal Agency table

for unit testing, don't worry about testing every case, only test a couple of the cases

- Have at least one test where a value can’t be found in the table
- Have at least one test for a value that is one of the removed agency names (make sure it maps to the correct agency name). Your code should be using a dictionary for these 10ish values

[PR which added Federal Agency table](https://github.com/cisagov/manage.get.gov/pull/1928)

Items that need deprecating:
**Note** "State, Local, and Tribal Government" should change to Non-Federal Agency. (it was removed entirely as an invalid option)

See below for the remaining (keep is what you should change any "remove" values to):

| Keep  | Remove |
| ------------- | ------------- |
| Appraisal Subcommittee of the Federal Financial Institutions Examination Council  | Appraisal Subcommittee |
| Barry Goldwater Scholarship and Excellence in Education Foundation | Barry Goldwater Scholarship and Excellence in Education Program |
| Federal Reserve Board of Governors | Federal Reserve System |
| Harry S. Truman Scholarship Foundation | Harry S Truman Scholarship Foundation |
| Japan-U.S. Friendship Commission _(create new, replace existing)_ | Japan-US Friendship Commission _and_ Japan-United States Friendship Commission _(remove both)_ | 
| John F. Kennedy Center for the Performing Arts | John F. Kennedy Center for Performing Arts |
| Occupational Safety and Health Review Commission | Occupational Safety & Health Review Commission |
| Corporation for National and Community Service | Corporation for National & Community Service |
| Export-Import Bank of the United States | Export/Import Bank of the U.S. |
| Medicare Payment Advisory Commission | Medical Payment Advisory Commission |
| Peace Corps | U.S. Peace Corps |
| U.S. Chemical Safety Board | Chemical Safety Board |
| U.S. Nuclear Waste Technical Review Board | Nuclear Waste Technical Review Board |

### Links to other issues

relates to #1928 (ticket to add federal agency table- closed)
relates to #1793 (ticket to connect federal agency table to the drop list- next ticket)

**Comment by therealslimhsiehdy** [comment]
This is Ticket part 2 for Federal Agency changes

**Comment by vickyszuchin** [comment]
This ticket was carried over to sprint 44 in the "In review" status.

**Comment by therealslimhsiehdy** [comment]
FYI we had approval on Friday from Zander for this ticket, but we decided not to merge due to the gulp issue -- we are waiting for [2075 ](https://github.com/cisagov/manage.get.gov/pull/2090) (the fix for the gulp issue) to be merged, and then we will merge this ticket as well.

(We also found a possible duplicate Federal Agency and are confirming if that should be removed + renamed as well)
