### ISSUE TITLE
Retrieve info from engineering Fellow on Cypress 

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2000]
### Issue description

@erinysong will be having a meeting with an engineering Fellow who has offered to knowledge share on cypress and how they used it on their project to perform end to end testing and get around login.gov. For reference, login.gov doesn't provide test accounts with two factor auth so they personally recommend to just stub out their end point when testing as the two factor auth options are not set in stone either.

### Acceptance criteria

- [ ] briefly review the fellow's [repo](https://github.com/GSA-TTS/FAC/blob/main/backend/cypress/e2e/login.cy.js) prior to the meeting
- [ ] meet and takes notes asking questions from [this thread](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1711648592669389) and any logical follow-ons you have
- [ ] summarize notes in the [end to end research doc](https://docs.google.com/document/d/1rozoga1bgDRfumAGqXdTYtXqGMaVfSZ-FLXZAi1-VMw/edit#heading=h.dk3ttsg8kvgo)
- [ ] sum up what you learned in an eng huddle meeting. ( don't foget to add it to [eng huddle agenda](https://docs.google.com/document/d/16S6VNKOYW2HI7bKwOwOdQzon5SZA0ZgkMkGfQHLZoTw/edit#heading=h.gw2e13758zoc) when you're ready.

### Additional context

[Slack discussion](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1712621404690189)

### Links to other issues

#1537

**Comment by h-m-f-t** [comment]
@abroddrick this is a test mention ⚙️

**Comment by h-m-f-t** [comment]
@h-m-f-t testing for you too
