### ISSUE TITLE
Verify registry implementation to allow user to renew year from current date

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2003]
### Issue description

Verify Cloudflare implementation to allow user to renew year from current date. The registry renewal command accepts the current date value instead of only the last expiration date

### Acceptance criteria

- [x] Verify registry renewal command accepts the current date value instead of only the last expiration date
- [x] Close #1806, once this functionality is confirmed in OT&E/production.
- [x] Create dev ticket to integrate with registrar renewal process, slotted for "Next" sprint from this completion.

### Links to other issues

Relates to #1806

Ticket created as a result: #2274

**Comment by abroddrick** [comment]
tentatively slotted for april 24th sprint

**Comment by abroddrick** [comment]
This was done but the feature is not up to par with what we want moving, it down to sprint 46 at the earliest

**Comment by abroddrick** [comment]
Closing as all steps are now complete ticket made was #2274
