### ISSUE TITLE
Dev: List all associated domains and requests for `users`

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2006]
### Issue description

As an analyst
I want to be able to view all the existing domains or requests associated with a particular **user**
so that I can adjudicate requests much easier

### Acceptance criteria
In Django admin:
- [ ] On an individual user record, below contact information, list all domains a user is associated with EXCEPT those in "deleted" state. Other criteria include:
  - [ ] Each domain links to the corresponding "domains" record
  - [ ] Each domain also displays its current state in parenthesis. For example: domain.gov (Ready)
  - [ ] Domains are listed in alphabetical order (starting with numerical, if applicable)
- [ ] On an individual user record, below list of domains, list all domain requests a user is associated with EXCEPT those in "started" or "withdrawn" status. Other criteria include:
  - [ ] Each request links to the corresponding "domain request" record
  - [ ] Each request also displays its current status in parenthesis. For example: domain.gov (In Review)
  - [ ] Domains are listed in alphabetical order (starting with numerical, if applicable)
- [ ] Before creating PR, confirm implementation plan with designer and share early iterations of the layout.

### Additional context

**NOTE:** A user can be associated with dozens of domains, so the design should accommodate that; explore ways to display many values without creating a long scrolling page. 

[Slack discussion thread
](https://cisa-corp.slack.com/archives/C05TS76RVS6/p1715179482192209)

### Links to other issues

related to: #1668 (this ticket was closed; design phased was skipped)

**Comment by vickyszuchin** [comment]
"Blocked" tag added: dependency on design ticket

**Comment by vickyszuchin** [comment]
Moved to "Backlog" status because it was split from #1668.

**Comment by vickyszuchin** [comment]
Blocked label: this is blocked by design ticket which is currently scheduled for sprint 45

**Comment by vickyszuchin** [comment]
Per agreement from design and dev (in refinement meeting), to merge the design (#1668) and this dev tickets into one ticket given the straight-forwardness of the design.

**Comment by vickyszuchin** [comment]
"refinement" label added: questions in slack discussion need to be addressed by product.

**Comment by PaulKuykendall** [comment]
@Katherine-Osos agreed to update the ACs with notes from the refinement meeting and the Slack channel.

**Comment by vickyszuchin** [comment]
Per guidance, any "In review" tickets from sprint 46 will be moved over to Sprint 47 noon EST on Day 3 (6/10).
