### ISSUE TITLE
Reminder: run migration script on stable

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2009]
### Issue description

Ticket #1911 creates a migration, since the dev lead is gone, other devs will be responsible for running the migration script once it reaches stable. 

### Acceptance criteria

After making the stable release that releases #1911  (located pr #1993) do the following
- [ ] ssh into the sandbox and get the number of domain information objects and domain requests with org_type set to null
- [ ] run the script with the real csv file
   - watch the output and verify that printed numbers of domain info and domain requests that _will_ be changed matches the number found above
- [ ] Verify it worked
  -  the number of changed domain info / domain requests matches the expected number that you got in the first AC
  - repeat the query from the first AC (via ssh shell into the sandbox) and confirm it's now 0
  - investigate any errors

### Additional context

If errors do occur, avoid hotfixing for just a few domains, only do a stable hotfix if the number is unreasonable to fix manually.

### Links to other issues

blocked by: #2008

**Comment by PaulKuykendall** [comment]
4/18 standup - this will likely be run next Tuesday.

**Comment by therealslimhsiehdy** [comment]
[Slack discussion on script](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1713909611005909) being run and see comments for more detailed information and notes
