### ISSUE TITLE
Investigate architecture and code impacts of combining creator/submitter

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2015]
### Issue description

Design requires creator and submitter to no longer be separated, though they were separated for engineering reasons: 1.) users leave 2.) people submit requests on behalf of others, 3.) a user is login.gov related so having a contact be associated on Requests had long term benefits.

With us collapsing these two how can we do it with out negative ramifications and what do we do with old requests that have this logic

### Acceptance criteria

- [ ] investigate ramifications of combining creator and submitter
   - what to do when they are different
   - what about old requests
   - what happens when a user leaves/gets deleted what should show on the analyst view
- [ ] update dev ticket made at the close of #1808 and investigate the other related design tickets for any updates/ ramifications
 

### Additional context

See historical comments: https://github.com/cisagov/manage.get.gov/issues/404#issuecomment-1442087169

### Links to other issues

blocks #1807 
blocks #2047

**Comment by abroddrick** [comment]
as of now I think I made all the tickets and have found everything @vickyszuchin but I think I want another day when I'm back to look over the admin portion as I think I'm missing a couple things

**Comment by vickyszuchin** [comment]
This ticket has been moved forward to sprint 46.

**Comment by abroddrick** [comment]
@vickyszuchin this was done, I just didn't close it
