### ISSUE TITLE
Bug: domain name in sidebar navigation and main nav overflows when domain name is long

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2016]
### Current Behavior

If a domain name is long, a user will see the name "overflowing" its container in the sidebar navigation on the domain management pages. See screenshot.

~~![Screenshot 2024-04-11 at 1 32 12 PM](https://github.com/cisagov/manage.get.gov/assets/107440934/ba0b5857-0d81-429a-b108-d4d21d04c357)~~

### Expected Behavior

~~Long domain names that risk running over the container should be truncated and show an ellipse with CSS~~

**Update:** On the domain page for domain overview, long domain names that risk running over the container on both the sidebar and "main container" should be wrapped to the next line 

This update was per [this slack discussion](https://cisa-corp.slack.com/archives/C06BZBJUUF8/p1726782507780149)

### Steps to Reproduce

View a really long domain name on the domain management pages, view the spillover

### AC

- [ ] For side: Long domain name on sidebar wraps
- [ ] For main container: Long domain name on main container wraps

### Additional Context

~~See [slack thread](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1712850397785749) where this bug was brought up~~
See [Slack thread ](https://cisa-corp.slack.com/archives/C06BZBJUUF8/p1726782507780149)for why we went with wrapping text versus truncating

**Comment by PaulKuykendall** [comment]
This could be addressed as part of #2544

**Comment by vickyszuchin** [comment]
@abroddrick would you provide the story point for this ticket? We can move this to "Ready" once that is provided.
