### ISSUE TITLE
Create a new field Agency that exists on Domain Request and Domain Info

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2029]
### Issue description

 #1793 and #1975 have the goal of making all agency values connected to the Agency table, instead of just the agency list that is hard encoded. However, we don't want to just automatically connect change the variable federal_agency to connect to the Federal Agency table, because then we will lose the values already entered (which are strings). We instead need to make a **new** field that holds a value that is connected to the agency table. After we have a field that exists for this on the domain request and domain information tables we will then be able to unblock the migration script ticket #1975

### Acceptance criteria

- [ ] add a new field to Domain Request and DomainInformation called agency that ties to the Federal Agency table
- [ ] superusers can see this but not analysts (this will just be empty for now so we don't need to show it to them and add confusion)
- [ ] displayed label on django admin should still say federal agency (hence, even more reason to not show for analysts, this may be confusing for analysts)

### Additional context

note, this should result in a migration file and permission change migration file, but as long as you can see this in django admin as a drop down as a superuser and add/remove it to Domains Information and domain request, you should not need a unit test. 

### Links to other issues

blocks #1975  (migration script to do next)
blocks #1793 (connect to drop down)

**Comment by therealslimhsiehdy** [comment]
Ticket #1, Erin and I are currently working on this
