### ISSUE TITLE
Admin: Reorder options in the request "status" dropdown menu

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#2036]
### Issue description

Within Django admin: We need to slightly modify the order in which domain "statuses" are listed in the dropdown menu on a Domain Request page. It's currently too easy to accidentally click "Approved" during the review process. 

### Acceptance criteria

- [ ] Statuses in the dropdown menu reflect this order: 
  - In Review
  - Action Needed
  - Approved
  - Rejected
  - Ineligible
  - Submitted
  - Withdrawn
  - Started

### Additional context

[See slack thread](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1712721335104159)

Only statuses applicable to the current state should be shown. (per normal operations)
Changing the order of the default list will change the list in the FSM.

**Comment by vickyszuchin** [comment]
PO suggested timeline: 1-2 sprint from sprint 43.
