### ISSUE TITLE
Certificate transparency discovery

### ISSUE THREAD

**Issue by erinysong** [cisagov/manage.get.gov#2037]
### Issue description

Certificate Transparency (CT) is a web security protocol in which log certificates are issued by a certificate authority (CA). This allows the public and site operators to see what certificates a CA has issued.

The .gov team procured [SSLMate](https://sslmate.com/) which offers SSL Certificates, a log aggregator that scrapes certificates, and Certificate Search API, an API that allows users to search CT logs that provide information on a domain's SSL certificates (e.g., expired certificates, subdomains).

This issue involves researching ways in which SSLMate's SSL Certificates can be used to improve the .gov program's services and provide useful information to users.

@h-m-f-t 

### Acceptance criteria

- [ ] Research and document findings on SSLMate's applications to .gov program.

### Links to other issues

#2040 covers researching Certificate Search API, the other SSLMate product .gov has procured.

**Comment by h-m-f-t** [comment]
Dup of #2040
