### ISSUE TITLE
Make lateral scrolling easier in Django Admin

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2042]
### Story

As a analyst
I want to be able easily laterally scroll tables in django admin
so that I don't waste time scrolling vertically first to access the scroll bar

### Acceptance Criteria

- [ ] investigate ways to make lateral scrolling easier for mouse users

### Additional Context

This [insight came out of the Diary Study](https://miro.com/app/board/uXjVNzTcAj4=/?moveToWidget=3458764585776862131&cot=14) with analysts. An analyst commented that its tedious for them to scroll laterally on the domain requests table because they first have to scroll down to find the scroll bar. Trackpad users can use gestures to easily laterally scroll across the table, but mouse users will have less ease scrolling with the current implementation. There are some workarounds for mouse users but they are not universally known or accessible. We should investigate ways we can improve this experience.

See [Product huddle notes from April 17, 2024](https://docs.google.com/document/d/1jatolB9YaQLITwqx25y0B1u5J23S_J19PawXtIaov8o/edit#heading=h.byp2x5js4o2b) for more discussion 

Suggested solutions
- put another scroll bar at the top of the table

**Comment by PaulKuykendall** [comment]
Thanks for capturing this, @gabydisarli! At the end of our Product Huddle, @Katherine-Osos pointed out that the Shift key will cause the mouse scroll-wheel to perform a lateral shift. Unless this is super-easy, I would recommend that the analysts using mice try the `shift`-scroll option to see if that eases their pain.

**Comment by PaulKuykendall** [comment]
@h-m-f-t - Will followup with Diana to see if the shift-scroll will suffice and make this ticket unnecessary

**Comment by PaulKuykendall** [comment]
Got confirmation from analysts that this is not necessary at this time.
