### ISSUE TITLE
Add summary box with user's profile information to Preamble

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2055]
### Issue description

As part of the larger work around adding a user profile, we need to add a users contact information to the preamble when they start a new request. This info will be pulled from their user profile and shown as a summary box on the preamble

### Acceptance criteria

- [ ] on the preamble page: add another text section: Follow the [content and layout shown here](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=2247%3A70204&mode=dev)
- [ ] add a summary box that shows the users contact information ^ the above link shows this too (this should go off of the contact object linked with their user
- [ ] all the above should only show when the profile waffle flag is turned on (see #2054 and linked pr #2100) 

### Links to other issues

Relates to #1808 (collapse creator/submitter design ticket)
Relates to: #1807 (implement user profile dev ticket)
Relates to #1585 (user profile design ticket)
Relates to #1573 (force invited domain manager to add contact info)
blocked by: #2054

**Comment by vickyszuchin** [comment]
Per guidance, any "In review" tickets from sprint 45 will be moved over to Sprint 46 noon EST on Day 4.
