### ISSUE TITLE
Add new link to empty domains table on the dashboard

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2056]
### Issue description

For users who have accidentally linked their wrong login.gov account to .gov. Let's add a new link that helps them self serve.

### Acceptance criteria

- [ ] New link is added to the domains table on the management dashboard when it is empty ([Figma](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=2727%3A7236&mode=dev))

### Additional context

This appears for all users who have a empty domains table.

### Links to other issues

Relates to https://github.com/cisagov/manage.get.gov/issues/1808 (collapse creator/submitter design ticket)
Relates: https://github.com/cisagov/manage.get.gov/issues/1807 (implement user profile dev ticket)
Relates to https://github.com/cisagov/manage.get.gov/issues/1585 (user profile design ticket)
Relates to https://github.com/cisagov/manage.get.gov/issues/1573 (force invited domain manager to add contact info)
Relates to: #[274](https://github.com/cisagov/get.gov/issues/274)

**Comment by PaulKuykendall** [comment]
in NEW triage - this should be fairly independent and useful. So specified a higher priority. Tentatively slotted into S44.

**Comment by vickyszuchin** [comment]
This ticket was reviewed by Rachid. Summary:
- quick fix
- no issue with adding this to sprint 44
