### ISSUE TITLE
create sandbox for christina

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2058]
### Issue description

Create Christina's sandbox

### Acceptance criteria

- [x] Christina's sandbox is created
- [ ] epp creds added
- [ ] email creds added
- [x] fixtures are loaded

### Links to other issues

blocked by: #2052

**Comment by vickyszuchin** [comment]
Note to developer: the "Blocked by" ticket seem incorrect.

**Comment by abroddrick** [comment]
@vickyszuchin the blocked by has been fixed it should have been blocked by 2052 and instead it had 2054, just a bad keyboard entry there.

**Comment by vickyszuchin** [comment]
"blocked" label removed. #2052 is done.
