### ISSUE TITLE
UI Design: wireframes for org manager

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#2063]
### Issue description

As a logged-in organization (portfolio) manager,
I want a dashboard with summary information about my organization, and 
I want a list of all the domains in my organization (portfolios), and
I want a `User settings` page where I can manage the domain managers privileges,

### Acceptance criteria

- [x] Wireframes for Org Manager Dashboard
- [x] Wireframes for domains page
- [x] Wireframes for User Management page, specific to the organization

### Additional context

Portfolio manager must be logged in and verified.
ADD link to requirements documentation.

### Links to other issues

Blocks: #2161

**Comment by vickyszuchin** [comment]
Moved to "Planned" with approvals from Paul and Katherine.
