### ISSUE TITLE
UX Discovery: Create strategy for exposing org details throughout the admin

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#2064]
### Issue description

As we implement the organization model, which will be loosely-coupled to the domains and domain managers which are part of that organization, we will need an elegant way to reflect the relationship between all of these entities.

This is a discovery exercise to show user(s), how the entity that they are looking at relates to other parts of the organization. For example, when looking at a domain, we need to indicate that it belongs to an organization. Similarly, when looking at a user, we need to indicate that they are part of a domain, and that they manage certain domains.

Also, under the organization model, the presented view of a domain or domain request will have some parts that are inherited from the organization, like organization name and address, and senior official, along with some parts that are specific to that particular domain. In this exercise, we will clearly define those fields in order to create requirements for developers to implement the necessary architecture.

### Acceptance criteria

- [x] review every affected page in the registrar to determine how it would show the org model relationships.
- [ ] Create dev tickets as necessary

### Additional context

We need to answer questions like the following:
* for each page, if it involves an organization, what data elements need to be on the page to best inform the user?
* how will we indicate that a domain or domain request belongs to an organization?
* how will we indicate that the request creator is an org manager?
* what information will we display on the organization dashboard, like a list of domains and other meta-data?

### Links to other issues

Epic: #1772 
Related to: #2063

**Comment by vickyszuchin** [comment]
Moved to "Planned" with approvals from Paul and Katherine.
