### ISSUE TITLE
Design: define notifications needed for org model

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#2065]
### Issue description

In addition to the regular notifications associated with domain requests and domain management, stakeholders within an organization will want to receive copies of certain notifications, based on their role and their user preferences.

STORY:
As an org member,
I want to receive notifications appropriate to certain events that take place within my organization
So that I may properly manage and be aware of those events

### Acceptance criteria

- [x] Determine notification requirements for org members regarding their organizations and their domains (emails, in-platform messaging)
- [x] Determine which of these notifications are also applicable to existing domain managers (who are not part of an org) and define how content can be used for that user group, as well.
- [x] Create ticket(s) for writing this content

### Additional context

- Existing registrar notifications are largely unaffected by the introduction of the "organizational model." However, the org model creates a need for additional or duplicate notifications for certain events.

- Some notifications will be applicable only to the org model, while other notifications will be applicable to current domain managers, as well. Keep both user groups in mind and define which notifications could be implemented before org model rolls out.

### Links to other issues

EPIC: #1772

**Comment by vickyszuchin** [comment]
"refinement" label added: this ticket is still being worked by @PaulKuykendall

**Comment by vickyszuchin** [comment]
@Katherine-Osos to review and split the issue into multiple tickets.

**Comment by vickyszuchin** [comment]
Removed "refinement" label: Katherine has modified this ticket to focus on defining the notifications needed. And added an AC to create separate tickets for writing that content once it's been defined.
