### ISSUE TITLE
Determine new term for "Authorizing Official" and where updates are needed

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#2096]
### Issue description

"Authorizing official" can be confusing for some users as that term has different meanings at various organizations (in particular, federal orgs). To reduce confusion for users, we need to come up with a new term to use instead of "authorizing official." 

### Acceptance criteria

- [x] Brainstorm options for replacing "authorizing official."
- [x] Discuss options with team and come to a decision on new term. (Agreed on Senior Official, SrO)
- [x] Identify where this term needs to be updated across the registrar/admin and make a plan for updating.
- [x] Create related tickets, as needed. 
  - [x] manage.get.gov impacts
  - [x] get.gov impacts
  - [x] Django Admin impacts

### Links to other issues

Blocks:
- [x] #2258 
- [x] #2259

**Comment by PaulKuykendall** [comment]
@PaulKuykendall  - Add this to tomorrow's fireside

**Comment by PaulKuykendall** [comment]
Discuss on 5/9/2024 Fireside.

**Comment by PaulKuykendall** [comment]
We have agreed on "Senior Official" or "A Senior Official". We will need just e tickets to make these changes in get.gov, manage, and admin.

**Comment by vickyszuchin** [comment]
Per guidance, any "In progress" tickets from sprint 45 will be over to Sprint 46 noon EST on Day 1.

**Comment by PaulKuykendall** [comment]
@PaulKuykendall - make dev tickets for manage & get.

**Comment by vickyszuchin** [comment]
Per guidance, any "In review" tickets from sprint 46 will be moved over to Sprint 47 noon EST on Day 3 (6/10).
