### ISSUE TITLE
Finalize list of Senior Officials (SOs) for federal agencies

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#2097]
### Issue description

The SOs for federal agencies are well defined. To streamline domain requests and ensure metadata across domains/requests is consistent, we need to create a table within the admin that pairs the appropriate SO with each federal organization. 

Before that table can be created, we need to finalize the list of SOs.

### Acceptance criteria

- [x] [Finalize list](https://docs.google.com/spreadsheets/d/14oXHFpKyUXS5_mDWARPusghGdHCrP67jCleOknaSx38/edit?usp=sharing) of SOs for federal agencies
- [ ] Create dev ticket for adding a table to the admin

**Comment by vickyszuchin** [comment]
Per fireside meeting, actions items regarding this ticket:

**Comment by vickyszuchin** [comment]
Per guideline, all "Planned" and "In progress" tickets from Sprint 46 will moved forward at noon EST on Day 1 of new sprint (Sprint 47).

**Comment by abroddrick** [comment]
@h-m-f-t I just realized that the table linked in this ticket is missing some Senior Officials. Is the link outdated and another is better or are we assuming we just won't have AOs for those agencies yet and will have to add it?

**Comment by PaulKuykendall** [comment]
@abroddrick - I would definitely keep the "initials" and "status" fields in the agency table. It may be interesting to filter by FCEB versus non-FCEB agencies in the future. Also, the initials/acronym are "official" and would be potentially useful in the future. https://www.cisa.gov/news-events/directives/federal-civilian-executive-branch-agencies-list

**Comment by h-m-f-t** [comment]
@abroddrick the linked spreadsheet is canonical. If it's empty there, the SO isn't known.

I also think adding initials would be worthwhile. Capturing whether a federal agency is "FCEB"=True would also be valuable.
