### ISSUE TITLE
UX Design: Determine additional ways to notify users of the processing delay

### ISSUE THREAD

**Issue by witha-c** [cisagov/manage.get.gov#2103]
### Issue description

How should we share information about processing delays with users in the authenticated registrar? 
 
Do we need to make changes to manage.get.gov content? 
Update content on preamble page?
Add a site-wide banner on manage.get.gov?

### Acceptance criteria

- [ ] Determine the updates that should be made to manage.get.gov
- [ ] Create designs in Figma
- [ ] Create dev ticket if applicable 

### Additional context

Early concepts are [here](https://www.figma.com/file/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?type=design&node-id=2919%3A5878&mode=design&t=WH0oaE7QfeOQ0J0d-1)

### Links to other issues

Relates to [279](https://github.com/cisagov/get.gov/issues/279)

**Comment by PaulKuykendall** [comment]
Analysts feel like this is "working" for the moment. No action at this time.
