### ISSUE TITLE
Django admin: text with embedded links does not have enough contrast in dark mode

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2106]
### Current Behavior

When in DJA dark mode, text with embedded links do not have enough contrast on the links.

See[ slack thread](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1714523594048779) for screenshot

### Expected Behavior

Text with embedded links when you are deleting an object have enough contrast on the links, in DJA dark mode meets accessibility requirement

### Steps to Reproduce

1. navigate to "user domain role" in Django admin
2. delete user role 

### Environment

Stable

**Comment by PaulKuykendall** [comment]
Did determine this bugs severity, we need to know how likely it is to occur and what the relative impact would be.
Does this throw us out of compliance? Or is it just a usability issue that might affect a very few people that operate in dark mode?
