### ISSUE TITLE
Design: Hi-Fidelity mockups of the domain management experience for Org admins

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#2123]
### Issue description

Create hi-fidelity wireframes for Org admins to manage domains. This includes the ability to view, favorite, filter, and search domains in the domains table. Additionally, this covers the flow an org admin takes from landing on the domains page, clicking manage a domain, making updates, and returning to the dashboard. 

### Acceptance criteria

**Create hi-fi mockups for**
- [x] domains page
- [x] domain management pages from the view of an org admin

**Create prototype for**
- [x] filtering domains
- [x] searching domains
- [x] managing a domain, updating its information, and returning to dashboard (domain page) Note: this prototype does not have to show all functionality of domain management pages.

**Team review**
- [x] share for product/po/design approval

**Handoff to development**
- [x] Discuss with @abroddrick on strategy for creating dev tickets
- [ ] Mark Figma pages as dev ready
- [ ] Create dev tickets and make sure google content docs are included in all tickets

### Additional context
**🚨Kickoff required🚨**
At the start of a development block for an org model feature, design & dev will have a kickoff to discuss designs and incorporate any dev feedback prior to implementation

### Links to other issues

Organization model epic: #1772 
Lo-fi wireframes: #2063

**Comment by vickyszuchin** [comment]
"refinement" label added: ACs need further refined. The refinement of the ACs are depended on a ticket (#2063) in current sprint. Revisit during next reminder (5/20).

**Comment by gabydisarli** [comment]
Breaking up this ticket to be more manageable to the design team and less blocking for developers

**Comment by vickyszuchin** [comment]
Per guideline, all "In review" tickets from Sprint 47 will moved forward at noon EST on Day 4 of new sprint (Sprint 48).

**Comment by gabydisarli** [comment]
closing as dev tickets are created and designs are approved
