### ISSUE TITLE
UX: create research plan for formal usability testing of org model

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#2125]
### Issue description

PROBLEM:
The introduction of the org model requires that we confirm with our potential users that are concept and designs are delightful and extraordinarily useful in supporting them in their responsibilities.

SOLUTION:
Create a plan to conduct formal usability testing for the org model, and prepare to execute.

### Acceptance criteria

- [ ] formal detailed plan for the org model usability testing is established and ready for execution

### Links to other issues

EPIC: #1772

**Comment by PaulKuykendall** [comment]
This is dependent on working software. However, the planning can happen sooner.

**Comment by Katherine-Osos** [comment]
@PaulKuykendall @katypies This is a duplicate ticket with #2404. Closing this ticket.
