### ISSUE TITLE
Product: create rollout strategy for org model participation

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#2126]
### Issue description

PROBLEM:
The introduction of the org model to the registrar requires a rollout plan for on boarding, new organizations, and education of the user base about interacting with the org model.

SOLUTION: 
Create a detailed plan for the formation of new organizations based on existing data, as well as rollout plan for presenting to the user community.

### Acceptance criteria

- [ ] acceptable, detailed plan for the creation of organizations based on the existing registrar data (product)
- [ ] detailed plan for the anticipated rollout and on boarding of new users (product)
- [ ] content created as necessary for communication with new users (design)

### Links to other issues

EPIC: #1772

**Comment by vickyszuchin** [comment]
"refinement" tag added: per triage meeting, the issue need more refinement. Currently, it is a combination product and design ticket. May consider splitting.

**Comment by katypies** [comment]
This has been superseded by other onboarding issues!
