### ISSUE TITLE
Requirements: for CSV exports for multi-domain managers

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#2127]
### Issue description

OPPORTUNITY:
The introduction of the org model to the domain registrar, creates an opportunity for enhanced reporting for administrators of these organizations. Additionally, non-org domain managers with multiple domains would benefit from downloadable reports showing all of the domains within their charge.

### Acceptance criteria

- [x] define requirements for reporting at the organization level and for any domain manager with multiple domains(product)
- [x] indicate where and how to download reports (light design work)
- [x] any design tickets, if necessary, are created.
- [x] dev ticket created
  - #2323  
  - #2348 

### Links to other issues

EPIC: #1772

**Comment by PaulKuykendall** [comment]
@PaulKuykendall - modify this to include non-org multidomain managers

**Comment by vickyszuchin** [comment]
@PaulKuykendall, title suggested during triage: "Determine the requirements for CSV exports for multi-domain domain managers"

**Comment by vickyszuchin** [comment]
Per guideline, all "Planned" and "In progress" tickets from Sprint 46 will moved forward at noon EST on Day 1 of new sprint (Sprint 47).

**Comment by PaulKuykendall** [comment]
@vickyszuchin - for today's standup. I deprioritized this temporarily due to my family situation and training. This will be my focus for this afternoon, since training is complete now.

**Comment by vickyszuchin** [comment]
Per guidance, any "In progress" tickets from sprint 47 will be moved over to Sprint 48 noon EST on Day 1.
