### ISSUE TITLE
Enhance `Additional details` page to require CISA rep contact name

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#2136]
### Issue description

In previous issue #1895, we allow a requester to specify with which regional representative they may be working in order to help our analysts make contact, if necessary, to reach an approval decision more quickly.

During the demo of this feature, it was determined that we would like to require the `first name` and `last name` of that CISA regional representative, and that the email address should be optional. This issue is intended to make that enhancement.

![Image](https://github.com/cisagov/manage.get.gov/assets/62573986/e215e8de-0924-43d3-859a-224545d82e27)

### Acceptance criteria

- [ ] if a request or indicates that they are working with a CISA regional representative on the additional information page, then the CISA regional representatives first and last name are required fields.
- [ ] similarly, the CISA regional representatives email address is requested, as optional.

### Additional context

This requirement came out of the May 3 demo of the new feature, allowing a domain requester to tell us if they're working with a person from the CISA regions.

### Links to other issues

Related to #1895, building upon that work.
Blocks: #2171

**Comment by vickyszuchin** [comment]
Per guidance, any "In review" tickets from sprint 45 will be moved over to Sprint 46 noon EST on Day 4 (5/28).

**Comment by vickyszuchin** [comment]
Per guidance, any "In review" tickets from sprint 46 will be moved over to Sprint 47 noon EST on Day 3 (6/10).
