### ISSUE TITLE
Go over requirements for Org model and begin looking at architecture impacts

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2143]
### Issue description

Paul has gathered requirements for the Org model but it needs dev review to see at a high level what still raises questions for development and what can be started architecture wise

### Acceptance criteria

- [ ] review the excel Paul has and get clarity/flag any issues

**Comment by vickyszuchin** [comment]
Per guidance, any "In progress" tickets from sprint 45 will be moved over to Sprint 46 noon EST on Day 1.

**Comment by abroddrick** [comment]
Moved back this was finished it was just not closed
