### ISSUE TITLE
Update the "Here's how you know" banner to align with latest USWDS

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#2145]
### Issue description

https://designsystem.digital.gov/components/banner/ has newer, better text describing how people can know they're on an official US government site. They have good .gov language! We should use it.

### Acceptance criteria

- [ ] Update [base.html](https://github.com/cisagov/manage.get.gov/blob/main/src/registrar/templates/base.html) with the content at https://designsystem.digital.gov/components/banner/

### Additional context

Updating USWDS should also pull in these changes, which we might consider doing instead.

This issue is for manage.get.gov. There is [another issue for get.gov](https://github.com/cisagov/get.gov/issues/291), since they are separate sites.

### Links to other issues

* 🔄 Related to cisagov/get.gov#291
* Related to #812 (possibly fixed by)

**Comment by PaulKuykendall** [comment]
This may already be covered when we update USWDS

**Comment by katypies** [comment]
This looks to be updated on manage.get.gov via the changes in #812 

![image](https://github.com/user-attachments/assets/27b26f30-dcaa-44d1-a30b-b47d47808c25)
