### ISSUE TITLE
Admin: Show all `domain managers` associated with a particular domain on one page

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#2150]
### Issue description

PROBLEM:
When looking at a domain record in the analyst tool, the analyst cannot directly see the list of domain managers associated with that particular domain. As a result, the analyst needs to navigate to the user roles link (side nav) and query the domain name to find the list of users. While that is effective, it is an extra step which can be streamlined into one view to aid the analysts.

Story:
As an analyst viewing a domain detail
I want to see a list of all associated **domain managers** with an indicator of their invited or retrieved state on that same page
So that I have immediate access to contacts regarding that particular domain.

### Acceptance criteria

- [ ] designed visuals or descriptions appropriate for development are delivered to product for review
- [ ] product has created necessary dev tickets based on design

### Additional context

This is the inverse of ticket #2006, which shows a list of domains for users. In this case, we want to show the list of USERS (domain managers) on a domain.

**Comment by h-m-f-t** [comment]
@PaulKuykendall hello in :slack:

**Comment by katypies** [comment]
Superceded by 
- #2524
