### ISSUE TITLE
Toolkit of UX research resources

### ISSUE THREAD

**Issue by witha-c** [cisagov/manage.get.gov#2155]
### Issue description

Compile a toolkit of research resources, including templates, checklists, and guides, that our design team has found useful in the past so it can guide our future research work. 

### Acceptance criteria

- [x] Gather and edit an initial set of resources to include in the toolkit. Among other, include these at a minimum: 
- [x] A basic checklist for conducting research with users (covering ethics (e.g. anonymity) and regulations (e.g. PRA))
- [x] An interview template

- [x] Set up the toolkit in the manage.get.gov Wiki
- [x] Create a process for planning and managing additions to the toolkit

### Additional context

[Toolkit draft](https://docs.google.com/document/d/1EvQ35lkjLnhrpc9FjIAqCgVUFGZBWG5XAzGVfdfhDqg/edit?usp=sharing)

### Links to other issues

Relates to #1830

**Comment by vickyszuchin** [comment]
Per design team, this ticket will continue in sprint 47.

**Comment by vickyszuchin** [comment]
Per guideline, all "In review" tickets from Sprint 49 will moved forward at noon EST on Day 4 to current sprint (Sprint 50).
