### ISSUE TITLE
Update documentation for setting up fed devices as dev machines and add links to onboarding flow

### ISSUE THREAD

**Issue by erinysong** [cisagov/manage.get.gov#2159]
### Issue description

A new federal engineer (i.e., really any product team member) should be able to use their government-furnished equipment (GFE) for development (and similar) work. Let's improve the processes in the "Developing..." doc below and include relevant links to it in our onboarding documentation.

- [Developing on a CISA laptop doc](https://docs.google.com/document/d/1ZyaaTWOEgVEHiHarNuv97CnYfUFe-4pfbuQm4ocLkn4/edit?usp=drive_web&ouid=114289654039812461823) (started by 18F and modeled after a GSA doc)
- [.gov Project: Onboarding](https://docs.google.com/document/d/1ukbpW4LSqkb_CCt8LWfpehP03qqfyYfvK3Fl21NaEq8/edit?pli=1#heading=h.6dw0iz1u56ox)
- [GitHub engineering onboarding ticket](https://github.com/cisagov/manage.get.gov/issues/new?labels=dev%2C+onboarding&template=developer-onboarding.md&title=Developer+Onboarding%3A+GH_HANDLE)

### Acceptance criteria

- [ ] Review "Developing on a CISA laptop" and update the document into a workable procedure/checklist. Update as needed.
- [ ] Have another team member try it out.
  - You can tag @katypies, @witha-c, or @h-m-f-t in Slack for a review.
- [ ] Update onboarding docs on ".gov Project: Onboarding" as needed.
~- [ ] Investigate options to move onboarding onto other markdown doc formats.~

**Comment by abroddrick** [comment]
hey @erinysong we had discussed in eng huddle we were going to go over the eng onboarding as a team and discuss what changes we want to make but postponed given we had _thought_ we were going to have so many people out in april/early may. What inspired the ticket creation here? We can move up the timeline of that group discussion if we are seeing a need to do this earlier

**Comment by h-m-f-t** [comment]
@abroddrick I asked @erinysong to create this issue. It's primarily about getting federal computers prepared for dev tasks.

**Comment by erinysong** [comment]
@abroddrick ah I forgot about the eng huddle where we discussed going over onboarding as a team, that was my bad. In that case, we can limit the scope of this ticket to only include updating setup on a federal laptop if that makes more sense

**Comment by h-m-f-t** [comment]
@abroddrick this is a test notification

**Comment by h-m-f-t** [comment]
@abroddrick this is a test message! :slack:

**Comment by katypies** [comment]
I added some comments/tried to start streamlining the 18F documentation regarding setting up a CISA laptop. Though, I'm at a stop/pause point and it maybe isn't as helpful as I was hoping it might be so far :D -- mostly though, I feel like I'm lacking a bit of context around some of it and whether I need alllll the things mentioned or not. In any case, I have not yet been successful in getting things set up on my CISA laptop, so am happy to be a guinea pig/help with updating initially even though I won't be doing any full-on development.

**Comment by h-m-f-t** [comment]
Thanks @katypies! I think we should definitely articulate in the doc who should be requesting what software. I can help with that.
