### ISSUE TITLE
Remove submitter from Domain Requests and Domain Info

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2162]
### Issue description

Creator will now be used to send emails (#2157) and at this point #2156 will have informed any user whose request is still active that their previous contact email (aka the submitter email) will no longer be used. We can now go ahead and just delete the submitter from Domain Request, Domain Info and any lingering places where it is still being used like unit tests, comments and fixtures

### Acceptance criteria

- [x] remove any contact associated with a submitter (this should be a migration file not a script)
- [x] remove submitter from models (domain Request/domain info)
- [x] remove submitter from references in comments and unit tests
- [x] remove submitter from fixtures
- [x] regenerate our database schema image without submitter in it
- [x] remove any other reference to submitter not mentioned above

### Links to other issues

- [ ] blocked by #2157 
- [ ] blocked by #2156 
- [ ] once merged run this one: #2285 
- [ ] blocked by #2327 
- [ ] blocked by #2408

**Comment by abroddrick** [comment]
marking this as blocked as we need to wait until the user profile feature is turned on. @vickyszuchin does product have a ticket for evaluating the profile ? We could block this one by that.

**Comment by vickyszuchin** [comment]
Removed "blocked". The dependencies on other tickets have been resolved.

**Comment by vickyszuchin** [comment]
This ticket was moved from sprint 51 to sprint 52 during Sprint 52 kickoff meeting.

**Comment by vickyszuchin** [comment]
Moved to current sprint (Sprint 53).
