### ISSUE TITLE
User research participant roster

### ISSUE THREAD

**Issue by witha-c** [cisagov/manage.get.gov#2163]
### Issue description

We currently track research participants in spreadsheets related to each research project, but it would be helpful to track them centrally so we can better manage interested users, users who have participated in several research efforts, and other helpful details about participants. 

### Acceptance criteria

- [x] The roster is a spreadsheet in the Research folder
- [x] A short Read Me outlines how to manage the information in the roster (adding users, updating information)

### Links to other issues

Relates to #1830 Define and document the user research process

**Comment by vickyszuchin** [comment]
Per design team, this ticket will continue in sprint 47.

**Comment by kristinacyin** [comment]
Note: Insights tab will take more work / investigation, will make a separate ticket for it
