### ISSUE TITLE
Content: Inform users who have different emails on their "submitter" vs user profile that further emails will go to the User profile email

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#2167]
### Issue description

Refer to ticket #2156 for all background and requirements.

For the case where a domain request has a different creator from the submitter, we need clear content for an email, which will be sent to all parties, explaining that future correspondence will go solely to the creator email, and that the submitter email address will not be used

### Acceptance criteria

- [ ] [Content](https://docs.google.com/document/d/1JluHpbVe7ky02-TFsR_eA_wRVFkZrDst4eL_XV4d33A/edit) for this informational email is complete and approved by the program for use

### Links to other issues

Blocks: #2156 
Relates to: #2180

**Comment by vickyszuchin** [comment]
Per guideline, all "Planned" and "In progress" tickets from Sprint 46 will moved forward at noon EST on Day 1 of new sprint (Sprint 47).

**Comment by h-m-f-t** [comment]
Added link to draft content.

**Comment by vickyszuchin** [comment]
Per guideline, all "In review" tickets from Sprint 47 will moved forward at noon EST on Day 4 of new sprint (Sprint 48).

**Comment by vickyszuchin** [comment]
Per guideline, all "In review" tickets from Sprint 48 will moved forward at noon EST on Day 4 of new sprint (Sprint 49).

**Comment by katypies** [comment]
Not doing this one. Instead, we're updating the content on the page, and on get.gov to reflect changes.
* #2360 
* https://github.com/cisagov/get.gov/issues/305
