### ISSUE TITLE
Figma: Update to allow requester to provide regional representative information (first & last name)

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2171]
### Issue description

In #2136, we allow a requester to specify with which regional representative they may be working in order to help our analysts make contact, if necessary, to reach an approval decision more quickly. This include the first name and last name of that CISA regional representative (required), and the email address (optional).

We need to update the Figma related to this change.

### Acceptance criteria

- [x] Update figma to allow requester to provide regional representative information (first & last name)

### Additional context

[slack discussion](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1715711785158789)

### Links to other issues

Blocks: #2136

**Comment by gabydisarli** [comment]
I had already tackled some of this update a while ago and wanted to clear this ticket from our queue so I finished out the remaining few tasks.
