### ISSUE TITLE
Add pagination on Domains and Domain Request tables on home page

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2177]
### Issue description

Users may have a lot of domains and/or domain requests which makes it hard to manage them if you have to scroll through a longs list. Some users may have over a hundred domains they manage, and a long list of domains in the home page table makes it harder to find domains and see their statuses. For a better user experience, we should add pagination below both the Domains and Domain Request table on the home page.

### Acceptance criteria

- [ ] Add pagination on the Domain and Request tables on the home page
- [ ] pagination should appear below the tables and use USWDS components as shown in [this figma](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=4096-41972&t=iy2f2NLu7ojgtb5j-0)
- [ ] pagination should only show if a user has more than 10 domains or more than 10 requests respectively
- [ ] ensure sort stays intact when going to the next page
- [ ] Design-review complete (post-dev), so designers can capture changes in their backlog

**Comment by Katherine-Osos** [comment]
I'm reviewing this PR and noticed: 
1) The pagination for "domains" appears below the table / outside of the white card (as intended) but there is a white strip behind it. Can you apply a fill that matches the background color?
![Screenshot 2024-05-28 at 11 40 47 AM](https://github.com/cisagov/manage.get.gov/assets/119689946/f816818e-4f9e-4ef9-b468-b83459a14dac)

2) The pagination for "domain requests" does **not** appear below the table / outside of the white card. It should match the layout used for "domains." Can you update that? 
![Screenshot 2024-05-28 at 11 44 55 AM](https://github.com/cisagov/manage.get.gov/assets/119689946/a41b0d94-9f43-45c2-bb7a-15c3537de6ea)

**Comment by Katherine-Osos** [comment]
3. When viewing page "1" and I click page "2" (for the "domains" table), the page updates so that the page numbers are anchored at the top. But that is disorienting because that means the "domain requests" table is in view ... and the content for the table I want ("domains") is out of the frame. Can you adjust so that using pagination anchors to the top of the table being manipulated?

**Comment by witha-c** [comment]
Removed "skipped design" to reflect that an update to design documentation or libraries has been made.
