### ISSUE TITLE
(User profile) Remove Your Contact from the Domain Request flow 

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2178]
### Issue description

We have added in user profile now, so we can remove YourContact on the Domain Request flow as users should now just enter it on their profile.

### Acceptance criteria

- [ ] Hide Your Contact on the Domain Request flow when the user profile flag is turned on
- [ ] Hide Your Contact from the review page
- [ ] Edit unit tests as needed but within reason. This is a WIP.

**Comment by vickyszuchin** [comment]
Per guidance, any "In review" tickets from sprint 45 will be moved over to Sprint 46 noon EST on Day 4 (5/28).
