### ISSUE TITLE
Add Search bar on Domains and Domain Requests

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2179]
### Issue description

Some users have a longs list of Domains and Domain requests making it hard to find what they are looking for. To mitigate this, we want to add the ability for a user to search for a domain or request and have the table filter the results.

### Acceptance criteria

- [ ] add search bar (small variant) in the Domains table centered in line with the word "Domain"
- [ ] add search bar (small variant) in the Domains Request table centered in line with the words "Domain requests"
- [ ] the Domain's table search should search by domain name
- [ ] the Domain Request table should search by requested domain name
- [ ] Show designers your finished result before you do unit tests so they can give early feedback on moving the placement/allignment or size of the search bar.

### Additional context
Domains table, search bar should be centered inline with the word "Domains"
![image](https://github.com/cisagov/manage.get.gov/assets/109625347/6aaedf71-296b-4ab5-998f-1f5c71c9e13d)

Request table, search bar should be centered in line with the words "Domain requests"
![image](https://github.com/cisagov/manage.get.gov/assets/109625347/ce6ef199-0e16-4744-981a-f4f62570e9cb)

NOTE: both searches should only search by name for now

**Comment by Katherine-MN** [comment]
Removed "skipped design" to reflect that design documentation has already been updated to reflect these changes.
