### ISSUE TITLE
Discovery: Finalize DNS hosting summary document

### ISSUE THREAD

**Issue by witha-c** [cisagov/manage.get.gov#2189]
### Issue description

Finalize the DNS Hosting Goals document and determine next steps

### Acceptance criteria

- [ ] Finalize drafting the document with Cameron
- [ ] Solicit feedback from the team
- [ ] Sync with product to create new issues/milestones to capture next steps

### Additional context

Relates to: #1999 
[Actual Document in process](https://docs.google.com/document/d/1iaaBi2iXKoVAPzEcRbXQbXwN1_v4Lf67Qz3C95nHLEw/edit#heading=h.bwz6akfvtix)

**Comment by vickyszuchin** [comment]
Added this issue to sprint 46 per Christina's plan.

**Comment by vickyszuchin** [comment]
Per design team, this ticket will continue in sprint 47.

**Comment by vickyszuchin** [comment]
Per guidance, any "In progress" tickets from sprint 47 will be moved over to Sprint 48 noon EST on Day 1.

**Comment by witha-c** [comment]
@kristinacyin!
