### ISSUE TITLE
Utilize cloud.gov's cloning to clone a database from one sandbox to another

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2193]
### Issue description

We tried adding in an export feature into our system, but our Domain Information table is so large it gives a 500 on export which blocks us from using that data. Cloud.gov's team mentioned we can clone a db instance so it may be a simpler solution to just use cloud.gov. The reason we avoided this first was their documentation is a bit lacking and this would all be command line actions which are prone to error. However, it is worth us doing in order to have a sandbox with a backup of our stable that we can use for testing 

### Acceptance criteria

- [ ] follow the instructions in [cloud.govs cg-manage-rds article](url) to clone the database of one sandbox to another
- [ ] Document how to do this in a readme with easy to follow steps
- [ ] communicate with cloud.gov (via a ticket or their office hours) if you have any questions with their documentation

**Comment by vickyszuchin** [comment]
Per @abroddrick will not do.
