### ISSUE TITLE
Export function fails on stable

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2194]
### Current Behavior

Exporting from Domain information causes a 500 error

### Expected Behavior

The domain information should export as a file, with no error.

### Steps to Reproduce

1. go to /admin
2. go to domain information
3. click export
4. see error

### Environment

stable

### AC
After looking at how this could be solved it was determined that we need to expand the scope of this ticket to include the following

- [ ] script to export all the files via command line
- [ ] script to import all the files via command line (on non-production environments)
- [ ] script for clean up the database before import (should only work on non-prod environments)
- [ ] updated documentation with how to perform the imports/exports (ie documentation should now refer to the appropriate command line commands)

**Comment by vickyszuchin** [comment]
It is needed to support the import/export effort. Accepting it into sprint 46.

**Comment by abroddrick** [comment]
@vickyszuchin this isn't a pulled in one, I was trying to add it to the next sprint
