### ISSUE TITLE
Emails: Create emails for adding/removing a domain manager

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#2197]
### Issue description

We need to send an email when:

- a domain manager has been added to a domain
- a domain manager has been removed from a domain

The email would be sent to all domain managers for the domain (including the person who invited the new manager).

### Acceptance criteria

- [x] Email content has been created to announce when a domain manager has been added/removed
- [x] Create dev ticket (#2370) 

### Additional context

See [Miro](https://miro.com/app/board/uXjVNm-Av80=/?moveToWidget=3458764589022732660&cot=14) for brainstorming on notifications

### Links to other issues

Related to #2314

**Comment by vickyszuchin** [comment]
Per guideline, all "In review" tickets from Sprint 47 will moved forward at noon EST on Day 4 of new sprint (Sprint 48).

**Comment by Katherine-Osos** [comment]
Content created for this ticket: 
[Manager added to approved domain](https://docs.google.com/document/d/1P8WUqPdggGHjocTCktXgZDcJI-CiUY5sEj5Na2loph0/edit) (New email)
[Manager removed from approved domain](https://docs.google.com/document/d/197x7Azy8ITAdwt_QtJnJx0-EfUMJmwd57cx-DGRe6vU/edit#heading=h.gjdgxs) (New email)
[You’ve been added to a domain](https://docs.google.com/document/d/1HnMdniAB9INphrLwKjiACyNLrenyXy0QFf0-yz4EStI/edit#heading=h.gjdgxs) (This is an existing email, made text updates)
