### ISSUE TITLE
Content: Create plan for reviewing/writing content that appears for org model

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#2201]
### Issue description

In the org model designs, we've inserted various alerts and placeholder messaging. This ticket is to review those designs and come up with a plan for documenting that messaging, providing updated wording (as needed), and identifying additional notifications that may be needed.

### Acceptance criteria

- [x] Review designs and come up with a plan for documenting content and providing edits.
- [x] Break up the work into content tickets.

### Additional context

New tickets created as part of this ticket: 
https://github.com/cisagov/manage.get.gov/issues/2757
https://github.com/cisagov/manage.get.gov/issues/2758
https://github.com/cisagov/manage.get.gov/issues/2759

**Comment by gabydisarli** [comment]
I've started to adjust this [content doc](https://docs.google.com/document/d/1A6YBskXQLdewTixM2DN6uf3D5HiebvUUOcJRzj_AEuw/edit?usp=sharing) to document all error + success messages across the current domain manager pages. I figured I could use it as a jumping off point for this work but I haven't had much time to continue the work. Just leaving it here for context whenever this work is picked up.

**Comment by Katherine-Osos** [comment]
@AnnaGingle This ticket is for notifications in the UI rather than emails. So for domain groups they would be messages like "You've successfully created the following group: <group name>."

**Comment by AnnaGingle** [comment]
@Katherine-Osos Thanks! The [email notifications are here](https://docs.google.com/spreadsheets/d/1R6_I8eYcGDI87ZZ_9Fsif2XlmsoPP4aqlLT_juUng30/edit?gid=40843946#gid=40843946).

**Comment by AnnaGingle** [comment]
New ticket for the alert displayed on the domain manager page when a domain only has one DM: https://github.com/cisagov/manage.get.gov/issues/2732. The design in the ticket may need to be updated if the alert content changes.
