### ISSUE TITLE
Make emails read-only for Users for analysts

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2218]
### Issue description
This issue came from a review of a piece of the User profile work [PR 2173](https://github.com/cisagov/manage.get.gov/pull/2173#top). We're now going to be telling users that their profile pulls their email from their login.gov account and can't be changed on our system. If an analyst goes and changes their contact email, this would overwrite the email from their profile. This would cause confusion down the line for users.

_Originally posted by @gabydisarli in https://github.com/cisagov/manage.get.gov/issues/2173#issuecomment-2125820380_
         

### Acceptance criteria

- [ ] make email field for users in /admin read-only for analysts
- [ ] the "Personal info" title on the User page should also be renamed to "User profile" 

### Additional context
[See slack thread](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1716414902413409)

Links to other issues
🔄 Relates to #2055

**Comment by PaulKuykendall** [comment]
This may be partially resolved over the next two sprints.

**Comment by gabydisarli** [comment]
> This may be partially resolved over the next two sprints.

Can you clarify? How will it be resolved?

**Comment by h-m-f-t** [comment]
@abroddrick can you address @gabydisarli's question?

**Comment by abroddrick** [comment]
Yes, @gabydisarli the issue where changing a contact changes a users info (including in their profile) is what would be resolved shortly. When we separate users and contacts changing a "Contact" will have 0 effect on a user. However, of course this doesn't solve the fact that if you actually go to the User table, click a User and change their data, then they will see that change on their profile. Hence, the contact portion of this will be resolved shortly.
