### ISSUE TITLE
In the status "audit trail" on /admin, append the "Reason" when the status is "Rejected" or "Action needed"

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#2234]
Some domain statuses have a "reason" that accompany their selection. For instance, if an analyst chooses to reject a domain, they also select from a list of generic reasons why the domain was rejected.

The "audit trail" in a request's status history should include the reason.

### Acceptance Criteria

- [ ] When an analyst uses "Rejected" or "Action needed", the selected reason for those statuses is appended to the audit trail

#### Current screenshot
<img width="759" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/603901/6ae1c0ae-a20a-44f0-ac68-7911b5d5014f">

#### Proposed addition 
|Status|User|Changed at|
|-------|----|-----------|
|Rejected *- Org not eligible for a .gov domain*|Cameron|date|

### Links to other issues
This was thought to be part of #1900 but broken out. See also #2132 and #1849.

**Comment by h-m-f-t** [comment]
The original A/C read:
> A new column should appear after the "Status" column and used to track the "Reason" associated "Rejected" or "Action needed" statuses.

Do we want a new column dedicated to the reason, or would appending the name of the "Reason" to the Status be suitable? Like the italics show:
|Status|User|Changed at|
|-------|----|-----------|
|Rejected *- Org not eligible for a .gov domain*|Cameron|date|

**Comment by abroddrick** [comment]
Aesthetically the status with combined reason looks nicer in table form.

**Comment by Katherine-Osos** [comment]
@h-m-f-t I think appending the status with the reason works well! Let's do that.
