### ISSUE TITLE
Additional Details: Update messaging that indicates "required" elements

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#2239]
### Issue description

There are some inconsistencies with how we're displaying required information on the "Additional details" step of the request form. We need to make some updates to the messaging on that page.

### Acceptance criteria

- [ ] Update the message that currently appears at the top of that page. New messaging should read:
  * Required fields are marked with an asterisk (*).
- [ ] Add a new message above the first set of yes/no radio buttons: 
  * Select one(*).
- [ ] Add a new message above the second set of yes/no radio buttons: 
  * Select one(*). 
- [ ] If "yes" is selected for the second question, display a new message above the open text field that reads:
  * Provide details below (*).

- [ ] End result should match this [Figma file](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?m=auto&node-id=4036-2594&t=jCnsUTPwyI62TbQD-1) even if not listed in the above AC

### Additional context

See mock up in this [Figma file](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?m=auto&node-id=4036-2594&t=jCnsUTPwyI62TbQD-1).

**Comment by vickyszuchin** [comment]
refinement tag added: Alysia requests the additional context by made into ACs.
