### ISSUE TITLE
"Cisa regional representative" and "Anything else" not showing as incomplete

### ISSUE THREAD

**Issue by zandercymatics** [cisagov/manage.get.gov#2240]
### Current Behavior

When filling out a new domain request form, if you don't fill out the "Additional details" page and instead skip past it (by manually going to `/review`, the "review" page indicates that those fields are complete when they actually aren't. 

### Expected Behavior

When the boolean fields `has_anything_else` and `has_cisa_representative` are None, then the review page should display "incomplete" like the other fields.

### Steps to Reproduce

1. Start a new domain request
2. In the url, navigate to /request/review
3. Note the additional details field

### Additional Context

See [slack thread](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1717102079182029) for issue discussion

![image](https://github.com/cisagov/manage.get.gov/assets/141044360/a9620be9-cfb8-4da0-96af-f791980a792c)
![image (1)](https://github.com/cisagov/manage.get.gov/assets/141044360/60db4b51-bea4-476e-9b38-eca9d216a554)

**Comment by vickyszuchin** [comment]
Moving this ticket from sprint 51 to current sprint (sprint 50) since it's status is "In review".
