### ISSUE TITLE
Design: Hi-fidelity mockups of the member management experience for Org admins

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2241]
### Issue description

Create hi-fidelity wireframes for Org admins to manage their members across an organization. This flow covers the ability for an org admin to view all members across their organization, view additional information about a specific member, add a new member, and set member permissions.

### Acceptance criteria

**Create hi-fi mockups for**
- [ ] Members page
- [ ] Individual member page

**Create prototype for**
- [ ] Expanding a member row to view more information
- [ ] Adding a new member flow 
- [ ] Viewing a current member and changing their role or permissions
- [ ] Managing their access to domains

**Team review**
- [ ] share for product/po/design approval

**Handoff to development**
- [ ]  Discuss with @abroddrick on strategy for creating dev tickets
- [ ]  Mark Figma pages as dev ready
- [ ]  Create dev tickets ~and make sure google content docs are included in all tickets~

### Additional context
**🚨Dev/Design meeting required🚨**
Prior to the start of a development block for an org model feature, design & dev will have a meeting to review designs and incorporate any dev feedback prior to implementation. **Hold off on making any dev tickets** until the review has happened and design has had time to incorporate any changes.

### Links to other issues

🔄 Organization model epic: https://github.com/cisagov/manage.get.gov/issues/1772
🔄 Related to: https://github.com/cisagov/manage.get.gov/issues/2063 (lo-fi wireframes)

**Comment by AnnaGingle** [comment]
[Brainstorming doc](https://docs.google.com/document/d/1S2FchsKOj6vkHEfCtRmET76mhycy8MXwG0LHrmCNlQI/edit)

**Comment by gabydisarli** [comment]
@AnnaGingle and I discussed this morning and agreed we should break up this ticket into smaller chunks with more defined AC. I will link those to this ticket and close this one as a won't do.

**Comment by gabydisarli** [comment]
> @AnnaGingle and I discussed this morning and agreed we should break up this ticket into smaller chunks with more defined AC. I will link those to this ticket and close this one as a won't do.

Three new tickets have been made:

1. [Design: Hi-fidelity Members page and managing members #2436](https://github.com/cisagov/manage.get.gov/issues/2436)
2. [Design: Hi-fidelity prototype of inviting a new member #2437](https://github.com/cisagov/manage.get.gov/issues/2437)
3. [Design: Hi-fidelity prototype Org admin invites another org admin #2438](https://github.com/cisagov/manage.get.gov/issues/2438)

I will pull #2436 into this sprint and will be closing this ticket as a won't do (since the work is being tracked elsewhere).

cc: @vickyszuchin @AnnaGingle
