### ISSUE TITLE
Design: Hi-Fidelity mockups of the Organization and Senior official pages for Org admins

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2242]
### Issue description

Create hi-fidelity wireframes of the Organization and Senior official pages for Org admins. These pages are a place for Org admins to view high level information about their organization. They can't edit their federal agency, but can edit their organization mailing address. They can only view their senior official information and can't edit it. 

**Note**: we haven't really nailed down how Org admins view suborganizations under their organization from the Organization page. Depending on what we decide that work may need to be tracked in a follow on ticket.

### Acceptance criteria

**Create hi-fi mockups for**
- [x] Senior official page
- [x] Organization page

**Create prototype for**
- [x] Viewing organization page and making an update to org mailing address

**Team review**
- [x] share for product/po/design approval

**Handoff to development**
- [x] Discuss with @abroddrick on strategy for creating dev tickets
- [ ] Mark Figma pages as dev ready
- [ ] Create dev tickets and make sure google content docs are included in all tickets

### Additional context

**🚨Kickoff required🚨**
At the start of a development block for an org model feature, design & dev will have a kickoff to discuss designs and incorporate any dev feedback prior to implementation

### Links to other issues

:countOrganization model epic: https://github.com/cisagov/manage.get.gov/issues/1772
🔄 Related: https://github.com/cisagov/manage.get.gov/issues/2063 (lo-fi wires)

**Comment by vickyszuchin** [comment]
Per guideline, all "In review" tickets from Sprint 47 will moved forward at noon EST on Day 4 of new sprint (Sprint 48).

**Comment by gabydisarli** [comment]
closing as dev tickets are created and designs are approved
