### ISSUE TITLE
Fix reset db job

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2249]
### Issue description

Our reset db job on github is broken and often results in errors if you run it. We need to fix this so we can reliable reset the db. Some issues that have happened are 1. reset doesn't work at all  and 2. reset works but migrations aren't deleted and it then can't run migrations and fill the db.

### Acceptance criteria

- [ ] either get the current github job working or make a new command that we can run to reset the db in non production environments (such as one that manually calls drop tables and clears migrations (the table django_migrations)

**Comment by vickyszuchin** [comment]
Per sprint planning meeting, this ticket need to move into sprint 49 from sprint 48.

**Comment by vickyszuchin** [comment]
Per guideline, all "In review" tickets from Sprint 49 will moved forward at noon EST on Day 4 to current sprint (Sprint 50).
