### ISSUE TITLE
Create a Github action to add Katherine to design review issues/tickets

### ISSUE THREAD

**Issue by katypies** [cisagov/manage.get.gov#2263]
### Issue description

@Katherine-Osos  helps manage the workloads and flows for design reviews on PRs. The current documented workflow requires a dev to add both a tag to issues needing design review, as well as adding Katherine on the issue. Instead, let's add Katherine as a watcher on any ticket where the review label/tag is added, so there's only one step required for devs to move something into design review.

### Acceptance criteria

- [ ] When the label `design-review` is added to an issue, automatically add @Katherine-Osos on that issue as well.
- [ ] Katherine should not be removed if the `design-review` label is removed 

### Additional context

Sample for a similar Github action that can be adapted: https://github.com/marketplace/actions/issue-label-notifier

**Comment by h-m-f-t** [comment]
Thanks @katypies!!

**Comment by gabydisarli** [comment]
I love this idea!

**Comment by vickyszuchin** [comment]
Per guidance, any "In progress" tickets from sprint 47 will be moved over to Sprint 48 noon EST on Day 1.

**Comment by vickyszuchin** [comment]
Per guideline, all "In review" tickets from Sprint 48 will moved forward at noon EST on Day 4 of new sprint (Sprint 49).
