### ISSUE TITLE
Update existing emails and request FSM diagram to match current architecture

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2294]
### Issue description

We have a domain request FSM diagram already but it's out of date. We should update it with our current FSM logic and email sending logic

### Acceptance criteria

- [ ] domain request state diagram now represents our current system

### Additional context

voted #2 most import thing for us to diagram in eng huddle

**Comment by PaulKuykendall** [comment]
Decided to give this to the new engineer as part of onboarding

**Comment by abroddrick** [comment]
Moved to next sprint since we didn't have Matt start on this yet and he is still onboarding

**Comment by Matt-Spence** [comment]
New version in Miro.

**Comment by vickyszuchin** [comment]
Per guideline, all "In review" tickets from Sprint 49 will moved forward at noon EST on Day 4 to current sprint (Sprint 50).
