### ISSUE TITLE
Audit and organize the "content" folder on Google drive

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#2306]
### Issue description

The "[content](https://drive.google.com/drive/folders/19zSImNKhW_GjNw5CLdNxSoFAGnLciMQo)" folder has gotten a little disorganized, which makes it difficult to find documents (especially for new team members). The purpose of this ticket is to audit what's in that folder and come up with a new structure.

This will be a continuation of the work done to organize the "[research](https://drive.google.com/drive/folders/1yEbS8EjjbUUeSU_470ijrWkf3tHaEqB_)" folder.

### Acceptance criteria

- [ ] Audit the "[content](https://drive.google.com/drive/folders/19zSImNKhW_GjNw5CLdNxSoFAGnLciMQo)" folder on Google drive
- [ ] Determine a new structure for organizing the files/folders
- [ ] Create an overview page (table of contents) to help guide people to the most useful documents
- [ ] Establish a new naming structure for files
- [ ] Katherine provide ideas for standardizing other folders and assets.

**Comment by vickyszuchin** [comment]
Per guidance, in-progress tickets will be moved at noon EST on Day 1 (Wednesday) to the new sprint.
