### ISSUE TITLE
Attempt the steps in "Developing on a CISA laptop" and improve the document

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2321]
### Issue description

A new federal .gov team member should be able to use their government-furnished equipment (GFE) for development (and similar) work. We have outlined the broad steps for setup in "[Developing on a CISA laptop](https://docs.google.com/document/d/1ZyaaTWOEgVEHiHarNuv97CnYfUFe-4pfbuQm4ocLkn4/edit#heading=h.nffo9qwynuw6)". 

We would like some new .gov staff to review and step through the instructions to make sure that they are accurate, and then make suggestions to improve the document.

### Acceptance criteria

- [x] Review "Developing on a CISA laptop" document
- [x] Execute setting up a GFE laptop instructions as defined in the document
- [x] Compile list of suggested document updates for dev team's review 

### Links to other issues

Related to:
- [ ] #2159

**Comment by h-m-f-t** [comment]
I know several parts of this are still in flight, but I think we have what we want for this ticket and should move to the next step, #2325.
