### ISSUE TITLE
Conduct feature review for User profile feature

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2327]
### Issue description

To make sure the Profile user feature is ready for deployment to our users, we should conduct a final walk-through of the feature with product, design and dev representation.

This is our first feature review. We can decide if we need a feature review checklist or plan for the project.

### Acceptance criteria

- [x] Schedule feature review meeting for user profile
- [x] Decide if feature is ready for release (Go/No go) 
- [x] Make tickets for any areas found that need improvement
- [ ] If we decide a feature review checklist or plan is needed for the project, create ticket

### Additional context

[User profile test scenarios](https://docs.google.com/document/d/1uzZy6a7u4uc9lLtfHfYpWQmGpmNFE_z7mE2GIDqhveY/edit#heading=h.fcfp9vo7aewg)

### Links to other issues

review after 
- #2157 
- #2320 
- #2358

**Comment by vickyszuchin** [comment]
Per guideline, all "In progress" tickets from Sprint 48 will moved forward at noon EST on Day 1 of new sprint (Sprint 4).

**Comment by katypies** [comment]
I am marking this ticket as complete - we determined that the feature is not ready, and new issues were created to address the bugs and UX changes needed:

* #2420 
* #2421 
* #2422
