### ISSUE TITLE
Show Portfolio on domain request and Domain info for superusers

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2336]
### Issue description

When we added the portfolio table we didn't add Portfolio to domain info or domain request, which keeps portfolio as not usable for our purposes. In order to actually make a portfolio have domain info and domain request 

### Acceptance criteria

- [ ] On domain request and Domain info in django admin, show portfolio at the top. This should allow users to select an existing portfolio
- [ ] only visible for superusers
- [ ] portfolio should now be linkable to mulitple domain infos and requests with no issue

### Links to other issues

broken from #2248

**Comment by vickyszuchin** [comment]
Moved it into Planned since this is split from a sprint 47 ticket.
