### ISSUE TITLE
Add edit icons to Domain Overview page

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2353]
### Issue description

Currently, we have "edit" links on the Domain Overview page. We should add the pencil / "edit" icon next to those links to streamline them with other links (like the cog for "Manage", and the eye for "View").

This will apply to all users (whether part of an Organization or not). 

### Acceptance criteria

- [ ] Add pencil "edit" icons to Domain Overview page  [see figma](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=4788-13705&t=9lLcDLKLOVzRRpWY-11)

No unit tests needed

**Comment by katypies** [comment]
I removed the requirement that this be based on a Figma mockup - I did not see this in an existing mockup but it's a small enough change that there's no need to wait on that in order to implement it. It may mean that the Figma needs to be updated, though, once implemented.

**Comment by Katherine-MN** [comment]
Removed "skipped design" to reflect that design documentation has already been updated to reflect these changes.
