### ISSUE TITLE
Update User Profile page to link to documentation

### ISSUE THREAD

**Issue by katypies** [cisagov/manage.get.gov#2360]
### Issue description

In https://github.com/cisagov/get.gov/issues/305, we're adding help content for updating contact information. The page/content from that issue should be linked from the User Profile page so people can access the help content when they're confronted with the information they want to change.

### Acceptance criteria

- [ ] Link added to User Profile page pointing to the get.gov content page from https://github.com/cisagov/get.gov/issues/305
- [ ] Confirm link location with Design

### Links to other issues

- ⛔  Blocked by https://github.com/cisagov/get.gov/issues/305

**Comment by katypies** [comment]
@gabydisarli - if you have a preference for where the link goes on this, please let us know here!

**Comment by gabydisarli** [comment]
@katypies I think that will depend on the content that's created. I imagine it will go somewhere in the first paragraph, so there might need to be some small content tweaks to the user profile pages that we should account for.

**Comment by vickyszuchin** [comment]
Per @abroddrick in refinement meeting (7/15), this ticket should be moved out to sprint 50. We are still awaiting completion of user profile tickets that is slotted in sprint 49. cc: @katypies

**Comment by abroddrick** [comment]
This shouldn't block  #2408 this was always meant to be done after, as the content shouldn't even show on get.gov until the flag is on and this one is blocked by the content. We should have the flag on first. Removing the "blocks language"
