### ISSUE TITLE
Portfolio-Organization Page

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2377]
### Issue description

As an org member
I want to be able to see my organization name and mailing address
so I can verify it is correct. 

Note, we will turn this non-editable based on permissions in a later ticket, so that only someone with org administrator permissions can edit this (and the view changes accordingly). This is not needed in the current ticket.

### Acceptance criteria

- [ ] the portfolio name is clickable link that takes you to [the organization page](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?t=62Sjs4ioPRj7Ef2G-0) which matches the figma
- [ ] the side navigation is added
- [ ] senior official nav link does nothing
- [ ] If possibly try to re-use the organization template that we already have or modify so that they can both stay in sync when minor changes are made (so we don't maintain two nearly identical views). 

### Links to other issues

- ⛔ blocked by #2349 
- 🚫 blocks #2378

**Comment by vickyszuchin** [comment]
Moved out to sprint 50.
