### ISSUE TITLE
Remove withdrawal functionality on Rejected requests and edit content

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2389]
### Issue description

Currently the image shown below is what shows for a rejected email. The user is provided with language regarding next steps and what to do if they want to make a change as well as an ability to withdraw this request. In actuality, withdraw is not allowed and if they try to withdraw it they will get a 500 error. The content here is also misleading. 

![image](https://github.com/cisagov/manage.get.gov/assets/109625347/e2e16a02-e91e-4d5b-aacb-a784daed72c8)

### Acceptance criteria

- [ ] For rejected requests don't show the Next steps and Need to make changes sections, including the "withdraw request" button

### Links to other issues

Related to: 
- #2401

**Comment by Katherine-MN** [comment]
Removed "skipped design" to reflect that an update to design documentation or libraries is not needed.
