### ISSUE TITLE
Design review: Analyst Portfolio view

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2402]
### Issue description

As the analyst view for the portfolio is all set in django admin, we just had mockups of what the admin view may look like and then attempted to follow it. All tickets for making this portfolio view have also not gone through design review. Thus, we need design to review this feature when it is ready in getgov-development and to suggest any changes desired. If no changes at all are desired at the moment, we would consider this feature complete for now.

Note the django admin tables to look at should be:

- Portfolio
- User Portfolio Permissions
- suborganization
- federal agency
- User
- Domain
- domain info  
- domain request 
note for the last 3 we haven't changed more than adding in portfolio and suborg. I expect we should hide more fields for org model domains/requests than are shown currently.

### Acceptance criteria

- [ ] Design reviews the django tables listed above.
- [ ] Document any changes needed or new additions in a document, including with screenshots so it is easy to follow
- [ ] Discuss changes with dev and determine which are small enough to be done as part of this ticket
- [ ] Work with dev to create new tickets for larger changes

### Additional context

Working with dev: Dev effort on this shouldn't be more than a "2" (2 full work days).
- Dev is responsible for answering questions from design, making minor changes (such as those that we would normally make on a PR).
- Anything that would take more than 4 hours to complete alone should be it's own ticket.
- If the amount of changes desired would result in the dev spending more than a full day on it, make a dev ticket for items where reasonable (communicate with Alysia).

NOTE: This design review does not include testing permissions and/or sending emails. That will be tested separately once that work is implemented.

### Links to other issues

- blocked by #2480 
- blocked by #2590 
- blocked by #2518
- blocked by #2660 
- blocked by #2521

**Comment by abroddrick** [comment]
may be done in sprint 51 or 50. CC: @Katherine-Osos on this

**Comment by katypies** [comment]
@abroddrick to identify which issues block this review

**Comment by katypies** [comment]
Leaving refinement on here, in case our experience with the m1 and m2 reviews indicates a need to update this.

**Comment by abroddrick** [comment]
Moving to 54 given I just added a quick fix to it, though this could be brought into 53, if the quick fix is dealt with quickly. CC: @Katherine-Osos and @witha-c

**Comment by vickyszuchin** [comment]
No adjustments needed on design review ticket template based on first design review ticket.

**Comment by abroddrick** [comment]
@Katherine-Osos, Zander is your ~victim~ volunteer for this one
