### ISSUE TITLE
DNS Hosting: Discovery user research planning

### ISSUE THREAD

**Issue by witha-c** [cisagov/manage.get.gov#2403]
### Issue description

Prep user research to help answer questions we still have after finalizing the DNS hosting goals document. 

### Acceptance criteria

- [x] Prep research plan that identifies our research questions, goals and assumptions
- [x] Identify 5-8 users

### Links to other issues
- 🔄 https://github.com/cisagov/manage.get.gov/issues/2189 
- #2612

**Comment by vickyszuchin** [comment]
Moving this ticket to sprint 52.

**Comment by vickyszuchin** [comment]
Moving this ticket to newly started sprint 53.
