### ISSUE TITLE
Org Model: Usability testing plan

### ISSUE THREAD

**Issue by witha-c** [cisagov/manage.get.gov#2404]
### Issue description

Prep research to help answer questions we have about org model designs and to test overall usability. 

### Acceptance criteria

- [x] Prep research plan that identifies our research questions, goals and assumptions
- [x] Identify 5-8 users
- [x] Prepare facilitator guide for tests that are ~60% complete. (When we decide we need to execute research for a particular module or research question, create a new ticket to refine the facilitator guide and prepare for testing) 
- [x] Review with team, including a practice run if necessary

**Comment by AnnaGingle** [comment]
[Beta Release Research Planning (meeting notes)](https://docs.google.com/document/d/1eBHL9FUFyYhC4PXeexQdceCw1wKXa35LYr1jlkUvvjE/edit#heading=h.i215si1vr1it)
WIP [Org model usability testing: Research Plan](https://docs.google.com/document/d/19xfeqngX_RYyWX5fvXNS06U2PDRjlsfWndWDPhltawY/edit)
[Launch Miro](https://miro.com/app/board/uXjVKnK9iq8=/)
