### ISSUE TITLE
Stable: Turn profile flag on 

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2408]
### Issue description

This ticket is a reminder to turn the feature flag on and should be reserved for the product team to manage when we decide to do this. 

### Acceptance criteria

- [ ] a team member turns on the portfolio feature flag for all users

### Links to other issues

Blocked by
- #2327 
- #2420 
- #2421 
- #2422 

Blocking:
- #2360

**Comment by vickyszuchin** [comment]
Moved it to "Ready". Has met the DoR.

**Comment by katypies** [comment]
This is ready to go! Thanks all!

cc: @therealslimhsiehdy @rachidatecs
