### ISSUE TITLE
Update error message and label for State / territory dropdown on domain management pages

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2410]
### Issue description

During an audit of our current error and success messages as part of the work for #2201 I've noticed some inconsistencies in our behavior on the Organization name and mailing address page in domain management. 

### Acceptance criteria

- [ ] Add error to state / territory dropdown if none is selected. Message should read: `Select the state, territory, or military post where your organization is located.`
- [ ] Change label to `State, territory, or military post` to match this same dropdown in the request form
- [ ] Change error message to: `Enter a zip code in the form of 12345 or 12345-6789` to match the request form
`

**Comment by PaulKuykendall** [comment]
Refining, just to determine approximate timing.

**Comment by gabydisarli** [comment]
We're closing this as a won't do because we're addressing all these AC as part of #2543 cc: @AnnaGingle
