### ISSUE TITLE
Analytic dashboard: create a CSV report for "Domain request decisions by date"

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2418]
### Issue description

The analysts and program would benefit from a downloadable report of all domain request decisions by date. The report would allow a better way to measure the domain review work analysts are doing.

List and order of columns to export:
- Domain
- Domain type [city...]
- Submission date - reflect the date of initial submission
- Decision [only Approved/Rejected/Ineligible]
- Date of decision
- Analyst

### Acceptance criteria

- [ ]  downloadable CSV report, as described above, is available by clicking an appropriately named button ("Adjudicated Domain requests by date") on the Analytics dashboard
- [ ] user can select a date window

### Additional context

[slack discussion](https://cisa-corp.slack.com/archives/C06VDEWTGSH/p1719430919766209)

**Comment by katypies** [comment]
@h-m-f-t  to refine this further with @amcelya  to determine whether this data could be added to an existing .csv rather than being a new one.

Looks related to #2415 and the details we may want to expose directly in a dashboard instead of an export.

**Comment by h-m-f-t** [comment]
I plan to close this one in favor of a new issue, but leaving it open for now. See [Slack thread](https://cisa-corp.slack.com/archives/C06VDEWTGSH/p1722532099535319?thread_ts=1719430919.766209&cid=C06VDEWTGSH).

**Comment by h-m-f-t** [comment]
Closing in favor of #2541.
