### ISSUE TITLE
Lockdown User profile phone field for analysts

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2439]
### Issue description
The ability to edit a User's profile should be allowed by Super admins only. If an analyst were to delete a user's phone number, our system would put them into a flow to update their profile which might be jarring if they weren't expecting it. We should lock down this field for analysts and make it read-only, like the other fields in the User profile section on /admin

### Acceptance Criteria

- [ ] make phone field read-only for analysts

### Links to other issues

**Comment by vickyszuchin** [comment]
Per Gaby: ticket can be a follow on to user profile MVP. It's not critical, just a good thing to do as a fast follow to prevent any accidental actions.
