### ISSUE TITLE
Member management experience for Org model (Team review)

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2456]
### Issue description

This ticket will track the Team review for the Members management experience (#2436, #2437, #2438)

### Acceptance criteria

- [x] Share with team for PO/Product initial approval
- [x] Set up a **Design/Dev review** meeting with relevant devs to review designs and gather feedback
 ❗ Smaller design updates will be made as part of this review period. Larger updates need to be a separate ticket. Avoid creating dev tickets **before the design/dev review is complete** unless it's determined that pieces of the work can be started before design has **been finalized.**
- [ ] Make any small updates needed as part of the team review period
- [ ] (optional) Reshare with PO/Product if for final approval if needed

### Links to other issues

🔄 #2436 
🔄 #2437 
🔄 #2438

**Comment by vickyszuchin** [comment]
This was reviewed in the sprint planning meeting.

**Comment by AnnaGingle** [comment]
Meeting scheduled for Sep 5th.

**Comment by gabydisarli** [comment]
New tickets created

</body></html>[Update the Domain Management Overview page](https://github.com/cisagov/manage.get.gov/issues/2730)	https://github.com/cisagov/manage.get.gov/issues/2730
["Add a domain manager" page updates](https://github.com/cisagov/manage.get.gov/issues/2729)	https://github.com/cisagov/manage.get.gov/issues/2729
[Member Management Page (part 1)](https://github.com/cisagov/manage.get.gov/issues/2725)	https://github.com/cisagov/manage.get.gov/issues/2725
[Org model domain Managers page updates](https://github.com/cisagov/manage.get.gov/issues/2728)	https://github.com/cisagov/manage.get.gov/issues/2728
