### ISSUE TITLE
Research: feasibility of integration of Leadership Connect

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2466]
### Issue description

Reviewing domain requests is a core work that underpins the .gov registry program. Analysts review and assess domain requests critically to ensure their legitimacy. Leadership Connect is a tool that analysts use on a regular basis to verify request information (e.g. Senior Official), and LC an [API](https://leadershipdir.atlassian.net/wiki/spaces/LCDOC/overview). 

This issue is _not_ about integrating with LC. We should simply explore the viability of automating some of the manual work analysts do now. We can test this locally and on sandbox without touching other code. Doing it on the command-line to test is fine, using something like cURL. No code/branch is needed.

### Acceptance criteria 
- [x] Use the API key in the [Google Doc](https://docs.google.com/document/d/1W_vQ0tVNoqw6Ebm9zo-KAmRB8T4sI6HBuYF_hMfstoI/edit?usp=sharing) for this issue.
- [x] Using the organizations named in the Google Doc, investigate whether Leadership Connect's API can be used to answer the following questions: 
  - [x] Is it possible to search for a given person's name (like a submitter or SO) and return whether a match is found in a given organization (and if so, return the org's name, the person's title, and their email address)? 
  - [x] Is it possible to search for a given website and get info about the relevant organization?
  - [x] Can we filter by [job focus](https://leadershipdir.atlassian.net/wiki/spaces/LCDOC/pages/25952262/API+Reference#5.2.1.-Filters%2FConditions) to get useful results?
  - [x] What is returned from these calls and how does it map to our values? 
- [x] Verify that API is callable from a Sandbox
- [x] Verify that API is callable from a local machine
- [x] In the Google Doc, document and summarize your research. List API calls and responses, including notes on useful findings and good callouts for mapping to our data. 

### Additional context

* Use [this Google Doc](https://docs.google.com/document/d/1W_vQ0tVNoqw6Ebm9zo-KAmRB8T4sI6HBuYF_hMfstoI/edit?usp=sharing) to support this research.
* If you have a cisa.dhs.gov email address, you can sign in to the [web version of LC](https://app.leadershipconnect.io/login), which might be helpful to understand the service. 
* [Slack thread](https://cisa-corp.slack.com/archives/C0792FS2KT6/p1718985137540489)
* Max of two days should be spent on this

**Comment by h-m-f-t** [comment]
Thanks @zandercymatics! I'm good to see this issue closed.

**Comment by vickyszuchin** [comment]
Marking this ticket as "Done" based on Cameron's comment. @abroddrick
