### ISSUE TITLE
Research: Actions to limit access to registrar (operations)

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2496]
### Issue description

**Problem**: In the event of a maintenance procedure or an unscheduled incident, it may become necessary to limit users' access to features and functions in the registrar.

There are potential scenarios

1. The site is completely down, and users are experiencing an error when trying to access any area of manage.get.gov.
2. The database is unavailable, and users receive errors when trying to save their work on any page.
3. The interface to the registry is unavailable and cannot process updates to registry specific data.
4. The database is available, but vulnerable or damaged, and operations wishes to protect its state from any changes for a period of time.

Investigate and prioritize solution(s) to these potential problem scenarios. Potential options are:

a. Activate a safe landing page for manage.get.gov indicating that the registrar is temporarily unavailable.
b. Allow access to the registrar in Read-only mode. No changes allowed. Indicate that the system is temporarily unable to process updates. All information would look normal to user, but no updates to any data are allowed. No new requests, no changes to any domain or domain request data
c. Allow only changes to **registrar** data, not affecting registry. (if Registry is down)
d. Allow only changes to **registry** data, like DNS entry and security email updates. (if Registrar database is down)

Things to consider:
- should we queue domain requests or suspend them? (This assumes a place to store the queued requests)
- how should we inform users of the degraded state of the application?
- what activities should we limit? No application changes, no withdrawals, no DNS changes, etc., in each scenario?

### Acceptance criteria

- [x] research what should be suspended when system encounters any issue
- [x] determine how we should recover from the suspended state
- [x] update procedural/compliance documentation as necessary. (w/Trevor) [Passed information to Trevor]
- [x] create design and dev tickets, as needed (coordinate with dev in creation of any dev tickets)

### Additional context

Consider the recent incident where a column in the database was inadvertently deleted. The team would like to have the ability to suspend all activity on the database temporarily so that a recent snapshot could be restored, and then synced to the last known good state.

Context from [Slack](https://cisa-corp.slack.com/archives/C05TS76RVS6/p1722458030577529?thread_ts=1722454537.235249&cid=C05TS76RVS6):
So, I will say when we talked about this, the main thing we would need to stop is anything that would put our db out of sync: Any request change (analysts and user facing), changes to SO & orgs on domains. Nameservers/dnssec and security emails can be left operational.

Suspending the action would be done via a flag in django admin, just like the profile feature and should be linked to a banner (we already have a ticket for a banner that could be used).

The registrar wouldn’t actually be unavailable, this would be a case when we want everything to stop because we are about to do a db change (due to an incident). We would essentially want a “down for maintenance” scenario to show for any users on the system. This would not apply to the registry going down. It also wouldn’t really apply to a massive bug causing 500s on every page (which would be a real “down” situation)

[Discovery Document](https://docs.google.com/document/d/16OIisw829WWCdgmZFtdLCfJPHcdcYcOV21A2_I88WSc/edit)
### Links to other issues

Related to:
* #2494 (Banner on get.gov)

**Comment by PaulKuykendall** [comment]
@PaulKuykendall - rewrite

**Comment by PaulKuykendall** [comment]
@PaulKuykendall - break this ticket down and develop the plan and sequencing. Involve @trevorbryant-cisa.

**Comment by PaulKuykendall** [comment]
I work thru the scenarios with Trevor, and settled on the Five Scenarios listed and the Four responses to them (ACTION A thru D).
