### ISSUE TITLE
Organization Details view only page

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2505]
### Issue description

We have and editable Organization name and mailing address page, per #2377; however only admins should see the org details as editable and instead everyone else should see it as view only.

### Acceptance criteria

- [ ] For users who can only see org details (everyone who is not admin) the org details page is read only and [matches this figma](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?node-id=6297-2218&t=KBnOSDLGrg0JFIGY-0)
- [ ] Only admins can edit the fields (federal agency is still non editable for anyone per the previous ticket)
- [ ] Use a header and paragraph markup for the read only items

### Links to other issues

- blocked by #2377

**Comment by vickyszuchin** [comment]
Added into sprint 50.
