### ISSUE TITLE
Conduct usability testing for Member management

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2511]
### Issue description

Conduct usability testing for member management feature in Org model.

### Acceptance criteria

- [x] meet with 3–5 users for one hour from two different federal agencies

### Links to other issues

https://github.com/cisagov/manage.get.gov/issues/2512
https://github.com/cisagov/manage.get.gov/issues/2513
https://github.com/cisagov/manage.get.gov/issues/2514

**Comment by gabydisarli** [comment]
1st session held Aug 1st

**Comment by AnnaGingle** [comment]
📁 Member management folder
- [Research plan](https://docs.google.com/document/d/1DV8RUvh8fVNEohdM1fOc8u7cRE5p0h6qzpkMQ7-bBSM/edit#heading=h.r0nipxp2ed3e)
- [Interview script](https://docs.google.com/document/d/1WNXS_9vosiVpLQ5Mx6JtLXpFgjar6B_brJx4Bly485k/edit#heading=h.r0nipxp2ed3e)
- [Research report ](https://docs.google.com/document/d/1XhWsIGmLiDgJQIb-v_BMk-Gg7ZUjDp3NbBc_jKQouoc/edit) to be completed in #2514

**Comment by gabydisarli** [comment]
second session held Aug 8th. We've only talked to one agency so far. See Anna's[ update in Slack](https://cisa-corp.slack.com/archives/C07589TAY57/p1723146442407199) for more information.

**Comment by AnnaGingle** [comment]
Last-day users can schedule an interview is tomorrow, August 23rd.
