### ISSUE TITLE
Add portfolio member section to Django admin Portfolio view

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2521]
### Issue description

As an analyst or superuser, I want to be able to look at the portfolio view and quickly know the human readable roles that members of the are assigned to. Permissions aren't easy to read so I want a quick way to see generally what they can do: Are they just a member, are they admin, readonly admin, a domain manager, can they make requests?

On django admin, we need to add the "Portfolio member" section to the Portfolio table and correctly show all users with their "role"/ human readable summary of their permissions (but not list the permissions themselves)

Note: We haven't solidified the member roles that will show to users, so consider this a first pass that will will update when member roles/permissions becomes more solidified. 

### Acceptance criteria

- [x] The portfolio view on django admin now has a Portfolio Member section that matches the [miro mockup](https://miro.com/app/board/uXjVKAEDJB4=/?moveToWidget=3458764593077028007&cot=14) 
- [ ] the rightmost column under show details shows any of the following View-only admin, Member, Domain manager, Domain requestor. If there is more than one of these that fits the users level of permissions& roles, show them as a comma separated list.  
- [x] Admins are not shown in the show details section and are shown in a way that matches the mockup
- [ ] If they have more permissions than just a normal member (such as they are a domain manager or can make/view requests) do not show the word "member" as that will be implied.

### Additional context
Note: that "view-only admin" is the newest name for read-only admin. as it ma
suggestion: User the @property field to add a field to the User table that provides their "portfolio_role_summary" which would be the list strings displayed in the second AC

bonus points if it is easy to have the permission/role labels stacked instead of as a comma separated list (not an AC though)
### Links to other issues

- blocked by #2520 
- blocks #2402

**Comment by PaulKuykendall** [comment]
@abroddrick - I added a bookmark link to where we believe this is referring to in the Miro. Please confirm. Thanks!

**Comment by abroddrick** [comment]
@PaulKuykendall now there are two links... I will delete the one that just says link, not sure which one you added.

**Comment by abroddrick** [comment]
this one was removed: [link](https://miro.com/app/board/uXjVKAEDJB4=/?openComment=3458764596004370313)
