### ISSUE TITLE
Show current name servers and domain managers on the Domain page in /admin

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#2524]
### Issue description

_As an analyst
I want to go to one place in /admin to see details about registered domains
So I can provide better, faster support_

A team member should be able to navigate to a specific domain and easily see information about the domain and its status.

### Acceptance criteria

For /admin > Domains > $domain (ie, once a specific domain has been selected), additional information should be visible:

- [ ] The current name server addresses (NS and any associated IPs)
- [ ] Whether DNSSEC is enabled (e.g., has ≥1 DS record; don't need to see the DS records)
- [ ] For existing domain managers,  have a table that shows their the user index (UID), and make it clickable to go to that User's page, the other fields in this table should be their name and email address
- [ ] Below the domain mangers table show a table for invited domain managers, containing the email address and status. Note this will just be invited for now but we plan to add in a "canceled" status which may be useful to see when receiving help desk questions. 

Some information should be removed from this page, since it's not usually relevant to a domain that's been approved, only in the request context:

- [ ] Remove the "Domain" line with the editable field (the domain is shown in bold a bit higher, and the domain name should *not* be editable.
- [ ] Remove "Creator" information from this view since this is visible in the Request and Domain information and is more applicable there
- [ ] Remove "Other Employees" and "No Other Contacts Rationale" from this page. Should still be viewable on requests and domain information.

### Additional context

A quick [Miro](https://miro.com/app/board/uXjVKnt-qfs=/) with a mockup of the changes -- formatting should match components we already use.
**Ignore** the note in the above miro about moving the line for the domain information title up.

[Refinement discussion in Slack](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1724426477455869)

**Comment by PaulKuykendall** [comment]
@katypies - will create a rough mockup with devtools.

**Comment by vickyszuchin** [comment]
Per discussion in product huddle, the product team will do discovery. From discovery, this ticket's scope and ACs will be updated. The ticket will then be re-label as a dev ticket for implementation in next sprint (tentatively targeted for sprint 52).

**Comment by PaulKuykendall** [comment]
Per product huddle 8/19, Kaitlin will hand markup these changes.

**Comment by katypies** [comment]
I've added a Miro mockup for this and tweaked the A/Cs accordingly. Switching this to dev and slotting at the bottom of next sprint!

cc: @abroddrick @PaulKuykendall @h-m-f-t

**Comment by vickyszuchin** [comment]
This ticket is unique. The ticket was in sprint 51 for product to work the ACs. Once that was completed. Then it was slotted for sprint 52 for the dev team to work. We missed a step for Alysia (dev) to review the ACs.  The "refinement" label originally was for product to refine the ACs. Added the "refinement" label on it now for @abroddrick and assigned developer to review the ACs and confirm the story point.

**Comment by katypies** [comment]
Added a link to the Slack thread. @abroddrick  is going to update A/Cs in accordance with that refinement discussion, and then this should be ready!

**Comment by abroddrick** [comment]
@dave-kennedy-ecs I updated this ticket with the gist of what was in the slack thread and removed refinement. I was debating on this being a 2 vs a 3, but went with three in case something else comes up as well on this.

**Comment by vickyszuchin** [comment]
Moved the status to "Ready" since refinement has been addressed.

**Comment by vickyszuchin** [comment]
Moving this to sprint 54.
