### ISSUE TITLE
Craete a new on/offboarding template for access to systems

### ISSUE THREAD

**Issue by kristinacyin** [cisagov/manage.get.gov#2532]
### Issue description

We've had a few teammates join/leave and this could be a little better organized. 

### Acceptance criteria
- [x] Create a new template for on/offboarding
- [x] Plan to share it with the team for review
- [ ] Create a new issue to update current on/offboarding docs and conduct a review

### Links to other issues

- #2530

**Comment by vickyszuchin** [comment]
Moving this ticket out to sprint 54 to give Product team some extra bandwidth for org model launch planning. It can be added back in if Product team has bandwidth.

**Comment by vickyszuchin** [comment]
Moving this ticket from sprint 54 to sprint 55.

**Comment by h-m-f-t** [comment]
@katypies I've updated this issue to reflect the work done. Can you add a link to the template you worked up and cite this in a new issue? I'm going to close this now.
