### ISSUE TITLE
Add additional dates to "all domain request metadata"

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#2541]
### Issue description

We're currently using "submitted date" to mean the last (or latest) time a request entered a submitted state, as there can be submission rounds. Let's add a few fields to domain requests and then update the CSV.

### Acceptance criteria

- [x] Create 3 new fields in the Domain request object
  - [x] "First submitted date" - the _first_ time the request entered `Submitted` (call it first_submitted_date in the code). Note you need to have this be set in the submit() function in domain_request
  - [x] "Last submitted date" – the latest time the request entered `Submitted` (this is really a rename of "submission_date" to be called last_submission_date). Check that the migration file says "rename" NOT altered field
  - [x] "Latest status update" – the date _an analyst or admin_ last updated the Status. (Note on save you can check for status change on the request and update this field)
- [x] Add these fields to the "all domain request metadata" CSV (see additional context below)
- [x] Show these dates on the Domain Requests table (next to current "Submitted" date field)

*Migrate data*
- [x] Prepare a migration script to fill first_submitted_date and latest status update
- [x] ensure the migration script has instructions on how to run it in the data_migration.md
- [x] make a ticket for running this script on staging and another for stable. 

### Additional context
if you don't check that the migration says `rename` from `submission_date` to `last_submission_date` you will delete every submission date in our database. It NEEDS to say `rename`. 

Note, for the migration script, you can use audit logs to get the status you need. 

* The new order of the first few fields in the Domain request csvCSV should be
  * Domain request, First submitted date, Last submitted date [replaces the current `Submitted date`], Status, Latest status update...
* In situations where an analyst puts a request into Submitted (uncommon), the `Latest status update` will be the same as the `Last submitted date`. That's ok.

Talked about in this [Slack thread](https://cisa-corp.slack.com/archives/C06VDEWTGSH/p1719430919766209).

### Links to other issues

- 🔄 Similar to #2166 
- 🙅 Replaces #2418

**Comment by abroddrick** [comment]
@h-m-f-t only one question on this now that I look at it. Do you want these fields showing on the Domain Request page for individual requests or on the Domain Request table shown to analyst in admin?

**Comment by h-m-f-t** [comment]
@abroddrick Good question! I could go either way on this. For now, let's add all the dates to both the individual request page and on the table inside `Domain requests`.

**Comment by h-m-f-t** [comment]
Added refinement to make sure the A/C's capture that last 2 comments...
