### ISSUE TITLE
Design Review: View and manage organization Details

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2543]
### Issue description

In the org model, all org users should be able see information about their organization. Admins can change their organization, but no one else can. No org user can change the Senior official in these pages. 

Design should review and compare the output for the organization details and compare against the most recent figma and requirements. 

### Acceptance criteria

- [ ] Design reviews the organization details (mailing address and senior official)
- [ ] Document any changes needed or new additions in a document, including with screenshots so it is easy to follow
- [ ] Discuss changes with dev and determine which are small enough to be done as part of this ticket
- [ ] Work with dev to create new tickets for larger changes

### Additional context

**Working with dev:** Dev effort on this shouldn't be more than a "2" (2 full work days).

- Dev is responsible for answering questions from design, making minor changes (such as those that we would normally make on a PR).
- Anything that would take more than 4 hours to complete alone should be it's own ticket.
- If the amount of changes desired would result in the dev spending more than a full day on it, make a dev ticket for items where reasonable (communicate with Alysia).

NOTE: This design review does not include testing permissions and/or sending emails. That will be tested separately once that work is implemented.

### Temporary Slack channel
Discussions for this design review should take place in this Slack channel: [#2543-design-review](https://dhscisa.enterprise.slack.com/archives/C07KZQZBTTJ)

### Links to other issues

- blocked by #2378

**Comment by katypies** [comment]
@abroddrick - quick question! Will the permission levels be ready to review with this? Or should this just be scoped to the page without the permissions piece?

**Comment by abroddrick** [comment]
I was not at all considering User permission management as part of this milestone, as that is a whole other can of worms. So no permissions management and viewing permissions were not be included. So basically, just details specific to the organization itself not Users in the org

**Comment by katypies** [comment]
Re-added `refinement`, because we'll need to revisit the A/Cs and process once we complete the domain management review (#2544 )

**Comment by AnnaGingle** [comment]
Hey @katypies! The domain management review has been going well. We have gotten started on reviewing and Rachid has already addresses some issues.

**Comment by vickyszuchin** [comment]
Dev team effort is 2 story point, per @abroddrick

**Comment by gabydisarli** [comment]
Design has approved PR for 2734 ✅

**Comment by abroddrick** [comment]
Reopening the issue as we don't want it closed before the code is approved by dev and merged to main
