### ISSUE TITLE
Design Review: View and Manage domains

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2544]
### Issue description

Domain management should now be complete, including the domain table, navigation, and both read-only and editable views of the domain management pages. Excluded from this review is anything for organization details, requests, etc.

### Acceptance criteria

- [x] Design reviews the domain management table and pages
- [x] Document any changes needed or new additions in a document, including with screenshots so it is easy to follow
- [x] Discuss changes with dev and determine which are small email to be done as part of this ticket 
- [x] Work with dev to create new tickets for larger changes 

### Additional context

**Working with dev:** Dev effort on this shouldn't be more than a "2" (2 full work days). 
- Dev is responsible for answering questions from design, making minor changes (such as those that we would normally make on a PR).
- Anything that would take more than 4 hours to complete alone should be it's own ticket. 
- If the amount of changes desired would result in the dev spending more than a full day on it, make a dev ticket for items where reasonable (communicate with Alysia).

NOTE: This design review does not include sending/testing email notifications to domain managers. That will be tested separately once that work is implemented.

### Temporary Slack channel
Discussions for this design review should take place in this Slack channel: [#2544-design-review](https://dhscisa.enterprise.slack.com/archives/C07HJTNV066)

### Tickets covered in this design review

- blocked by #2493 
- blocked by #2460 
- blocked by #2348 
- blocked by #2354 
- blocked by #2352

**Comment by AnnaGingle** [comment]
Looking at this now

**Comment by AnnaGingle** [comment]
I thought this was a PR review. Nevermind!

**Comment by abroddrick** [comment]
Totally get you!  I didn't realize it was notifying every for the "design-review tag" on tickets and not just katherine

**Comment by abroddrick** [comment]
@Katherine-Osos and @witha-c do you want this one to include email sending when dns info is changed? That seems like a separate beast and I was not including it in this initial scope; however, if it's easier for design to tackle both at once I can add that to the blocked list and push this out a couple sprints. Thoughts here? (putting refinement tag to note the question and moving this to next sprint just to emphasize that the currently scoped tickets will all be ready for review by next sprint)

**Comment by Katherine-Osos** [comment]
@abroddrick I don't think email sending has to be part of this review.

**Comment by abroddrick** [comment]
Perfect! Removing refinement then! I will leave it in for next sprint, but obviously up to you two on if you want design to do it now or later

**Comment by abroddrick** [comment]
No it was not, but is a good one for us to tackle!

**Comment by abroddrick** [comment]
Noting on here that the dev effort on this shouldn't be more than a 2 of time (2 full work days). Dev is responsible for answering questions from design, making minor changes (such as those that we would normally make on a PR), anything that would take more than 4 hours to complete alone should be it's own ticket. If the amount of changes desired would result in the dev spending more than a full day on it, make a dev ticket for items where reasonable (communicate with Alysia).

**Comment by abroddrick** [comment]
@AnnaGingle and @gabydisarli, @rachidatecs will be your victim- I mean- point of contact from engineering.

**Comment by AnnaGingle** [comment]
Accessibility checks

- [ ] Domains (home)
- [ ] Domain overview (view-only)
- [ ] Domain overview (edit)
- [ ] DNS
- [ ] Suborg
- [ ] Security Email
- [ ] portfolio page

**Comment by gabydisarli** [comment]
Visual design checks


- [ ] Domains (home)
- [ ] Domain overview
- [ ] DNS / Name servers
- [ ] DNS / DNSSEC
- [ ] DNSSEC / DS data
- [ ] Suborg
- [ ] Security Email


Design is approved!
