### ISSUE TITLE
Update fixtures script to add portfolios an other missing items

### ISSUE THREAD

**Issue by erinysong** [cisagov/manage.get.gov#2564]
### Issue description

Portfolios and organizations are currently not included in our migration seed data, which requires developers to manually make portfolios and organizations to test org model features. Adding portfolios, senior officials, organizations, suborgs to our seed script would reduce the time it takes to manually create them. 

While we are changing fixtures we should go ahead and make sure all info on requests is also filled in. Right now there are some fields that don't get filled in on requests from fixtures and we should remedy that as well. Domain Requests also has new date fields and that should be included in fixtures where possible. 

We are also missing domains in an expired state, as these are difficult to create manually. Thus instead of just creating one domain we should have two domains on that is in the expired state.

Likewise, we also have issues on development and staging where it would be nice to re-run the domain/domain request fixtures to create new fixtures for users. But fixtures fails usually when running again. We should make sure the fixtures won't crash/error out if you re-run it.
### Acceptance criteria

- [x] Update fixtures script to autogenerate portfolios and any dependencies a portfolio object requires (e.g., Senior Official, Organization). This includes filling in suborg/portfolio for suborg domains
- [x] add "senior official" data to all portfolio domain requests and domains infos (should be covered in the AC above but here 
- [x] add "expiration" dates to all approved domains (portfolio and non portfolio)
- [x] add "submission" dates to all domain requests that aren't in "started" status (portfolio and non portfolio)
- [x] update domain_request fixtures to match the current object (we have added fields since this was last touched)
- [x] add a new domain to each user that is in an expired state (aka it needs an expiration date in the past)
- [x] make any other fixture updates deemed beneficial that are found when going through the code, such as for other easy-to-add missing fields. (You do not need to go out of your way to look for these though, just if you see something obvious go ahead and fix that too).
- [x] fixtures can be re-run without crashing (logging errors though is okay)
- [x] on fixtures re-run more domains/domain requests should be made for the fixtures users.
- [x] Fixture data is only made for  fixtures users, even on first runs.

**Comment by vickyszuchin** [comment]
@abroddrick would you review and provide the story point for this ticket?
