### ISSUE TITLE
Figma component audit: manage.get.gov

### ISSUE THREAD

**Issue by AnnaGingle** [cisagov/manage.get.gov#2582]
### Issue description

Audit the figma components and document inconsistencies between the file and what's in manage.get.gov production. A design component is a functional element of a user interface (UI) that is derived from design elements like color, typography, and spacing. Components are the building blocks of a design system and can be individual elements like buttons or icons, or a collection of elements like menus and layouts. 

### Acceptance Criteria

- [x] Audit shared with design team
- [x] Tickets are created for each component that needs to updated or added to the Figma design system
- [x] In this issue, link to new issues that are creating as an outcome of this work.

### Additional Context

The Figma file is out of date and doesn't always match what's in production. This leads to doubled efforts when designers have to make updates to a screen that hasn't been kept up to date in Figma. The Figma should have parity with what's in production so devs and designers know that the Figma is correct and can be trusted.

### Links to other issues

- Plan for design system improvements [#2584](https://github.com/cisagov/manage.get.gov/issues/2584)
- Figma component audit: get.gov [#2585](https://github.com/cisagov/manage.get.gov/issues/2585)
- Plan for Figma design system updates [#2583](https://github.com/cisagov/manage.get.gov/issues/2583)

**Links to files:**
- [Figma Audit](https://docs.google.com/spreadsheets/d/1jWK1VMdK1zqLCbYN0Efp0rGNFMGJP-iKgQefplIUFUw/edit?usp=sharing)
- [Modal](https://github.com/cisagov/manage.get.gov/issues/2675)
- [Radio button and Radio Tile](https://github.com/cisagov/manage.get.gov/issues/2676)
- [Text input - Text area](https://github.com/cisagov/manage.get.gov/issues/2677)
- [Text input - Select](https://github.com/cisagov/manage.get.gov/issues/2678)
- [Status Alert](https://github.com/cisagov/manage.get.gov/issues/2679)
- [Checkbox and Checkbox Tile](https://github.com/cisagov/manage.get.gov/issues/2680)
- [Border style](https://github.com/cisagov/manage.get.gov/issues/2681)
- [Domain Section](https://github.com/cisagov/manage.get.gov/issues/2682)
- [Divider](https://github.com/cisagov/manage.get.gov/issues/2672)
- [Footer](https://github.com/cisagov/manage.get.gov/issues/2673)
- [Some component tickets that got updates](https://github.com/cisagov/manage.get.gov/issues/2585)

**Comment by joet333** [comment]
Created Figma Audit doc, but still need to adjust and create columns etc.

**Comment by joet333** [comment]
Audit file has been shared with team in prior story. Have started auditing these pages against the component in Figma library.

**Comment by joet333** [comment]
@Katherine-Osos should we bring this story into this sprint since I finished the other one already?

**Comment by joet333** [comment]
Registrar setup audit completed. Working on Manage pages next about halfway through and then will start making tickets.

**Comment by joet333** [comment]
Completed Form and Manage Audit. Noted that Org model has some customized components to move. Starting to create issues for components and update anything from get.gov audit. (note that I will be redoing the get.gov because comments because unattached)

**Comment by joet333** [comment]
Stories all created and linked to this story. Noting that audits for manage.get.gov are split between the current file and new "Jyoti branch" file. Also note that org model was not audited since it is currently being worked on. Closing this story.
