### ISSUE TITLE
Plan for design system improvement

### ISSUE THREAD

**Issue by AnnaGingle** [cisagov/manage.get.gov#2584]
### Issue description
Our Figma design library has not been kept up to date and as a result slows designers and engineers down. 
### Acceptance criteria
- [x] Create and share a plan with the design team
- [x] Create new tickets 
### Additional context
We are looking to make our design system more robust including parity with what is in production. We want to be more organized, so that navigating our designs is easy for anyone. Our file size is huge, and wonky things happen as a result. Lastly, we need to establish processes for updating, and maintaining ours design and design system.
### Links to other issues

- Figma component audit: manage.get.gov [#2582](https://github.com/cisagov/manage.get.gov/issues/2582)
- Figma component audit: get.gov [#2585](https://github.com/cisagov/manage.get.gov/issues/2585)
- Plan for Figma design system updates [#2583](https://github.com/cisagov/manage.get.gov/issues/2583)

**Links to files:**

- [Figma Audit](https://docs.google.com/spreadsheets/d/1jWK1VMdK1zqLCbYN0Efp0rGNFMGJP-iKgQefplIUFUw/edit?usp=sharing)
- [High Level Overview ](https://docs.google.com/presentation/d/1Jzxv1Eq2jjCN6G4o2dF4PziShQai8oAq/edit#slide=id.p14)
- Plan for design team (after audit) -- not started

**Comment by joet333** [comment]
Starting to work on general roadmap/overview (WIP) and creating doc for audit (WIP). 
Adding links to both in the story itself.

**Comment by joet333** [comment]
Sharing out plan tomorrow and new issues with first steps created.

**Comment by joet333** [comment]
Meeting to share this at 2pm today, but will mark complete now for sprint closing (doesnt need to rollover)
