### ISSUE TITLE
Figma component audit: get.gov

### ISSUE THREAD

**Issue by AnnaGingle** [cisagov/manage.get.gov#2585]
### Issue description
Audit the figma components and document inconsistencies between the file and what's in get.gov production.

### Acceptance Criteria
- [x] Audit shared with design team
- [x] Tickets are created for each component that needs to updated or added to the Figma design system. If appropriate update tickets from the manage.get.gov audit.
- [x] In this issue, link to new issues that are creating as an outcome of this work.

### Additional Context
The Figma file is out of date and doesn't always match what's in production. This leads to doubled efforts when designers have to make updates to a screen that hasn't been kept up to date in Figma. The Figma should have parity with what's in production so devs and designers know that the Figma is correct and can be trusted.

### Issue Links
- Figma component audit: manage.get.gov [#2582](https://github.com/cisagov/manage.get.gov/issues/2582)
- Plan for Figma design system updates [#2583](https://github.com/cisagov/manage.get.gov/issues/2583)
- Plan for design system improvements [#2584](https://github.com/cisagov/manage.get.gov/issues/2584)

**Links to files:**

- [Figma Audit](https://docs.google.com/spreadsheets/d/1jWK1VMdK1zqLCbYN0Efp0rGNFMGJP-iKgQefplIUFUw/edit?usp=sharing)
- [Figma file for get.gov base audit](https://www.figma.com/design/qeWM03sfjXgHBHB23rsD6X/get.gov-base-pages?node-id=3972-37221&t=EYLG4WYgLEHq3t5C-1)

- [Alerts](https://github.com/cisagov/manage.get.gov/issues/2628)
- [Banner](https://github.com/cisagov/manage.get.gov/issues/2634)
- [Button ](https://github.com/cisagov/manage.get.gov/issues/2624)(includes button outline, button icon variant, text button/link) 
- [Button Group](https://github.com/cisagov/manage.get.gov/issues/2629)
- [Colors](https://github.com/cisagov/manage.get.gov/issues/2630)
- [Dg/mgmt Sidenav](https://github.com/cisagov/manage.get.gov/issues/2631)
- [get/get-section/D](https://github.com/cisagov/manage.get.gov/issues/2633)
- [Header (includes get/Header) ](https://github.com/cisagov/manage.get.gov/issues/2635)
- [Icon](https://github.com/cisagov/manage.get.gov/issues/2636)
- [Icon List](https://github.com/cisagov/manage.get.gov/issues/2637)
- [Link](https://github.com/cisagov/manage.get.gov/issues/2638)
- [NavItems-Styled](https://github.com/cisagov/manage.get.gov/issues/2639)
- [Pagination](https://github.com/cisagov/manage.get.gov/issues/2640)
- [Search](https://github.com/cisagov/manage.get.gov/issues/2641)
- [Site Alert](https://github.com/cisagov/manage.get.gov/issues/2642)
- [Tag](https://github.com/cisagov/manage.get.gov/issues/2643)
- [Text Input](https://github.com/cisagov/manage.get.gov/issues/2646)
- [.gov text image](https://github.com/cisagov/manage.get.gov/issues/2685#issue-2494783678)

**Comment by joet333** [comment]
Created Figma Audit doc, but still need to adjust and create columns etc.

**Comment by joet333** [comment]
Started Audit Friday. Slowly working on filling it out.

**Comment by joet333** [comment]
Completed .gov/home and /gov domain first page. Working on .gov/choosing your .gov domain name. Noting that a bunch of mocks/templates for the sub pages are missing on this .gov/choosingyour.govdomain page

**Comment by joet333** [comment]
get.gov audit has been completed where all the components that have been used in those pages are marked with updates. I am now going to work on a template for creating those issues and figuring out how to best create them all knowing I still might have more things uncovered as I start working on manage.get.gov


https://www.figma.com/design/qeWM03sfjXgHBHB23rsD6X/get.gov-template-pages?node-id=2196-35124&t=hEF2DJgoESX1VrG1-1
^^ new draft for get.gov template pages -- reduced the bulk significantly.

**Comment by joet333** [comment]
Created and added all issues to found from components used in get.gov site. Note that styles besides Color has not been created yet and will be audited in a separate issue. 

While this is done, stories linked might change when auditing Manage and Registrar pages so those stories should not be pointed or prioritized yet.

**Comment by joet333** [comment]
Because my comments from the audit got unattached :(  ... I will need to create another story for reauditing the Mockups of get.gov. I still have the old comments so I think it will go faster. @Katherine-Osos should I go ahead and create that ticket? (not a high priority though)

**Comment by Katherine-Osos** [comment]
Let's reuse this existing ticket since it's not "new" work. I'll reopen it.

**Comment by joet333** [comment]
Redid comments located here https://www.figma.com/design/qeWM03sfjXgHBHB23rsD6X/get.gov-base-pages?node-id=3972-37221&t=EYLG4WYgLEHq3t5C-1. Updated one component based on reaudit (.gov text image wrong color) listed above. Closing again now that its completed.
