### ISSUE TITLE
DNS hosting discovery research: Facilitator guide and participant recruiting 

### ISSUE THREAD

**Issue by witha-c** [cisagov/manage.get.gov#2612]
### Issue description

Recruit research participants and finalize facilitator guide. 

### Acceptance criteria

- [x] Invite the 5-8 users identified in #2403 
- [x] Identify additional users, invite in waves
- [x] Update participant tracker 
- [x] Finalize the facilitator guide

### Links to other issues
- 🔄 https://github.com/cisagov/manage.get.gov/issues/2189 
- #2403

**Comment by witha-c** [comment]
Timeline: Send invitations by Sept. 5, bookings/appointments link valid Sept. 6 - 30. Send reminder email Sept. 16. cc @kristinacyin

**Comment by vickyszuchin** [comment]
Moving this to sprint 54.

**Comment by vickyszuchin** [comment]
Any "In progress" tickets from Sprint 55 will be moved to the current sprint at noon EST (10am MT/9am PST)
