### ISSUE TITLE
Customer research panel scoping

### ISSUE THREAD

**Issue by witha-c** [cisagov/manage.get.gov#2613]
### Issue description

The .gov product team would like to chat with customers at least once per sprint. The design team’s researchers can offer their expertise to help set up a process for product to process and share out what they learn. The design team would also like to keep the door open for this panel to include quick usability testing, along the lines of what rapid research offers, but less formalized. 

This ticket is for design to lead the exploration of product’s requirements for this activity and prepare some concepts for how to structure it. 

[Google doc of ideas and more info](https://docs.google.com/document/d/1BnIFK4stwMub2lf4DBvoJd9qkBUQKnVBFRfjAZciNFw/edit) 

### Acceptance criteria

- [x] Design gathers requirements from product
- [x] Design prepares a draft plan for product review

### Links to other issues

Implementation: #2604

**Comment by vickyszuchin** [comment]
Moved all "In progress" sprint 57 tickets to the current sprint (sprint 58), per guidance.
