### ISSUE TITLE
Content: Create emails to send when organization info is updated

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#2620]
### Story

As an org admin 
I want to be notified when organization details are updated
so that I'm aware of the changes.

### Acceptance Criteria

- [x] Create email content for the following scenarios:
  - [x] org admin updates organization name and mailing address
  - [x] org admin updates senior official
- [ ] Create dev ticket for implementation

### Additional Context

- All org admins should be CC'd on the email. 
- Only send email if changes are made directly within the registrar, not in the admin.
- For **non-org model** domains, updates to mailing address & senior official info will be announced via this [email for domain-related updates](https://github.com/cisagov/manage.get.gov/issues/2307). But in **org model**, this info no longer lives at the domain level. Therefore, a separate notification is needed.

**Comment by katypies** [comment]
@Katherine-Osos  to review the order of operations for content and notifications. This may go to Sprint 54 instead of 53 once that's done.

**Comment by Katherine-Osos** [comment]
Content created for this ticket can be found [here](https://docs.google.com/document/d/1BSzoBWGaWSTHm0HGDhlzKnWObDBHh9ExzuBUXAB_3Qo/edit#heading=h.gjdgxs).
