### ISSUE TITLE
Figma Library: Button

### ISSUE THREAD

**Issue by joet333** [cisagov/manage.get.gov#2623]
**Issue description**

**Acceptance criteria**

**Additional context**

**Links to other issues**

**Comment by AnnaGingle** [comment]
The format looks good! Maybe we could change `Links to other issues` to `Links to related issues`.

For the Acceptance criteria section, I think there will be a couple of things are true for all components. For example:
- [ ] A Figma branch is created and reviewed by another designer.
- [ ] Changes are merged.
Alternatively, we could link out to a document, so if we adjust the process we don't have to update every single ticket.

**Comment by AnnaGingle** [comment]
@joet333 Can you update the description so that product knows this ticket is WIP?

**Comment by h-m-f-t** [comment]
(All issues are works in progress! It's not in the project, so it's not something we'll focus on.)

I'd recommend using the `Issue` issue template, though: 
<img width="1263" alt="image" src="https://github.com/user-attachments/assets/407dacbd-d478-4594-ac1b-4530f7f9cc22">

**Comment by AnnaGingle** [comment]
@joet333 I made [another test ticket](https://github.com/cisagov/manage.get.gov/issues/2624) using the issue template.

**Comment by gabydisarli** [comment]
This ticket isn't relevant anymore as we've tracked the button update for the design system in another ticket.
