### ISSUE TITLE
(2) Figma Design System : Update Button Group

### ISSUE THREAD

**Issue by joet333** [cisagov/manage.get.gov#2629]
### Issue description

The button group/variations/states in the Figma design system does not match production. The following issues are :
-  Ensure that button padding between buttons is 8px (total of 16px between the buttons)
- (optional) There are some instances where there is save but not cancel button, determine and document pattern decision and rules.  (this can be a separate story if needed)

### Acceptance criteria

- [x] Figma component matches production. 
- [ ] Auto-layout is used when possible. Boolean logic is used to reduce the number of variants when appropriate.
- [ ] Changes are made in a Figma branch and are reviewed by another designer. 
- [ ] Changes are merged.

### Additional context

- Are there instances of this component nested in other components?:
- Does the component have instances of other components? If yes, do they to be updated?
- Do the changes apply to specific variants of the component?

### Links to other issues

Add any tickets that come out of this work.

**Comment by joet333** [comment]
cc @AnnaGingle

**Comment by joet333** [comment]
Updated post manage.get.gov audit - 

- (optional) There are some instances where there is save but not cancel button, determine and document pattern decision and rules.  (this can be a separate story if needed)

**Comment by joet333** [comment]
@gabydisarli @AnnaGingle  was this work completed when you did the button update by chance?

**Comment by gabydisarli** [comment]
@joet333 I did not complete this so I think this ticket can remain. This is what I did:

> Removed `Button group - next save`. This component was only used in the page Style/Misc/Exploration in the Registrar file and not really a needed component since we have Button group.

**Comment by kimberly-a** [comment]
Kept button group padding as 12px to match production and USWDS
