### ISSUE TITLE
(3) Figma Design System: Update Dg/mgmt-sidenav 

### ISSUE THREAD

**Issue by joet333** [cisagov/manage.get.gov#2631]
### Issue description

The Dg/mgmt-sidenav   --/Component / Variant / State: in the Figma design system does not match production. The following issues are :
- There is 8px of vertical padding instead of 12px 

### Acceptance criteria

- [x] Figma component matches production. 
- [x] Auto-layout is used when possible. Boolean logic is used to reduce the number of variants when appropriate.
- [x] Changes are made in a Figma branch and are reviewed by another designer. 
- [x] Changes are merged.

### Additional context

- Are there instances of this component nested in other components?:
- Does the component have instances of other components? If yes, do they to be updated?
- Do the changes apply to specific variants of the component?

### Links to other issues

Add any tickets that come out of this work.

**Comment by joet333** [comment]
cc @AnnaGingle

**Comment by AnnaGingle** [comment]
Is this the nav for manage.get.gov or get.gov?

**Comment by joet333** [comment]
Given how we are using the folders to designate the different platforms "Get/footer" and "Registrar/footer" It would be good to have that same naming convention applied to this component for each  See Footer change log for more information. 

May need to add new components 
-- including the get.gov sidebar

Talk about when to make it local components vs global.

ex "Get/sidenav"  and "Registar/sidenav"


@AnnaGingle  @gabydisarli

**Comment by vickyszuchin** [comment]
Moving from sprint 54 to sprint 55.
