### ISSUE TITLE
(0) Figma Design System: Update Banner 

### ISSUE THREAD

**Issue by joet333** [cisagov/manage.get.gov#2634]
### Issue description

The banner/component/variants/states in the Figma design system does not match production. The following issues are :
- Add Dark Blue Variation (already created look for get/header in .gov Design CISA - this color option used very often) 
- Relink to the main component
- Add open variation with options for flexibility (like icons, text etc.)

### Acceptance criteria

- [ ] Figma component matches production. 
- [ ] Auto-layout is used when possible. Boolean logic is used to reduce the number of variants when appropriate.
- [ ] Changes are made in a Figma branch and are reviewed by another designer. 
- [ ] Changes are merged.

### Additional context

- Are there instances of this component nested in other components?:
- Does the component have instances of other components? If yes, do they to be updated?
- Do the changes apply to specific variants of the component?

### Links to other issues

Add any tickets that come out of this work.

**Comment by joet333** [comment]
cc @AnnaGingle

**Comment by AnnaGingle** [comment]
Is this USA banner?

**Comment by AnnaGingle** [comment]
No changes were needed on this component.
