### ISSUE TITLE
(0) Figma Design System: Update Icon

### ISSUE THREAD

**Issue by joet333** [cisagov/manage.get.gov#2636]
### Issue description

The default icon in the Figma design system might benefit from additional variations :
-  A variation that includes a background circle button with white text.
- A variation that includes a smaller size of 16px (currently only have 24 px)

### Acceptance criteria

- [ ] Changes are made in a Figma branch and are reviewed by another designer. 
- [ ] Changes are merged.

### Additional context

- Are there instances of this component nested in other components?:
- Does the component have instances of other components? If yes, do they to be updated?
- Do the changes apply to specific variants of the component?

### Links to other issues

Add any tickets that come out of this work.

**Comment by joet333** [comment]
cc @AnnaGingle

**Comment by AnnaGingle** [comment]
The circle background isn't an icon it's a USWDS component.

**Comment by AnnaGingle** [comment]
@gabydisarli do you think we need a size variant of the icon?

**Comment by AnnaGingle** [comment]
@joet333 Where is `A variation that includes a background circle button with white text` used in the system?

**Comment by joet333** [comment]
Created 16px variation

Decided we really dont have enough instances to justify a variation that includes a background circle button with white text.
- after audit only one place uses the background color (get.gov)

Wondering if a color option would be useful too? will ask the question in review of branch.

**Comment by joet333** [comment]
decided not to make another color option at this time. reviewed and merged.
