### ISSUE TITLE
(3) Figma Design System: Update Pagination

### ISSUE THREAD

**Issue by joet333** [cisagov/manage.get.gov#2640]
### Issue description

The Pagination/states in the Figma design system could benefit from the the following :
-  Add a "group" variation option for common pagination states including an active first page, an active middle page, and an active last page. (I believe this will be helpful for mockup purposes instead of designers having to put together the different elements each time) 

### Acceptance criteria

- [ ] Figma component matches production. 
- [ ] Auto-layout is used when possible. Boolean logic is used to reduce the number of variants when appropriate.
- [ ] Changes are made in a Figma branch and are reviewed by another designer. 
- [ ] Changes are merged.

### Additional context

- Are there instances of this component nested in other components?:
- Does the component have instances of other components? If yes, do they to be updated?
- Do the changes apply to specific variants of the component?

### Links to other issues

Add any tickets that come out of this work.

**Comment by gabydisarli** [comment]
Adding @SamiyahKey as an additional assignee so she can get some experience updating a component. We will be working on this ticket together.
