### ISSUE TITLE
(2) Figma Design System: Update Search 

### ISSUE THREAD

**Issue by joet333** [cisagov/manage.get.gov#2641]
### Issue description

The search component/variations in the Figma design system does not match production. The following issues are :

- [x] - Create all states including, hover, active (putting text in w/"x" button"), value with but not selected, and disabled. 
- [ ] - Text input should inherit all text input properties 
- [x] - Search button attached to the text input and inherit all button state properties
- [x] - Optional -  Link text input to search component
- [x] - Optional - Link Search button to button component 

### Acceptance criteria

- [x] Figma component matches production. 
- [x] Auto-layout is used when possible. Boolean logic is used to reduce the number of variants when appropriate.
- [ ] Changes are made in a Figma branch and are reviewed by another designer. 
- [ ] Changes are merged.

### Additional context

- Are there instances of this component nested in other components?:
- Does the component have instances of other components? If yes, do they to be updated?
- Do the changes apply to specific variants of the component?

### Links to other issues

Add any tickets that come out of this work.

**Comment by AnnaGingle** [comment]
Hi @joet333 this is ready for review! I did not include text input in this component as it would reset all of our instances in the designs today.
