### ISSUE TITLE
(3) Figma Design System: Update Site Alert

### ISSUE THREAD

**Issue by joet333** [cisagov/manage.get.gov#2642]
### Issue description

The Site Alert/Variations in the Figma design system does not match production. The following issues are :
-  Needs minimum width defined (responsive behavior)
-  Update link option to have behavior properties (see [Link Ticket](https://github.com/cisagov/manage.get.gov/issues/2638)) 

### Acceptance criteria

- [x] Figma component matches production. 
- [x] Auto-layout is used when possible. Boolean logic is used to reduce the number of variants when appropriate.
- [x] Changes are made in a Figma branch and are reviewed by another designer. 
- [x] Changes are merged.

### Additional context

- Are there instances of this component nested in other components?:
- Does the component have instances of other components? If yes, do they to be updated?
- Do the changes apply to specific variants of the component?

### Links to other issues

Add any tickets that come out of this work.

**Comment by vickyszuchin** [comment]
Moving this ticket from sprint 54 to the current sprint (sprint 55). cc: @Katherine-Osos

**Comment by joet333** [comment]
Hi Vicky. Can you see if there's a Way to take me off these github email
notification? Thanks.

**Comment by h-m-f-t** [comment]
Hi @joet333! Since you're the creator of the issue, I think the only way will be for you to "unsubscribe" from notifications on a per-issue basis... 
<img width="421" alt="image" src="https://github.com/user-attachments/assets/78e99807-b0fc-4586-9b0d-e242ed6d38d5">

**Comment by joet333** [comment]
oh! Good to know! As long as it's not a security problem, it is fine by me.
I just felt really nervous someone was going to come for me because I was
getting emails.

Anyway, take care and thank you!
