### ISSUE TITLE
Refactor the join lookup on user transfer to work with the refactored portfolio (multiple per user instead of one)

### ISSUE THREAD

**Issue by rachidatecs** [cisagov/manage.get.gov#2644]
### Issue description

#2579 was implemented at the same time as #2586 

We need to revise the portfolio transfer logic to account for multiple portfolios per user and different sets of permissions/roles on those portfolios

### Acceptance criteria

- [ ] The portfolio transfer logic is updated to account for multiple portfolios and permissions/roles
- [ ] no errors occur if you merge two contacts where one or both have multiple portfolios with permissions

### Links to other issues

resulted from #2579

**Comment by vickyszuchin** [comment]
Added "refinement" label, no ACs defined. @rachidatecs would you add ACs to this ticket?
