### ISSUE TITLE
Remove Cisa Region from portfolio and add sticky bar

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2660]
### Issue description

The portfolio page can get long once we have lots of members and so on, given that we also already use a sticky save bar on Domain Requests we should apply this to the portfolio page. While we are there, let's remove Cisa Region from showing as this is not helpful to analysts for a portfolio

### Acceptance criteria

- [x] add sticky bar to the portfolio page. This should match the domain request sticky bar with the only difference being "Requested domain" it should said "Organization:<organization_name>"
- [x] remove Cisa Region

### Additional context

Sticky bar example from Domain Requests. Note that instead of "Requested domain" it should said "Organization:<organizaiton_name>"
![image](https://github.com/user-attachments/assets/00d89565-d23b-4395-b9f1-a5c689458bb1)

### Links to other issues

- [ ] blocks #2402

**Comment by vickyszuchin** [comment]
Developer has started this ticket. Moving it from sprint 53 (originally slotted) into current sprint (sprint 53). Given that it is story pointed as 1, it should not post a risk adding it.

**Comment by abroddrick** [comment]
removing pulled in temporarily as the person who picked it up had to drop prior to working on it ( a lot).
