### ISSUE TITLE
Pages with tables have the max width set to 1920

### ISSUE THREAD

**Issue by AnnaGingle** [cisagov/manage.get.gov#2669]
### Story

The majority of our users use devices with a 1920 resolution. Our max-width today is much smaller, and content can be hard to read or cut off entirely. 
As a user with a device that has a 1920px resolution, I want the website content to be displayed optimally within the available screen space so that I can easily read and navigate through the information without experiencing any issues with text being too small or cut off.

### Acceptance Criteria

Org model pages that have tables have a max width of 1920. This includes the main content, header, top navigation, and footer.
- [ ] Domains page (home)
- [ ] Members
- [ ] Domain requests

Non-org pages that have tables have a max width of 1920. This includes the main content, header, top navigation, and footer.
- [ ] Manage your domains (home)

### Additional Context

[Slack thread](https://cisa-corp.slack.com/archives/C07HJTNV066/p1724710837578829)
![Screenshot 2024-08-27 at 1 46 13 PM](https://github.com/user-attachments/assets/11db7142-9f14-48bc-aa8e-4aaeafda413c)

### Rachid's notes

You probably want to add a context_processor to return the page(s) in question to templates, then add custom classes to header/footer/the content itself when the conditions are right. 

Remember to use BEM

### Issue Links

🔄 Relates to #2655
🔄 Relates to #2544

**Comment by katypies** [comment]
@AnnaGingle  Can you update the Slack link to point to one that isn't Truss-specific since not everyone on the team can see that?

**Comment by vickyszuchin** [comment]
Added "refinement", pending update from @AnnaGingle

**Comment by AnnaGingle** [comment]
@katypies I don't have a CISA slack account so I can get that link. @gabydisarli Are you able to grab it?

**Comment by vickyszuchin** [comment]
Thread link updated.
