### ISSUE TITLE
(2) Figma Design System: Update Text Input - Select

### ISSUE THREAD

**Issue by joet333** [cisagov/manage.get.gov#2678]
### Issue description

The text input-select /variants/states in the Figma design system does not match production. The following issues are :
- Selected text color needs to be Ink color
- States for active, active disabled, and hover needs to be created

### Acceptance criteria

- [ ] Figma component matches production. 
- [ ] Auto-layout is used when possible. Boolean logic is used to reduce the number of variants when appropriate.
- [ ] Changes are made in a Figma branch and are reviewed by another designer. 
- [ ] Changes are merged.

### Additional context

- Are there instances of this component nested in other components?:
- Does the component have instances of other components? If yes, do they to be updated?
- Do the changes apply to specific variants of the component?

### Links to other issues

Add any tickets that come out of this work.

**Comment by vickyszuchin** [comment]
Any "In progress" tickets from Sprint 55 will be moved to the current sprint (Sprint 56) at noon EST (10am MT/9am PST) on Day 1.

**Comment by vickyszuchin** [comment]
Any "In progress" tickets from Sprint 55 will be moved to the current sprint (Sprint 56) at noon EST (10am MT/9am PST) on Day 1.
