### ISSUE TITLE
Run populate_domain_request_dates on Staging

### ISSUE THREAD

**Issue by Matt-Spence** [cisagov/manage.get.gov#2683]
### Issue description

There is a new management script populate_domain_request_dates that needs to be run on staging. 

### Acceptance criteria

- [ ] Populate_domain_request_dates script is run successfully on staging
- [ ] New fields are confirmed to be populated with correct values

### Additional context
Data is populated with audit log history, but sometimes our fake data is generated without any history. This might mean that some domain requests will not be updated, in which case we just want to confirm that this is because they have no history. The script will skip any request that has no history, so it should be clear which requests this applies to.

### Links to other issues

- #2541

**Comment by abroddrick** [comment]
@Matt-Spence I assume your script will print which requests were not updated correct? also does your script factor in the fact that some requests are just in the started state, thus never submitted etc and shouldn't print our as error?

**Comment by Matt-Spence** [comment]
@abroddrick one correction on the above: I forgot that I didn't include the debug option in the script, which means it will default to True (always run in debug mode).
