### ISSUE TITLE
Run populate_domain_request_dates script on Stable

### ISSUE THREAD

**Issue by Matt-Spence** [cisagov/manage.get.gov#2684]
### Issue description

There is a new management script populate_domain_request_dates that needs to be run on stable.

### Acceptance criteria

- [ ] Populate_domain_request_dates script is run successfully on stable
- [ ] New fields are confirmed to be populated with correct values

### Additional context

Data is populated with audit log history. On sandbox environments this means that many requests are skipped, because they are generated without any history. On stable, however, every record should have a history so no requests should meet the requirements for being skipped.

### Links to other issues

- #2541

**Comment by abroddrick** [comment]
ran this on staging, will run on stable as soon as it's released. Current ETA for running this is this coming tuesday
