### ISSUE TITLE
(3) Figma Design System: Update ".gov" Text Image

### ISSUE THREAD

**Issue by joet333** [cisagov/manage.get.gov#2685]
### Issue description

The ".gov" text image in header of both get.gov and manage.get.gov in the Figma design system does not match production. The following issues are :
- get.gov "get.gov" should be color#001726
- manage.get.gov ".gov Registrar" should be #1b1b1b
- consider working with development to make both of these the same color

### Acceptance criteria

- [x] Figma component matches production. 
- [x] Auto-layout is used when possible. Boolean logic is used to reduce the number of variants when appropriate.
- [x] Changes are made in a Figma branch and are reviewed by another designer. 
- [x] Changes are merged.

### Additional context

- Are there instances of this component nested in other components?:
- Does the component have instances of other components? If yes, do they to be updated?
- Do the changes apply to specific variants of the component?

### Links to other issues

Add any tickets that come out of this work.

**Comment by AnnaGingle** [comment]
Hi @joet333 ! Does this refer to the logo component?

**Comment by AnnaGingle** [comment]
Or actually is it just updating the text color?
