### ISSUE TITLE
Conduct user research for DNS hosting discovery 

### ISSUE THREAD

**Issue by witha-c** [cisagov/manage.get.gov#2689]
### Issue description

Conduct research sessions with 3-5 users on the discovery questions outlined in the DNS hosting summary [document](https://docs.google.com/document/d/1iaaBi2iXKoVAPzEcRbXQbXwN1_v4Lf67Qz3C95nHLEw/edit). 

### Acceptance criteria

- [x] complete research sessions with 3-5 users 

### Links to other issues

- https://github.com/cisagov/manage.get.gov/issues/2612
- https://github.com/cisagov/manage.get.gov/issues/2403

**Comment by vickyszuchin** [comment]
We discussed the scope of this ticket in sprint 53 planning.

**Comment by vickyszuchin** [comment]
Moved forward from sprint 53 to sprint 54.
