### ISSUE TITLE
The sort button on suborganization does not sort correctly when the table is paginated

### ISSUE THREAD

**Issue by zandercymatics** [cisagov/manage.get.gov#2696]
### Issue description

In the portfolio view, the filter button for the `suborganization` column on the domains table does not sort items outside of items that are paginated. 

More specifically, clicking the sort button will sort suborganization items: _but only those within the paginated view_. For instance, if you had 100 suborganization records and showed 10 records per line, the sort button currently only sorts by those first 10 records rather than sorting by all 100 of them.

This appears to be caused by our custom sort logic for pagination breaking (see additional context). Thus, the column is sorting as it would by default - which we do not want.

### Acceptance criteria

- [ ] The suborganization field sorts paginated content correctly

### Additional context
[See this slack thread for context](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1725035423448189)

Note: when clicking the sort button, `get-gov.js` appears to be throwing errors
![image](https://github.com/user-attachments/assets/43c12c8c-d219-4c47-84fa-0ecf6af51346)

**Comment by abroddrick** [comment]
@zandercymatics on bug tickets you should actually describe what the issue is as opposed to saying it hits an error, it breaks, it doesn't work right, you want to say how specifically does it appear broken? 500 error? console errors? It doesn't sort at all and just appears to only highlight the table? Please update the ticket with a bit more description.

**Comment by vickyszuchin** [comment]
Added "refinement" as it is pending refinement from @zandercymatics

**Comment by abroddrick** [comment]
Removed refinement! Thank you Zander!
