### ISSUE TITLE
Service design presentation prep

### ISSUE THREAD

**Issue by witha-c** [cisagov/manage.get.gov#2701]
### Issue description

@jaxonsilva24 is joining the .gov team for FY25 and will be doing service design work that helps the .gov team while also serving his home office. He will prep a brief presentation to talk about service design and what he will be doing this year. 

### Acceptance criteria

Presentation covers:
- [x] About @jaxonsilva24 
- [x] What service design is, connected to the context of .gov
- [x] Description of common visualizations/maps and their value, how to use them
- [x] Overview of the service design work that @jaxonsilva24 will be doing while with the .gov team

### Additional context

We will plan to schedule the presentation for a team workshop in sprint 54.

**Comment by vickyszuchin** [comment]
Moved from sprint 53 to sprint 54.
