### ISSUE TITLE
Portfolio user with VIEW_MANAGED_DOMAINS permission can view domains that they don't manage

### ISSUE THREAD

**Issue by dave-kennedy-ecs** [cisagov/manage.get.gov#2717]
### Current Behavior

User has MEMBER role and VIEW_MANAGED_DOMAINS permission for portfolio YYYY. User does not have VIEW_ALL_DOMAINS for portfolio YYYY. Domain XXXX is in portfolio YYYY. User does not manage Domain XXXX. User can see Domain XXXX in domains table when organization_feature waffle flag is true.

### Expected Behavior

User should not see Domain XXXX in the domains table. 

### Steps to Reproduce

1. Create portfolio.
2. Grant user Member role for the portfolio, plus additional permission, VIEW_MANAGED_DOMAINS.
3. Grant user a Manager role for Domain ZZZZ.
4. Set the portfolio for Domain YYYY and Domain ZZZZ.
5. Set the organization_feature waffle flag to Yes
6. Navigate to the home page.  You will see both YYYY and ZZZZ; however, you should only see ZZZZ

**Comment by vickyszuchin** [comment]
See [slack thread](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1725563827335239) for troubleshooting and decision on ticket.
