### ISSUE TITLE
Investigate copying one database to another sandbox

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2724]
### Issue description

We have talked with cloud.gov on how to pull down a backup of stable, but the first option we tried had various issues with developers, including many technical blockers stemming from their machines. It also required us to download a copy onto our local machine, but many devs use personal devices and should not put a copy of our db on their personal device. 

With all of this, we emailed cloud.gov and received an alternative solution. This will require heads down time to work through and may require emailing cloud.gov or joining their office hours for questions. We also do have some hours of help were we can get their help if we get stuck with the steps they dictate.

### Acceptance criteria

- [ ] claim a free sandbox to pull from (and one that can receive the data if needed). Do not touch stable, staging or development while performing this investigation
- [ ] Follow the instructions below for being able to copy the database from one sandbox into another sandbox
- [ ] determine if this can be setup to automatically pipe data from one db to another or run every hour
- [ ] communicate with/ ask questions to cloud.gov if needed (keep Alysia and Cameron cc:ed in emails and get approval before using troubleshooting hours if needed). if you want to attend the cloud.gov office hours, this meeitng can be shared with you
- [ ] discuss finding in eng huddle or another adhoc setting.
- [ ] If deemed doable on developer sandboxes, write out instructions on what is needed and make tickets for what would be needed to have this working on stable to pipe stable db to staging. 

### Additional context

Quote from cloud.gov on suggested alternative approach

> This would involve setting up a temporary docker application with an S3 bucket bound to that application. Additionally you would bind the old RDS instance to the temporary docker application. 
> 
> You would then dump the data from the old RDS instance into that temporary docker application and then transfer it to the S3 bucket from there. After the data is transferred to S3, you would unbind the old RDS instance, bind the new RDS instance and then [connect the new RDS instance to S3 and load the data into the new RDS instance](https://cloud.gov/knowledge-base/2023-02-13-Connecting-PostgreSQL-RDS-instance-to-S3/).
> 
> If you need to share the service instance that contains the data with another space in your organization, please refer to the documentation on sharing service instances, linked [here](https://cloud.gov/docs/deployment/managed-services/#sharing-service-instances). Please let us know if you have any additional questions or would like any further clarification.

**Comment by abroddrick** [comment]
Tentatively reserving for Matt to work on

**Comment by vickyszuchin** [comment]
Moving this ticket from sprint 54 to sprint 55.
