### ISSUE TITLE
Code to check for pending submitted requests and prevents the user from submitting new requests is not working

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2726]
### Current Behavior

~~We check for pending submitted requests and supposedly prevents the user from submitting new requests. This code seems to be obsolete. The pending requests code is no longer doing anything.~~

### Expected Behavior

~~Application checks for pending submitted requests and prevents the user from submitting new requests.~~

### Steps to Reproduce
~~
1. Create and submit an application
2. Create a second application and submit it. It goes through instead of throwing an alert.
~~

### Environment

Stable

### Additional Context

Relevant code:
https://github.com/cisagov/manage.get.gov/blob/ae143e78cd97d1fe97fd12d01db183ed5818d48b/src/registrar/views/domain_request.py#L256
https://github.com/cisagov/manage.get.gov/blob/ae143e78cd97d1fe97fd12d01db183ed5818d48b/src/registrar/templates/domain_request_form.html#L80
https://github.com/cisagov/manage.get.gov/blob/ae143e78cd97d1fe97fd12d01db183ed5818d48b/src/registrar/views/domain_request.py#L507
That last part in POST may not be firing

The unit test `test_domain_request_multiple_domain_requests_exist` passes, strangely enough.

### Issue Links

False alert. This code still works when the user does not have an approved request.

_No response_

**Comment by rachidatecs** [comment]
False alert. This code still works when the user does not have an approved request. We can close this one.
