### ISSUE TITLE
Upon request submission (at confimation page), Back button redirects to submit screen for non-org users

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/manage.get.gov#2727]
### Issue description

On domain requests for non-org users, if you submit, you get redirected to the confirmation screen. If you hit browser back button, you go back to submit screen. You should instead go back to either 1) the homepage if regular user or 2) the domain requests page if org user.

Desired flow:
1. fill out a non-org request
2. submit the non-org request
3. see confirmation message
4. click back and you are back at the submit screen the domain request table / home page. They will see their request in the queue.

### Acceptance criteria

- [ ] Upon request submission (at confirmation page), Back button redirects to homepage for non-org users
- [ ] Upon request submission (at confirmation page), Back button redirects to requests for org users

### Additional context

[Slack thread](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1725645681665469)

**Comment by vickyszuchin** [comment]
Ticket refined by @rachidatecs

**Comment by abroddrick** [comment]
looks refined to me!

**Comment by PaulKuykendall** [comment]
Sprint planning: There's a thread in progress to discuss this ticket. "Add a breadcrumb??"

**Comment by abroddrick** [comment]
Closing in favor of sending this back to design in #2884 and using a breadcrumb etc instead of controlling the back button functionality.
