### ISSUE TITLE
"Add a domain manager" page updates

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2729]
### Issue description

With the addition of user management, some minor tweaks have been made to the add domain manger page for the org model, and one tweak has been made to the non org model view.
Specifically we want an alert to show in the org model view if someone tries to add a domain manager that is already invited to or is a member of another org. In this case we also don't want to make a user domain roles or domain invitation for them.

Both the nonorg and org model users should see the new breadcrumb, as that is an accessibility standard we are working to have on all pages.

### Acceptance criteria

- [x] match [this figma](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=7903-44203&node-type=FRAME&t=DocU1Z5Zw6pWozSJ-0)  for adding the alert and breadcrumb,
including the annotations for the "add domain manger page"
- [x] breadcrumb is added to non org model view as well as org model view of this page
- [x] alert is added to the org model view only. This requires being able to check if the person has permissions or is invited to another org. 
- [x] No domain invitation/user domain role should be created for someone who is part of another org
- [x] content is updated to in the org model view

### Links to other issues

- [ ] related to #2456 (team review of member mangement)

**Comment by abroddrick** [comment]
just waiting on response from[ this message](https://cisa-corp.slack.com/archives/C07589TAY57/p1726243339140859?thread_ts=1725651508.923769&cid=C07589TAY57) before marking as ready

**Comment by PaulKuykendall** [comment]
in Sprint planning: This is blocked by a bug discovered during review.
