### ISSUE TITLE
Run the Update_First_Ready script on Stable

### ISSUE THREAD

**Issue by Matt-Spence** [cisagov/manage.get.gov#2742]
### Issue description

As described in #2560, some first_ready values were incorrect for some transition domains. This script corrects those values using the created_at date. It's a simple script that accepts no parameters and will display everything that will be updated beforehand.

### Acceptance criteria

- [ ] Update_first_ready script is run successfully on Staging

### Links to other issues

- Blocked by Staging 1.1.1 being released to Stable

**Comment by abroddrick** [comment]
Ran today, no errors found 81 domains were updated.
