### ISSUE TITLE
UAT Preparation and Review for m1/m2 launch

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#2745]
### Issue description

Collaboration between Product and Dev to pre-evaluate test cases in the target environment, to ensure that we are ready for UAT. 

Requesting Dev support (as needed) to confirm test environment setup with code and application.

### Acceptance criteria

- [x] Setup and maintain AG environment for UAT effort
- [x] Answer any questions from Product regarding codebase and environment for UAT
- [x] Discuss changes identified by UAT testing and determine which are small enough to be done as part of this ticket
- [ ] Create new tickets for larger changes (> 4hrs)
- [ ] time boxed to 2 days, when approaching the 2 working day time box all outstanding changes should be made into a ticket or tickets
- [ ] Work with Product to identify any blockers to UAT and Release

### Links to other issues

similar to design review tickets
* #2402 
* #2543 

depends on
* #2712

**Comment by PaulKuykendall** [comment]
Paul initially pointed this at 2 to timebox dev time.

@abroddrick - who would you suggest to work on this with me?

**Comment by abroddrick** [comment]
@PaulKuykendall I think to keep in line with how we did the design reviews, how would you feel about making a temporary channel for uat testing with all engineers just like with the design reviews. This way any questions are just in one spot and it doesn't get lost or overload an existing channel? (Also, guarantees that questions and findings aren't being communicated in a dms)

CC: @asaki222

**Comment by PaulKuykendall** [comment]
@abroddrick - I think a temp channel would be good for UAT. @h-m-f-t, did you already request this?

**Comment by vickyszuchin** [comment]
Moving this ticket from sprint 54 to sprint 55.

**Comment by katypies** [comment]
Marking this as complete! We've onboarded at least one user for m1/m2, with plans for additional users. There were no blocking issues, and new tickets will be created for additional portfolios to be created, scripts to be run, or enhancements we discover as we bring new users on!
