### ISSUE TITLE
DNS hosting UX brainstorming

### ISSUE THREAD

**Issue by witha-c** [cisagov/manage.get.gov#2747]
### Issue description

Designing the user's experience of setting up DNS hosting may be more straightforward than designing other parts of their experience, such as help content, transitions from different starting points, and security guardrails. What are all of those experience elements? Which might be more complex than others? 

### Acceptance criteria

- [x] Start drafting a map of possible user flows
- [x] Get a better sense of the scope of experiences we'll be designing

**Comment by gabydisarli** [comment]
We've started this [Miro board ](https://miro.com/app/board/uXjVKammr_w=/?moveToWidget=3458764602419674477&cot=14)for creating storymaps for primary user scenarios.

**Comment by gabydisarli** [comment]
I believe we can call this ticket done as there's been some good discussion on the Miro board mentioned above. The board explores some user flows and uncovers open questions and begins to document some of the design tickets we will need.
