### ISSUE TITLE
User research support to m1/m2 release

### ISSUE THREAD

**Issue by witha-c** [cisagov/manage.get.gov#2748]
### Issue description

Design will support m1/m2 release feedback sessions with users by preparing scripts to be used during those sessions. 

### Acceptance criteria

- [x] The script is informed by the [list](https://docs.google.com/document/d/1eBHL9FUFyYhC4PXeexQdceCw1wKXa35LYr1jlkUvvjE/edit#heading=h.d6pqopse1m68) of information that product wants to learn from users
- [x] The script includes [a section to address domain groups ](https://docs.google.com/document/d/19xfeqngX_RYyWX5fvXNS06U2PDRjlsfWndWDPhltawY/edit#heading=h.vi6fdmz7mknq)
- [x] Share with Design for review
- [x] Iterate with Product to finalize

### Additional context

- [Script](https://docs.google.com/document/d/17s7s7bXvB4zHxLTiaw6NNPFy8-3blWXkQrFFG3nCiIs/edit#heading=h.3dtg56qy1hnw)
- [Product strategy doc](https://docs.google.com/document/d/1IS-X0Bo6-jj3dXtRDvPWS-ZlgLzG1SFxD9j9YB_18zo/edit#heading=h.hy3nlqrc6pq1)
- [Release planning spreadsheet](https://docs.google.com/spreadsheets/d/1qpXqcTgDzgUQMLPFM2-iBUYJUVVH6l7C-M5zNKq-6u0/edit?gid=822961363#gid=822961363)

### Links to other issues

🔄 relates to #2674

**Comment by AnnaGingle** [comment]
Need the product strategy doc to begin this work.

**Comment by AnnaGingle** [comment]
No feedback to address from product
