### ISSUE TITLE
Org Model: Update "view only" message on the domains page and fix tooltip

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#2775]
### Issue description

**Domain page**: We need to update the message that displays if a user can only view a domain, but not manage it. 

**Domains table**: We also need to fix the tooltip that appears when hovering over the "On Hold" status. The tooltip gets cut off when there are multiple domains in the table with different statuses. Note: the tooltip _doesn't_  seem to get cut off if the "On Hold" domain is the only one listed in the table.

### Acceptance criteria

- [x] On the domain page, update the message that appears if a user can only view a domain, but not manage it. Use the text in [this document](https://docs.google.com/document/d/1u-K1yQKb16H3AWj33mH2e1LJme6Ay9dNXMG8isiOXWk/edit#heading=h.tsr9qh4ofhbi).
- [x] In the domain table, fix the tooltip that appears when hovering over a domain in "on hold" status. The beginning of the tooltip gets cut off.

### Additional context

Beginning of tooltip gets cut off:
 
![Image](https://github.com/user-attachments/assets/7f70d59e-842f-4ec9-ad51-8ec522a36bdc)

**Comment by rachidatecs** [comment]
@Katherine-Osos @abroddrick I just reviewed this ticket. The tooltip getting cut off is due to how the responsive table wrapper sets the overflow. This could prove to be really tricky to solve. A easier approach would be to shorten the tooltip text (could work, would need testing). Is that an option?

**Comment by Katherine-Osos** [comment]
@rachidatecs @CocoByte All the words in that message are pretty important, but I think we only need to reduce a few characters, right? Can you try this (shortened by 3 characters)

> This domain is administratively paused. It can’t be edited and won’t resolve in DNS. Contact help@get.gov for details.

**Comment by abroddrick** [comment]
@Katherine-Osos unfortunately, shortening it by 3 characters could still result in it being cut off on some screen sizes. To avoid it ever being cut off the ideal state would be for it to be just a few words, such as "needs name servers".

**Comment by Katherine-Osos** [comment]
@abroddrick The tooltip resizes appropriately on most screensizes, it's just the version I posted above that gets cut off and it's two letters. Can a dev give it a try before we make any more adjustments?

**Comment by vickyszuchin** [comment]
Moving this ticket from sprint 55 to the current sprint (sprint 56). cc: @abroddrick @lizpearl
