### ISSUE TITLE
Update generic error messaging for zip code and email address

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#2777]
### Issue description

A couple of fields still display generic error messaging when the field is left blank: "This field is required." 

We need to update the messaging to be more specific. The updates should apply to all instances of the fields, in org model and non-org model.

### Acceptance criteria
These updates apply to relevant pages in the org model AND non-org model setup.

- [x] On the "Organization" page:
  - [x] When zip code is required and left blank, update error message to read: 
    - Enter a 5-digit or 9-digit ZIP code, like 12345 or 12345-6789.
  - [x] When zip code uses wrong format, update the error message to match the message listed above. (we want them to be consistent)
- [x] On the "add a domain manager" page:
  - [x] When email address is required and left blank, update error message to read: 
    - Enter an email address in the required format, like name@example.com.
- [x] Review registrar and verify other instances where these fields appear show this updated messaging

### Additional context

note to dev, this is just error message updates, you don't need to write unit tests for this, manually testing is sufficient

**Comment by gabydisarli** [comment]
Checked error messages across the following pages and everything looks good

### Non Org model
**Domain Mgmt**
- Organization page (zip)
- Add a domain manager (email)
- Senior official (email)
- Security email (email)

**Request form**
- Organization page (zip)
- Other employees (email)
- Senior official (email)


### Org Model
Domain Mgmt
- Add a domain manager (email)
- Security email (email)

**Org info**
- Organization page (zip)
