### ISSUE TITLE
Django admin table bugs: The Import/Export buttons are overlapping with the table result text / generic org type is displayed

### ISSUE THREAD

**Issue by zandercymatics** [cisagov/manage.get.gov#2851]
### Current Behavior

Currently, the import/export buttons on the model tables are overlapping the sorted result text when it reaches a certain length. This is most when searching on a really long string, or filtering on a property (like portfolio) that has a long name.

As well, the domain request / domain tables contain the "generic org type" column but it should be the "organization name" field.

### Expected Behavior

The result text and import/export buttons should wrap rather than overlap.

The domain request / domain tables should use the organization name field rather than generic org type

### Steps to Reproduce

1. On the table search bar, search for a really long string and hit enter

### Additional Context

This issue was discovered during review for ticket #2402. [See this slack thread for more context](https://cisa-corp.slack.com/archives/C07NPR8HSLQ/p1727217835114149). 

![image](https://github.com/user-attachments/assets/af7aca70-db7a-40a1-a2ac-5acb362c4d84)

### Issue Links

- blocked by #2402

**Comment by katypies** [comment]
We're going to close this. While it's an issue, it's not something we expect Analysts will encounter in their searches. If it does come up, we can always re-open the ticket to prioritize.
