### ISSUE TITLE
Add @property to portfolio related fields in Domain Requests

### ISSUE THREAD

**Issue by CocoByte** [cisagov/manage.get.gov#2852]
### Issue description

With the introduction of org model, certain fields stored in Domain Requests are now also stored in Portfolios.  We want to prioritize displaying portfolio data if a portfolio is present.  To accomplish this, we will add new getter functions to the Domain Request model that will check to see if the given domain request is assigned to a portfolio and return the portfolio data for that field if a portfolio is present.  These getters should be assigned the @property tag ([see documentation](https://dev.to/doridoro/django-model-properties-28ac)) so we can use them in our frontend.

For example, if a domain request is part of an org federal_type will come from the organization. But on django admin we are using federal_type as a filter option and we show it on the request, pulling the data directly from the request object. Instead, we want to change our django admin setup to pull a property converted_fed_type that will check if the request is part of a portfolio. if it is part of the portfolio, then we return the info from the linked federal agency, otherwise we return the stored federal agency field value. 

### Acceptance criteria
- [x] All instances of the following Domain Request fields on django admin domain request table should be altered to use a property field that is returning either the stored domain request value or the corresponding portfolio value where appropriate. 
- [x] Filters/table/and record views on domain requests admin are all updated to use the corresponding property field for each field listed below
- [ ] The domain request report  on the Request table are updated to use the appropriate property fields 
- [ ] Domain Request fields that should pull from an org and to which all the above AC apply:
  - [x]  organization_name
  - [x]  generic_org_type  (called "organization_type" in Portfolio)
  - [x]  federal_agency - should come from federal agency from federal agency entry associated with the portfolio
  - [x]  federal_type - should come from federal agency table entry associated with the portfolio
  - [x]  state_territory - should be from portfolio organization address
  - [x]  urbanization - should be from portfolio organization address
  - [ ] senior_official

### Additional context

Note: in the example below I use "converted_" to start off this function name, if you think of a better name feel free to change this. 
Example for Federal_type
in models/domain_request.py
```
# add a property function
@property
def converted_fed_type(self,):
"""" returns the federal_type field of the Federal Agency if the domain request is in a portfolio
     otherwise it returns the federal_type from the domain request object itself""""
    if self.portfolio:
        #note here that the portfolio already has an @property getter to return federal type
        return self.portfolio.federal_type
    return self.federal_type

```
in DomainRequestAdmin in admin.py
```
# change the list_display to no longer use federal_type and instead have it user converted_fed_typ
list_display = [
        "requested_domain",
        "first_submitted_date",
        ...
        "converted_federal_type", #see the change here
        "federal_agency",
        "organization_name",
        ....# you get the gist,
    ]

# then you also have to adjust the filter since this is used for a filter
list_filter = (
        StatusListFilter,
        "generic_org_type",
        "converted_federal_type", # see the change here
        ElectionOfficeFilter,
        "rejection_reason",
        InvestigatorFilter,
    )

#replace all other occurrences in **DomainRequest** admin.py
```

**Comment by CocoByte** [comment]
@abroddrick  I am unsure if "Notes" should also have @parameter for it.  Also, I am ignoring some fields like "about_your_organization" as well as fields related to federal_type (such as "federally_recognized_tribe" and "state_recognized_tribe") since these do not show up in portfolios...do you have any thoughts on how we should approach these non-portfolio fields?

**Comment by h-m-f-t** [comment]
I think we'll want to have tribal information as part of the org model eventually (i.e., it maybe should have @ parameter) but I defer to engineering on the need for this now.

**Comment by h-m-f-t** [comment]
Adding refinement simply because it's still marked draft and we've moving it out of new.

**Comment by asaki222** [comment]
I updated the AC to remove the DomainRequest MetaData req. It touches the domain information model which is beyond the scope of the ticket.

**Comment by vickyszuchin** [comment]
This ticket has been moved from sprint 56 to sprint 57 per, "In-review: the ticket will move over at noon EST on Day 4 (Monday) to the new sprint". cc: @abroddrick @lizpearl
