### ISSUE TITLE
Org Member Page - Invite A New Member (INVITATION ONLY)

### ISSUE THREAD

**Issue by therealslimhsiehdy** [cisagov/manage.get.gov#2854]
### Issue description

For the org model, users will need to invite other users to join the organization and select the permissions they want for these users. In #2769 we created the first part of the Member invitation flow, which is a form with conditional fields and a continue button that doesn't work. Here we will create the modal pop-up that forms when you click "continue" and generate the actual invitation need. 

### Acceptance criteria

- [ ] Clicking on "Invite member" on the "Add a new member page" opens a modal pop up ([see Figma](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=8288-38591&t=bqgIgKGnGc7JTI1y-4)) ([updated link](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=10288-41436&node-type=frame&t=uwc9xgmgw410uQpY-0))
- [ ] In modal, clicking "cancel" closes the modal and goes back to the "add a new member page"
- [ ] Clicking "Yes, invite member" in the modal displays success message on the "Manage member" page and navigates user to the "Manage member" as well ([see Figma](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-registar?node-id=8288-38583&t=bqgIgKGnGc7JTI1y-4))
- [ ] Invitation is made for the member that is being invited

### Additional context
We do not have an email yet to send the user, so you do not need to add in that functionality yet.

### Links to other issues

- Blocked by #2769

**Comment by vickyszuchin** [comment]
Moved all "In progress" sprint 57 tickets to the current sprint (sprint 58), per guidance.
