### ISSUE TITLE
Renew  certificates

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/manage.get.gov#2856]
### Issue description

The registrar-registry certificate and the login.gov certificate expire in late October. Let's renew them both.

### Acceptance criteria

- [ ] Review [the login.gov documentation](https://github.com/cisagov/manage.get.gov/blob/main/docs/operations/runbooks/rotate_application_secrets.md#django_secret_login_key)and the [cloudflare documentation](https://github.com/cisagov/manage.get.gov/blob/main/docs/operations/runbooks/rotate_application_secrets.md#registry_cert-and-registry_key-and-registry_key_passphrase) for cert generation and create the cert
- [ ] Update the registry certificate in the **registry** admin portal.
- [ ] Update the login.gov cert and create the ticket for login.gov to apply the change
- [ ] Confirm with Cloudflare in our shared Slack channel that all systems are go
- [ ] set slack reminders for both
- [ ] add both to our team calendar
- [ ] update credentials on stable  when the certs have been applied

**Comment by h-m-f-t** [comment]
@abroddrick can you update the documentation anchor above and add a link?

**Comment by h-m-f-t** [comment]
@abroddrick, re-opening to check two things:
1. Can you update the documentation link above to wherever it really is?
2. I'm not seeing anything on the team calendar that feds have access to. Was that's A/C done, and if so, which calendar was that added to?

**Comment by abroddrick** [comment]
Good call out on the documentation @h-m-f-t, I had marked that as done a while ago. Just updated the link(s) and double checked it saved. Fair on the calendar setup, Liz set those up today, so they should all be there now!
