### ISSUE TITLE
Portfolio (django admin): Hide federal agency when the organization type is not federal

### ISSUE THREAD

**Issue by zandercymatics** [cisagov/manage.get.gov#2861]
### Issue description

On the portfolio page, we dynamically hide the organization name field when the organization type is set to `Federal`. 
For this ticket, we should do the inverse: hide the federal agency field  when the organization type is not federal.

### Acceptance criteria

- [ ] The federal agency field is hidden on the page when the organization_type is not federal.
- [ ] The federal agency field is set to `non-federal agency` on save if the organization_type is not federal. 
- [ ] Ensure that the organization name is still visible when organization_type is not federal.

### Additional context

In `get-gov-admin.js`, there is an existing IIFE called `dynamicPortfolioFields`. This may be a good spot for this change.

### Links to other issues

relates to:
-  https://github.com/cisagov/manage.get.gov/issues/2402

**Comment by abroddrick** [comment]
Closing in favor of adding it to another related ticket #2976
