### ISSUE TITLE
Django admin: Update portfolio fields on Domain Information

### ISSUE THREAD

**Issue by zandercymatics** [cisagov/manage.get.gov#2867]
### Issue description

In #2934 we updated the layout of Domain Requests for Org model and non-org model requests, and added in conditional logic so that fields that were only relevant to the org model requests disappeared for non org model requests and visa versa. Meanwhile, in #2852 we updated the domain requests so the the filters and domain request table in admin also pull from the portfolio when appropriate and the domain request otherwise. We should now copy what was done for domain requests so domain info has the same logic and layout and ensure that domain (which uses domaininfo inline) receives those layout changes appropriately. 

The goal of this ticket should be to make sure all places where we display domain info data now pulls from portfolio when appropriate on the change form views of admin
### Acceptance criteria

**Domain Information** 
- [x] Copy what was done in #2934 to now apply to Domain Info and Domain
    - this include the conditional showing/hiding of fields 
    - also be sure to match the new layout created 2934
- [x] exception: unlike 2934, domain info (and domain) should **not** have requested suborganization fields (requested suborg name, city,state )
- [x] Be especially sure to apply the same suborganization logic that was added into 2934 (see the ACs on that ticket regarding suborganization)

### Additional context

Regarding the `series of dashes` AC, your solution should keep select2 (or at least replace it) as it offers us a performance boost and a search bar.

Refer PR for #2934 so that it is easy to do this change.
### Links to other issues

- [ ] blocked by #2934 
- [ ] blocked by #2852

**Comment by katypies** [comment]
@abroddrick to review this to see if some items need to be split out for domain requests.

**Comment by abroddrick** [comment]
Removed domain request items

**Comment by h-m-f-t** [comment]
Right now, this issue and #2826 are both planned next sprint (57) and this issue appears to touch select2 which we're proposing be in-sourced. Paging @abroddrick for awareness and whether these two should be sequenced in a certain order.

- #2826
