### ISSUE TITLE
Onboard "org admin" users from select federal agencies for Org Model

### ISSUE THREAD

**Issue by katypies** [cisagov/manage.get.gov#2876]
### Issue

We're working with OMB to identify designees for several federal executive branch agencies who would be good candidates for the Org Model work, and in particular the Admin role. Many of these may not already be users in the registrar, since they are less likely to be domain managers. We'll need to onboard these users to the registrar and to their portfolio of domains.

### Acceptance Criteria

- [ ] Review lists of designees from each agency to determine who may already be a User
- [ ] Identify and communicate pre-work for each user, such as setting up Login.gov with the registrar
- [ ] Configure each portfolio in the Django Admin, with the designated users set up within those portfolios
- [ ] Set up onboarding scheduling for designees to walk them through the pages they'll see, information, and any questions they may have

**Comment by vickyszuchin** [comment]
In-progress: the ticket will move over at noon EST on Day 1 (Wednesday) to the new sprint.

**Comment by katypies** [comment]
Closing this ticket out ✅ . We'll continue to work on onboarding new federal agencies but capture and track that separately since it's operational.
