### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2889]
### Issue description

We have a handful of dependabot PRs that are cluttering up our PR tab and want to both update all dependencies at once and close these out. To do this we can just follow our documented process for updating dependencies to update everything in one go. We should then be able to close out the dependabot PRs.

### Acceptance criteria

- [ ] Follow the[ instructions](https://github.com/cisagov/manage.get.gov/blob/main/docs/operations/runbooks/update_python_dependencies.md) to update all the dependencies at once
- [ ] handle any errors that occur
- [ ] Close the dependabot PRs currently open

### Additional context

Note, most likely there should not be any errors as the current dependabot PRs are all passing checks.

**Comment by h-m-f-t** [comment]
I agree – let's do this next sprint. Will this include https://github.com/cisagov/get.gov/pulls?

**Comment by abroddrick** [comment]
@h-m-f-t good call out. No, that was not the intent. We should have another ticket to just update all of the ones on get.gov

**Comment by abroddrick** [comment]
Just looked at those closer and saw they actually are doing dependency checks on beta, not main, so I made [this ticket ](https://github.com/cisagov/get.gov/issues/319)for next sprint so we can get fresh dependabot updates. CC: @lizpearl
