### ISSUE TITLE
Dev Practices documentation

### ISSUE THREAD

**Issue by erinysong** [cisagov/manage.get.gov#2898]
### Issue description

On 9/30 engineering huddle, we decided to consolidate team practices into a dev-practices folder. Currently this folder includes code-review.md which includes PR best practices that we moved from our PR template in #2140. Since `code-review.md` also includes coding best practices from our PR template, our 2 viable options are:

1. Turn code-review.md into a general dev standards page (example: [CCAO data handbook.md](https://github.com/ccao-data/wiki/blob/master/Handbook/Handbook.md)) which has a PR review section and coding standards section.
2. Split code-review.md into code-review.md with PR practices and code-standards.md

### Acceptance criteria

- [ ] Choose one of the above options to organize our code review and coding practices in our dev-practices folder.
- [ ] Document team coding practices in dev-practices. Possible examples: naming conventions, front-end practices, how to write good comments. 
- [ ] Present changes at eng huddle and move forward after feedback.

### Additional context

Consider adapting contents of [conventional comments guide](https://conventionalcomments.org/)

**Comment by h-m-f-t** [comment]
@erinysong, does this issue supplant #2870? They seem closely related but I'm unsure of your intent.

**Comment by erinysong** [comment]
@h-m-f-t I think they can be combined into a single issue - this was an action item from eng huddle and I forgot I made an identical ticket basically covering the same issue 🤦‍♀

**Comment by erinysong** [comment]
Closing issue - duplicate of #2870
