### ISSUE TITLE
Create Workflow to Clone Staging to Sandbox

### ISSUE THREAD

**Issue by Matt-Spence** [cisagov/manage.get.gov#2901]
### Issue description

We have been investigating how to best create an easily accessible backup of Stable, as well as how to enhance our testing capabilities on staging. One way to accomplish both of these goals is to regularly backup stable to staging using a github workflow that clones the database in stable to staging at regular intervals (cloud.gov has suggested we do this not more than once a day). The way this is proposed to work is that we will temporarily share the staging rds database with the Stable Space, then bind it to a temporary docker application created in Stable. Then, we can use the [cg-manage-rds](https://github.com/cloud-gov/manage-rds) tool to clone the database **from** stable **to** staging.

Before we do anything on Stable, however, we want to test the idea on Staging. Once we have proven out the idea on staging, we can edit the resulting workflow to target stable. 

### Acceptance criteria

- [x] Claim another sandbox **other than development**  that can be used alongside Staging.
- [x] Create a new workflow that:
    - [x] Runs hourly
    - [x] Shares the other database with the Staging space
    - [x] clones the database from staging to the other sandbox database
    - [x] cleans up all changes
- [x] Also, it would be nice to have a standardized nomenclature for referring to the two databases (e.g. Target vs Origin, Old vs New, etc). Define how we should refer to the two databases so that we can avoid confusion when discussing the workflow.
- [x] After the workflow has been merged, check that staging and the target database are working properly at least 3 different times, two of which should be done when the workflow is running.

### Additional context

NOTE: Due to the final AC, the PR for this will need to be made **without** "Resolves #2901", as the ticket won't technically be complete when the PR is merged.

Most of this can be accomplished simply using the cloudfoundry CLI. For reference, you can find how to share a service [here](https://cloud.gov/docs/deployment/managed-services/#sharing-service-instances), how to create an app [here](https://cloud.gov/docs/deployment/deployment/), and how to bind services [here](https://cloud.gov/docs/deployment/managed-services/#bind-the-service-instance). See below for an example of how this works:

```
# target the sandbox space
cf target -s [sandbox space name]

# list services in sandbox
cf services

# share the sandbox db with the Staging space
cf share-service [database service name from previous command] -s Staging

# target the Staging space
cf target -s Staging

# install the cg-manage-rds tool
pip install git+https://github.com/cloud-gov/cg-manage-rds.git

# clone from staging to the sandbox
# NOTE: the included options will drop the target database before restoring
# if you want to test without dropping the target, remove the options
cg-manage-rds clone  --roptions "--clean" [staging db service name] [sandbox db service name]

# delete the local copy of the backup that gets created
rm db_backup.sql

# target the sandbox space
cf target -s [sandbox]

# un-share the sandbox from Staging
cf unshare-service [sandbox db name] -s Staging
```

### Links to other issues

- Relates to #2724
- Blocks #2903

**Comment by abroddrick** [comment]
Closing due to it being tested and working
