### ISSUE TITLE
Edit Workflow to Backup Stable to Staging

### ISSUE THREAD

**Issue by Matt-Spence** [cisagov/manage.get.gov#2903]
### Issue description

We have been investigating how to best create an easily accessible backup of Stable, as well as how to enhance our testing capabilities on staging. One way to accomplish both of these goals is to regularly backup stable to staging using a github workflow that clones the database in stable to staging at regular intervals (cloud.gov has suggested we do this not more than once a day). The way this is proposed to work is that we will temporarily share the staging rds database with the Stable Space, then bind it to a temporary docker application created in Stable. Then, we can use the [cg-manage-rds](https://github.com/cloud-gov/manage-rds) tool to clone the database from stable to staging.

A version of this workflow backing up staging to a sandbox should have been created as part of #2901. Now that workflow needs to be edited so that it clones from stable to staging.

### Acceptance criteria

- [ ] The database backup workflow now clones from stable to staging and to litterbox
- [ ] check at least 3 times when this flow is running and verify there are no errors, be sure to check the logs at this time.

### Links to other issues

- Blocked by #2901

**Comment by vickyszuchin** [comment]
Moved all "In progress" sprint 57 tickets to the current sprint (sprint 58), per guidance.
