### ISSUE TITLE
Arrow position on active header of sortable table columns

### ISSUE THREAD

**Issue by rachidatecs** [cisagov/manage.get.gov#2910]
### Current Behavior

<img width="631" alt="Screenshot 2024-10-04 at 11 29 11 AM" src="https://github.com/user-attachments/assets/e2cd9b7d-9d0d-4c3f-84bc-5614c808b034">
 The position of the arrow icon on the active header should match the position of the arrow icon on the inactive header.

### Expected Behavior

 The position of the arrow icon on the active header should match the position of the arrow icon on the inactive header.  Note, that in the picture the inactive headers have the arrow directly to the right of their title. 

All tables should be updated (org model and non org model) so that this expected behavior is met. 
### Steps to Reproduce

1. Click sort on a dynamic table header

### Issue Links

- Complete as part of #3165

**Comment by h-m-f-t** [comment]
@rachidatecs, what's "match the position" mean in your comment?

**Comment by h-m-f-t** [comment]
This seems like a nice thing to do and also a small?

**Comment by Katherine-Osos** [comment]
@rachidatecs Can you confirm that making this change will update the arrows for all tables—in org model and non-org model?

**Comment by abroddrick** [comment]
@Katherine-Osos I agree that we should add that as an AC here
