### ISSUE TITLE
Preparation for discovery interview with city org types

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#2929]
### Issue description

Now that we've decided to open up m1/m2 to our first city, we should prep our current materials for some discovery conversations with these org types. We have a lot of material created already and prototypes prepped, but we should spend a little time honing them and making sure we have are ready for any upcoming conversations. 

### Acceptance criteria

- [ ] review current materials and note any changes/updates needed
- [ ] Make updates and prep needed materials to set us up for future conversations with city org types

**Comment by Katherine-Osos** [comment]
Closing - this is no longer needed.
