### ISSUE TITLE
Create our Web metrics plan

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/manage.get.gov#293]
Plan for web metrics including internal/external search and implementation of DAP, GA4, google tag manager.

Acceptance Criteria:

- [x] Sufficiently [detailed list of all MVP metrics to track](https://docs.google.com/spreadsheets/d/1jEI2Vuy76HnRQoFnV5HbFrKrvlsbU07iWz7wTt2RZDQ/edit#gid=0).
- [x] ALL issues/tickets created and labeled to implement this plan.

---------
Related to #512, #513, #1320  

Reference: https://github.com/cisagov/getgov/blob/main/docs/product/product_strategy.md
Additional refs: 
* [Some indicators we want to track](https://docs.google.com/document/d/1BSxRAt3Z7-IdFLQUKfLDTksQigWXpCrAFrNBBYgtm5s/edit#heading=h.1fob9te)
* [Analytics thoughts](https://docs.google.com/document/d/1FIGZwVhH2VAK5_y-i5jycGYfggqMKc49yaLmo-6xUwY/edit)

**Comment by kitsushadow** [comment]
To discuss with further refinement
Google console log, google tag manager, submitting sitemaps and more

**Comment by kitsushadow** [comment]
ToDo: Separate DAP as MVP vs GA4 and Google tag Manager @kitsushadow

**Comment by michelle-rago** [comment]
@h-m-f-t @PaulKuykendall I think the next step for the [metrics plan](https://docs.google.com/document/d/177eujxWbkDBXOu3VYtSCqYgqM40nD7tc1oXbkh8v1M4/edit) is to validate that these are the metrics we want to track, prioritize them, and to verify that we can get them.
