### ISSUE TITLE
Update Domain Requests Django admin view

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#2934]
### Issue description

For org and non-org domain requests we want to change the layout and add in more conditional logic to show and hide fields. When the org model flag is on we want to show the fields that are relevant to the org model, such as requested suborganization and portfolio, but hide those orgmodel only fields if the org model flag is not on. 
[miro mock-up](https://miro.com/app/board/uXjVKAEDJB4=/?moveToWidget=3458764603003059103&cot=14)

[miro providing more information about the conditional fields and what's been moved](https://miro.com/app/board/uXjVKAEDJB4=/?moveToWidget=3458764603003059156&cot=10)

### Acceptance criteria

- [ ] Follow the miro mockup to move fields and display some fields conditionally note this applies to org and non-org requests
- [ ] ensure all annotations and comments on the two miro mockups are addressed
- [x] Show series of dashes if a portfolio hasn’t been selected, and do the same with suborganization. (portfolio field, suborg field)
   - Copy the style present on some of the non-select2 fields, like state_territory
- [x] The "suborganization" field should only appear if a Portfolio has been selected; display should be conditional.
- [x] The "suborganization" field should only show suborgs associated with the selected portfolio.
    - "Associated" in this context means that the dropdown list should only return suborganizations with the current portfolio.
- [x] Requested suborganization city/ state should show conditionally if the requested suborganization field is filled in

The below are annotations from the miro mockup, please refer to the miro for pictures. If design adds additional annotations/ comments not listed here they should still included as in scope:
-  [x] For all requests (portfolios AND non-portfolios): Move these fields to a new section with blue-bar that reads "Requested by":
    - Portfolio
    - Suborganization
    - Creator
- [x] For all requests (portfolios AND non-portfolios): Move "Approved domain" to appear directly below the "Status" field. Should only display if the status is "Approved."
- [x] Senior official
    - This should pull from the corresponding Senior Official for the portfolio
    - Display role, email, phone below the name (as usual)
   - For superusers AND analysts ... this should be "view only" but the name should **link** to the corresponding Senior Official record.
- [x] Hide the following fields for portfolio requests:
    - Other employees
    - No other contacts rationale
    - CISA regional rep first name
    - CISA regional rep last name
    - CISA regional rep email
- [x] For non org model requests, Cisa regional information should show in the Organization section just at is does currently.
- [x] For the Type of Org / Org name and mailing address sections on **portfolio** requests
   -  These two sections should pull from the corresponding Portfolio record for the selected agency.
   - Only display the fields that are displayed on the Portfolio page; hide the other fields (e.g. hide "Election office" and "Tribe name").
    - For superusers AND analysts ... this info should be "view only" and the values link to the corresponding Portfolio record.
    - requested suborg contained in this same section as suborganization, right below suborganization. suborganization city and state should also go below the requested sub org
- [x] The following should be links for Org model requests because they should be pulling from the portfolio (and thus you should edit the portfolio not the domain request if change is desired). All links below should take a user to the portfolio page:
    - federal agency
    - federal type
    - organization type
    - organization address 
- [x] For **non federal** requests (and either part of a portfolio or not): always show organization name in the Organization section at the top
- [x] For **non federal** domain requests (either part of portfolio or not), hide the federal fields (federal type & agency)
- [x] If org type **is** "federal" hide organization name **ONLY** if a portfolio is selected. Otherwise allow for both organization and federal agency to show.

### Additional context
Note: This may not be a 5 complexity wise, but with the sheer size of changes and refactors it seems fitting to give it a 5, as whoever takes this should take their time to double check ACs and the miro.

### Links to other issues

- [ ] blocked by #2852 
- [ ] blocks #2867

**Comment by h-m-f-t** [comment]
Calling this ready now that refinement is removed.
