### ISSUE TITLE
screen reader output

### ISSUE THREAD

**Issue by AnnaGingle** [cisagov/manage.get.gov#2959]

**Comment by h-m-f-t** [comment]
(@AnnaGingle, is this a draft issue or...?)

**Comment by AnnaGingle** [comment]
@h-m-f-t This is a child issue of [#2958](https://github.com/cisagov/manage.get.gov/issues/2958). I was teaching Samiyah how to create issues in github. I thought closing the parent would close the sub-issue. Good catch!
