### ISSUE TITLE
Finalize Account and Zones discovery

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#3000]
### Issue description

In #2873, the discovery for Accounts and Zones, we found that we have some follow on tasks that were best done by someone who has not spent a lot of time in the document before.  The goal of this is to close of the discovery regarding Accounts and Zones and have the document act as an example of how we want technical discovery to look going forward. 

### Acceptance criteria

- [ ] Copy the current account, zone and setup technical discovery documentation to [this new tab](https://docs.google.com/document/d/1Yq5d2M3MgM2vPhUBZ0k5wOmCQst4vND9-2qEZ55-h-Y/edit?pli=1&tab=t.xtdzq83a5xj) in the technical discovery doc **and** adjust the format to now use the new template created in #2998 
- [ ] _Where possible_ condense the current discovery information using concise language and bullet points
- [ ] Evaluate the current options provided and propose a new solution
- [ ] Add a flow diagram of the setup steps. This diagram should include the communications between the new service and the 3rd party API and the new service and our existing software.
- [ ] Adjust the miro database model diagram if needed.

### Links to other issues

- blocked by #2998

**Comment by erinysong** [comment]
[Accounts and Zones doc](https://docs.google.com/document/d/1Yq5d2M3MgM2vPhUBZ0k5wOmCQst4vND9-2qEZ55-h-Y/edit?pli=1&tab=t.xtdzq83a5xj#heading=h.541waiws5byv) added as a tab to original DHS hosting research doc
