### ISSUE TITLE
New user permissions not added by running fixtures

### ISSUE THREAD

**Issue by lizpearl** [cisagov/manage.get.gov#3012]
### Current Behavior

Recently a couple of new users were added to our current [user fixtures](https://github.com/cisagov/manage.get.gov/blob/main/src/registrar/fixtures/fixtures_users.py)

On some of the sandboxes, loading the data resulted in an error so the newly added users were unable to login.  Recreating the db from scratch works but we don't want to do this on sandboxes where we want to preserve the data.

Some discussions about the issue:
- [Original request to add to user fixture](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1729262801560299) 
- [Thread about errors in running the fixtures in the development sandbox](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1729697696403319)
- [Thread about errors in other sandboxes](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1729711250598149). [Additional debugging was added ](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1729891044401619?thread_ts=1729711250.598149&cid=C05BGB4L5NF)
- [500 error on hotgov](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1729870462706859)
- [More discussion on hotgov](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1729888097423649)

### Expected Behavior

- Running fixtures should exit successfully
- New users should have access to `/admin` after fixtures are run with **both** their analyst and super user accounts (if applicable)

### Steps to Reproduce

Run fixtures on the `ky` sandbox.  The `manage.py/load` command should fail, and the new users do not have permission for '/admin'

### Additional Context
Note: you could also test this bug out by starting on a freshly reset sandbox that has fixtures freshly loaded and then add a fake user to to fixtures (both analyst and superuser). Re run fixtures again and see if everything runs fine.

**Comment by rachidatecs** [comment]
NOTE:  We're only addressing issues where the sandbox is error free and it might not address the original issue of fixing the development sandbox.
