### ISSUE TITLE
Complete Dependabot dependency updates

### ISSUE THREAD

**Issue by abroddrick** [cisagov/manage.get.gov#3065]
### Issue description

In this repo's [security](https://github.com/cisagov/manage.get.gov/security/dependabot) tab, we have several updates that have come in for packages we use. Let's update these.

Some of these updates are for the same package; only the most recent upgrade needs to be applied. For instance, there are several django updates that call out updating to 4.2.14 and then later ones mention 4.2.15. We'll just go to the latest version.

### Acceptance criteria

- [ ] All security updates are applied to our code base; there should be 0 security updates in this tab when is completed.
- [ ] If an update has already been applied to our system and is now non-applicable/ already resolved, just dismiss the alert as "inaccurate".

**Comment by erinysong** [comment]
Can I get confirmation that we can dismiss the following warning:
- [49: PostCSS line return parsing error](https://github.com/cisagov/manage.get.gov/security/dependabot/49) - postcss already recommended stable version 8.4.31 in main

And dismiss or not resolve the following warning:
- [80: Uncontrolled resource consumption in braces](https://github.com/cisagov/manage.get.gov/security/dependabot/80) - The braces vulnerability are from dependencies in @uswds/compile. We can't resolve this vulnerability until it's resolved on their end.

**Comment by erinysong** [comment]
@lizpearl 
Can I get confirmation that we can dismiss the following warning:
[49: PostCSS line return parsing error](https://github.com/cisagov/manage.get.gov/security/dependabot/49) - postcss already recommended stable version 8.4.31 in main

And dismiss or not resolve the following warning:
[80: Uncontrolled resource consumption in braces](https://github.com/cisagov/manage.get.gov/security/dependabot/80) - The braces vulnerability are from dependencies in @uswds/compile. We can't resolve this vulnerability until it's resolved on their end.

**Comment by h-m-f-t** [comment]
@erinysong it's unclear to me that the first acceptance criteria was met here. Can you explain why that initial link still has several vulnerable dependencies? 

If sensitive, feel free to share  elsewhere. cc: @lizpearl @abroddrick

**Comment by erinysong** [comment]
thank you for the heads up @h-m-f-t. hm it looks like duplicate warnings got made for each dependabot vulnerability. For example open warning [116](https://github.com/cisagov/manage.get.gov/security/dependabot/116) is identical to the resolved warning [117](https://github.com/cisagov/manage.get.gov/security/dependabot/117). Just cross checked with every open dependency and aside from the exceptions listed in the issue PR, each one has an identical vulnerability warning marked as fixed.

I would learn resolving the duplicate vulnerability warnings that didn't get marked fixed since updating our dependencies should resolve them but also open to other suggestions

**Comment by h-m-f-t** [comment]
Thanks Erin! That makes sense.

**Comment by erinysong** [comment]
update - I was wrong and the open issues were actually because the warnings were being caught in different files. Manually updating our Python dependencies should fix this and will do that right now. Thank you @lizpearl for finding the source!

**Comment by erinysong** [comment]
Open Django warnings have been resolved in #3277 - thank you for bringing this to attention!
