### ISSUE TITLE
Improve dropdown menu for names of federal agencies in request form

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/manage.get.gov#337]
The list of federal agencies is correct but not complete. We should ensure it's universally correct (even if it means we're the source of truth) and make "Organization" (which is basically the agency subcomponent) dependent on the "Agency" selection.

**Acceptance Criteria**

- [x] Review all sources add add any missing agencies.
- [ ] Make sub-agency a controlled list, sourcing from the data above.
- [ ] Make "Organization" dependent on agency selection

**Comment by michelle-rago** [comment]
Examples in #283 

Other examples of agency lists:
[10x form](https://feedback.gsa.gov/jfe/form/SV_1Im8dTPnjnV3HpP)
[USAJobs search results](https://www.usajobs.gov/Search/)
Non-hierarchical list https://www.usa.gov/federal-agencies includes cabinet departments and sub-agencies; sub-agencies also appear on agency pages https://www.usa.gov/federal-agencies/u-s-department-of-homeland-security

**Comment by michelle-rago** [comment]
Ideally we would have the federal agency and sub-agency drop-downs on a separate screen. All users would get the same "Organization name and mailing address" screen.

**Comment by michelle-rago** [comment]
The list of federal agencies needs to be improved. It includes generic terms like "Legislative branch." 

Ideally, the list of agencies and sub-agencies would be generated based on the federal branch a user chooses.

**Comment by h-m-f-t** [comment]
I forgot this existed, which is a pretty good canonical (but aged) take https://www.whitehouse.gov/wp-content/uploads/2018/06/app_c.pdf

**Comment by michelle-rago** [comment]
The USAGov folks maintain a list to populate https://www.usa.gov/agency-index. We briefly talked with them about reusing their data. We can pick that back up if there's interest.

**Comment by abroddrick** [comment]
@PaulKuykendall I added refinement on here if this is truly MVP we should start discussing this one, it related to the other ticket about making federal agency a table.

**Comment by Katherine-Osos** [comment]
@h-m-f-t I think this update might be covered in work we're doing for Org Model. Can you verify if this ticket is still needed? 

cc: @PaulKuykendall @katypies

**Comment by h-m-f-t** [comment]
I agree that we're solving this via the org model. Let's close this.
