### ISSUE TITLE
Pre-load information from login.gov into the Your Contact Information

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/manage.get.gov#404]
**Acceptance Criteria**

- User Story: As a domain request applicant, I want my information from login preloaded into the my contact question so that I don't have to load information the system already knows
- Update the the "your Contact" question to preload the information from login.gov

**Comment by calerubensteingsa** [comment]
Background:

“Your contact information” isn’t prefilled, although the copy suggests it should be
A UserProfile is a type of Contact object, but the contact object in the application is not associated with the logged in user’s UserProfile.
Details pulled from Login.gov are stored in User, not in UserProfile
This is so that an un-user-editable record is preserved while allowing users to update contact data as needed
Architected right for what it is trying to do but some changes needed to accomplish https://github.com/cisagov/getgov/issues/404

**Comment by h-m-f-t** [comment]
Outmoded by #1807
