### ISSUE TITLE
Add dropdown for  Type of work question

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/manage.get.gov#447]
**Acceptance Criteria**

- [ ] Develop controlled list for "Type of work" question

Slack thread: https://gsa-tts.slack.com/archives/C03QM0JGSQG/p1677702708763699

Related to https://github.com/cisagov/getgov/issues/446

**Comment by h-m-f-t** [comment]
(see [comment](https://github.com/cisagov/getgov/issues/446#issuecomment-1696440186) in #446)
