### ISSUE TITLE
Email Content: Domain is live

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/manage.get.gov#473]
- [x] [Draft email](https://docs.google.com/document/d/151QMKvzW_pOSMuc52yso0UOofGupzpshnYzhV2yLXVU/edit#) @michelle-rago

**Comment by abroddrick** [comment]
linking to #731 and marking as discovery as "live" is up in the air. Do we still want to send the email now that we are considering Live not a state for application

**Comment by h-m-f-t** [comment]
Good call. I think this is a useful future task when we begin actively checking whether the domain is correctly added to DNS, but not something we'll do now.

We should see if the language in prior emails is sufficiently "final" (to be clear that we're not reaching out again) now that we're removing this from the notification set. (cc: @gabydisarli, @Katherine-Osos, @brooksr4)

**Comment by Katherine-Osos** [comment]
@h-m-f-t I read through all the status-change emails in the content folder and none of them mention contact after the domain is approved.

**Comment by h-m-f-t** [comment]
This is a later task because we'll wont be checking domain liveness at MVP, only that a domain application was approved.

**Comment by katypies** [comment]
This is useful, but we're not going to tackle this now.
