### ISSUE TITLE
Make the /availability endpoint available at {beta.}get.gov so potential users can check a domain's availability

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/manage.get.gov#476]
As a potential registrant, I want to see whether the domain I want is available so that I can know if I should make a different choice.

Implements #561 

AC

- [ ] Match designs in [this Figma link](https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&node-id=1813%3A27518&mode=design&t=3grPKvKJpmrKHlIq-1)
- [ ] Updated tests accordingly

🔄 : #561

**Comment by igorkorenfeld** [comment]
Adding some additional context: 

Potential registrants may want to check if a domain name is available before they start their domain request or even have a Login.gov/get.gov account. Currently the availability api is only accessible within the application which requires an account. We would like to make the availability api publicly available. However we should remain aware of the risks of maintaining the public api.

**Comment by abroddrick** [comment]
where would this go?

**Comment by PaulKuykendall** [comment]
This is redundant with #561

**Comment by PaulKuykendall** [comment]
Refined 8/24. Clarified language around WHERE this is being made available. This is MVP for New Applications.

**Comment by therealslimhsiehdy** [comment]
[Research document ](https://docs.google.com/document/d/1d5iJ307tK8uMNH5jhrCw_Sc58mSTYuTTzUsPhlpb1RM) on the Domain availability UI + API addition

**Comment by erinysong** [comment]
Subtickets required for edge cases:

- [ ] long domain strings
- [ ] www. case 
- [ ] update API base url to stable when cloudflare migrates data
- [ ] clean .gov from alert when added in domain input

**Comment by erinysong** [comment]
[PR#100 in getgov-home for additional context
](https://github.com/cisagov/getgov-home/pull/100)
Handle edge case of including [www](http://www/). in the search input. This is most likely best handled by updating the manage.get.gov's availability endpoint to handle the [www](http://www/). prefix when parsing arguments, similarly to how the API handles the .gov suffix.

**Comment by erinysong** [comment]
[PR#100 in getgov-home for additional context
](https://github.com/cisagov/getgov-home/pull/100)

Update API base URL from staging link to stable link after Cloudflare migrates its data 11/15/2023.
Currently beta.get.gov pulls data from the registrar's staging environment (https://getgov-staging.app.cloud.gov/api/v1/available/) because the registrar's stable environment API is not accurate until Cloudflare migrates data on Wednesday, November 15, 2023. Once Cloudflare updates its migrations, we will need to update the base URL to the stable environment (https://manage.get.gov/api/v1/available/

**Comment by erinysong** [comment]
[PR#100 in getgov-home for additional context
](https://github.com/cisagov/getgov-home/pull/100)
 Remove the redundant .gov added when a user inputs a domain name with .gov into the search input.

**Comment by h-m-f-t** [comment]
@erinysong, thanks so much for creating these new issues! Really excellent work.

**Comment by h-m-f-t** [comment]
Completed at https://github.com/cisagov/getgov-home/pull/100
