### ISSUE TITLE
Redirect logout to {beta.}get.gov info site

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/manage.get.gov#489]
Now that we have the `cloud.gov Pages` site setup at get.gov, we should redirect logout actions to that site. 

As a logged-in user of the registrar
I want to be redirected to the new get.gov informational site when I log out
So that I stay in the .gov experience rather than login.gov

AC:
- [ ] **Given** a logged-in user on the .gov registrar, **when** I logout and also choose "Yes, sign out of login.gov," **then** I am redirected to the get.gov as an unauthenticated user.
- [ ] Language on login.gov screen reads "Do you want to sign out of Login.gov and return to **get.gov**?

![Image](https://github.com/cisagov/manage.get.gov/assets/62573986/9964a4dd-03db-4044-9e7e-55f6503c9748)

### Additional Context:
Currently, if we select to "return to the .gov registrar," we go back to login.gov.... and if we select to go back to the .gov registrar, we get a nasty 401 error because we aren't logged in anymore.

### Links to related issues
🔄 #1509

**Comment by h-m-f-t** [comment]
@PaulKuykendall, the change needed to resolve this issue happens in manage.get.gov (see https://developers.login.gov/oidc/logout/), so I've changed the "Product/Component" value from `(beta.)get.gov` to `manage.get.gov`.

**Comment by h-m-f-t** [comment]
The docs I shared above look like the right answer, but @abroddrick should confirm before we get to next sprint. 

I'm fairly certain that if we resolve this, we also resolve https://github.com/cisagov/getgov-home/issues/137

**Comment by abroddrick** [comment]
confirmed that this documentation seems like the right approach and I agree it may resolve 1509 as well

**Comment by neilmb** [comment]
I think that the least disruptive setting is to use Django's `LOGOUT_REDIRECT_URL` setting and keep the Login.gov configuration as redirecting to the current URL of https://manage.get.gov/openid/callback/logout/. That keeps the staging and production Login.gov configurations most parallel. Asking on Slack if we can just use one setting for all of our environments.

**Comment by neilmb** [comment]
In the Login.gov configuration, there is only one "Friendly name" that is used on logging in and logging out.

<img width="747" alt="Screenshot 2024-01-03 at 8 49 43 AM" src="https://github.com/cisagov/manage.get.gov/assets/443389/8186be7e-9e08-4ed0-8f49-cd2a18ab45b4">

We won't be able to make the logout message say "Do you want to sign out of Login.gov and return to get.gov" without making the login message say "get.gov is using Login.gov to allow you to sign in to your account safely and securely."

@h-m-f-t @michelle-rago @Katherine-Osos Is this a content change that we want to make for login and logout?

**Comment by neilmb** [comment]
Slack discussion supports changing the friendly name to "get.gov" for both login and logout. https://gsa-tts.slack.com/archives/C05BDEA3C11/p1704294022815889
