### ISSUE TITLE
Confirm analytics are operational after request re-opening

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/manage.get.gov#511]
**Acceptance Criteria**

- [x] Confirm Google Search Console is operational after the get.gov site is migrated
- [x] Confirm DAP is working as expected (DAP can only be added to public sites)
- [x] Confirm Cloudflare analytics is operational

Related to #293

**Comment by michelle-rago** [comment]
Consider adding a separate version of Google Analytics for get.gov and manage.get.gov.

**Comment by PaulKuykendall** [comment]
This should be fairly simple.. would like to get this checked off, soon.

**Comment by PaulKuykendall** [comment]
@rachidatecs - can you check this out?
