### ISSUE TITLE
Implement DAP on {beta.}get.gov website

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/manage.get.gov#512]
**Acceptance Criteria**

- [x] Add this DAP code to every beta.get.gov public page
`<script async type="text/javascript" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=DHS&subagency=CISA" id="_fed_an_ua_tag"></script>`

[Instructions for adding DAP code](https://digital.gov/guides/dap/add-your-site-dap/#appropriate-placement-of-the-dap-script-tag)

Related to: #293

**Comment by kitsushadow** [comment]
Refinement note: Discuss how to implement on the different pages.

**Comment by h-m-f-t** [comment]
Completed via https://github.com/cisagov/getgov-home/pull/99
