### ISSUE TITLE
Implement Free Version of Google Analytics on get.gov and Registrar

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/manage.get.gov#513]
**Acceptance Criteria**

- [x] Procure free version of Google Analytics
- [ ] Implement on get.gov, beta.get.gov, and manage.get.gov

Instructions from Google: "Below is the Google tag for this account. Copy and paste it in the code of every page of your website, immediately after the `<head>` element." 

`<!-- Google tag (gtag.js) --> <script async src="https://www.googletagmanager.com/gtag/js?id=G-PZ5QSP6QPL"></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-PZ5QSP6QPL'); </script>`

Related to #293

**Comment by michelle-rago** [comment]
It's the `<head>` element. Weird! Sorry!
