### ISSUE TITLE
Investigate how to deal with users who have multiple email addresses on their Login.gov account

### ISSUE THREAD

**Issue by neilmb** [cisagov/manage.get.gov#523]
A single user account on Login.gov can have multiple email addresses associated with it. Currently, we only deal with the single email address that Login gives us (that's the email they used when they logged in that time) but we probably want to handle domain invitations for all of the email addresses on that account.

For this ticket, we should consider the situation where a user has more than one email address on their account and decide what we want the user experience to be, then create tickets for implementing that behavior in our Django/OIDC user code.

A/C: 
- [ ] Decisions to be documented and summary provided to the Product team  who have final approval
- [ ] Walkthrough and capture what happens to a user who has multiple emails.
  - [ ] Use Case: When a user "registers or logs in" for the first time.
  - [ ] Use Case: When an action that would send an email is executed for a user.
  - [ ] Use Case: When a user edits their profile
  - [ ] Other use cases as needed
- [ ] make dev tickets per investigation

Timebox to 1 day until you get input from Product team. 

### Additional Context
Alysia's current thoughts:
we can get [all_emails](https://developers.login.gov/attributes/) from login.gov and store in the User object. In the User object the field emails should be something like `models.ArrayField(models.CharField(max_length=100),  default=list)`. We could keep email as well and let email refer to the email which we will send notifications to the user and which they see on their user profile. 

For this we just need to walk through the code and see all the places we are using a users email (such as domain invitations) and add those as cases here. Then troubleshoot how we want to handle them, as there are several options. Best to have a couple people on this for brainstorming.

**Comment by abroddrick** [comment]
Tested this and currently, if a user already has a login.gov account but a domain invitation is sent to their other email, then they will not be able to see this domain as viewable.

**Comment by h-m-f-t** [comment]
Given an email exchange with Login in February, I anticipate this issue is also a blocker to PIV-only auth working correctly.

**Comment by h-m-f-t** [comment]
This issue came up in the context of the org model + #1807; see [Slack thread](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1712084055142789?thread_ts=1711127406.745849&cid=C05BDEA3C11).

**Comment by PaulKuykendall** [comment]
In 5/6/24 refinement: "I think we detect multiple emails > we ask them our profile questions > we get the email we want > we nudge them to remove extraneous email addresses from Login" - Cameron

**Comment by h-m-f-t** [comment]
@abroddrick can you link to (or provide a comment on) how this has been resolved?

**Comment by abroddrick** [comment]
As a result of this ticket in sprint 45, #2198 was made. I just linked 2198 to this research ticket for better tracking. Good call out Cameron!
