### ISSUE TITLE
Email Content: Domain information has changed

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/manage.get.gov#536]
- [x] [Draft email ](https://docs.google.com/document/d/1L2CSQXX5Wa_v8ASqJxLP147xH_9pASs-xUIthvRSaZ4/edit#)@michelle-rago 

**Acceptance Criteria**

- Email notification alerting the submitter that their domain information change has been successful

**Comment by h-m-f-t** [comment]
(The engineering ticket for this has not been created.)

**Comment by katypies** [comment]
This is likely to be solved in a different way with notifications.
