### ISSUE TITLE
Design: Inform users of .gov requirements before starting a new domain request (previously known as preamble)

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/manage.get.gov#547]
Domain requestors should be aware of certain requirements (e.g., that they need a verified Login account) and other information before logging in. 

### Acceptance Criteria
- [x] Identify what needs to be conveyed to users. [Draft content](https://docs.google.com/document/d/15FpRLKXGeeNJ5D8uCu1YtRDZSWN5ZrJPKXJV4tCY6fw/edit#heading=h.cldogb82du8p). 
- [x] Determine how users should be presented with this content (e.g. new page, modal) and create/update Figma design. Flows from get.gov and manage.get.gov are in [this Mural](https://app.mural.co/t/gsa6/m/gsa6/1701893071504/3b10ecf79684c8e3a1387d7fe5665b58f3c156fa?sender=michellerago0372).

### Additional Context

Dev tickets:[147](https://github.com/cisagov/getgov-home/issues/147), cisagov/manage.get.gov#1485

**Comment by abroddrick** [comment]
@gabydisarli , @brooksr4 or @Katherine-Osos has the question asked above "preamble appear before or after login" been answered by design? I am thinking after login. Also can someone link the figma or any user flow you had in mind for the preamble?

**Comment by Katherine-Osos** [comment]
@abroddrick That question has not been answered and is a blocker for anyone starting this work. The copy should probably be revisited after a decision is made, as well, to ensure it still makes sense. 

You could add it to the agenda for product huddle next week to discuss.

**Comment by abroddrick** [comment]
Okay I labeled it as refinement so no one accidentally pics it up.

**Comment by PaulKuykendall** [comment]
changed labels -dev +design

**Comment by gabydisarli** [comment]
added some additional details/links and ac

**Comment by gabydisarli** [comment]
@Katherine-Osos  can we change the title of this to _Design: inform users of .gov requirements before starting a new domain request?_ Since this is specific to that action. The way it reads now implies this would be shown to domain managers logging in as well and could even be mistaken for ticket #1144

**Comment by michelle-rago** [comment]
@h-m-f-t @Katherine-Osos If we have dev time to dedicate to this I think it will be achievable. I'll propose a flow for this in the next few days.

**Comment by gabydisarli** [comment]
design is done with some final decisions being made on content formatting. This is good to go!
