### ISSUE TITLE
Log registry actions to an audit table in the database

### ISSUE THREAD

**Issue by SSPJ** [cisagov/manage.get.gov#579]
Whenever a call is performed via EPP protocol, record the command and the logged in user who performed the command in the registrar database.

The existing audit table may be suitable or a new table may need to be created.

Where to insert the code? The Domain model or the EPPLibWrapper class may be the right place.

**Comment by PaulKuykendall** [comment]
@abroddrick @zandercymatics @dave-kennedy-ecs - Is this now obsolete/unnecessary? If so, please close. If not, please label "refinement" Thanks!

**Comment by abroddrick** [comment]
We are closing this as a won't do, with the caveat that we will be saving ds data in our database and ensuring that appears in Audit logs. At  that point all major epp changes will be logged in audit logs (public contact, dnssec, and name servers).
