### ISSUE TITLE
Bug: Applicant cannot advance past the other employees from your org question under certain circumstances

### ISSUE THREAD

**Issue by SSPJ** [cisagov/manage.get.gov#589]
On the "other employees" page of the domain application once a user enters data into the fields for contact and hits save. They cannot then erase all the data from the fields and advance. **Since this question is optional**, a user should be able to erase the data from the contact fields and save, effectively "removing" that contact. 

### Steps to reproduce
1. start a new domain request 
2. on the other employees from your org page, fill in all details for other contact 1. 
3. Hit save and continue
4. return to the other employees from your org page and erase all the data
5. Hit save and continue (this is where errors get thrown).

### Acceptance Criteria

- [ ] Once the data is erased, the user should be able to hit save and continue and then see the No other employees from your org page so they can explain why they are not providing a contact.
- [ ] No errors should show if they erase all the data and hit save and continue.

### Issue Links
🔗  to: #903 (this is a separate ticket for future work where a remove/delete contact button will be designed and implemented)

### Implementation note
On brief inspection, it looks like other forms use a "clean" function which will be triggered before is_valid. The OtherContactsForm may just need this clean function to set the values to be null as opposed to empty strings. There also should be a unit test to make sure if a user manually removes everything (effectively deleting the value) that the contact associated gets removed from the domain as well.

**Comment by gabydisarli** [comment]
I will make a new ticket for designing a button to remove extra contacts
