### ISSUE TITLE
Implement page-level redirects from legacy get.gov to new content

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/manage.get.gov#607]
Suggested [page-level redirects](https://docs.google.com/spreadsheets/d/1EeO_JDz7aD_XV0sgwSHP0JpZB_7c69ojcNzW873N5so/edit#gid=374195031)

**Comment by PaulKuykendall** [comment]
Needs additional information to guide the refinement vs live experience.

**Comment by PaulKuykendall** [comment]
FOR REFINEMENT: Do we clearly know where these changes will be made?? In DNS, or Jekyll?? @h-m-f-t

**Comment by PaulKuykendall** [comment]
Cameron working this out with Michelle.

**Comment by michelle-rago** [comment]
We are going to try implementing redirects with Cloudflare page rules.

**Comment by michelle-rago** [comment]
@PaulKuykendall @h-m-f-t Can you look at the few redirects I entered at https://dash.cloudflare.com/4ae8dbfda31c745ce889c30355a4c58e/get.gov/rules/redirect-rules. I added redirects 2-4. Let me know what you think. Thanks!

**Comment by michelle-rago** [comment]
All page-level redirects have been drafted in Cloudflare. They are set up for beta.get.gov for now. We'll remove the "beta" prior to launch (as per the checklist).
