### ISSUE TITLE
Deleting everything from a required contact field and submitting restores its previous content

### ISSUE THREAD

**Issue by neilmb** [cisagov/manage.get.gov#672]
### Current Behavior

On https://getgov-nmb.app.cloud.gov/domain/4/authorizing-official if I delete everything in the "Email" field and click "Save" to submit the form, then I see an error message that the email field is required, but the previous contents of the email field have been restored.

![Screenshot 2023-06-01 at 3 13 51 PM](https://github.com/cisagov/getgov/assets/443389/e778a19c-2435-4af2-a888-4c7f0e44df1d)

Which is confusing because the error message says that it is required, but it has put a value there.

### Expected Behavior

I think what I expected is for the field to be blank along with the error message.

### Steps to Reproduce

1. Go to an approved domain's authorizing official page.
2. Delete the contents of the email field.
3. Click "Save".

### Additional Context (optional)

I have a hypothesis that this is happening because of the way we have defined our fields on the Contact model and indicated that the field was required in our ContactForm, but that's just a guess.

**Comment by vickyszuchin** [comment]
Refinement notes (10/12/23):
1. Per Neil, this behavior is most likely from how Django handle forms on submission. Django error handling for invalid response is to revert to last saved value. This is the default behavior. 
2. The scope of this ticket should be expanded for handling of all fields, not just the email field.
3. Decision - not MVP

**Comment by PaulKuykendall** [comment]
gotta be obe by now
