### ISSUE TITLE
DISCOVERY: Use consistent domain request status labels

### ISSUE THREAD

**Issue by SSPJ** [cisagov/manage.get.gov#731]
A domain request goes through various stages / step on the way to approval / rejection.

Go through the Django application and the registrar site to make sure that the words being used for the different statuses of the domain request match the ones given in the table here: https://docs.google.com/document/d/1I4sx-z2pbxdehj2Skci_sFZQvV8gEKE-nLu1CxxvaGc/edit

This may be dependent on the outcome of #554 .

**Comment by h-m-f-t** [comment]
What's left to do in light of #964? Just the content updates?

**Comment by PaulKuykendall** [comment]
OBE
