### ISSUE TITLE
Update FSM ADR with discussions about FSM-Admin

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/manage.get.gov#733]
### Story

As a team we need to determine if we shall use FSM-Admin and update the according FSM ADR in github capturing the outcome from Engineering Huddle.

### Acceptance Criteria

- [ ] Document the resulting decision and discussion in the ADR

### Additional Context (optional)

[FSM ADR](https://github.com/cisagov/getgov/blob/main/docs/architecture/decisions/0015-use-django-fsm.md)

**Comment by PaulKuykendall** [comment]
@neilmb - can you take a quick look at this? Is it still relevant ? Thanks much

**Comment by PaulKuykendall** [comment]
Per Neil - closing as "won't do"
