### ISSUE TITLE
Design: allow users to delete domain requests they've started or withdrawn

### ISSUE THREAD

**Issue by SSPJ** [cisagov/manage.get.gov#735]
To respect user's privacy, we should enable the ability for users to delete domain applications before they have submitted them or after they have withdrawn them.

AC:

- [x] Complete design to address this
- [x] Dev tickets are created to implement this design, and linked to this design ticket.

Related to: #1482 (This ticket, 735, takes priority)
Relates to: #1574 (Dev ticket)

**Comment by h-m-f-t** [comment]
See comments at https://docs.google.com/document/d/1no29E2c9QWIHf_2wv3GCy6AotZ2_PVbIBiavKW-opxE/edit?disco=AAAA0mJIcAg
