### ISSUE TITLE
Get.gov (Info Site): Create plan for reviewing all content

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#771]
### Issue Description
Much of the content on the info site (unauthenticated public site) wasn't reviewed by a second person yet (i.e. only the content designer reviewed the pages). Need to ensure there aren't any grammar, formatting, or other errors. Also ensure the content is still accurate based on changes made to the registrar since it was first written.
- Identify all pages on the site and come up with a plan for review
- Create tickets for conducting the content review

### Acceptance Criteria
- Review plan created
- Tickets created for conducting the content review

### Issue Links
During this review, it may be good to identify links related to this story: https://github.com/cisagov/getgov/issues/766

**Comment by vickyszuchin** [comment]
Per Katherine, this ticket can be assigned to sprint 31.
