### ISSUE TITLE
Add more info about DNS hosting to get.gov

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#777]
### Story
As a registrant
I want more info about DNS hosting
so that I understand why it's necessary and how the process works.

### Acceptance Criteria
Approved verbiage related to DNS hosting has been added to Get.gov info site (unauthenticated public site).

### Additional Context
During user testing, there were multiple references to the challenges of DNS hosting. While CISA can’t suggest any providers, it’s worth exploring language that explains more of the process and steps a domain owner will have to take. Also, set expectations that a domain does not automatically mean DNS services or an easy connection.

**Comment by brooksr4** [comment]
This might relate to #894

**Comment by h-m-f-t** [comment]
There's a whole world in this issue! It's still necessary, but I'm going to close this because we'll create many content issues when we offer DNS hosting.
