### ISSUE TITLE
Content: Clarify next steps (after domain request submission) on the Manage Domain Request Page

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#778]
### Story

As a Registrant Applicant I want to understand what to expect after I have submitted my domain request application so that I can be prepared for what is to come.

![domainrequestforapplication01](https://github.com/cisagov/getgov/assets/107440934/d914e6ab-6ef2-4c79-8dc9-09212258da1c)

### Acceptance Criteria

The post-submission communication clearly helps applicants answer the following questions:

1. When will the first reach-out occur?
2. What happens if they doesn’t respond to CISA?
3. How can they come back and check the status of their application?
4. What's the workflow for review and approval?
5. Will the applicant see the stages and know how to react to each change in status?
6. What happens if they need to change the application as submitted?
7. What's involved in withdrawing a request?

Any updates should work in tandem with the email communication a registrant applicant receives post-submission. You can find that [email draft here.](https://docs.google.com/document/d/14PBLpFrXqxYDh2TU9Ucjh22jyECDCX6irC0wM8dJUdk/edit)

### Additional Context

To find the Manage Domain Review Page, go to Manage your domains, find the Active domain requests table, locate the application you want to manage and click the 'Manage' button. You will see a summary of your submitted request along with a button to withdraw the application.

### Issue Links
[Content draft for Manage your domains > Domain summary > Status: received
](https://docs.google.com/document/d/1XMc3RxozSaTKztTCZqLIkQL4FTUda2dOWW6S-0_VcTk/edit?usp=sharing)[Content draft for Manage your domains > Domain summary > Status: in review
](https://docs.google.com/document/d/1TTPCo0LOVJG-NSVSGgVpqWWz0kL01tpv_FJGIfhR1Qc/edit?usp=sharing)
🔄 Relates to: #770 Make sure that the language for both this page and the Confirmation Page are aligned

**Comment by brooksr4** [comment]
Below is some potential copy updates for this page. This in brackets are things that I don't know the answer to though

> What to Expect Next
> 
> Thank you for submitting your .gov domain request. Here's a brief overview of what comes next:
> 
> 1. Review Process: We're currently in the process of reviewing your domain request. This step typically takes around 20 business days, so we appreciate your patience.
> 
> 2. Stages of the Request:
> 
> Initial Review: Your request is currently in the "Received" stage.
> 
> - [Stage 2]: [Brief description of what happens during this stage.]
> - [Stage 3]: [Brief description of what happens during this stage.]
> - ... [Additional stages as necessary]
> 
> Please note that at each stage, your status will be updated and you'll know exactly how to react or if any action is needed on your part.
> 3. Communication: Throughout the review, we might need some additional information or clarifications from you. In such cases, we'll reach out via email. Similarly, once we complete our review, you'll receive an email update from us.
> 
> 4. If We Don’t Hear Back: If for some reason you don't respond to our outreach or communications, [outline the consequences or next steps here].
> 
> 5. Checking Status: Curious about where your request stands? Feel free to [check the status of your application] at any point.
> 
> Got questions in the meantime? Don’t hesitate to [contact us].
> 
> Modifying Your Request
> 
> Realized you need to make some adjustments to your domain request?
> 
> - Before Editing: To make changes, you'll first need to withdraw your current request.
> - Post-Withdrawal: After withdrawing, you can edit your request and submit it again. However, a heads up: modifying your request could extend the review period.
> 
> [Button: Withdraw Request]

**Comment by h-m-f-t** [comment]
@brooksr4, is the text of your comment in a doc somewhere so I can give feedback?

**Comment by brooksr4** [comment]
> 

Yes here's a link to the doc where it is: https://docs.google.com/document/d/1TTPCo0LOVJG-NSVSGgVpqWWz0kL01tpv_FJGIfhR1Qc/edit?usp=sharing

**Comment by michelle-rago** [comment]
👋 Just a reminder that we are using sentence case for all content on this project. So, for example "What to Expect Next" would be "What to expect next." LMK if the sentence case decision has been changed.

**Comment by brooksr4** [comment]
I think I just missed the sentence case part. Admittedly content writing is not my forte... but I updated it to reflect that.

**Comment by Katherine-Osos** [comment]
We're shifting things around a bit, and I'll be taking over this ticket. Since this is not related to domain mgmt or admin, I'll likely put this on the backburner for a bit.

**Comment by PaulKuykendall** [comment]
Looks like much of the work has been done, per comments above. So, this may just need review and implementation.

**Comment by vickyszuchin** [comment]
Per Katherine, move status from "In review" to "Backlog". The work for this ticket needs to be redone.
