### ISSUE TITLE
Update USWDS from 3.3 to current version

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#812]
### Issue Description

Investigate and implement as appropriate, version updates to USWDS and any/all other software packages, so that our dev efforts remain modern and reliable.

[Ref Slack Message](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1689089571419709?thread_ts=1689089565.297719&cid=C05BDEA3C11)

Need to enumerate packages, to cover all.

AC:

1. All packages have been assessed for potential to upgrade.
 a. review packages we should updated
3. As required, all tickets are written and prioritized for execution.
### Additional Context (optional)

Update USWDS separately of this.

**Comment by abroddrick** [comment]
Can I suggest we just change this to updating USWDS and then make another ticket that is lower priority for finding a better way to automate package updates? @rachidatecs  thoughts since you brought this up?

**Comment by rachidatecs** [comment]
> Can I suggest we just change this to updating USWDS and then make another ticket that is lower priority for finding a better way to automate package updates? [@rachidatecs](https://github.com/rachidatecs) thoughts since you brought this up?
> 
> CC: [@PaulKuykendall](https://github.com/PaulKuykendall)

100% agree
