### ISSUE TITLE
Notify me when I can submit a new request

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#830]
As a prospective new registrant (not already in the .gov database),
I want to know when the moratorium has lifted
So that I may submit my request for a new .gov domain.

AC:

1. When the moratorium ends and the registrar site is available, an email is sent to all people in a list indicating that they can return to the site to submit their request.

Depends on public launch of the NEW registrar.

**Comment by h-m-f-t** [comment]
This was completed when we published https://get.gov/updates/2023/10/13/transition-update/#a-pause-on-new-gov-domain-requests. See [Form](https://forms.office.com/pages/responsepage.aspx?id=bOfNPG2UEkq7evydCEI1SqHke9Gh6wJEl3kQ5EjWUKlUQTFFSjE1RVFTNENCNUNES1FHNzBOOUNRUi4u).
