### ISSUE TITLE
AO Info: Remove middle name and phone number fields

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#843]
### Issue Description

CISA analysts rarely need to contact the authorizing official (AO) and, if they do, they will typically coordinate thru a local agent and won't use the contact info in this application.

To reduce the amount of info requestor's need to provide for the AO, we should remove two fields that provide little value: 
- Middle Name
- Phone Number

### Acceptance Criteria
- [ ] Those fields are removed in all instances within UI. 
- Within the application process, on the Authorizing Official step
- On domain management pages, on the Authorizing Official page

### Additional Context (optional)

This issue came out of discussions related to #783 

![Image](https://github.com/cisagov/getgov/assets/119689946/92990222-7382-46c0-ad28-57d145ddb979)

**Comment by therealslimhsiehdy** [comment]
Note to self: In both the Admin + Analyst view and the registrar and Django Admin view
