### ISSUE TITLE
AO Step: Customize Opening Paragraph based on Org Type Selected (e.g. "Federal")

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#844]
### Issue Description

If a user chooses "Federal" as their organization type, we need to hide the opening paragraph on the AO step. It conflicts with the suggestions we provide for who to select as a federal AO.

For all other org types, this paragraph should be exposed. 

### A/C
- [ ] The content that is crossed out only appears for non-federal agencies. 
- [ ] The content should not be duplicated across multiple templates (i.e., it should only live in one place, making it easy to update in one place in the future).

### Additional Context (optional)

This issue came out of discussions related to https://github.com/cisagov/getgov/issues/783

![Image](https://github.com/cisagov/getgov/assets/119689946/324d4fef-963e-470b-9c65-93aa6b7e8e18)

**Comment by h-m-f-t** [comment]
It might be the case the we don't actually _hide_ the opening paragraph but instead not include that opening para in the base template.
