### ISSUE TITLE
Testing of Status Transitions

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/manage.get.gov#846]
### Issue Description

Use Staging (check with Devs before testing) to test status transitions and capture any behavior that is not intended.

A/C: Status Document is captured with changes required and corresponding tickets are created to capture work, if necessary.

### Additional Context (optional)

Current known issues are:
- going from Approved --> Rejected/Ineligible  --> Approved #811 

https://docs.google.com/document/d/1no29E2c9QWIHf_2wv3GCy6AotZ2_PVbIBiavKW-opxE/edit#heading=h.3as4poj

**Comment by PaulKuykendall** [comment]
Covered by other effort.
OBE
