### ISSUE TITLE
Add "Export" feature to Domain Management dashboard

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/manage.get.gov#863]
As a domain owner/manager, I want to export all my domain information to a file which I can download, so that I may have a record of all my domains and their statuses at that time.

Per the referenced UI design, please

Add the "Export Domains" functionality

This was removed by
- #861, as it was not necessary for MVP.

AC:

- [ ]  "Export Domains" functionality creates a CSV file with all domain information in it, suitable for download

**Comment by Katherine-Osos** [comment]
@PaulKuykendall @katypies I believe this was covered in this ticket #2323. Thoughts on closing this one?

**Comment by PaulKuykendall** [comment]
This ticket is obsolete, functionality was released in ticket # 2323
