### ISSUE TITLE
Prevent users from submitting multiple applications (under certain circumstances)

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/manage.get.gov#872]
### Story

As a domain applicant 
I want to be prohibited from submitting a new request when I have an request in the statuses of: _Submitted, In Review, or Action Needed_ and I have no approved requests.
so that non-verified users cannot have multiple applications.

### Acceptance Criteria

- [ ] (Condition 1) A user is _not_ permitted to **submit** a new domain request: if the user has no approved requests(s) **AND** they have a request in the _Submitted, In Review, or Action Needed_ status.
- [ ] A user in "condition 1" may always **start** a new request, which may be saved as a draft if it cannot be submitted, per these rules.
- [ ] A user in "condition 1" will see an alert, which persists on each of the pages of new requests, that informs the user that they cannot submit the request because they currently have a pending request. The pending request is identified in the alert and there will be a link in the alert to take you back to the dashboard.
- [ ] The final "Submit domain request" button on the final review page is replaced with an outlined button with the CTA 'Save and return to manage your domains.' This button takes you back to the Dashboard, and the draft is saved.
- [ ] Unit Tests are completed and up-to-date

### Issue Links
[Figma prototype with alert messaging and final button copy/styling](https://www.figma.com/proto/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?page-id=4829%3A39692&type=design&node-id=754-29647&viewport=1151%2C-64%2C0.28&t=06tdmsLsE9S8vmBx-1&scaling=min-zoom&starting-point-node-id=754%3A29647&show-proto-sidebar=1&mode=design)

Relates to: check #896

**Comment by kitsushadow** [comment]
Reference: https://miro.com/app/board/uXjVM3jz3Bs=/?moveToWidget=3458764559100173150&cot=14

**Comment by abroddrick** [comment]
I think this one needs to move to a later sprint at least 33, thoughts @PaulKuykendall and @vickyszuchin . It doesn't meet priorities for the next two sprints, interested in thoughts though.

**Comment by PaulKuykendall** [comment]
Pulled this out of Sprint 31, and to backlog. This will be reprioritized for a future slice/sprint.
