### ISSUE TITLE
Guiding content for Domain & DNS Management

### ISSUE THREAD

**Issue by brooksr4** [cisagov/manage.get.gov#894]
### Story

As a .gov domain registrant
I want have a guide for setting up my DNS data
so that I know how to correctly connect my new .gov domain with my system

### Acceptance Criteria

- [x] a page includes step by step instructions on how to set up the DNS settings with the new domain
- [x] The new page is linked to on the Domain Name Servers page

### Issue Links

🔄 Relates to: #817

**Comment by Katherine-Osos** [comment]
We may not need this ticket anymore. We already added some DNS info to the "Help>Domain management" section of the info site. During refinement, confirm whether that is sufficient.
