### ISSUE TITLE
Inform new registrants about HSTS preloading

### ISSUE THREAD

**Issue by brooksr4** [cisagov/manage.get.gov#895]
### Story

As a domain registrant, 
I want to know what my obligations are regarding .gov's stance to [preload new domains by default](https://get.gov/2020/6/21/an-intent-to-preload/#:~:text=Beginning%20September%201%2C%202020%2C%20all%20new%20.gov%20domains%20will%20be%20automatically%20preloaded.)
so that I am aware of what I need to know.

### Acceptance Criteria
- [x] [Draft content in domain security best practices](https://docs.google.com/document/d/1w67KM_CzWi5Mc7AaMU_VBB1MKUn6kqQzOh3CWZNZos4/edit?disco=AAABD51T6LM)
  - [x]  cisagov/getgov-home#175
- [x] ~Add content to the [request form's requirements page](https://github.com/cisagov/getgov/blob/d92f2895564e9cde1986fce9cb4ac76dd5a1d89b/src/registrar/templates/application_requirements.html#L38) about preloading~
- [x] Check if any updates are needed for https://beta.get.gov/domains/benefits/ with preloading link ([text](https://docs.google.com/document/d/1KYYOvy5adYu5vgmXBFXNXzD0m-Vt3GWp1rqs-9yOxxk/edit?disco=AAABD3ANWuQ))
- [x] Add text to [approved email template](https://docs.google.com/document/d/1fIl752pZrDwm4SxF1IXKByYyXPmt97YiMJx0a3sQt3g/edit?disco=AAABAHCe8Nc)
  - [ ] #1665

### Additional Context

Here is a link to a screenshot of how this shows in the verisign system: https://drive.google.com/file/d/1Fx_hH6Ocrw5QffZJO17uGkAHuvsY-bo_/view?usp=sharing

### Issue Links

🔄 Relates to: #817
🔧 Fixed by #1665 and cisagov/getgov-home#175

**Comment by h-m-f-t** [comment]
I think the text in the screenshot is a pretty good start. (Who wrote that language 🤔...)

**Comment by Katherine-Osos** [comment]
@h-m-f-t This went thru refinement, but a priority wasn't assigned. Should this be a "later" design ticket?

**Comment by h-m-f-t** [comment]
This should roll to 36, but it's a small update I can get done the first week of January.
