### ISSUE TITLE
Design + Content: Add yes/no question to Other employees from your org page

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#897]
### Story

As a domain request applicant
I want the ability to optionally add contact information for other employees from my organization
so that the information may be used to help CISA analysts assess my organizations eligibility for a .gov domain

### Acceptance Criteria

- [x] Content is drafted for the question that will show on the _Other employees from your organization_ page of the domain request application. [See current introductory text that precedes this question](https://docs.google.com/document/d/1GTTeRvKfe3lA_w2U4X_CBk8Q7BpMe7W0m_eVZsTHzEE/edit#heading=h.sqyw64) and ensure that it makes sense in that context.
- [x] Figma design & prototype is created to visualize how this question appears and how it will function. [See the mockup for this page in Figma](https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&node-id=392-6055&mode=design&t=qJf3zpvD9juOtXCA-0). The question should appear alone on the page at first. If the user clicks yes, then they should see the 'Organizational contact' form on the same page. If they click no, they should see a 'No other employees from your organization?' text form show on the same page. describe why they have no additional contacts to provide. Note that this additional page is not mocked up in Figma, but can be viewed on the stable site.

### Issue Links

Implementation ticket #661

**Comment by h-m-f-t** [comment]
@h-m-f-t review that the content is accurate so #661 is unblocked and ready to be slotted

**Comment by Katherine-Osos** [comment]
@h-m-f-t This is still marked for refinement but I see you self-assigned it. Is this needed for MVP? or should we add the "Next" or "Later" label?

**Comment by h-m-f-t** [comment]
Sorry to block this for so long! I've added some additional comments to the [draft text](https://docs.google.com/document/d/1GTTeRvKfe3lA_w2U4X_CBk8Q7BpMe7W0m_eVZsTHzEE/edit).
