### ISSUE TITLE
Registrar: Add and implement button to "Remove extra contacts"

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#903]
### Story

As a applicant
I want to be able to remove extra contacts I've added on the [Other employees from your org page](https://getgov-staging.app.cloud.gov/register/other_contacts/)
so that I don't waste time erasing the data I entered into the organization contact fields

### Acceptance Criteria
- [ ] fix add button to match the functionality on nameservers, dnssec and so on
- [ ] implement buttons to "remove" extra contacts on Other Contacts page, [using same pattern](https://github.com/cisagov/getgov/pull/1166) from DNSSEC and Name Servers.
- [ ] Implement look and functionality from this [Figma mockup](https://www.figma.com/file/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?type=design&mode=design). To enter prototype mode click the "present" button at the top right.

### Additional Context

See [Slack Thread](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1697669491409489)

### Issue Links

🔄 Relates to #589

**Comment by abroddrick** [comment]
@PaulKuykendall can we add this to one of the sprints for mvp? This seems very frustrating to not be able to remove someone if you added the wrong person and I wouldn't want it lost in the backlog. CC: @h-m-f-t

**Comment by abroddrick** [comment]
Added it to sprint 35 for now
