### ISSUE TITLE
Domain Mgmt: Update character limit for email address

### ISSUE THREAD

**Issue by Katherine-Osos** [cisagov/manage.get.gov#951]
### Issue Description

When managing a domain, on the **Your Contact Information** page and the **Authorizing Official** page, the email field notes a max limit of 254 characters. But all other email fields in the registrar note a limit of 320 characters. 

Update those email fields' max limit (and related messaging) to allow up to 320 characters.

Screenshot of current messaging:

![Image](https://github.com/cisagov/getgov/assets/119689946/aebf4df8-2e50-4983-b263-fae9372f74c7)

### Issue Links

In the future, replace the messaging with error: #952

**Comment by PaulKuykendall** [comment]
I would recommend that this be "later" since this is a consistency issue and not likely to cause a problem for launch.

**Comment by abroddrick** [comment]
Closing as already completed
