### ISSUE TITLE
Email Content: Domain request rejected (naming requirements not met)

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/manage.get.gov#965]
### AC
- [x] draft email for [Domain request rejected (naming requirements)](https://docs.google.com/document/d/1NkCtY3Rvr9GmvfzFnwCOsXT_Ww1J0Wp_06u0T0YKuKM/edit#heading=h.gjdgxs)
- [x] Email draft should live inside this [google folder](https://drive.google.com/drive/folders/1gkUyKEad42GiwzN7carJtMAw1RHyG8KC?usp=sharing)

### Additional links
[Domain Request Rejection Reasons](https://docs.google.com/spreadsheets/d/1mdwvwxmMR7rV63A7rysEtxKyZhyzK-ALKa2X_zA4I4k/edit#gid=0)

### Related Issue
https://github.com/cisagov/getgov/issues/608

**Comment by h-m-f-t** [comment]
Left a comment for @gabydisarli in the doc. If we can improve on that section, that'd be great. Excellent work.
