### ISSUE TITLE
Make a secrets management process that works for this team on an ongoing basis

### ISSUE THREAD

**Issue by neilmb** [cisagov/manage.get.gov#978]
Our registrar interacts with a number of third-party systems and for each of those systems, we have various secret information for authenticating (certificates, passwords, private keys, etc.). We need a plan for storing these secrets so that they (1) cannot be lost or misplaced, (2) are held safely and with low risk of disclosure, and (3) are accessible to developers who need to know them in order to connect to other systems.

**Comment by h-m-f-t** [comment]
An [approach has been drafted](https://docs.google.com/document/d/1_BbJmjYZNYLNh4jJPPnUEG9tFCzJrOc0nMrZrnSKKyw/edit?usp=sharing).

**Comment by neilmb** [comment]
We have been using the KeePass process successfully now to manage secrets for production launch, so I'd say we can close this ticket until we need something more/better from the process.
