### ISSUE TITLE
Django admin: Changes to "Organization name and mailing address" not populating in "Log Entries" in Django Admin

### ISSUE THREAD

**Issue by zandercymatics** [cisagov/manage.get.gov#979]
### Current Behavior

Within the Django Admin portal, user actions are logged under the 'Log Entries' tab. For instance, changing the 'Authorizing Official' will generate a logable event. However, this does not appear to be happening for update actions that occur on the DomainOrgNameAddressForm object. 

### Expected Behavior

Updates made to the DomainOrgNameAddressForm object are logged in Django Admin.

### Steps to Reproduce

1. As a superuser or analyst, click 'manage' on an approved Domain.
2. Click 'Organization name and mailing address' and edit any field. 
3. Navigate to /admin, then click 'log entries'
4. Note the sound of crickets

### Environment
Any supported environment.

### Additional Context

![image](https://github.com/cisagov/getgov/assets/141044360/af86752a-94ea-4440-9f22-f3888fe28326)
![image](https://github.com/cisagov/getgov/assets/141044360/a7293958-89aa-4b43-aa7d-2755177ffb71)

**Comment by vickyszuchin** [comment]
Per Rachid in Product huddle chat (0/27/2023):

That #979 could be simple. Neil identified that m2m relationships need an extra little something for changes to track in django auditlog and this could be the case here

**Comment by vickyszuchin** [comment]
This bug has been sized and meets DoR criteria. Moving to "Ready."
