### ISSUE TITLE
Test domain migration script

### ISSUE THREAD

**Issue by kitsushadow** [cisagov/manage.get.gov#981]
### Issue Description

* Create a script to to test that all domains moved correctly.
* Script should have an option to run all other scripts created for migration using test data and should simulate a user login for each user in domain invitation
* do a diff between the transition_domain and the following tables: domain, domain_information and the domain_invitation. It should:
  * Print any domains that exist in the transition_domain table but not in their corresponding domain, domain information or domain invitation tables.
   * Print which table this domain is missing from 
   * Check for duplicate entries in any of these tables and print which are duplicates and in which tables
   * emails should be sent to the appropriate users
   * note that all moved domains should now be accessible on django admin for an analyst

-ensure each script can be ran on sandbox, update readme with how to actually run on sandbox as needed.
- edit readme accordingly with how to run this script and any other specifics that are relevant

- ### Additional Context (optional)

https://docs.google.com/document/d/1UkQZdAmcGprXWdHX_PuT155CCNPbf_Gf/edit?pli=1#heading=h.iqv2v8lecjpn
Goal is to be able to test the functionality of the currently made scripts but also be usable once we have already ran the scripts in production and then double check that all data is correct
### Issue Links

blocked by: #926
blocked by: #927

**Comment by abroddrick** [comment]
From Sprint planning, we can ask our registry provider to load test domains for us for testing.
