### ISSUE TITLE
Design: modify alert re Contact Info on domain management pages for analysts/admins

### ISSUE THREAD

**Issue by rachidatecs** [cisagov/manage.get.gov#994]
### Story

As an admin managing a domain through the domain management pages accessed through Django admin, 
I want to see a revised alert message that explains that the contact information that's displayed is my own
so that I'm not confused or overwrite the domain's Contact by mistake.

### Acceptance Criteria

- Text in alert on domain management pages accessed through Django admin is descriptive re contact information

### Additional Context

Need a designer or a designer/dev on this one.

### Issue Links

Relates to #806

**Comment by Katherine-Osos** [comment]
This may no longer be an issue once we implement an "account" or "user profile" section of the registrar.

**Comment by Katherine-Osos** [comment]
@rachidatecs I believe this ticket is no longer relevant now that we have a profile section. Can you confirm whether you agree?

**Comment by Katherine-Osos** [comment]
I'm closing this ticket because it's no longer applicable. We've moved the contact info to another section of the registrar.
