### ISSUE TITLE
Implement basic reporting functionality for MVP (besides Domain Growth report)

### ISSUE THREAD

**Issue by brooksr4** [cisagov/manage.get.gov#996]
### Story

As an Admin, I want to quickly export domain data reports directly from the domains page (/admin/registrar/domain/) so that I can easily access and analyze the domain data.

### Acceptance Criteria

- [ ] Three reports are available to download on the domains page:
  - [ ] [Domains by type](https://docs.google.com/spreadsheets/d/1_nMU2obW22U6NlOSC2ARxf3PpsJnSe2wMo5AyLSzXzk/edit?usp=sharing) (sorted by domain name)
  - [ ] [current-full.csv](https://github.com/cisagov/dotgov-data/blob/main/current-full.csv) (sorted by domain name, then agency, then domain type)
  - [ ] [current-federal.csv](https://github.com/cisagov/dotgov-data/blob/main/current-federal.csv) (sorted by domain name, then agency, then domain type)
- [ ] Each CSV report should contain accurate and up-to-date domain data from the database, sorted in the ways they are in the examples above.
- [ ] Single dropdown with the three report options which the user can select
- [ ] Clicking on each report triggers an immediate download of the relevant CSV report
- [ ] The UI components should be consistent with the existing design language of the admin portal.

### Additional Context

- This feature is a stop-gap measure, meant to provide immediate access to crucial reports while the ideal report interface is being developed. Future work is at #997.

- Security email may be pulled from .gov database rather than thru EPP call to registry.

### Issue Links

🔄 Relates to: #938 #143 #1075

**Comment by h-m-f-t** [comment]
Excellent! The only thing this is missing is the publication of current-federal.csv and current-full.csv at a public URL. Added at #1075.

**Comment by h-m-f-t** [comment]
I've re-added the refinement label so the product leads to ensure the A/C are clear.
