### ISSUE TITLE
Implement Domain Growth report export

### ISSUE THREAD

**Issue by brooksr4** [cisagov/manage.get.gov#998]
### Story

As an Admin, I want to specify a date range on the Admin home page and quickly export the Domain Growth data as a CSV for analysis.

### Acceptance Criteria

- [ ] Form fields for "Start Date" and "End Date" are present on the Admin home page.
- [ ] A button labeled "Export Domain Growth Report" is adjacent to the date fields.
- [ ] Clicking the button triggers a download of a CSV report containing newly approved domains and deletions between the specified dates.
- [ ] The exported data should be accurate, reflecting actual domain activations and deletions for the chosen date range.
- [ ] Domains should only be included if they are in the Ready or Deleted.

### Additional Context

**Required Fields for MVP:**

- Domain Name (actual, full domain name)
- Domain Type (e.g, Federal, State, County, ...)
- Domain Status (domain.state, not to be confused with EPP status)

The MVP for Domain Growth focuses on quick access to data through exports, with a more detailed UI visualization planned for later (#999).

* [Screenshot from current domain growth report](https://drive.google.com/file/d/1ukYqjFp3-K6HO0PvnHuSr3ceaCBeQC-o/view?usp=drive_link) (note that this shows a web table of data, which is work for #999, _not_ this issue)
* [Example domain growth report](https://docs.google.com/spreadsheets/d/1GJ4FpRZIgU0P4dgcZwOoO_l2Y1Qd3-p9q6xmRQdekMQ/edit?usp=drive_link)

### Issue Links

🔄 Relates to: #938 #143 #1139

**Comment by brooksr4** [comment]
Here's a sketch of what this could look like: 
![New Drawing 17](https://github.com/cisagov/getgov/assets/13547334/3c6caf3b-7503-4170-ae3c-cb1a06c21297)

**Comment by h-m-f-t** [comment]
I've re-added the refinement label so the product leads to ensure the A/C are clear.

**Comment by PaulKuykendall** [comment]
Neil: We can used "CreatedAt" times for newly approved domains. Deleted may be a little trickier. (This is rare, but does happen)
