### ISSUE TITLE
Enhance "domain growth" report by showing details in-registrar

### ISSUE THREAD

**Issue by brooksr4** [cisagov/manage.get.gov#999]
This is the post-MVP update to #998 and adds both data visualization and detailed listings for a comprehensive user experience.

### Story

As an Admin, I want to navigate to the Domain Growth report from the reports list, input a date range, view a summary and visualization of domain activations and deletions, and have the option to see detailed data and summary metrics.

### Acceptance Criteria

- [ ] The "Domain Growth" report is listed in the "Reports" section on the Admin home page.
- [ ] Clicking on it takes the user to a dedicated page for the Domain Growth report.
- [ ] The user can input a "Start Date" and "End Date" to filter the data.
- [ ] The filtered data is summarized (number of total activations and total deletions, broken down by domain type).
  - [ ] Optional: a bar chart or similar visualization could display activations and deletions over the chosen date range.
- [ ] Detailed listings of domain activations and deletions are viewable (i.e., the raw data that makes up the summary in the prior bullet).
- [ ] An option to export the displayed data as a CSV is available.

### Additional Context

This data is used regularly for quarterly reporting. An example statement that's provided to meet that reporting follows:
> There were 8,140 non-federal domains published in the .gov zone as of Sept 15, 2023, with 230 domains activated in Q4.
> * City:  128
> * County:  48
> * Independent Intrastate:  33
> * Interstate:  3
> * Tribal:  4
> * State:  14        
>
> There were 8 non-federal domains deleted from the .gov zone during this period. Deletions occur upon request (e.g., entities no longer need the domain, their government organization becomes defunct) or because they were administratively removed (e.g., they failed to meet the requirements stipulated under the rules promulgated in the DOTGOV Act.

### Issue Links

🔄 Relates to: #938 #143 
♻️ Supersedes #998

**Comment by brooksr4** [comment]
Here's a screenshot of what it looks like in Verisign 
![Web capture_7-9-2023_122017_gsa dotgov gov](https://github.com/cisagov/getgov/assets/13547334/9dd3f192-6031-491e-b26e-ee7910788360)

And Here's a sketch of what it could look like in Django Admin:
![New Drawing 14](https://github.com/cisagov/getgov/assets/13547334/a452d64b-83a2-4c94-a8c5-09a3053e46ca)

**Comment by h-m-f-t** [comment]
It would be a useful addition to this report to include a Date column where the value is the date the domain was activated/deleted. Post MVP could also add back the Authorizing Agency (probably called something different in our new db), City, and State. See [example report](https://docs.google.com/spreadsheets/d/1GJ4FpRZIgU0P4dgcZwOoO_l2Y1Qd3-p9q6xmRQdekMQ/edit?pli=1#gid=1566240776).

**Comment by Katherine-Osos** [comment]
@h-m-f-t Is this ticket still needed or has it been covered by the reports that are already in the admin?

**Comment by h-m-f-t** [comment]
Having reports shown in-platform would be nice, but this isn't necessary. Closing!
